({
	'bold': 'Tučné',
	'copy': 'Kopírovat',
	'cut': 'Vyjmout',
	'delete': 'Odstranit',
	'indent': 'Odsadit',
	'insertHorizontalRule': 'Vodorovné pravítko',
	'insertOrderedList': 'Číslovaný seznam',
	'insertUnorderedList': 'Seznam s odrážkami',
	'italic': 'Kurzíva',
	'justifyCenter': 'Zarovnat na střed',
	'justifyFull': 'Do bloku',
	'justifyLeft': 'Zarovnat vlevo',
	'justifyRight': 'Zarovnat vpravo',
	'outdent': 'Předsadit',
	'paste': 'Vložit',
	'redo': 'Opakovat',
	'removeFormat': 'Odebrat formát',
	'selectAll': 'Vybrat vše',
	'strikethrough': 'Přeškrtnutí',
	'subscript': 'Dolní index',
	'superscript': 'Horní index',
	'underline': 'Podtržení',
	'undo': 'Zpět',
	'unlink': 'Odebrat odkaz',
	'createLink': 'Vytvořit odkaz',
	'toggleDir': 'Přepnout směr',
	'insertImage': 'Vložit obraz',
	'insertTable': 'Vložit/upravit tabulku',
	'toggleTableBorder': 'Přepnout ohraničení tabulky',
	'deleteTable': 'Odstranit tabulku',
	'tableProp': 'Vlastnost tabulky',
	'htmlToggle': 'Zdroj HTML',
	'foreColor': 'Barva popředí',
	'hiliteColor': 'Barva pozadí',
	'plainFormatBlock': 'Styl odstavce',
	'formatBlock': 'Styl odstavce',
	'fontSize': 'Velikost písma',
	'fontName': 'Název písma',
	/* Error messages */
	'systemShortcutFF': 'Akce "${0}" je v prohlížeči Mozilla Firefox dostupná pouze prostřednictvím klávesové zkratky. Použijte klávesy ${1}.',
	'ctrlKey':'Ctrl+${0}'
})
