#!/usr/share/ucs-test/runner python
## desc: Overwrite default tab with settings/extended_attribute
## tags: [udm-extendedattribute]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import sys
import subprocess
import univention.testing.strings as uts
import univention.testing.utils as utils
import univention.testing.udm as udm_test

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		properties = {
			'name': uts.random_name(),
			'shortDescription': uts.random_string(),
			'CLIName': uts.random_name(),
			'module': 'users/user',
			'objectClass': 'univentionFreeAttributes',
			'ldapMapping': 'univentionFreeAttribute15',
			'tabName': 'General'
		}

		extended_attribute = udm.create_object('settings/extended_attribute', position = udm.UNIVENTION_CONTAINER, **properties)
		
		module_help_text = subprocess.Popen([udm.PATH_UDM_CLI_CLIENT, properties['module']], stdout = subprocess.PIPE).communicate()[0].splitlines()


		for i in range(0, len(module_help_text)):
			if properties['tabName'] in module_help_text[i]:
				if not properties['CLIName'] in module_help_text[i+1]:
					utils.fail('Could not find settings/extended_attributes CLI name under tab "%s" in module "%s" as expected' % (properties['tabName'], properties['module']))
				for i2 in range(i, len(module_help_text)-i):
					if properties['tabName'] in module_help_text[i+i2]:
						utils.fail('Tab "%s" in "%s" module not overwritten by settings/extended_attribute' % (properties['tabName'], properties['module']))
				sys.exit(0)
						

		utils.fail('Could not find tab "%s" in module "%s" ' % (properties['tabName'], properties['module']))
