#!/bin/sh
#
# Univention Postgrey
#  postinst script
#
# SPDX-FileCopyrightText: 2011-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ ! -f "/etc/postgrey/whitelist_recipients.local" ]
then
	install -m 0644 -o 0 -g 0 /dev/null "/etc/postgrey/whitelist_recipients.local"
fi
if [ ! -f "/etc/postgrey/whitelist_clients.local" ]
then
	install -m 0644 -o 0 -g 0 /dev/null "/etc/postgrey/whitelist_clients.local"
fi

#DEBHELPER#

univention-config-registry set "mail/postfix/greylisting?enabled" \
                               "mail/postfix/greylisting/delay?300" \
                               "mail/postfix/greylisting/max-age?35" \
                               "mail/postfix/greylisting/retry-window?48" \
                               "mail/postfix/greylisting/lookup?host" \
                               "mail/postfix/greylisting/privacy?true" \
                               "mail/postfix/greylisting/client/whitelist/auto?5" \
                               "mail/postfix/greylisting/client/whitelist?/etc/postgrey/whitelist_clients /etc/postgrey/whitelist_clients.local" \
                               "mail/postfix/greylisting/recipient/whitelist?/etc/postgrey/whitelist_recipients /etc/postgrey/whitelist_recipients.local"

univention-config-registry commit "/etc/init.d/postgrey"


invoke-rc.d postgrey restart
invoke-rc.d postfix restart

exit 0
