<table border="0" align="center" width="95%" cellpadding="3" cellspacing="2">
<tr class="header">
    <td class="header">
        <b><?php printf(_("%s Terms of Agreement"), $registry->getParam('name', $module)); ?></b>
    </td>
</tr>
<tr>
    <td>&nbsp;</td>
</tr>
<tr>
    <td class="light">
        <?php printf(_("Please read the following text.  You MUST agree with the terms to use the system.")); ?>
    </td>
</tr>
<tr>
    <td>&nbsp;</td>
</tr>
