# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "univention-directory-reports"
version = "18.0.0"
description = "UCS - directory manager report generation"
license = "AGPL-3.0-only"
requires-python = ">= 3.11"
dependencies = [
    "trml2pdf",
    "univention-config-registry",
    "univention-debug-python",
    "univention-directory-manager-modules",
    "univention-lib",
]
maintainers = [
    { name = "Univention GmbH", email = "packages@univention.de" },
]

[project.urls]
Homepage = "https://www.univention.de/"

[tool.setuptools]
packages = ["univention.directory.reports"]

[tool.setuptools.package-dir]
"univention.directory.reports" = "modules/univention/directory/reports"
