#!/bin/sh
#
# Univention Mail Server
#
# SPDX-FileCopyrightText: 2011-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

univention-config-registry set \
	mail/postfix/virtual/enabled=yes \
	mail/postfix/transport/ldap/enabled=yes \
	mail/postfix/inet/interfaces=all

if dpkg --compare-versions "$2" lt 14.0.7-1
then
	univention-config-registry set \
	mail/postfix/smtpd/data_restrictions?reject_unauth_pipelining \
	mail/postfix/smtpd/discard_ehlo_keywords?"chunking, silent-discard"
fi

eval "$(univention-config-registry shell)"

for file in transport virtual canonical access relocated; do
  if [ ! -e /etc/postfix/$file ]; then
      touch /etc/postfix/$file
  fi
  postmap /etc/postfix/$file
done

. /usr/share/univention-lib/all.sh
call_joinscript 67univention-mail-server.inst

if [ -z "$postfix_autostart" ] || [ "$postfix_autostart" = "yes" ]; then
	/etc/init.d/postfix restart
fi

# configure firewall
ucr set security/packetfilter/package/univention-mail-postfix/tcp/25/all="ACCEPT" \
		security/packetfilter/package/univention-mail-postfix/tcp/25/all/en="SMTP" \
		security/packetfilter/package/univention-mail-postfix/tcp/465/all="ACCEPT" \
		security/packetfilter/package/univention-mail-postfix/tcp/465/all/en="SSMTP" \
		security/packetfilter/package/univention-mail-postfix/tcp/587/all="ACCEPT" \
		security/packetfilter/package/univention-mail-postfix/tcp/587/all/en="SMTP/submission"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

if [ "$1" = "configure" ]; then
	uinst=/usr/lib/univention-install/67univention-mail-server.uinst
	[ -e "$uinst" ] && rm "$uinst"
	if [ -z "$2" ]; then
		ucr set mail/postfix/activate_unionmap_in_virtual_alias_maps=yes
		ucr set mail/postfix/activate_ldap_attribute_mailForwardCopyToSelf_in_virtual_alias_maps=yes
		/etc/init.d/postfix reload && /etc/init.d/postfix restart
	fi
fi


exit 0
