#!/bin/sh
#
# Univention Mail Postfix
#  preinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

createLogfile () {
	touch $1
	chown $2 $1
	chmod $3 $1
}

#DEBHELPER#

createLogfile /var/log/mail.err root:root 640
createLogfile /var/log/mail.info root:adm 640
createLogfile /var/log/mail.log root:adm 640
createLogfile /var/log/mail.warn root:root 640

dpkg-maintscript-helper rm_conffile /etc/univention/templates/modules/create-archivefolder.py 11.0.1-99 -- "$@"
rm -f /etc/univention/templates/modules/create-archivefolder.pyc /etc/univention/templates/modules/create-archivefolder.pyo

exit 0
