#!/bin/sh
#
# postrm script for univention-mail-server
#
# SPDX-FileCopyrightText: 2012-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only


. /usr/share/univention-lib/base.sh

case "$1" in
	remove|purge)
		univention-config-registry set \
			mail/postfix/virtual/enabled=no \
			mail/postfix/transport/ldap/enabled=no \
			mail/postfix/inet/interfaces=127.0.0.1
	;;
esac

if [ "$1" = "remove" ] ; then
	call_unjoinscript 67univention-mail-server.uinst
fi

#DEBHELPER#

exit 0
