#!/bin/sh
#
# Univention Server Role "Managed Node"
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2003-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

xargs -d '\n' univention-config-registry set <<__UCR__
samba/share/home?no
samba/share/netlogon?no
server/password/interval?21
server/role=memberserver
server/password/cron?0 1 * * *
__UCR__

#DEBHELPER#

exit 0
