#!/bin/sh
#
# Univention Server Role "Primary Directory Node"
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2003-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

eval "$(univention-config-registry shell)"

xargs -d '\n' univention-config-registry set <<__UCR__
ldap/server/name=${hostname:-}.${domainname:-}
ldap/server/port?7389
ldap/server/type=master
server/password/interval?21
server/role=domaincontroller_master
server/password/cron?0 1 * * *
__UCR__

mkdir -p /var/lib/samba/netlogon/scripts/

# Bug #47581: fix broken OX schemata registration
/usr/share/univention-server-master/reregister_ox_ldap_schema.sh

#DEBHELPER#

exit 0
