#!/bin/bash
#
# Univention Server Role "Primary Directory Node"
#  preinst script for the debian package
#
# SPDX-FileCopyrightText: 2003-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

install -d -m 0755 /usr/share/univention-install/

if [ -e /etc/hostname ]; then
	hostname=$(cat /etc/hostname)
fi

domainname=$(/bin/dnsdomainname)

if [ -n "${hostname}${domainname}" ]
then
	# generate ssl certificate
	if [ ! -e "/etc/univention/ssl/$hostname/cert.pem" ]
	then
		. /usr/share/univention-ssl/make-certificates.sh
		gencert "$hostname.$domainname" "$hostname.$domainname"
		ln -snf "$hostname.$domainname" "/etc/univention/ssl/$hostname"
	fi
fi

if [ ! -e /etc/ldap.secret ]
then
	touch /etc/ldap.secret
	chmod 600 /etc/ldap.secret
	create_machine_password > /etc/ldap.secret
fi

if [ ! -e /etc/ldap-backup.secret ]
then
	touch /etc/ldap-backup.secret
	chmod 600 /etc/ldap-backup.secret
	create_machine_password > /etc/ldap-backup.secret
fi

exit 0
