#!/bin/sh
#
# Univention Server Role "Replica Directory Node"
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2003-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

xargs -d '\n' univention-config-registry set <<__UCR__
ldap/server/port?7389
ldap/server/type?slave
server/password/interval?21
server/role=domaincontroller_slave
server/password/cron?0 1 * * *
__UCR__

#DEBHELPER#

exit 0
