#!/bin/sh
#
# Univention Server Role "Backup Directory Node"
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2003-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

xargs -d '\n' univention-config-registry set <<__UCR__
ldap/server/port?7389
ldap/server/type?slave
server/password/interval?21
server/role=domaincontroller_backup
server/password/cron?0 1 * * *
__UCR__

install -d -m 755 /var/lib/samba/netlogon/scripts/

# Bug #47581: fix broken OX schemata registration
/usr/share/univention-server-backup/reregister_ox_ldap_schema.sh

#DEBHELPER#

exit 0
