etc/bootsplash/themes/managedclient/config/*cfg etc/bootsplash/themes/managedclient/config/
etc/bootsplash/themes/managedclient/images/*jpg etc/bootsplash/themes/managedclient/images/
managed-client etc/init.d/
univention-directory-policy/univention-set-ldap-server usr/lib/univention-directory-policy/
check_connection usr/share/univention-managed-client/
univention-ldap-server-available usr/sbin/
