#!/bin/sh
#
# Univention Server Installation
#  pstinst script for the debian package
#
# Copyright 2004-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#


if [ "$1" = "configure" ]; then
	eval $(univention-config-registry shell server/role)

	if [ ! -e /var/lib/univention-client-boot/linux-server ]; then
		if [ -e /var/lib/univention-repository/boot/linux-2.6.32 ]; then
			ln -sf /var/lib/univention-repository/boot/linux-2.6.32 /var/lib/univention-client-boot/linux-server
			ln -sf /var/lib/univention-repository/boot/linux-2.6.32.bin /var/lib/univention-client-boot/linux.bin
		elif [ -e /var/lib/univention-repository/boot/linux-2.6.32-64gb ]; then
			ln -sf /var/lib/univention-repository/boot/linux-2.6.32-64gb /var/lib/univention-client-boot/linux-server
			ln -sf /var/lib/univention-repository/boot/linux-2.6.32-64gb.bin /var/lib/univention-client-boot/linux.bin
		elif [ -e /var/lib/univention-repository/boot/linux-2.6.18 ]; then
			ln -sf /var/lib/univention-repository/boot/linux-2.6.18 /var/lib/univention-client-boot/linux-server
			ln -sf /var/lib/univention-repository/boot/linux-2.6.18.bin /var/lib/univention-client-boot/linux.bin
		elif [ -e /var/lib/univention-repository/boot/linux-2.6.30 ]; then
			ln -sf /var/lib/univention-repository/boot/linux-2.6.30 /var/lib/univention-client-boot/linux-server
			ln -sf /var/lib/univention-repository/boot/linux-2.6.30.bin /var/lib/univention-client-boot/linux.bin
		elif [ -e /var/lib/univention-repository/boot/linux-2.6.26 ]; then
			ln -sf /var/lib/univention-repository/boot/linux-2.6.26 /var/lib/univention-client-boot/linux-server
			ln -sf /var/lib/univention-repository/boot/linux-2.6.26.bin /var/lib/univention-client-boot/linux.bin
		else
			ln -sf /var/lib/univention-repository/boot/linux-2.6.32 /var/lib/univention-client-boot/linux-server
			ln -sf /var/lib/univention-repository/boot/linux-2.6.32.bin /var/lib/univention-client-boot/linux.bin
		fi
	fi
	if [ "$server_role" = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]
	then
		/usr/lib/univention-install/81univention-server-installation.inst
	fi
	if test -f /etc/init.d/univention-directory-listener
		then
		/etc/init.d/univention-directory-listener crestart
	fi

	# copy fixed 10_debootstrap.sh to script/installer in repo dir Bug #23590
	eval "$(univention-config-registry shell repository/mirror/basepath)"
	if [ -z "$repository_mirror_basepath" ]; then
		repository_mirror_basepath="/var/lib/univention-repository"
	fi
	mkdir -p "$repository_mirror_basepath/script/installer"
	if [ ! -f "$repository_mirror_basepath/script/installer/10_debootstrap.sh" ]; then
		cp /usr/share/univention-net-installer/10_debootstrap.sh "$repository_mirror_basepath/script/installer/10_debootstrap.sh"
		chmod 755 "$repository_mirror_basepath/script/installer/10_debootstrap.sh"
	fi
fi
