#!/bin/sh
#
# Univention Directory Manager Modules
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

eval "$(univention-config-registry shell)"

#DEBHELPER#

if [ "$1" = "configure" ]; then
	if [ -z "$2" ]; then
		# only set this for new installations
		univention-config-registry set \
			directory/manager/web/modules/users/user/properties/homePostalAddress/syntax=postalAddress \
			password/hashing/method?SHA-512
		univention-config-registry set \
			directory/manager/user/activate_ldap_attribute_mailForwardCopyToSelf=yes
	fi

	univention-config-registry set \
		directory/manager/web/modules/groups/group/caching/uniqueMember/timeout?300 \
		directory/manager/user_group/uniqueness=true \
		directory/manager/templates/alphanum/whitelist?'' \
		password/hashing/method?MD5 # for update keep old behavior
fi

stop_udm_cli_server

call_joinscript 18python-univention-directory-manager.inst

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "17.3.7"; then
	# shellcheck disable=SC2154
	if [ "$server_role" = "domaincontroller_master" ]; then
		univention-directory-manager container/cn create \
			--ignore_exists \
			--position "cn=internal" \
			--set name="recyclebin" \
			--set description="Container for deleted LDAP objects (Recycle Bin)" || true

		univention-directory-manager container/cn create \
			--ignore_exists \
			--position "cn=policies,$ldap_base" \
			--set name="recyclebin" \
			--set policyPath=1 \
			--set description="Container for Recycle Bin policies" || true

		univention-directory-manager policies/recyclebin create \
			--ignore_exists \
			--position "cn=recyclebin,cn=policies,$ldap_base" \
			--set name="default-settings" \
			--set retention_days="180" \
			--set enabled=TRUE \
			--append udm_modules="users/user" \
			--append udm_modules="groups/group" || true
	fi
fi

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "15.0.11-29"; then
	# shellcheck disable=SC1112,SC2154
	univention-directory-manager settings/extended_attribute modify --dn "cn=objectFlag,cn=custom attributes,cn=univention,$ldap_base" \
		--append translationShortDescription='"fr_FR" "Drapeau d’objet Univention"' \
		--append translationLongDescription='"fr_FR" "Définir des drapeaux pour un objet"'
fi

# On each incompatible change of UDM code, e.g. new syntax classes, new python modules,
# we need to restart services which use univention.admin.modules.update()
# to reload modules in long running processes. Increase version each time such a change is performed!
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "17.4.10"; then
	deb-systemd-invoke restart univention-directory-listener.service || true
	deb-systemd-invoke restart univention-directory-manager-rest.service || true
	# restart ucs@school importer service if available
	# shellcheck disable=SC2015
	systemctl is-active ucs-school-import-celery-worker.service && deb-systemd-invoke restart ucs-school-import-celery-worker.service || true
	systemctl is-active ucs-school-import-http-api.service && deb-systemd-invoke restart ucs-school-import-http-api.service || true
fi

exit 0
