#!/usr/share/ucs-test/runner python
## desc: Create and install a simple docker app
## tags: [docker]
## exposure: dangerous
## packages:
##   - docker.io

from dockertest import *

if __name__ == '__main__':
	
	with Appcenter() as appcenter:
		app_name = get_app_name()
		app_version = get_app_version()

		app = App(name=app_name, version=app_version)

		try:
			app.set_ini_parameter(DockerImage='docker.software-univention.de/ucs-appbox-amd64:4.1-0')
			app.add_to_local_appcenter()

			appcenter.update()

			app.install()

			app.verify()
		finally:
			app.uninstall()
			app.remove()

