#!/usr/share/ucs-test/runner python
## desc: Create and install a simple DC Slave docker app
## tags: [docker]
## exposure: dangerous
## packages:
##   - docker.io

from dockertest import *
from univention.testing.utils import get_ldap_connection

if __name__ == '__main__':
	
	with Appcenter() as appcenter:
		app_name = get_app_name()
		app_version = get_app_version()

		app = App(name=app_name, version=app_version)

		try:
			app.set_ini_parameter(DockerImage='docker.software-univention.de/ucs-appbox-amd64:4.1-0', DockerServerRole='domaincontroller_slave', DockerScriptSetup='/usr/sbin/%s-setup' % app_name)
			app.add_script(setup='''#!/bin/bash
set -x -e
univention-install --yes --no-install-recommends univention-server-slave univention-server-member-
/usr/share/univention-docker-container-mode/setup "$@"
''')

			app.add_to_local_appcenter()

			appcenter.update()

			app.install()

			app.verify()

			lo = get_ldap_connection()
			print lo.searchDn(filter='(&(cn=%s-*)(objectClass=univentionDomainController)(univentionServerRole=slave)(!(aRecord=*)))' % app_name, unique=True, required=True)

		finally:
			app.uninstall()
			app.remove()

