#!/usr/bin/python2.4
# -*- coding: utf-8 -*-
#
# Univention Samba
#  helper script: checks password 'quality'
#
# Copyright (C) 2001, 2002, 2003, 2004, 2005, 2006 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import re

line = sys.stdin.readline()
line=line.strip('\n')

_re1=re.compile('.*[a-z].*')
_re2=re.compile('.*[A-Z].*')
_re3=re.compile('.*[0-9].*')
_re4=re.compile('.*[^a-zA-Z0-9].*')
if _re1.match(line) and _re2.match(line) and _re3.match(line) and _re4.match(line):
	sys.exit(0)

sys.exit(1)
