#!/bin/sh
#
# Univention Serverview
#  postrm script
#
# Copyright (C) 2004, 2005, 2006 Univention GmbH
#
# http://www.univention.de/
# 
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
set -e

#DEBHELPER#

case "$1" in
  configure)

  univention-baseconfig commit /etc/snmp/snmpd.conf
  /etc/init.d/snmpd restart
  
  if [ -x /etc/init.d/eecd ]; then
      /etc/init.d/eecd stop
  else
      /etc/init.d/srvmagt-eecd restart
  fi

  if [ -x /etc/init.d/srvmagt ]; then
      /etc/init.d/srvmagt stop
  else
      /etc/init.d/srvmagt-agents restart
  fi

  # dpt loose connection to snmpd by restart or reload snmpd
  if [ -x /etc/init.d/dpt ] ;then
    /etc/init.d/dpt stop
    sleep 2
    /etc/init.d/dpt start
    sleep 1
   fi

  ;;

esac

exit 0

