#!/bin/sh
#
# Univention Heimdal
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# configure firewall
ucr set security/packetfilter/package/univention-heimdal-common/tcp/544/all=ACCEPT \
        security/packetfilter/package/univention-heimdal-common/tcp/544/all/en="krsh"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart


eval "$(univention-config-registry shell domainname)"

realm="$(echo $domainname | tr "[:lower:]" "[:upper:]")"

univention-config-registry set "kerberos/realm?$realm"

exit 0
