#!/bin/sh
#
# Univention Heimdal
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

. /usr/share/univention-lib/all.sh

eval "$(univention-config-registry shell)"

univention-config-registry set kerberos/autostart?yes \
	kerberos/password/quality/check?yes

call_joinscript 11univention-heimdal-init.inst
call_joinscript 15univention-heimdal-kdc.inst

# configure firewall
univention-config-registry set security/packetfilter/package/univention-heimdal-kdc/tcp/88/all="ACCEPT" \
		security/packetfilter/package/univention-heimdal-kdc/tcp/88/all/en="kerberos" \
		security/packetfilter/package/univention-heimdal-kdc/udp/88/all="ACCEPT" \
		security/packetfilter/package/univention-heimdal-kdc/udp/88/all/en="kerberos" \
		security/packetfilter/package/univention-heimdal-kdc/udp/464/all="ACCEPT" \
		security/packetfilter/package/univention-heimdal-kdc/udp/464/all/en="kpasswd" \
		security/packetfilter/package/univention-heimdal-kdc/tcp/464/all="ACCEPT" \
		security/packetfilter/package/univention-heimdal-kdc/tcp/464/all/en="kpasswd" \
		security/packetfilter/package/univention-heimdal-kdc/tcp/749/all="ACCEPT" \
		security/packetfilter/package/univention-heimdal-kdc/tcp/749/all/en="kadmin"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart


# fix for http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=470404
# fix for https://forge.univention.org/bugzilla/show_bug.cgi?id=16462
for fn in kdc.conf kadmind.acl ; do
	if [ ! -e "/var/lib/heimdal-kdc/$fn" ] ; then
	 	ln -s /etc/heimdal-kdc/$fn /var/lib/heimdal-kdc/$fn
	else
	 	if [ ! -h "/var/lib/heimdal-kdc/$fn" ] ; then
	 		mv /var/lib/heimdal-kdc/$fn /var/lib/heimdal-kdc/$fn.BACKUP
	 		ln -s /etc/heimdal-kdc/$fn /var/lib/heimdal-kdc/$fn
	 	fi
	fi
done

if [ "$1" = "configure" ]; then
	if [ -n "$2" ]; then
		invoke-rc.d heimdal-kdc restart
	fi

	systemctl try-restart univention-directory-listener
fi

hdbdir='/var/lib/heimdal-kdc'	## configured by heimdal/debian/rules
kstash_file="${hdbdir}/m-key"	## created by kstash in heimdal-kdc.postinst
if [ -f "$kstash_file" ]; then
	mv "${kstash_file}" "${kstash_file}.DISABLED"
fi

exit 0
