({
	'bold': 'Vet',
	'copy': 'Kopiëren',
	'cut': 'Knippen',
	'delete': 'Wissen',
	'indent': 'Inspringen',
	'insertHorizontalRule': 'Horizontale liniaal',
	'insertOrderedList': 'Genummerde lijst',
	'insertUnorderedList': 'Lijst met opsommingstekens',
	'italic': 'Cursief',
	'justifyCenter': 'Centreren',
	'justifyFull': 'Uitvullen',
	'justifyLeft': 'Links uitlijnen',
	'justifyRight': 'Rechts uitlijnen',
	'outdent': 'Uitspringen',
	'paste': 'Plakken',
	'redo': 'Opnieuw',
	'removeFormat': 'Opmaak verwijderen',
	'selectAll': 'Alles selecteren',
	'strikethrough': 'Doorhalen',
	'subscript': 'Subscript',
	'superscript': 'Superscript',
	'underline': 'Onderstrepen',
	'undo': 'Ongedaan maken',
	'unlink': 'Link verwijderen',
	'createLink': 'Link maken',
	'toggleDir': 'Schrijfrichting wijzigen',
	'insertImage': 'Afbeelding invoegen',
	'insertTable': 'Tabel invoegen/bewerken',
	'toggleTableBorder': 'Tabelkader wijzigen',
	'deleteTable': 'Tabel wissen',
	'tableProp': 'Tabeleigenschap',
	'htmlToggle': 'HTML-bron',
	'foreColor': 'Voorgrondkleur',
	'hiliteColor': 'Achtergrondkleur',
	'plainFormatBlock': 'Alineastijl',
	'formatBlock': 'Alineastijl',
	'fontSize': 'Lettergrootte',
	'fontName': 'Lettertype',
	/* Error messages */
	'systemShortcutFF': 'De actie "${0}" is alleen beschikbaar in Mozilla Firefox via een sneltoestcombinatie. Gebruik ${1}.',
	'ctrlKey':'Ctrl+${0}'
})
