#!/usr/share/ucs-test/runner python
## desc: Create and remove DHCP service
## tags: [udm-dhcp,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
		if not utils.verify_ldap_object(dhcpService):
			utils.fail()

		udm.remove_object('dhcp/service', dn = dhcpService)
		if utils.verify_ldap_object(dhcpService):
			utils.fail('Could still find DHCP service "%s" in LDAP after it should have been removed' % dhcpService)

