#!/usr/share/ucs-test/runner python
## desc: Create minimal DHCP host
## tags: [udm-dhcp,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		utils.verify_ldap_object(udm.create_object('dhcp/host',
												   host = uts.random_name(),
												   hwaddress = 'ethernet 01:ff:78:38:ab:24', superordinate = udm.create_object('dhcp/service', service = uts.random_name())
												  )
								)
