#!/usr/share/ucs-test/runner python
## desc: Create and remove DHCP host
## tags: [udm-dhcp,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
		dhcpHost = udm.create_object('dhcp/host', superordinate = dhcpService, host = uts.random_name(), hwaddress = 'ethernet 01:ff:78:38:ab:24', fixedaddress = '10.20.30.40')
		
		if not utils.verify_ldap_object(dhcpHost):
			utils.fail()
		
		udm.remove_object('dhcp/host', dn = dhcpHost, superordinate = dhcpService)
		if utils.verify_ldap_object(dhcpHost):
			utils.fail('Could still find DHCP host "%s" in LDAP after it should have been removed' % dhcpHost)
