#!/usr/share/ucs-test/runner python
## desc: Remove DHCP shared network
## tags: [udm-dhcp,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts


if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
		dhcpSharedNetwork = udm.create_object('dhcp/shared', name = uts.random_name(), superordinate = dhcpService)

		udm.remove_object('dhcp/shared', dn = dhcpSharedNetwork, superordinate = dhcpService)
		utils.verify_ldap_object(dhcpSharedNetwork, should_exist = False)
