#!/usr/share/ucs-test/runner python
## desc: Create and remove DHCP shared subnet
## tags: [udm-dhcp,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
		dhcpSharedNetwork = udm.create_object('dhcp/shared', name = uts.random_name(), superordinate = dhcpService)
		dhcpSharedSubnet = udm.create_object('dhcp/sharedsubnet', superordinate = dhcpSharedNetwork, subnet = '10.20.30.0', subnetmask = '24')

		if not utils.verify_ldap_object(dhcpSharedSubnet):
			utils.fail()

		udm.remove_object('dhcp/sharedsubnet', dn = dhcpSharedSubnet, superordinate = dhcpSharedNetwork)
		if utils.verify_ldap_object(dhcpSharedSubnet):
			utils.fail('Could still find DHCP shared subnet in LDAP after it should have been removed')

