#!/usr/share/ucs-test/runner python
## desc: Check DHCP shared subnet attributes
## tags: [udm-dhcp]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import sys
import univention.testing as test
import univention.testing.udm as udm_test
import univention.testing.strings as uts
import univention.uldap as uldap

if __name__ == '__main__':
	dhcpSharedSubnetProperties = {
		'subnet': '10.20.30.0',
		'subnetmask': '24',
		'broadcastaddress': '10.20.30.255',
		'range': '10.20.30.1 10.20.30.254'
	}

	ldap = uldap.getAdminConnection()
	ldapMapping = {
		'cn':'subnet',
		'dhcpNetMask':'subnetmask',
		'dhcpRange':'range',
		'univentionDhcpBroadcastAddress':'broadcastaddress'
	}
	ldapFilter = '(&(cn=%s)(objectClass=univentionDhcpSharedSubnet))' % dhcpSharedSubnetProperties['subnet']

	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
		dhcpSharedNetwork = udm.create_object('dhcp/shared', name = uts.random_name(), superordinate = dhcpService)
		dhcpSharedSubnet = udm.create_object('dhcp/sharedsubnet', superordinate = dhcpSharedNetwork, **dhcpSharedSubnetProperties)

		for attr, value in ldap.search(base = dhcpSharedNetwork, filter = ldapFilter, attr = ldapMapping.values())[0][1].items():
			if value != [dhcpSharedSubnetProperties[ldapMapping[attr]]]:
				test.fail('Expected "%s" of created DHCP shared subnet to be %r, but found %r instead'  % (attr, value, [dhcpSharedSubnetProperties[ldapMapping[attr]]]))
