#!/usr/share/ucs-test/runner python
## desc: Test if UDM correctly creates a DHCP host object when a computer object with given dhcpEntryZone is created
## tags: [udm-test,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		dhcpService = udm.create_object('dhcp/service', service = uts.random_name())
	
		hostProperties = {
			'name': uts.random_name(),
			'ip': '10.20.30.40',
			'mac': '00:11:22:33:44:55',
			'dhcpEntryZone': '%s 10.20.30.40 00:11:22:33:44:55' % dhcpService
		}

		udm.create_object('computers/windows', **hostProperties)

		if not utils.verify_ldap_object('cn=%s,%s' % (hostProperties['name'], dhcpService), {
			'cn': [hostProperties['name']],
			'univentionDhcpFixedAddress': [hostProperties['ip']],
			'dhcpHWAddress': ['ethernet %s' % hostProperties['mac']]
		}):
			utils.fail()
