.\" @(#)man/man8/getkeycodes.8	1.0 Nov  8 22:30:48 MET 1994
.TH GETKEYCODES 8 "8 Nov 1994" "Local" "Keyboard Support"
.SH NAME
getkeycodes \- print kernel scancode-to-keycode mapping table
.SH SYNOPSIS
.B getkeycodes
.SH DESCRIPTION
The
.I getkeycodes
command prints the kernel scancode-to-keycode mapping table.
.SH OPTIONS
None.
.SH "SEE ALSO"
.I "setkeycodes (8)"


