#!/usr/share/ucs-test/runner python
## desc: Set TXT during dns/forward_zone creation
## tags: [udm]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools

import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		txt_record = uts.random_string()

		forward_zone = udm.create_object('dns/forward_zone', zone='%s.%s' % (uts.random_name(), uts.random_name()), txt=txt_record, nameserver=uts.random_dns_record())
		utils.verify_ldap_object(forward_zone, {'tXTRecord': [txt_record]})
