#!/usr/share/ucs-test/runner python
## desc: DNS service record, append and remove locations
## tags: [udm-dns,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.udm as udm_test
import univention.testing.strings as uts
import univention.testing.utils as utils



if __name__ == '__main__':
	forwardZoneName = '%s.%s' % (uts.random_name(), uts.random_name())
	locations = ['0 1 2 %s' % forwardZoneName, '4 5 6 %s' % forwardZoneName, '7 8 9 %s' % forwardZoneName, '10 11 12 %s' % forwardZoneName]

	with udm_test.UCSTestUDM() as udm:
		forwardZone = udm.create_object('dns/forward_zone', zone = forwardZoneName, nameserver = uts.random_string())
		srvRecord = udm.create_object('dns/srv_record', superordinate = forwardZone, name = '%s tcp %s' % (uts.random_string(), uts.random_string()), append = {'location': locations[:2]})
		
		udm.modify_object('dns/srv_record', superordinate = forwardZone, dn = srvRecord, append = {'location': locations[2:]})
		if not utils.verify_ldap_object(srvRecord, {'sRVRecord': locations}):
			utils.fail()

		udm.modify_object('dns/srv_record', superordinate = forwardZone, dn = srvRecord, remove = {'location': locations[:2]})
		if not utils.verify_ldap_object(srvRecord, {'sRVRecord': locations[2:]}):
			utils.fail()
