#!/usr/share/ucs-test/runner python
## desc: DNS host, test setting, appending and removing MX records
## tags: [udm-dns,apptest]
## roles: [domaincontroller_master]
## bugs: [15654]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts


if __name__ == '__main__':
	MXrecords = ['1 10.20.30.40', '2 10.20.30.41', '3 10.20.30.42']

	with udm_test.UCSTestUDM() as udm:
		forwardZone = udm.create_object('dns/forward_zone', zone = '%s.%s' % (uts.random_name(), uts.random_name()), nameserver = uts.random_string())
		hostRecord = udm.create_object('dns/host_record', superordinate = forwardZone, name = uts.random_name(), mx = MXrecords[0])
		
		udm.modify_object('dns/host_record', dn = hostRecord, superordinate = forwardZone, append = {'mx': MXrecords[1:]})
		if not utils.verify_ldap_object(hostRecord, {'mXRecord': MXrecords}):
			utils.fail()
		
		udm.modify_object('dns/host_record', dn = hostRecord, superordinate = forwardZone, remove = {'mx': MXrecords[:2]})
		if not utils.verify_ldap_object(hostRecord, {'mXRecord': MXrecords[2:]}):
			utils.fail()
