#!/usr/share/ucs-test/runner bash
## desc: "Check whether container can be recursively moved on ad-side in read-mode"
## exposure: dangerous
## packages:
## - univention-ad-connector
## tags:
##  - skip_admember

. "$TESTLIBPATH/base.sh" || exit 137
. "$TESTLIBPATH/udm.sh" || exit 137
. "$TESTLIBPATH/random.sh" || exit 137 

. "adconnector.sh" || exit 137
test -n "$connector_ad_ldap_host" || exit 137


#                 Container3
#                /
#      Container1--User
#     /
# Base
#     \
#      Container2

# shall become

# Base--Container2--Container1--User
#                             \
#                              Container3

RETRYREJECTED="$(ucr get connector/s4/retryrejected)"
ad_set_retry_rejected 2

CONTAINER1="$(random_chars)1"
CONTAINER2="$(random_chars)2"
CONTAINER3="$(random_chars)3"
UDM_users_user_username="$(random_chars)"

SYNCMODE="$(ad_get_sync_mode)"
ad_set_sync_mode "sync"
# restart in any case because the RETRYREJECTED may be changed

section "Create initial Tree structure"

ad_container_create "$CONTAINER1" || fail_test 110
ad_container_create "$CONTAINER2" || fail_test 110
ad_container_create "$CONTAINER3" "" "CN=$CONTAINER1,$(ad_get_base)" || fail_test 110
ad_createuser "$UDM_users_user_username" "" "CN=$CONTAINER1,$(ad_get_base)" || fail_test 110
ad_wait_for_synchronization; fail_bool 0 110
UDM_container_cn_name="$CONTAINER3"

UDM_container_cn_name="$CONTAINER1"
udm_exists "container/cn"; fail_bool 0 110
ad_exists "CN=$CONTAINER1,$(ad_get_base)"; fail_bool 0 110
UDM_container_cn_name="$CONTAINER2"
udm_exists "container/cn"; fail_bool 0 110
ad_exists "CN=$CONTAINER2,$(ad_get_base)"; fail_bool 0 110
UDM_container_cn_name="$CONTAINER3"
udm_exists "container/cn" "" "" "cn=$CONTAINER1,$ldap_base"; fail_bool 0 110
ad_exists "CN=$CONTAINER3,CN=$CONTAINER1,$(ad_get_base)"; fail_bool 0 110
udm_exists "users/user" "" "" "cn=$CONTAINER1,$ldap_base"; fail_bool 0 110

section "Move $CONTAINER1 into $CONTAINER2"

ad_set_sync_mode "read"

ad_move "CN=$CONTAINER1,$(ad_get_base)" "CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)" || fail_test 110
ad_wait_for_synchronization; fail_bool 0 110

UDM_container_cn_name="$CONTAINER1"
udm_exists "container/cn"; fail_bool 1 110
ad_exists "CN=$CONTAINER1,$(ad_get_base)"; fail_bool 1 110

UDM_container_cn_name="$CONTAINER2"
udm_exists "container/cn"; fail_bool 0 110
ad_exists "CN=$CONTAINER2,$(ad_get_base)"; fail_bool 0 110
UDM_container_cn_name="$CONTAINER1"
udm_exists "container/cn" "" "" "cn=$CONTAINER2,$ldap_base"; fail_bool 0 110
ad_exists "CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)"; fail_bool 0 110
UDM_container_cn_name="$CONTAINER3"
udm_exists "container/cn" "" "" "cn=$CONTAINER1,cn=$CONTAINER2,$ldap_base"; fail_bool 0 110
ad_exists "CN=$CONTAINER3,CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)"; fail_bool 0 110
udm_exists "users/user" "" "" "cn=$CONTAINER1,cn=$CONTAINER2,$ldap_base"; fail_bool 0 110
ad_exists "CN=$UDM_users_user_username,CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)"; fail_bool 0 110

section "Clean up"

ad_delete "CN=$UDM_users_user_username,CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)" || fail_test 110
ad_wait_for_synchronization; fail_bool 0 110
ad_delete "CN=$CONTAINER3,CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)" || fail_test 110
ad_wait_for_synchronization; fail_bool 0 110
ad_delete "CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)" || fail_test 110
ad_wait_for_synchronization; fail_bool 0 110
ad_delete "CN=$CONTAINER2,$(ad_get_base)" || fail_test 110
ad_wait_for_synchronization; fail_bool 0 110

UDM_container_cn_name="$CONTAINER2"
udm_exists "container/cn"; fail_bool 1 110
ad_exists "CN=$CONTAINER2,$(ad_get_base)"; fail_bool 1 110
UDM_container_cn_name="$CONTAINER1"
udm_exists "container/cn" "" "" "cn=$CONTAINER2,$ldap_base"; fail_bool 1 110
ad_exists "CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)"; fail_bool 1 110
UDM_container_cn_name="$CONTAINER3"
udm_exists "container/cn" "" "" "cn=$CONTAINER1,cn=$CONTAINER2,$ldap_base"; fail_bool 1 110
ad_exists "CN=$CONTAINER3,CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)"; fail_bool 1 110
udm_exists "users/user" "" "" "cn=$CONTAINER1,cn=$CONTAINER2,$ldap_base"; fail_bool 1 110
ad_exists "CN=$UDM_users_user_username,CN=$CONTAINER1,CN=$CONTAINER2,$(ad_get_base)"; fail_bool 1 110

ad_set_retry_rejected "$RETRYREJECTED"
ad_set_sync_mode "$SYNCMODE"

exit "$RETVAL"
