#!/usr/bin/python2.6
import univention.config_registry
import ldap
import heimdal
import sys

def salt_krb5Keys(principal, keys):
	context = heimdal.context()
	new_keys = []
	for k in keys:
		(keyblock, salt, kvno) = heimdal.asn1_decode_key(k)
		if salt.saltvalue():
			return []
		krb5_principal = heimdal.principal(context, principal)
		krb5_salt = heimdal.salt(context, krb5_principal)
		new_keys.append(heimdal.asn1_encode_key(keyblock, krb5_salt, kvno))
	return new_keys

class ldapconnection:
	def __init__(self, location, port, binddn , bindpw, protocol = 'ldaps'):
		if protocol.lower() == 'ldapi':
			import urllib
			location = urllib.quote(location)
		uri = '%s://%s:%s' % ( protocol, location, port )

		try:
			self.lo = ldap.initialize(uri)
			self.lo.simple_bind_s(binddn, bindpw)
		except ldap.LDAPError, error_message:
			print error_message
			raise

	def ldapsearch_async( self, base, scope = ldap.SCOPE_SUBTREE, ldapfilter = '(objectClass=*)', attrlist = None):
		timeout = 0
		try:
			result_id = self.lo.search(base, scope, ldapfilter, attrlist)
			while 1:
				result_type, result_data = self.lo.result(result_id, timeout)
				if (result_data == []):
					break
				else:
					if result_type == ldap.RES_SEARCH_ENTRY:
						yield result_data[0]
		except ldap.LDAPError, error_message:
			print error_message
			raise

	def ldapmodify_object( self, dn, object_dict ):
		try:
			modlist = []
			for attr, value in object_dict.items():
				modlist.append((ldap.MOD_REPLACE, attr, value))
			res = self.lo.modify_s(dn, modlist)
		except ldap.LDAPError, error_message:
			print error_message
			raise

def main():
	ucr = univention.config_registry.ConfigRegistry()
	ucr.load()

	if ucr['ldap/server/type'] != 'master':
		print "salt_krb5Keys: nothing to do, only works on the LDAP master."
		return 0

	ldap_base = ucr['ldap/base']
	binddn = "cn=admin,%s" % ldap_base
	bindpw = open('/etc/ldap.secret').read().strip()

	ldapfilter = "(objectClass=krb5Principal)"
	attrlist = ['krb5PrincipalName', 'krb5Key']

	lc = ldapconnection(ucr['ldap/master'], ucr.get('ldap/master/port', 7389), binddn, bindpw, 'ldaps')
	for dn, object_dict in lc.ldapsearch_async(ldap_base, ldapfilter = ldapfilter, attrlist = attrlist):
		mod_krb5Keys = salt_krb5Keys(object_dict['krb5PrincipalName'][0], object_dict['krb5Key'])
		if mod_krb5Keys:
			lc.ldapmodify_object(dn, { 'krb5Key' : mod_krb5Keys } )

	return 0

if __name__=='__main__':
    sys.exit(main())

