#!/bin/sh
#
# Univention MariaDB
#  postinst script
#
# SPDX-FileCopyrightText: 2017-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(ucr shell hostname domainname)"

# MariaDB 10.11 (UCS 5.2) uses unix_socket authentication for the root user by default.
# /etc/mysql.secret is no longer needed for authentication. However, some UCS code still reads this
# file, so we continue to create it if it does not exist to avoid breaking those components (for
# now).
create_mysql_secret_if_not_exists () {
	if [ ! -e /etc/mysql.secret ]; then
		touch /etc/mysql.secret
		chmod 600 /etc/mysql.secret
		chown root /etc/mysql.secret
		makepasswd --nocrypt --chars=20 >> /etc/mysql.secret
	fi
}

case "$1" in
    configure)
	create_mysql_secret_if_not_exists

	# mariadb behaves like mysql in ucs 4.3; use and reuse old mysql ucr values
	ucr set mysql/config/mysqld/bind_address?0.0.0.0 \
		mysql/config/mysqld/max_connections?151 \
		mysql/config/mysqld/max_allowed_packet?33554432 \
		mysql/config/mysqld/query_cache_size?33554432 \
		mysql/config/mysqld/query_cache_limit?2097152 \
		mysql/config/mysqld/innodb_buffer_pool_size?157286400

	[ -e /var/univention-join/joined ] && ucr set \
		mysql/config/mariadb/ssl-ca?"/etc/univention/ssl/ucsCA/CAcert.pem" \
		mysql/config/mariadb/ssl-cert?"/etc/univention/ssl/${hostname:-}.${domainname:-}/cert.pem" \
		mysql/config/mariadb/ssl-key?"/etc/univention/ssl/${hostname:-}.${domainname:-}/private.key"

	# Bug #46537: Use the mariadb default values
	# Debian changed the mariadb defaults to utf8mb4 / utf8mb4_general_ci
	ucr set mysql/config/mysqld/collation-server?latin1_swedish_ci \
		mysql/config/mysqld/character-set-server?latin1
esac

systemctl --system daemon-reload >/dev/null
systemctl restart mariadb

exit 0
