#!/usr/share/ucs-test/runner python
## desc: Test setting the quota through pam with usrquota
## roles-not: [basesystem]
## exposure: dangerous
## packages:
##   - univention-quota

from quota_test import QuoataCheck


def main():
	quoataCheck = QuoataCheck(quota_type="usrquota")
	quoataCheck.test_quota_pam()


if __name__ == '__main__':
	main()
