#!/usr/share/ucs-test/runner bash
## desc: "Restarting samba - needed since https://forge.univention.org/bugzilla/show_bug.cgi?id=52130"
## exposure: safe
## packages:
##  - univention-samba
## roles:
## - domaincontroller_slave
## tags: [basic]
## join: true

/etc/init.d/samba restart
