#!/bin/sh
#
# Univention Fetchmail
#  postrm script
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

. /usr/share/univention-lib/all.sh
. /usr/share/univention-join/joinscripthelper.lib

if [ "$1" = "remove" ]; then
	call_unjoinscript 93univention-fetchmail-uninstall.uinst
	joinscript_remove_script_from_status_file univention-fetchmail
fi

exit 0
