.\"                                      Hey, EMACS: -*- nroff -*-
.TH JITTER 1 2012-08-01
.SH NAME
jitter \- delay program execution for limited random time

.SH SYNOPSIS
.B jitter
.I seconds command
.RI [ command-options ...]

.SH DESCRIPTION
This manual page documents briefly the
.B jitter
command.
It sleeps for a random time between 0 and \fIseconds\fP before executing \fIcommand\fP with the given \fIcommand-options\fP.
It is useful for de-skewing
.BR crontab (5)
entries, so they don't overload a network server by connecting to it at exactly the same time.

.SH OPTIONS
.TP
.I seconds
Maximum number of \fIseconds\fP to wait.
.TP
.IR command\  [ command-options ..]
The \fIcommand\fP to execute after the randomly chosen delay has passed.
The \fIoptions\fP are passed to the command as is.

.SH EXAMPLE
Run the updater in the next 5 minutes:
.nf
jitter 300 univention-update net
.fi

.SH SEE ALSO
.BR sleep (1),
.BR crontab (5).

.SH AUTHOR
Copyright (c) 2001-2019 Univention GmbH, Germany
