.\"                                      Hey, EMACS: -*- nroff -*-
.TH LDAPSEARCH-WRAPPER 1 2012-08-01
.SH NAME
ldapsearch\-wrapper \- unwrapper long ldif-fields

.SH SYNOPSIS
.B ldapsearch\-wrapper
.BI <\  in \ >\  out

.SH DESCRIPTION
This manual page documents briefly the
.B ldapsearch\-wrapper
command.
It is a tool to unwrap the output of
.BR ldapsearch (1),
which uses the
.BR ldif (5)
format for its output:
Long lines are wrapped and start with a leading space.
This program undoes this wrapping and outputs the unwrapped long lines.

.SH EXAMPLE
.nf
ldapsearch ... | ldapsearch-wrapper
.fi

.SH SEE ALSO
.BR ldapsearch (1),
.BR ldapsearch-decode64 (1),
.BR ldif (5).

.SH AUTHOR
Copyright (c) 2001-2019 Univention GmbH, Germany
