.\"                                      Hey, EMACS: -*- nroff -*-
.TH LDAPSEARCH-DECODE64 1 2009-12-03
.SH NAME
ldapsearch\-decode64 \- decode base64 encoded ldif-fields

.SH SYNOPSIS
.B ldapsearch\-decode64
.BI <\  in \ >\  out

.SH DESCRIPTION
This manual page documents briefly the
.B ldapsearch\-decode64
command.
It decodes binary fields from the output of
.BR ldapsearch (1),
which uses the
.B base64
encoding.

.SH EXAMPLE
.nf
ldapsearch ... | ldapsearch-wrapper | ldapsearch-decode64
.fi

.SH SEE ALSO
.BR ldapsearch (1),
.BR ldapsearch-wrapper (1),
.BR ldif (5).

.SH AUTHOR
Copyright (c) 2001-2019 Univention GmbH, Germany
