.\"                                      Hey, EMACS: -*- nroff -*-
.TH UNIVENTION\-CHECK\-TEMPLATES 8 2016-10-17
.SH NAME
univention\-check\-templates \- list modified and not updated UCR templates

.SH SYNOPSIS
.B univention\-check\-templates

.SH DESCRIPTION
This manual page documents briefly the
.B univention\-check\-templates
command.
It scans the
.I /etc/univention/
directory for modified files, for which updates are available by newer packages, but which weren't updates during installation, because they contain local modifications.

.SH FILES
.TP
.I /etc/univention/
Directory containing UCR files.

.SH SEE ALSO
.BR univention\-config\-registry (8).

.SH AUTHOR
Copyright (c) 2001-2019 Univention GmbH, Germany
