#!/bin/sh
#
# Univention Management Console
#  prerm script for the debian package
#
# SPDX-FileCopyrightText: 2016-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$1" in
    remove|deconfigure)
		# unregister JavaScript hook
		univention-config-registry unset "umc/web/hooks/univention-management-console-module-passwordchange"
		;;

	upgrade)
		;;

    failed-upgrade)
		;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

#DEBHELPER#

exit 0
