www/univention-management-console.svg usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/scalable/
www/* usr/share/univention-portal/
listener/*.py usr/lib/univention-directory-listener/system
univention-blog.png usr/share/univention-portal/
univention-portal-server usr/bin/
univention-portal-server.service /lib/systemd/system
portal-server-password-rotate usr/lib/univention-server/server_password_change.d/
univention-system-setup/cleanup-post.d/11_portal_restart usr/lib/univention-system-setup/cleanup-post.d
