sonar.projectKey=univention_dev_ucs_b516e798-f6ad-4963-8afd-0a16addd858d
sonar.projectName=Univention Corporate Server (UCS)
sonar.qualitygate.wait=true

# Source directories
sonar.sources=base, container, mail, management, monitoring, oidc, packaging, saml, services

# Test directories
sonar.tests=packaging/univention-unittests/python/univention/unittests, management/univention-appcenter/unittests, management/univention-management-console/tests, management/univention-web/tests, management/univention-management-console-module-lib/unittests, management/univention-directory-listener/tests, management/univention-portal/frontend/tests, management/univention-portal/unittests, management/univention-directory-notifier/tests, management/univention-directory-manager-modules/unittests, management/univention-self-service/unittests, management/univention-directory-reports/test, services/univention-radius/tests, services/univention-ldb-modules/tests, base/univention-group-membership-cache/unittest, base/univention-config-registry/tests, base/univention-system-activation/tests, base/univention-python/unittests, base/univention-debug/tests, base/univention-base-files/tests, base/univention-l10n-fr/fr/test, base/univention-system-setup/tests, base/univention-ipcalc/tests, base/univention-debug-python/tests, base/univention-ssl/tests, base/univention-updater/tests, base/univention-lib/unittests, base/univention-quota/test, base/univention-pam/tests, test

# Encoding and exclusions
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/test/**, **/tests/**, **/unittest/**, **/unittests/**, **/swagger-ui-standalone-preset.js


# Language-specific settings
sonar.python.version=3.11

# Coverage reports (uncomment if applicable)
# sonar.python.coverage.reportPaths=coverage*.xml
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Links
sonar.links.homepage=https://git.knut.univention.de/univention/dev/ucs
sonar.links.issue=https://git.knut.univention.de/univention/dev/ucs/-/issues
sonar.links.scm=https://git.knut.univention.de/univention/dev/ucs

