#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
"""Inserts copyright statements into REUSE.toml from all Copyright information in DEB-5 compatible copyright information in Debian packages in subdirectories."""

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import toml
from debian.copyright import Copyright, NotMachineReadableError  # 0.1.49


REPO_ROOT = Path('.').resolve()
REUSE_TOML_PATH = REPO_ROOT / 'REUSE.toml'
START_MARKER = '## BEGIN AUTOMATIC GENERATED COPYRIGHT INFORMATION'
END_MARKER = '## END AUTOMATIC GENERATED COPYRIGHT INFORMATION'
BLOCK_HEADLINE = '# This block is auto-generated by update-reuse-toml.py. Do not edit manually.'
RE_MARKER = re.compile(rf'{re.escape(START_MARKER)}.*?{re.escape(END_MARKER)}', flags=re.DOTALL)


@dataclass
class Annotation:
    path: str | list[str]
    spdx_license: str
    copyright_text: str | None = None
    precedence: str = 'override'

    def to_toml_dict(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            'path': self.path,
            'precedence': self.precedence,
            'SPDX-License-Identifier': self.spdx_license,
        }
        if self.copyright_text:
            data['SPDX-FileCopyrightText'] = self.copyright_text
        return data


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-n', '--dry-run', action='store_true', help='Do not change original file')
    args = parser.parse_args()

    generated_annotations: list[Annotation] = []
    for path, dep5 in find_dep5_files():
        generated_annotations.extend(build_annotations(dep5, path))
    # generated_annotations.sort(key=_annotation_sort_key)

    content = REUSE_TOML_PATH.read_text(encoding='utf-8') if REUSE_TOML_PATH.exists() else START_MARKER + END_MARKER
    if START_MARKER not in content:
        content += f'\n{START_MARKER}\n{END_MARKER}'

    replacement = toml.dumps({'annotations': [annotation.to_toml_dict() for annotation in generated_annotations]})
    new_content = RE_MARKER.sub(START_MARKER + '\n' + BLOCK_HEADLINE + '\n\n' + replacement + END_MARKER, content)

    if new_content != content:
        print(f'Updated {REUSE_TOML_PATH} with {len(generated_annotations)} annotations.')
        print('\n'.join(difflib.unified_diff(content.splitlines(), new_content.splitlines(), str(REUSE_TOML_PATH), str(REUSE_TOML_PATH))))
        if not args.dry_run:
            REUSE_TOML_PATH.write_text(new_content, encoding='utf-8')
        return 1

    return 0


def _annotation_sort_key(a: Annotation) -> tuple:
    path = a.path
    if isinstance(path, str):
        path_key = (path,)
    else:
        path_key = tuple(path)

    return (
        path_key,
        a.spdx_license,
        a.copyright_text,
    )


def find_dep5_files():
    for path in sorted(REPO_ROOT.glob('**/debian/copyright')):
        try:
            with open(path, encoding='utf-8') as fd:
                dep5 = Copyright(fd.read())
        except NotMachineReadableError:
            print('Not machine readable', path, file=sys.stderr)
            continue
        yield path, dep5


def normalize_pattern(pattern: str, base_path: Path):
    pattern = pattern.strip()
    # FIXME: multiple conditions may be true
    if pattern.endswith('/*'):
        pattern = pattern[:-1] + '**'
    elif pattern.endswith('/'):
        pattern += '**'
    elif '*' in pattern:
        pattern = pattern.replace('*', '**')
    elif '?' in pattern:
        pattern = pattern.replace('?', '*')

    full_path = base_path.parent.parent / pattern
    try:
        rel_path = full_path.relative_to(REPO_ROOT)
    except ValueError:
        rel_path = full_path
    return str(rel_path)


def build_annotations(dep5, base_path: Path) -> list[Annotation]:
    annotations: list[Annotation] = []
    for para in dep5.all_paragraphs():
        try:
            license_id = para.license.synopsis
            if not para.files or not license_id:
                continue
        except AttributeError:
            continue

        # if license_id.startswith('AGPL-3.0-only'):
        #     continue

        paths = [normalize_pattern(p, base_path) for p in para.files]
        annotations.append(
            Annotation(
                path=paths if len(paths) > 1 else paths[0],
                spdx_license=license_id.replace('WITH', 'AND'),
                copyright_text=para.copyright.strip().replace('\n', '\\n') if hasattr(para, 'copyright') else None,
            ),
        )
    return annotations


if __name__ == '__main__':
    sys.exit(main())
