#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright 2020-2022 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.


from importlib import import_module

import pytest

from univention.admin import modules, property as prop


@pytest.mark.parametrize(
        'object, property, expected_widget',
        [
            # users
            # users/user
            ('users/user', 'username', 'TextBox'),
            ('users/user', 'uidNumber', 'TextBox'),
            ('users/user', 'gidNumber', 'TextBox'),
            ('users/user', 'firstname', 'TextBox'),
            ('users/user', 'lastname', 'TextBox'),
            ('users/user', 'gecos', 'TextBox'),
            ('users/user', 'displayName', 'TextBox'),
            ('users/user', 'title', 'TextBox'),
            ('users/user', 'initials', 'TextBox'),
            ('users/user', 'preferredDeliveryMethod', 'TextBox'),
            ('users/user', 'sambaPrivileges', 'ComboBox'),
            ('users/user', 'description', 'TextBox'),
            ('users/user', 'organisation', 'TextBox'),
            ('users/user', 'userexpiry', 'DateBox'),
            ('users/user', 'passwordexpiry', 'DateBox'),
            ('users/user', 'pwdChangeNextLogin', 'CheckBox'),
            ('users/user', 'preferredLanguage', 'TextBox'),
            ('users/user', 'disabled', 'CheckBox'),
            ('users/user', 'accountActivationDate', 'ComplexInput'),
            ('users/user', 'locked', 'umc/modules/udm/LockedCheckBox'),
            ('users/user', 'lockedTime', 'TextBox'),
            ('users/user', 'unlock', 'CheckBox'),
            ('users/user', 'unlockTime', 'TextBox'),
            ('users/user', 'password', 'PasswordInputBox'),
            ('users/user', 'street', 'TextBox'),
            ('users/user', 'e-mail', 'TextBox'),
            ('users/user', 'postcode', 'TextBox'),
            ('users/user', 'postOfficeBox', 'TextBox'),
            ('users/user', 'city', 'TextBox'),
            ('users/user', 'country', 'ComboBox'),
            ('users/user', 'phone', 'TextBox'),
            ('users/user', 'employeeNumber', 'TextBox'),
            ('users/user', 'roomNumber', 'TextBox'),
            ('users/user', 'secretary', 'umc/modules/udm/MultiObjectSelect'),
            ('users/user', 'departmentNumber', 'TextBox'),
            ('users/user', 'employeeType', 'TextBox'),
            ('users/user', 'homePostalAddress', 'MultiInput'),
            ('users/user', 'physicalDeliveryOfficeName', 'TextBox'),
            ('users/user', 'homeTelephoneNumber', 'TextBox'),
            ('users/user', 'mobileTelephoneNumber', 'TextBox'),
            ('users/user', 'pagerTelephoneNumber', 'TextBox'),
            ('users/user', 'birthday', 'DateBox'),
            ('users/user', 'unixhome', 'TextBox'),
            ('users/user', 'shell', 'TextBox'),
            ('users/user', 'sambahome', 'TextBox'),
            ('users/user', 'scriptpath', 'TextBox'),
            ('users/user', 'profilepath', 'TextBox'),
            ('users/user', 'homedrive', 'TextBox'),
            ('users/user', 'sambaRID', 'TextBox'),
            ('users/user', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('users/user', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('users/user', 'mailHomeServer', 'umc/modules/udm/ComboBox'),
            ('users/user', 'mailPrimaryAddress', 'MailBox'),
            ('users/user', 'mailAlternativeAddress', 'MailBox'),
            ('users/user', 'mailForwardAddress', 'TextBox'),
            ('users/user', 'mailForwardCopyToSelf', 'ComboBox'),
            ('users/user', 'overridePWHistory', 'CheckBox'),
            ('users/user', 'overridePWLength', 'CheckBox'),
            ('users/user', 'homeShare', 'umc/modules/udm/ComboBox'),
            ('users/user', 'homeSharePath', 'TextBox'),
            ('users/user', 'sambaUserWorkstations', 'TextBox'),
            ('users/user', 'sambaLogonHours', 'MultiSelect'),
            ('users/user', 'jpegPhoto', 'ImageUploader'),
            ('users/user', 'userCertificate', 'umc/modules/udm/CertificateUploader'),
            ('users/user', 'certificateIssuerCountry', 'TextBox'),
            ('users/user', 'certificateIssuerState', 'TextBox'),
            ('users/user', 'certificateIssuerLocation', 'TextBox'),
            ('users/user', 'certificateIssuerOrganisation', 'TextBox'),
            ('users/user', 'certificateIssuerOrganisationalUnit', 'TextBox'),
            ('users/user', 'certificateIssuerCommonName', 'TextBox'),
            ('users/user', 'certificateIssuerMail', 'TextBox'),
            ('users/user', 'certificateSubjectCountry', 'TextBox'),
            ('users/user', 'certificateSubjectState', 'TextBox'),
            ('users/user', 'certificateSubjectLocation', 'TextBox'),
            ('users/user', 'certificateSubjectOrganisation', 'TextBox'),
            ('users/user', 'certificateSubjectOrganisationalUnit', 'TextBox'),
            ('users/user', 'certificateSubjectCommonName', 'TextBox'),
            ('users/user', 'certificateSubjectMail', 'TextBox'),
            ('users/user', 'certificateDateNotBefore', 'DateBox'),
            ('users/user', 'certificateDateNotAfter', 'DateBox'),
            ('users/user', 'certificateVersion', 'TextBox'),
            ('users/user', 'certificateSerial', 'TextBox'),
            ('users/user', 'umcProperty', 'MultiInput'),
            ('users/user', 'serviceSpecificPassword', 'TextBox'),
            # users/contact
            ('users/contact', 'cn', 'TextBox'),
            ('users/contact', 'lastname', 'TextBox'),
            ('users/contact', 'firstname', 'TextBox'),
            ('users/contact', 'title', 'TextBox'),
            ('users/contact', 'initials', 'TextBox'),
            ('users/contact', 'description', 'TextBox'),
            ('users/contact', 'displayName', 'TextBox'),
            ('users/contact', 'birthday', 'DateBox'),
            ('users/contact', 'jpegPhoto', 'ImageUploader'),
            ('users/contact', 'organisation', 'TextBox'),
            ('users/contact', 'employeeNumber', 'TextBox'),
            ('users/contact', 'employeeType', 'TextBox'),
            ('users/contact', 'secretary', 'umc/modules/udm/MultiObjectSelect'),
            ('users/contact', 'e-mail', 'TextBox'),
            ('users/contact', 'phone', 'TextBox'),
            ('users/contact', 'roomNumber', 'TextBox'),
            ('users/contact', 'departmentNumber', 'TextBox'),
            ('users/contact', 'street', 'TextBox'),
            ('users/contact', 'postcode', 'TextBox'),
            ('users/contact', 'postOfficeBox', 'TextBox'),
            ('users/contact', 'preferredLanguage', 'TextBox'),
            ('users/contact', 'city', 'TextBox'),
            ('users/contact', 'country', 'ComboBox'),
            ('users/contact', 'homeTelephoneNumber', 'TextBox'),
            ('users/contact', 'mobileTelephoneNumber', 'TextBox'),
            ('users/contact', 'pagerTelephoneNumber', 'TextBox'),
            ('users/contact', 'homePostalAddress', 'MultiInput'),
            ('users/contact', 'preferredDeliveryMethod', 'TextBox'),
            ('users/contact', 'physicalDeliveryOfficeName', 'TextBox'),
            # users/ldap
            ('users/ldap', 'username', 'TextBox'),
            ('users/ldap', 'lastname', 'TextBox'),
            ('users/ldap', 'name', 'TextBox'),
            ('users/ldap', 'description', 'TextBox'),
            ('users/ldap', 'disabled', 'CheckBox'),
            ('users/ldap', 'password', 'PasswordInputBox'),
            ('users/ldap', 'locked', 'umc/modules/udm/LockedCheckBox'),
            ('users/ldap', 'overridePWHistory', 'CheckBox'),
            ('users/ldap', 'overridePWLength', 'CheckBox'),
            # users/passwd
            ('users/passwd', 'username', 'TextBox'),
            ('users/passwd', 'password', 'PasswordInputBox'),
            # computers
            # computers/computer
            ('computers/computer', 'name', 'TextBox'),
            ('computers/computer', 'dnsAlias', 'TextBox'),
            ('computers/computer', 'description', 'TextBox'),
            ('computers/computer', 'mac', 'TextBox'),
            ('computers/computer', 'ip', 'TextBox'),
            ('computers/computer', 'inventoryNumber', 'TextBox'),
            ('computers/computer', 'fqdn', 'TextBox'),
            # computers/ipmanagedclient
            ('computers/ipmanagedclient', 'name', 'TextBox'),
            ('computers/ipmanagedclient', 'description', 'TextBox'),
            ('computers/ipmanagedclient', 'mac', 'TextBox'),
            ('computers/ipmanagedclient', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/ipmanagedclient', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/ipmanagedclient', 'ip', 'TextBox'),
            ('computers/ipmanagedclient', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/ipmanagedclient', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/ipmanagedclient', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/ipmanagedclient', 'dnsAlias', 'TextBox'),
            ('computers/ipmanagedclient', 'dhcpEntryZone', 'MultiInput'),
            ('computers/ipmanagedclient', 'inventoryNumber', 'TextBox'),
            ('computers/ipmanagedclient', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/ipmanagedclient', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/ipmanagedclient', 'domain', 'TextBox'),
            ('computers/ipmanagedclient', 'nagiosContactEmail', 'TextBox'),
            ('computers/ipmanagedclient', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/ipmanagedclient', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/linux
            ('computers/linux', 'name', 'TextBox'),
            ('computers/linux', 'description', 'TextBox'),
            ('computers/linux', 'operatingSystem', 'TextBox'),
            ('computers/linux', 'operatingSystemVersion', 'TextBox'),
            ('computers/linux', 'domain', 'TextBox'),
            ('computers/linux', 'mac', 'TextBox'),
            ('computers/linux', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/linux', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/linux', 'ip', 'TextBox'),
            ('computers/linux', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/linux', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/linux', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/linux', 'dnsAlias', 'TextBox'),
            ('computers/linux', 'dhcpEntryZone', 'MultiInput'),
            ('computers/linux', 'password', 'PasswordInputBox'),
            ('computers/linux', 'unixhome', 'TextBox'),
            ('computers/linux', 'shell', 'TextBox'),
            ('computers/linux', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/linux', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/linux', 'inventoryNumber', 'TextBox'),
            ('computers/linux', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/linux', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/linux', 'sambaRID', 'TextBox'),
            ('computers/linux', 'nagiosContactEmail', 'TextBox'),
            ('computers/linux', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/linux', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/macos
            ('computers/macos', 'name', 'TextBox'),
            ('computers/macos', 'description', 'TextBox'),
            ('computers/macos', 'operatingSystem', 'TextBox'),
            ('computers/macos', 'operatingSystemVersion', 'TextBox'),
            ('computers/macos', 'domain', 'TextBox'),
            ('computers/macos', 'mac', 'TextBox'),
            ('computers/macos', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/macos', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/macos', 'ip', 'TextBox'),
            ('computers/macos', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/macos', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/macos', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/macos', 'dnsAlias', 'TextBox'),
            ('computers/macos', 'dhcpEntryZone', 'MultiInput'),
            ('computers/macos', 'password', 'PasswordInputBox'),
            ('computers/macos', 'unixhome', 'TextBox'),
            ('computers/macos', 'shell', 'TextBox'),
            ('computers/macos', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/macos', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/macos', 'inventoryNumber', 'TextBox'),
            ('computers/macos', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/macos', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/macos', 'sambaRID', 'TextBox'),
            ('computers/macos', 'nagiosContactEmail', 'TextBox'),
            ('computers/macos', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/macos', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/windows
            ('computers/windows', 'name', 'TextBox'),
            ('computers/windows', 'description', 'TextBox'),
            ('computers/windows', 'operatingSystem', 'TextBox'),
            ('computers/windows', 'operatingSystemVersion', 'TextBox'),
            ('computers/windows', 'domain', 'TextBox'),
            ('computers/windows', 'mac', 'TextBox'),
            ('computers/windows', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/windows', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/windows', 'ip', 'TextBox'),
            ('computers/windows', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/windows', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/windows', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/windows', 'dnsAlias', 'TextBox'),
            ('computers/windows', 'dhcpEntryZone', 'MultiInput'),
            ('computers/windows', 'password', 'PasswordInputBox'),
            ('computers/windows', 'ntCompatibility', 'CheckBox'),
            ('computers/windows', 'unixhome', 'TextBox'),
            ('computers/windows', 'shell', 'TextBox'),
            ('computers/windows', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/windows', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/windows', 'inventoryNumber', 'TextBox'),
            ('computers/windows', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/windows', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/windows', 'sambaRID', 'TextBox'),
            ('computers/windows', 'nagiosContactEmail', 'TextBox'),
            ('computers/windows', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/windows', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/ubuntu
            ('computers/ubuntu', 'name', 'TextBox'),
            ('computers/ubuntu', 'description', 'TextBox'),
            ('computers/ubuntu', 'operatingSystem', 'TextBox'),
            ('computers/ubuntu', 'operatingSystemVersion', 'TextBox'),
            ('computers/ubuntu', 'domain', 'TextBox'),
            ('computers/ubuntu', 'mac', 'TextBox'),
            ('computers/ubuntu', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/ubuntu', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/ubuntu', 'ip', 'TextBox'),
            ('computers/ubuntu', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/ubuntu', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/ubuntu', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/ubuntu', 'dnsAlias', 'TextBox'),
            ('computers/ubuntu', 'dhcpEntryZone', 'MultiInput'),
            ('computers/ubuntu', 'password', 'PasswordInputBox'),
            ('computers/ubuntu', 'unixhome', 'TextBox'),
            ('computers/ubuntu', 'shell', 'TextBox'),
            ('computers/ubuntu', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/ubuntu', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/ubuntu', 'inventoryNumber', 'TextBox'),
            ('computers/ubuntu', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/ubuntu', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/ubuntu', 'sambaRID', 'TextBox'),
            ('computers/ubuntu', 'nagiosContactEmail', 'TextBox'),
            ('computers/ubuntu', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/ubuntu', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/domaincontroller_master
            ('computers/domaincontroller_master', 'name', 'TextBox'),
            ('computers/domaincontroller_master', 'description', 'TextBox'),
            ('computers/domaincontroller_master', 'operatingSystem', 'TextBox'),
            ('computers/domaincontroller_master', 'operatingSystemVersion', 'TextBox'),
            ('computers/domaincontroller_master', 'domain', 'TextBox'),
            ('computers/domaincontroller_master', 'mac', 'TextBox'),
            ('computers/domaincontroller_master', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_master', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_master', 'ip', 'TextBox'),
            ('computers/domaincontroller_master', 'serverRole', 'TextBox'),
            ('computers/domaincontroller_master', 'service', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_master', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/domaincontroller_master', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/domaincontroller_master', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/domaincontroller_master', 'dnsAlias', 'TextBox'),
            ('computers/domaincontroller_master', 'dhcpEntryZone', 'MultiInput'),
            ('computers/domaincontroller_master', 'password', 'PasswordInputBox'),
            ('computers/domaincontroller_master', 'unixhome', 'TextBox'),
            ('computers/domaincontroller_master', 'shell', 'TextBox'),
            ('computers/domaincontroller_master', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_master', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_master', 'reinstall', 'CheckBox'),
            ('computers/domaincontroller_master', 'reinstalloption', 'TextBox'),
            ('computers/domaincontroller_master', 'instprofile', 'TextBox'),
            ('computers/domaincontroller_master', 'inventoryNumber', 'TextBox'),
            ('computers/domaincontroller_master', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_master', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_master', 'sambaRID', 'TextBox'),
            ('computers/domaincontroller_master', 'nagiosContactEmail', 'TextBox'),
            ('computers/domaincontroller_master', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_master', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/domaincontroller_slave
            ('computers/domaincontroller_slave', 'name', 'TextBox'),
            ('computers/domaincontroller_slave', 'description', 'TextBox'),
            ('computers/domaincontroller_slave', 'operatingSystem', 'TextBox'),
            ('computers/domaincontroller_slave', 'operatingSystemVersion', 'TextBox'),
            ('computers/domaincontroller_slave', 'domain', 'TextBox'),
            ('computers/domaincontroller_slave', 'mac', 'TextBox'),
            ('computers/domaincontroller_slave', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_slave', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_slave', 'ip', 'TextBox'),
            ('computers/domaincontroller_slave', 'serverRole', 'TextBox'),
            ('computers/domaincontroller_slave', 'service', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_slave', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/domaincontroller_slave', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/domaincontroller_slave', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/domaincontroller_slave', 'dnsAlias', 'TextBox'),
            ('computers/domaincontroller_slave', 'dhcpEntryZone', 'MultiInput'),
            ('computers/domaincontroller_slave', 'password', 'PasswordInputBox'),
            ('computers/domaincontroller_slave', 'unixhome', 'TextBox'),
            ('computers/domaincontroller_slave', 'shell', 'TextBox'),
            ('computers/domaincontroller_slave', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_slave', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_slave', 'reinstall', 'CheckBox'),
            ('computers/domaincontroller_slave', 'reinstalloption', 'TextBox'),
            ('computers/domaincontroller_slave', 'instprofile', 'TextBox'),
            ('computers/domaincontroller_slave', 'inventoryNumber', 'TextBox'),
            ('computers/domaincontroller_slave', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_slave', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_slave', 'sambaRID', 'TextBox'),
            ('computers/domaincontroller_slave', 'nagiosContactEmail', 'TextBox'),
            ('computers/domaincontroller_slave', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_slave', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/domaincontroller_backup
            ('computers/domaincontroller_backup', 'name', 'TextBox'),
            ('computers/domaincontroller_backup', 'description', 'TextBox'),
            ('computers/domaincontroller_backup', 'operatingSystem', 'TextBox'),
            ('computers/domaincontroller_backup', 'operatingSystemVersion', 'TextBox'),
            ('computers/domaincontroller_backup', 'domain', 'TextBox'),
            ('computers/domaincontroller_backup', 'mac', 'TextBox'),
            ('computers/domaincontroller_backup', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_backup', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_backup', 'ip', 'TextBox'),
            ('computers/domaincontroller_backup', 'serverRole', 'TextBox'),
            ('computers/domaincontroller_backup', 'service', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_backup', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/domaincontroller_backup', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/domaincontroller_backup', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/domaincontroller_backup', 'dnsAlias', 'TextBox'),
            ('computers/domaincontroller_backup', 'dhcpEntryZone', 'MultiInput'),
            ('computers/domaincontroller_backup', 'password', 'PasswordInputBox'),
            ('computers/domaincontroller_backup', 'unixhome', 'TextBox'),
            ('computers/domaincontroller_backup', 'shell', 'TextBox'),
            ('computers/domaincontroller_backup', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_backup', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/domaincontroller_backup', 'reinstall', 'CheckBox'),
            ('computers/domaincontroller_backup', 'reinstalloption', 'TextBox'),
            ('computers/domaincontroller_backup', 'instprofile', 'TextBox'),
            ('computers/domaincontroller_backup', 'inventoryNumber', 'TextBox'),
            ('computers/domaincontroller_backup', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_backup', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_backup', 'sambaRID', 'TextBox'),
            ('computers/domaincontroller_backup', 'nagiosContactEmail', 'TextBox'),
            ('computers/domaincontroller_backup', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/domaincontroller_backup', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/memberserver
            ('computers/memberserver', 'name', 'TextBox'),
            ('computers/memberserver', 'description', 'TextBox'),
            ('computers/memberserver', 'operatingSystem', 'TextBox'),
            ('computers/memberserver', 'operatingSystemVersion', 'TextBox'),
            ('computers/memberserver', 'domain', 'TextBox'),
            ('computers/memberserver', 'mac', 'TextBox'),
            ('computers/memberserver', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/memberserver', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/memberserver', 'ip', 'TextBox'),
            ('computers/memberserver', 'serverRole', 'TextBox'),
            ('computers/memberserver', 'service', 'umc/modules/udm/ComboBox'),
            ('computers/memberserver', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/memberserver', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/memberserver', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/memberserver', 'dnsAlias', 'TextBox'),
            ('computers/memberserver', 'dhcpEntryZone', 'MultiInput'),
            ('computers/memberserver', 'password', 'PasswordInputBox'),
            ('computers/memberserver', 'unixhome', 'TextBox'),
            ('computers/memberserver', 'shell', 'TextBox'),
            ('computers/memberserver', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/memberserver', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/memberserver', 'reinstall', 'CheckBox'),
            ('computers/memberserver', 'reinstalloption', 'TextBox'),
            ('computers/memberserver', 'instprofile', 'TextBox'),
            ('computers/memberserver', 'inventoryNumber', 'TextBox'),
            ('computers/memberserver', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/memberserver', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/memberserver', 'sambaRID', 'TextBox'),
            ('computers/memberserver', 'nagiosContactEmail', 'TextBox'),
            ('computers/memberserver', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/memberserver', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # computers/windows_domaincontroller
            ('computers/windows_domaincontroller', 'name', 'TextBox'),
            ('computers/windows_domaincontroller', 'description', 'TextBox'),
            ('computers/windows_domaincontroller', 'operatingSystem', 'TextBox'),
            ('computers/windows_domaincontroller', 'operatingSystemVersion', 'TextBox'),
            ('computers/windows_domaincontroller', 'domain', 'TextBox'),
            ('computers/windows_domaincontroller', 'mac', 'TextBox'),
            ('computers/windows_domaincontroller', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/windows_domaincontroller', 'network', 'umc/modules/udm/ComboBox'),
            ('computers/windows_domaincontroller', 'ip', 'TextBox'),
            ('computers/windows_domaincontroller', 'serverRole', 'TextBox'),
            ('computers/windows_domaincontroller', 'service', 'umc/modules/udm/ComboBox'),
            ('computers/windows_domaincontroller', 'dnsEntryZoneForward', 'MultiInput'),
            ('computers/windows_domaincontroller', 'dnsEntryZoneReverse', 'MultiInput'),
            ('computers/windows_domaincontroller', 'dnsEntryZoneAlias', 'MultiInput'),
            ('computers/windows_domaincontroller', 'dnsAlias', 'TextBox'),
            ('computers/windows_domaincontroller', 'dhcpEntryZone', 'MultiInput'),
            ('computers/windows_domaincontroller', 'password', 'PasswordInputBox'),
            ('computers/windows_domaincontroller', 'unixhome', 'TextBox'),
            ('computers/windows_domaincontroller', 'shell', 'TextBox'),
            ('computers/windows_domaincontroller', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/windows_domaincontroller', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('computers/windows_domaincontroller', 'inventoryNumber', 'TextBox'),
            ('computers/windows_domaincontroller', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/windows_domaincontroller', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/windows_domaincontroller', 'sambaRID', 'TextBox'),
            ('computers/windows_domaincontroller', 'nagiosContactEmail', 'TextBox'),
            ('computers/windows_domaincontroller', 'nagiosParents', 'umc/modules/udm/MultiObjectSelect'),
            ('computers/windows_domaincontroller', 'nagiosServices', 'umc/modules/udm/MultiObjectSelect'),
            # dhcp
            # dhcp/dhcp
            ('dhcp/dhcp', 'name', 'TextBox'),
            # dhcp/host
            ('dhcp/host', 'host', 'TextBox'),
            ('dhcp/host', 'hwaddress', 'ComplexInput'),
            ('dhcp/host', 'fixedaddress', 'TextBox'),
            ('dhcp/host', 'option', 'TextBox'),
            ('dhcp/host', 'statements', 'TextArea'),
            # dhcp/pool
            ('dhcp/pool', 'name', 'TextBox'),
            ('dhcp/pool', 'range', 'MultiInput'),
            ('dhcp/pool', 'failover_peer', 'TextBox'),
            ('dhcp/pool', 'known_clients', 'ComboBox'),
            ('dhcp/pool', 'unknown_clients', 'ComboBox'),
            ('dhcp/pool', 'dynamic_bootp_clients', 'ComboBox'),
            ('dhcp/pool', 'all_clients', 'ComboBox'),
            ('dhcp/pool', 'option', 'TextBox'),
            ('dhcp/pool', 'statements', 'TextArea'),
            # dhcp/server
            ('dhcp/server', 'server', 'TextBox'),
            # dhcp/service
            ('dhcp/service', 'service', 'TextBox'),
            # dhcp/shared
            ('dhcp/shared', 'name', 'TextBox'),
            ('dhcp/shared', 'option', 'TextBox'),
            ('dhcp/shared', 'statements', 'TextArea'),
            # dhcp/sharedsubnet
            ('dhcp/sharedsubnet', 'subnet', 'TextBox'),
            ('dhcp/sharedsubnet', 'subnetmask', 'TextBox'),
            ('dhcp/sharedsubnet', 'broadcastaddress', 'TextBox'),
            ('dhcp/sharedsubnet', 'range', 'MultiInput'),
            ('dhcp/sharedsubnet', 'option', 'TextBox'),
            ('dhcp/sharedsubnet', 'statements', 'TextArea'),
            # dhcp/subnet
            ('dhcp/subnet', 'subnet', 'TextBox'),
            ('dhcp/subnet', 'subnetmask', 'TextBox'),
            ('dhcp/subnet', 'broadcastaddress', 'TextBox'),
            ('dhcp/subnet', 'range', 'MultiInput'),
            ('dhcp/subnet', 'option', 'TextBox'),
            ('dhcp/subnet', 'statements', 'TextArea'),
            # groups
            # groups/group
            ('groups/group', 'name', 'TextBox'),
            ('groups/group', 'gidNumber', 'TextBox'),
            ('groups/group', 'sambaRID', 'TextBox'),
            ('groups/group', 'sambaGroupType', 'ComboBox'),
            ('groups/group', 'sambaPrivileges', 'ComboBox'),
            ('groups/group', 'adGroupType', 'ComboBox'),
            ('groups/group', 'description', 'TextBox'),
            ('groups/group', 'users', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'hosts', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'mailAddress', 'MailBox'),
            ('groups/group', 'memberOf', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'memberOf', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'nestedGroup', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'nestedGroup', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'allowedEmailUsers', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'allowedEmailGroups', 'umc/modules/udm/MultiObjectSelect'),
            ('groups/group', 'allowedEmailGroups', 'umc/modules/udm/MultiObjectSelect'),
            # dns
            # dns/dns
            ('dns/dns', 'name', 'TextBox'),
            # dns/forward_zone
            ('dns/forward_zone', 'zone', 'TextBox'),
            ('dns/forward_zone', 'zonettl', 'ComplexInput'),
            ('dns/forward_zone', 'contact', 'TextBox'),
            ('dns/forward_zone', 'serial', 'TextBox'),
            ('dns/forward_zone', 'refresh', 'ComplexInput'),
            ('dns/forward_zone', 'retry', 'ComplexInput'),
            ('dns/forward_zone', 'expire', 'ComplexInput'),
            ('dns/forward_zone', 'ttl', 'ComplexInput'),
            ('dns/forward_zone', 'nameserver', 'TextBox'),
            ('dns/forward_zone', 'mx', 'MultiInput'),
            ('dns/forward_zone', 'txt', 'TextBox'),
            ('dns/forward_zone', 'a', 'TextBox'),
            # dns/host_record
            ('dns/host_record', 'name', 'TextBox'),
            ('dns/host_record', 'zonettl', 'ComplexInput'),
            ('dns/host_record', 'a', 'TextBox'),
            ('dns/host_record', 'mx', 'MultiInput'),
            ('dns/host_record', 'txt', 'TextBox'),
            # dns/ns_record
            ('dns/ns_record', 'zone', 'TextBox'),
            ('dns/ns_record', 'zonettl', 'ComplexInput'),
            ('dns/ns_record', 'nameserver', 'TextBox'),
            # dns/ptr_record
            ('dns/ptr_record', 'address', 'TextBox'),
            ('dns/ptr_record', 'ip', 'TextBox'),
            ('dns/ptr_record', 'ptr_record', 'TextBox'),
            # dns/reverse_zone
            ('dns/reverse_zone', 'subnet', 'TextBox'),
            ('dns/reverse_zone', 'zonettl', 'ComplexInput'),
            ('dns/reverse_zone', 'contact', 'TextBox'),
            ('dns/reverse_zone', 'serial', 'TextBox'),
            ('dns/reverse_zone', 'refresh', 'ComplexInput'),
            ('dns/reverse_zone', 'retry', 'ComplexInput'),
            ('dns/reverse_zone', 'expire', 'ComplexInput'),
            ('dns/reverse_zone', 'ttl', 'ComplexInput'),
            ('dns/reverse_zone', 'nameserver', 'TextBox'),
            # dns/srv_record
            ('dns/srv_record', 'name', 'ComplexInput'),
            ('dns/srv_record', 'location', 'MultiInput'),
            ('dns/srv_record', 'zonettl', 'ComplexInput'),
            # dns/txt_record
            ('dns/txt_record', 'name', 'TextBox'),
            ('dns/txt_record', 'zonettl', 'ComplexInput'),
            ('dns/txt_record', 'txt', 'TextBox'),
            # kerberos
            # kerberos/kdcentry
            ('kerberos/kdcentry', 'name', 'TextBox'),
            ('kerberos/kdcentry', 'description', 'TextBox'),
            ('kerberos/kdcentry', 'password', 'PasswordInputBox'),
            ('kerberos/kdcentry', 'generateRandomPassword', 'CheckBox'),
            ('kerberos/kdcentry', 'keyVersionNumber', 'TextBox'),
            ('kerberos/kdcentry', 'KDCFlags', 'TextBox'),
            ('kerberos/kdcentry', 'maxLife', 'TextBox'),
            ('kerberos/kdcentry', 'maxRenew', 'TextBox'),
            # mail
            # mail/domain
            ('mail/domain', 'name', 'TextBox'),
            # mail/folder
            ('mail/folder', 'name', 'TextBox'),
            ('mail/folder', 'mailDomain', 'ComboBox'),
            ('mail/folder', 'sharedFolderUserACL', 'MultiInput'),
            ('mail/folder', 'sharedFolderGroupACL', 'MultiInput'),
            ('mail/folder', 'mailQuota', 'TextBox'),
            ('mail/folder', 'mailHomeServer', 'umc/modules/udm/ComboBox'),
            ('mail/folder', 'mailPrimaryAddress', 'MailBox'),
            # mail/lists
            ('mail/lists', 'name', 'TextBox'),
            ('mail/lists', 'description', 'TextBox'),
            ('mail/lists', 'members', 'TextBox'),
            ('mail/lists', 'mailAddress', 'MailBox'),
            ('mail/lists', 'allowedEmailUsers', 'umc/modules/udm/MultiObjectSelect'),
            ('mail/lists', 'allowedEmailGroups', 'umc/modules/udm/MultiObjectSelect'),
            ('mail/lists', 'allowedEmailGroups', 'umc/modules/udm/MultiObjectSelect'),
            # mail/mail
            ('mail/mail', 'name', 'TextBox'),
            # nagios
            # nagios/nagios
            ('nagios/nagios', 'name', 'TextBox'),
            # nagios/service
            ('nagios/service', 'name', 'TextBox'),
            # nagios/timeperiod
            ('nagios/timeperiod', 'name', 'TextBox'),
            ('nagios/timeperiod', 'description', 'TextBox'),
            ('nagios/timeperiod', 'periodMonday', 'TextBox'),
            ('nagios/timeperiod', 'periodTuesday', 'TextBox'),
            ('nagios/timeperiod', 'periodWednesday', 'TextBox'),
            ('nagios/timeperiod', 'periodThursday', 'TextBox'),
            ('nagios/timeperiod', 'periodFriday', 'TextBox'),
            ('nagios/timeperiod', 'periodSaturday', 'TextBox'),
            ('nagios/timeperiod', 'periodSunday', 'TextBox'),
            # networks
            # networks/network
            ('networks/network', 'name', 'TextBox'),
            ('networks/network', 'network', 'TextBox'),
            ('networks/network', 'netmask', 'TextBox'),
            ('networks/network', 'nextIp', 'TextBox'),
            ('networks/network', 'ipRange', 'MultiInput'),
            ('networks/network', 'dnsEntryZoneForward', 'umc/modules/udm/ComboBox'),
            ('networks/network', 'dnsEntryZoneReverse', 'umc/modules/udm/ComboBox'),
            ('networks/network', 'dhcpEntryZone', 'umc/modules/udm/ComboBox'),
            # policies
            # policies/admin_container
            ('policies/admin_container', 'name', 'TextBox'),
            ('policies/admin_container', 'listModules', 'ComboBox'),
            ('policies/admin_container', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/admin_container', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/admin_container', 'fixedAttributes', 'ComboBox'),
            ('policies/admin_container', 'emptyAttributes', 'ComboBox'),
            ('policies/admin_container', 'ldapFilter', 'TextBox'),
            # policies/desktop
            ('policies/desktop', 'name', 'TextBox'),
            ('policies/desktop', 'language', 'ComboBox'),
            ('policies/desktop', 'profile', 'ComboBox'),
            ('policies/desktop', 'logonScripts', 'TextBox'),
            ('policies/desktop', 'logoutScripts', 'TextBox'),
            ('policies/desktop', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/desktop', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/desktop', 'fixedAttributes', 'ComboBox'),
            ('policies/desktop', 'emptyAttributes', 'ComboBox'),
            ('policies/desktop', 'ldapFilter', 'TextBox'),
            # policies/dhcp_boot
            ('policies/dhcp_boot', 'name', 'TextBox'),
            ('policies/dhcp_boot', 'boot_server', 'TextBox'),
            ('policies/dhcp_boot', 'boot_filename', 'TextBox'),
            ('policies/dhcp_boot', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_boot', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_boot', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_boot', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_boot', 'ldapFilter', 'TextBox'),
            # policies/dhcp_dns
            ('policies/dhcp_dns', 'name', 'TextBox'),
            ('policies/dhcp_dns', 'domain_name', 'TextBox'),
            ('policies/dhcp_dns', 'domain_name_servers', 'TextBox'),
            ('policies/dhcp_dns', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_dns', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_dns', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_dns', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_dns', 'ldapFilter', 'TextBox'),
            # policies/dhcp_leasetime
            ('policies/dhcp_leasetime', 'name', 'TextBox'),
            ('policies/dhcp_leasetime', 'lease_time_default', 'ComplexInput'),
            ('policies/dhcp_leasetime', 'lease_time_max', 'ComplexInput'),
            ('policies/dhcp_leasetime', 'lease_time_min', 'ComplexInput'),
            ('policies/dhcp_leasetime', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_leasetime', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_leasetime', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_leasetime', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_leasetime', 'ldapFilter', 'TextBox'),
            # policies/dhcp_netbios
            ('policies/dhcp_netbios', 'name', 'TextBox'),
            ('policies/dhcp_netbios', 'netbios_name_servers', 'TextBox'),
            ('policies/dhcp_netbios', 'netbios_scope', 'TextBox'),
            ('policies/dhcp_netbios', 'netbios_node_type', 'ComboBox'),
            ('policies/dhcp_netbios', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_netbios', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_netbios', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_netbios', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_netbios', 'ldapFilter', 'TextBox'),
            # policies/dhcp_routing
            ('policies/dhcp_routing', 'name', 'TextBox'),
            ('policies/dhcp_routing', 'routers', 'TextBox'),
            ('policies/dhcp_routing', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_routing', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_routing', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_routing', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_routing', 'ldapFilter', 'TextBox'),
            # policies/dhcp_scope
            ('policies/dhcp_scope', 'name', 'TextBox'),
            ('policies/dhcp_scope', 'scopeUnknownClients', 'ComboBox'),
            ('policies/dhcp_scope', 'bootp', 'ComboBox'),
            ('policies/dhcp_scope', 'booting', 'ComboBox'),
            ('policies/dhcp_scope', 'duplicates', 'ComboBox'),
            ('policies/dhcp_scope', 'declines', 'ComboBox'),
            ('policies/dhcp_scope', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_scope', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_scope', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_scope', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_scope', 'ldapFilter', 'TextBox'),
            # policies/dhcp_statements
            ('policies/dhcp_statements', 'name', 'TextBox'),
            ('policies/dhcp_statements', 'authoritative', 'ComboBox'),
            ('policies/dhcp_statements', 'boot-unknown-clients', 'ComboBox'),
            ('policies/dhcp_statements', 'pingCheck', 'ComboBox'),
            ('policies/dhcp_statements', 'getLeaseHostnames', 'ComboBox'),
            ('policies/dhcp_statements', 'serverIdentifier', 'TextBox'),
            ('policies/dhcp_statements', 'serverName', 'TextBox'),
            ('policies/dhcp_statements', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_statements', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/dhcp_statements', 'fixedAttributes', 'ComboBox'),
            ('policies/dhcp_statements', 'emptyAttributes', 'ComboBox'),
            ('policies/dhcp_statements', 'ldapFilter', 'TextBox'),
            # policies/ldapserver
            ('policies/ldapserver', 'name', 'TextBox'),
            ('policies/ldapserver', 'ldapServer', 'umc/modules/udm/ComboBox'),
            ('policies/ldapserver', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/ldapserver', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/ldapserver', 'fixedAttributes', 'ComboBox'),
            ('policies/ldapserver', 'emptyAttributes', 'ComboBox'),
            ('policies/ldapserver', 'ldapFilter', 'TextBox'),
            # policies/maintenance
            ('policies/maintenance', 'name', 'TextBox'),
            ('policies/maintenance', 'startup', 'CheckBox'),
            ('policies/maintenance', 'shutdown', 'CheckBox'),
            ('policies/maintenance', 'reboot', 'ComboBox'),
            ('policies/maintenance', 'cron', 'CheckBox'),
            ('policies/maintenance', 'month', 'ComboBox'),
            ('policies/maintenance', 'day', 'ComboBox'),
            ('policies/maintenance', 'weekday', 'ComboBox'),
            ('policies/maintenance', 'hour', 'ComboBox'),
            ('policies/maintenance', 'minute', 'ComboBox'),
            ('policies/maintenance', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/maintenance', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/maintenance', 'fixedAttributes', 'ComboBox'),
            ('policies/maintenance', 'emptyAttributes', 'ComboBox'),
            ('policies/maintenance', 'ldapFilter', 'TextBox'),
            # policies/masterpackages
            ('policies/masterpackages', 'name', 'TextBox'),
            ('policies/masterpackages', 'masterPackages', 'ComboBox'),
            ('policies/masterpackages', 'masterPackagesRemove', 'ComboBox'),
            ('policies/masterpackages', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/masterpackages', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/masterpackages', 'fixedAttributes', 'ComboBox'),
            ('policies/masterpackages', 'emptyAttributes', 'ComboBox'),
            ('policies/masterpackages', 'ldapFilter', 'TextBox'),
            # policies/memberpackages
            ('policies/memberpackages', 'name', 'TextBox'),
            ('policies/memberpackages', 'memberPackages', 'ComboBox'),
            ('policies/memberpackages', 'memberPackagesRemove', 'ComboBox'),
            ('policies/memberpackages', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/memberpackages', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/memberpackages', 'fixedAttributes', 'ComboBox'),
            ('policies/memberpackages', 'emptyAttributes', 'ComboBox'),
            ('policies/memberpackages', 'ldapFilter', 'TextBox'),
            # policies/nfsmounts
            ('policies/nfsmounts', 'name', 'TextBox'),
            ('policies/nfsmounts', 'nfsMounts', 'MultiInput'),
            ('policies/nfsmounts', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/nfsmounts', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/nfsmounts', 'fixedAttributes', 'ComboBox'),
            ('policies/nfsmounts', 'emptyAttributes', 'ComboBox'),
            ('policies/nfsmounts', 'ldapFilter', 'TextBox'),
            # policies/printserver
            ('policies/printserver', 'name', 'TextBox'),
            ('policies/printserver', 'printServer', 'umc/modules/udm/ComboBox'),
            ('policies/printserver', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/printserver', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/printserver', 'fixedAttributes', 'ComboBox'),
            ('policies/printserver', 'emptyAttributes', 'ComboBox'),
            ('policies/printserver', 'ldapFilter', 'TextBox'),
            # policies/pwhistory
            ('policies/pwhistory', 'name', 'TextBox'),
            ('policies/pwhistory', 'length', 'TextBox'),
            ('policies/pwhistory', 'expiryInterval', 'TextBox'),
            ('policies/pwhistory', 'pwLength', 'TextBox'),
            ('policies/pwhistory', 'pwQualityCheck', 'CheckBox'),
            ('policies/pwhistory', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/pwhistory', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/pwhistory', 'fixedAttributes', 'ComboBox'),
            ('policies/pwhistory', 'emptyAttributes', 'ComboBox'),
            ('policies/pwhistory', 'ldapFilter', 'TextBox'),
            # policies/registry
            ('policies/registry', 'name', 'TextBox'),
            ('policies/registry', 'registry', 'MultiInput'),
            ('policies/registry', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/registry', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/registry', 'fixedAttributes', 'ComboBox'),
            ('policies/registry', 'emptyAttributes', 'ComboBox'),
            ('policies/registry', 'ldapFilter', 'TextBox'),
            # policies/release
            ('policies/release', 'name', 'TextBox'),
            ('policies/release', 'activate', 'CheckBox'),
            ('policies/release', 'releaseVersion', 'TextBox'),
            ('policies/release', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/release', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/release', 'fixedAttributes', 'ComboBox'),
            ('policies/release', 'emptyAttributes', 'ComboBox'),
            ('policies/release', 'ldapFilter', 'TextBox'),
            # policies/repositoryserver
            ('policies/repositoryserver', 'name', 'TextBox'),
            ('policies/repositoryserver', 'repositoryServer', 'umc/modules/udm/ComboBox'),
            ('policies/repositoryserver', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/repositoryserver', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/repositoryserver', 'fixedAttributes', 'ComboBox'),
            ('policies/repositoryserver', 'emptyAttributes', 'ComboBox'),
            ('policies/repositoryserver', 'ldapFilter', 'TextBox'),
            # policies/share_userquota
            ('policies/share_userquota', 'name', 'TextBox'),
            ('policies/share_userquota', 'softLimitSpace', 'TextBox'),
            ('policies/share_userquota', 'hardLimitSpace', 'TextBox'),
            ('policies/share_userquota', 'softLimitInodes', 'TextBox'),
            ('policies/share_userquota', 'hardLimitInodes', 'TextBox'),
            ('policies/share_userquota', 'reapplyeverylogin', 'CheckBox'),
            ('policies/share_userquota', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/share_userquota', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/share_userquota', 'fixedAttributes', 'ComboBox'),
            ('policies/share_userquota', 'emptyAttributes', 'ComboBox'),
            ('policies/share_userquota', 'ldapFilter', 'TextBox'),
            # policies/slavepackages
            ('policies/slavepackages', 'name', 'TextBox'),
            ('policies/slavepackages', 'slavePackages', 'ComboBox'),
            ('policies/slavepackages', 'slavePackagesRemove', 'ComboBox'),
            ('policies/slavepackages', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/slavepackages', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/slavepackages', 'fixedAttributes', 'ComboBox'),
            ('policies/slavepackages', 'emptyAttributes', 'ComboBox'),
            ('policies/slavepackages', 'ldapFilter', 'TextBox'),
            # policies/umc
            ('policies/umc', 'name', 'TextBox'),
            ('policies/umc', 'allow', 'umc/modules/udm/ComboBox'),
            ('policies/umc', 'requiredObjectClasses', 'SuggestionBox'),
            ('policies/umc', 'prohibitedObjectClasses', 'SuggestionBox'),
            ('policies/umc', 'fixedAttributes', 'ComboBox'),
            ('policies/umc', 'emptyAttributes', 'ComboBox'),
            ('policies/umc', 'ldapFilter', 'TextBox'),
            # settings
            # settings/cn
            ('settings/cn', 'name', 'TextBox'),
            # settings/data
            ('settings/data', 'name', 'TextBox'),
            ('settings/data', 'description', 'TextBox'),
            ('settings/data', 'filename', 'TextBox'),
            ('settings/data', 'data', 'TextArea'),
            ('settings/data', 'data_type', 'TextBox'),
            ('settings/data', 'ucsversionstart', 'TextBox'),
            ('settings/data', 'ucsversionend', 'TextBox'),
            ('settings/data', 'meta', 'TextBox'),
            ('settings/data', 'package', 'TextBox'),
            ('settings/data', 'packageversion', 'TextBox'),
            # settings/default
            ('settings/default', 'name', 'TextBox'),
            ('settings/default', 'defaultGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultComputerGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultComputerGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultDomainControllerGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultDomainControllerGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultDomainControllerMBGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultDomainControllerMBGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultMemberServerGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultMemberServerGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultClientGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultClientGroup', 'umc/modules/udm/ComboBox'),
            ('settings/default', 'defaultKdeProfiles', 'TextBox'),
            # settings/directory
            ('settings/directory', 'name', 'TextBox'),
            ('settings/directory', 'policies', 'TextBox'),
            ('settings/directory', 'dns', 'TextBox'),
            ('settings/directory', 'dhcp', 'TextBox'),
            ('settings/directory', 'users', 'TextBox'),
            ('settings/directory', 'groups', 'TextBox'),
            ('settings/directory', 'computers', 'TextBox'),
            ('settings/directory', 'domaincontroller', 'TextBox'),
            ('settings/directory', 'networks', 'TextBox'),
            ('settings/directory', 'shares', 'TextBox'),
            ('settings/directory', 'printers', 'TextBox'),
            ('settings/directory', 'mail', 'TextBox'),
            ('settings/directory', 'license', 'TextBox'),
            # settings/extended_attribute
            ('settings/extended_attribute', 'name', 'TextBox'),
            ('settings/extended_attribute', 'shortDescription', 'TextBox'),
            ('settings/extended_attribute', 'longDescription', 'TextBox'),
            ('settings/extended_attribute', 'translationShortDescription', 'MultiInput'),
            ('settings/extended_attribute', 'translationLongDescription', 'MultiInput'),
            ('settings/extended_attribute', 'translationTabName', 'MultiInput'),
            ('settings/extended_attribute', 'translationGroupName', 'MultiInput'),
            ('settings/extended_attribute', 'syntax', 'SuggestionBox'),
            ('settings/extended_attribute', 'hook', 'TextBox'),
            ('settings/extended_attribute', 'multivalue', 'CheckBox'),
            ('settings/extended_attribute', 'default', 'TextBox'),
            ('settings/extended_attribute', 'disableUDMWeb', 'CheckBox'),
            ('settings/extended_attribute', 'tabName', 'TextBox'),
            ('settings/extended_attribute', 'tabPosition', 'TextBox'),
            ('settings/extended_attribute', 'groupName', 'TextBox'),
            ('settings/extended_attribute', 'groupPosition', 'TextBox'),
            ('settings/extended_attribute', 'tabAdvanced', 'CheckBox'),
            ('settings/extended_attribute', 'overwriteTab', 'CheckBox'),
            ('settings/extended_attribute', 'overwritePosition', 'TextBox'),
            ('settings/extended_attribute', 'fullWidth', 'CheckBox'),
            ('settings/extended_attribute', 'ldapMapping', 'SuggestionBox'),
            ('settings/extended_attribute', 'mayChange', 'CheckBox'),
            ('settings/extended_attribute', 'notEditable', 'CheckBox'),
            ('settings/extended_attribute', 'valueRequired', 'CheckBox'),
            ('settings/extended_attribute', 'objectClass', 'SuggestionBox'),
            ('settings/extended_attribute', 'deleteObjectClass', 'CheckBox'),
            ('settings/extended_attribute', 'module', 'ComboBox'),
            ('settings/extended_attribute', 'version', 'TextBox'),
            ('settings/extended_attribute', 'CLIName', 'TextBox'),
            ('settings/extended_attribute', 'options', 'SuggestionBox'),
            ('settings/extended_attribute', 'doNotSearch', 'CheckBox'),
            ('settings/extended_attribute', 'copyable', 'CheckBox'),
            # settings/extended_options
            ('settings/extended_options', 'name', 'TextBox'),
            ('settings/extended_options', 'shortDescription', 'TextBox'),
            ('settings/extended_options', 'longDescription', 'TextBox'),
            ('settings/extended_options', 'translationShortDescription', 'MultiInput'),
            ('settings/extended_options', 'translationLongDescription', 'MultiInput'),
            ('settings/extended_options', 'default', 'CheckBox'),
            ('settings/extended_options', 'editable', 'CheckBox'),
            ('settings/extended_options', 'module', 'ComboBox'),
            ('settings/extended_options', 'objectClass', 'SuggestionBox'),
            ('settings/extended_options', 'isApp', 'CheckBox'),
            # settings/ldapacl
            ('settings/ldapacl', 'name', 'TextBox'),
            ('settings/ldapacl', 'filename', 'TextBox'),
            ('settings/ldapacl', 'data', 'TextArea'),
            ('settings/ldapacl', 'active', 'CheckBox'),
            ('settings/ldapacl', 'appidentifier', 'TextArea'),
            ('settings/ldapacl', 'package', 'TextBox'),
            ('settings/ldapacl', 'packageversion', 'TextBox'),
            ('settings/ldapacl', 'ucsversionstart', 'TextBox'),
            ('settings/ldapacl', 'ucsversionend', 'TextBox'),
            # settings/ldapschema
            ('settings/ldapschema', 'name', 'TextBox'),
            ('settings/ldapschema', 'filename', 'TextBox'),
            ('settings/ldapschema', 'data', 'TextArea'),
            ('settings/ldapschema', 'active', 'CheckBox'),
            ('settings/ldapschema', 'appidentifier', 'TextArea'),
            ('settings/ldapschema', 'package', 'TextBox'),
            ('settings/ldapschema', 'packageversion', 'TextBox'),
            # settings/license
            ('settings/license', 'name', 'TextBox'),
            ('settings/license', 'expires', 'TextBox'),
            ('settings/license', 'module', 'TextBox'),
            ('settings/license', 'base', 'TextBox'),
            ('settings/license', 'signature', 'TextBox'),
            ('settings/license', 'accounts', 'TextBox'),
            ('settings/license', 'clients', 'TextBox'),
            ('settings/license', 'groupwareaccounts', 'TextBox'),
            ('settings/license', 'desktops', 'TextBox'),
            ('settings/license', 'productTypes', 'TextBox'),
            ('settings/license', 'oemProductTypes', 'TextBox'),
            ('settings/license', 'product', 'TextBox'),
            ('settings/license', 'keyID', 'TextBox'),
            ('settings/license', 'servers', 'TextBox'),
            ('settings/license', 'support', 'TextBox'),
            ('settings/license', 'premiumsupport', 'TextBox'),
            ('settings/license', 'managedclients', 'TextBox'),
            ('settings/license', 'users', 'TextBox'),
            ('settings/license', 'virtualdesktopusers', 'TextBox'),
            ('settings/license', 'virtualdesktopclients', 'TextBox'),
            ('settings/license', 'corporateclients', 'TextBox'),
            ('settings/license', 'version', 'TextBox'),
            # settings/lock
            ('settings/lock', 'name', 'TextBox'),
            ('settings/lock', 'locktime', 'TextBox'),
            # settings/packages
            ('settings/packages', 'name', 'TextBox'),
            ('settings/packages', 'packageList', 'TextBox'),
            # settings/portal_all
            ('settings/portal_all', 'name', 'TextBox'),
            ('settings/portal_all', 'displayName', 'MultiInput'),
            # settings/portal_category
            ('settings/portal_category', 'name', 'TextBox'),
            ('settings/portal_category', 'displayName', 'MultiInput'),
            # settings/portal_entry
            ('settings/portal_entry', 'name', 'TextBox'),
            ('settings/portal_entry', 'displayName', 'MultiInput'),
            ('settings/portal_entry', 'description', 'MultiInput'),
            ('settings/portal_entry', 'favorite', 'CheckBox'),
            ('settings/portal_entry', 'category', 'ComboBox'),
            ('settings/portal_entry', 'link', 'TextBox'),
            ('settings/portal_entry', 'portal', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/portal_entry', 'authRestriction', 'ComboBox'),
            ('settings/portal_entry', 'allowedGroups', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/portal_entry', 'allowedGroups', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/portal_entry', 'activated', 'CheckBox'),
            ('settings/portal_entry', 'icon', 'ImageUploader'),
            ('settings/portal_entry', 'linkTarget', 'ComboBox'),
            # settings/portal
            ('settings/portal', 'name', 'TextBox'),
            ('settings/portal', 'displayName', 'MultiInput'),
            ('settings/portal', 'showMenu', 'CheckBox'),
            ('settings/portal', 'showSearch', 'CheckBox'),
            ('settings/portal', 'showLogin', 'CheckBox'),
            ('settings/portal', 'showApps', 'CheckBox'),
            ('settings/portal', 'showServers', 'CheckBox'),
            ('settings/portal', 'background', 'ImageUploader'),
            ('settings/portal', 'logo', 'ImageUploader'),
            ('settings/portal', 'cssBackground', 'TextBox'),
            ('settings/portal', 'fontColor', 'ComboBox'),
            ('settings/portal', 'portalComputers', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/portal', 'ensureLogin', 'CheckBox'),
            ('settings/portal', 'anonymousEmpty', 'MultiInput'),
            ('settings/portal', 'autoLayoutCategories', 'CheckBox'),
            ('settings/portal', 'portalEntriesOrder', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/portal', 'links', 'MultiInput'),
            ('settings/portal', 'content', 'umc/modules/udm/PortalContent'),
            ('settings/portal', 'defaultLinkTarget', 'ComboBox'),
            # settings/printermodel
            ('settings/printermodel', 'name', 'TextBox'),
            ('settings/printermodel', 'printmodel', 'MultiInput'),
            # settings/printeruri
            ('settings/printeruri', 'name', 'TextBox'),
            ('settings/printeruri', 'printeruri', 'TextBox'),
            # settings/prohibited_username
            ('settings/prohibited_username', 'name', 'TextBox'),
            ('settings/prohibited_username', 'usernames', 'TextBox'),
            # settings/sambaconfig
            ('settings/sambaconfig', 'name', 'TextBox'),
            ('settings/sambaconfig', 'passwordLength', 'TextBox'),
            ('settings/sambaconfig', 'passwordHistory', 'TextBox'),
            ('settings/sambaconfig', 'minPasswordAge', 'ComplexInput'),
            ('settings/sambaconfig', 'badLockoutAttempts', 'TextBox'),
            ('settings/sambaconfig', 'logonToChangePW', 'CheckBox'),
            ('settings/sambaconfig', 'maxPasswordAge', 'ComplexInput'),
            ('settings/sambaconfig', 'lockoutDuration', 'ComplexInput'),
            ('settings/sambaconfig', 'resetCountMinutes', 'TextBox'),
            ('settings/sambaconfig', 'disconnectTime', 'ComplexInput'),
            ('settings/sambaconfig', 'refuseMachinePWChange', 'CheckBox'),
            # settings/sambadomain
            ('settings/sambadomain', 'name', 'TextBox'),
            ('settings/sambadomain', 'SID', 'TextBox'),
            ('settings/sambadomain', 'NextUserRid', 'TextBox'),
            ('settings/sambadomain', 'NextGroupRid', 'TextBox'),
            ('settings/sambadomain', 'NextRid', 'TextBox'),
            ('settings/sambadomain', 'passwordLength', 'TextBox'),
            ('settings/sambadomain', 'passwordHistory', 'TextBox'),
            ('settings/sambadomain', 'minPasswordAge', 'ComplexInput'),
            ('settings/sambadomain', 'badLockoutAttempts', 'TextBox'),
            ('settings/sambadomain', 'logonToChangePW', 'CheckBox'),
            ('settings/sambadomain', 'maxPasswordAge', 'ComplexInput'),
            ('settings/sambadomain', 'lockoutDuration', 'ComplexInput'),
            ('settings/sambadomain', 'resetCountMinutes', 'TextBox'),
            ('settings/sambadomain', 'disconnectTime', 'ComplexInput'),
            ('settings/sambadomain', 'refuseMachinePWChange', 'CheckBox'),
            ('settings/sambadomain', 'domainPasswordComplex', 'CheckBox'),
            ('settings/sambadomain', 'domainPasswordStoreCleartext', 'CheckBox'),
            ('settings/sambadomain', 'domainPwdProperties', 'TextBox'),
            # settings/service
            ('settings/service', 'name', 'TextBox'),
            # settings/settings
            # settings/syntax
            ('settings/syntax', 'name', 'TextBox'),
            ('settings/syntax', 'description', 'TextBox'),
            ('settings/syntax', 'filter', 'TextBox'),
            ('settings/syntax', 'base', 'TextBox'),
            ('settings/syntax', 'attribute', 'TextBox'),
            ('settings/syntax', 'ldapattribute', 'TextBox'),
            ('settings/syntax', 'viewonly', 'CheckBox'),
            ('settings/syntax', 'addEmptyValue', 'CheckBox'),
            ('settings/syntax', 'value', 'TextBox'),
            ('settings/syntax', 'ldapvalue', 'TextBox'),
            # settings/udm_hook
            ('settings/udm_hook', 'name', 'TextBox'),
            ('settings/udm_hook', 'filename', 'TextBox'),
            ('settings/udm_hook', 'data', 'TextArea'),
            ('settings/udm_hook', 'active', 'CheckBox'),
            ('settings/udm_hook', 'appidentifier', 'TextArea'),
            ('settings/udm_hook', 'package', 'TextBox'),
            ('settings/udm_hook', 'packageversion', 'TextBox'),
            ('settings/udm_hook', 'ucsversionstart', 'TextBox'),
            ('settings/udm_hook', 'ucsversionend', 'TextBox'),
            ('settings/udm_hook', 'messagecatalog', 'MultiInput'),
            # settings/udm_module
            ('settings/udm_module', 'name', 'TextBox'),
            ('settings/udm_module', 'filename', 'TextBox'),
            ('settings/udm_module', 'data', 'TextArea'),
            ('settings/udm_module', 'active', 'CheckBox'),
            ('settings/udm_module', 'appidentifier', 'TextArea'),
            ('settings/udm_module', 'package', 'TextBox'),
            ('settings/udm_module', 'packageversion', 'TextBox'),
            ('settings/udm_module', 'ucsversionstart', 'TextBox'),
            ('settings/udm_module', 'ucsversionend', 'TextBox'),
            ('settings/udm_module', 'messagecatalog', 'MultiInput'),
            ('settings/udm_module', 'umcmessagecatalog', 'MultiInput'),
            ('settings/udm_module', 'umcregistration', 'TextArea'),
            ('settings/udm_module', 'icon', 'TextArea'),
            # settings/udm_syntax
            ('settings/udm_syntax', 'name', 'TextBox'),
            ('settings/udm_syntax', 'filename', 'TextBox'),
            ('settings/udm_syntax', 'data', 'TextArea'),
            ('settings/udm_syntax', 'active', 'CheckBox'),
            ('settings/udm_syntax', 'appidentifier', 'TextArea'),
            ('settings/udm_syntax', 'package', 'TextBox'),
            ('settings/udm_syntax', 'packageversion', 'TextBox'),
            ('settings/udm_syntax', 'ucsversionstart', 'TextBox'),
            ('settings/udm_syntax', 'ucsversionend', 'TextBox'),
            ('settings/udm_syntax', 'messagecatalog', 'MultiInput'),
            # settings/umc_operationset
            ('settings/umc_operationset', 'name', 'TextBox'),
            ('settings/umc_operationset', 'description', 'TextBox'),
            ('settings/umc_operationset', 'operation', 'MultiInput'),
            ('settings/umc_operationset', 'flavor', 'TextBox'),
            ('settings/umc_operationset', 'hosts', 'TextBox'),
            # settings/usertemplate
            ('settings/usertemplate', 'name', 'TextBox'),
            ('settings/usertemplate', 'title', 'TextBox'),
            ('settings/usertemplate', 'initials', 'TextBox'),
            ('settings/usertemplate', 'preferredDeliveryMethod', 'TextBox'),
            ('settings/usertemplate', 'description', 'TextBox'),
            ('settings/usertemplate', 'displayName', 'TextBox'),
            ('settings/usertemplate', 'organisation', 'TextBox'),
            ('settings/usertemplate', 'pwdChangeNextLogin', 'CheckBox'),
            ('settings/usertemplate', 'disabled', 'CheckBox'),
            ('settings/usertemplate', 'e-mail', 'TextBox'),
            ('settings/usertemplate', 'unixhome', 'TextBox'),
            ('settings/usertemplate', 'homeShare', 'umc/modules/udm/ComboBox'),
            ('settings/usertemplate', 'homeSharePath', 'TextBox'),
            ('settings/usertemplate', 'shell', 'TextBox'),
            ('settings/usertemplate', 'sambahome', 'TextBox'),
            ('settings/usertemplate', 'scriptpath', 'TextBox'),
            ('settings/usertemplate', 'profilepath', 'TextBox'),
            ('settings/usertemplate', 'homedrive', 'TextBox'),
            ('settings/usertemplate', 'street', 'TextBox'),
            ('settings/usertemplate', 'postcode', 'TextBox'),
            ('settings/usertemplate', 'city', 'TextBox'),
            ('settings/usertemplate', 'country', 'ComboBox'),
            ('settings/usertemplate', 'phone', 'TextBox'),
            ('settings/usertemplate', 'employeeNumber', 'TextBox'),
            ('settings/usertemplate', 'roomNumber', 'TextBox'),
            ('settings/usertemplate', 'secretary', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/usertemplate', 'departmentNumber', 'TextBox'),
            ('settings/usertemplate', 'employeeType', 'TextBox'),
            ('settings/usertemplate', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/usertemplate', 'groups', 'umc/modules/udm/MultiObjectSelect'),
            ('settings/usertemplate', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('settings/usertemplate', 'primaryGroup', 'umc/modules/udm/ComboBox'),
            ('settings/usertemplate', 'mailPrimaryAddress', 'TextBox'),
            ('settings/usertemplate', 'mailAlternativeAddress', 'TextBox'),
            ('settings/usertemplate', 'physicalDeliveryOfficeName', 'TextBox'),
            ('settings/usertemplate', 'postOfficeBox', 'TextBox'),
            ('settings/usertemplate', 'preferredLanguage', 'TextBox'),
            ('settings/usertemplate', '_options', 'ComboBox'),
            # shares
            # shares/printergroup
            ('shares/printergroup', 'name', 'TextBox'),
            ('shares/printergroup', 'spoolHost', 'umc/modules/udm/ComboBox'),
            ('shares/printergroup', 'groupMember', 'umc/modules/udm/ComboBox'),
            ('shares/printergroup', 'sambaName', 'TextBox'),
            # shares/printer
            ('shares/printer', 'name', 'TextBox'),
            ('shares/printer', 'location', 'TextBox'),
            ('shares/printer', 'description', 'TextBox'),
            ('shares/printer', 'spoolHost', 'umc/modules/udm/ComboBox'),
            ('shares/printer', 'uri', 'ComplexInput'),
            ('shares/printer', 'model', 'ComboBox'),
            ('shares/printer', 'producer', 'umc/modules/udm/ComboBox'),
            ('shares/printer', 'sambaName', 'TextBox'),
            ('shares/printer', 'ACLtype', 'ComboBox'),
            ('shares/printer', 'ACLUsers', 'umc/modules/udm/MultiObjectSelect'),
            ('shares/printer', 'ACLGroups', 'umc/modules/udm/MultiObjectSelect'),
            ('shares/printer', 'ACLGroups', 'umc/modules/udm/MultiObjectSelect'),
            # shares/print
            ('shares/print', 'name', 'TextBox'),
            ('shares/print', 'spoolHost', 'umc/modules/udm/ComboBox'),
            ('shares/print', 'sambaName', 'TextBox'),
            # shares/share
            ('shares/share', 'name', 'TextBox'),
            ('shares/share', 'printablename', 'TextBox'),
            ('shares/share', 'host', 'umc/modules/udm/ComboBox'),
            ('shares/share', 'path', 'TextBox'),
            ('shares/share', 'owner', 'umc/modules/udm/ComboBox'),
            ('shares/share', 'group', 'umc/modules/udm/ComboBox'),
            ('shares/share', 'directorymode', 'UnixAccessRightsExtended'),
            ('shares/share', 'writeable', 'CheckBox'),
            ('shares/share', 'sync', 'ComboBox'),
            ('shares/share', 'subtree_checking', 'CheckBox'),
            ('shares/share', 'root_squash', 'CheckBox'),
            ('shares/share', 'nfs_hosts', 'TextBox'),
            ('shares/share', 'sambaWriteable', 'CheckBox'),
            ('shares/share', 'sambaName', 'TextBox'),
            ('shares/share', 'sambaBrowseable', 'CheckBox'),
            ('shares/share', 'sambaPublic', 'CheckBox'),
            ('shares/share', 'sambaDosFilemode', 'CheckBox'),
            ('shares/share', 'sambaHideUnreadable', 'CheckBox'),
            ('shares/share', 'sambaCreateMode', 'UnixAccessRights'),
            ('shares/share', 'sambaDirectoryMode', 'UnixAccessRights'),
            ('shares/share', 'sambaForceCreateMode', 'UnixAccessRights'),
            ('shares/share', 'sambaForceDirectoryMode', 'UnixAccessRights'),
            ('shares/share', 'sambaSecurityMode', 'UnixAccessRights'),
            ('shares/share', 'sambaDirectorySecurityMode', 'UnixAccessRights'),
            ('shares/share', 'sambaForceSecurityMode', 'UnixAccessRights'),
            ('shares/share', 'sambaForceDirectorySecurityMode', 'UnixAccessRights'),
            ('shares/share', 'sambaLocking', 'CheckBox'),
            ('shares/share', 'sambaBlockingLocks', 'CheckBox'),
            ('shares/share', 'sambaStrictLocking', 'ComboBox'),
            ('shares/share', 'sambaOplocks', 'CheckBox'),
            ('shares/share', 'sambaLevel2Oplocks', 'CheckBox'),
            ('shares/share', 'sambaFakeOplocks', 'CheckBox'),
            ('shares/share', 'sambaBlockSize', 'TextBox'),
            ('shares/share', 'sambaCscPolicy', 'ComboBox'),
            ('shares/share', 'sambaHostsAllow', 'TextBox'),
            ('shares/share', 'sambaHostsDeny', 'TextBox'),
            ('shares/share', 'sambaValidUsers', 'TextBox'),
            ('shares/share', 'sambaInvalidUsers', 'TextBox'),
            ('shares/share', 'sambaForceUser', 'TextBox'),
            ('shares/share', 'sambaForceGroup', 'TextBox'),
            ('shares/share', 'sambaHideFiles', 'TextBox'),
            ('shares/share', 'sambaNtAclSupport', 'CheckBox'),
            ('shares/share', 'sambaInheritAcls', 'CheckBox'),
            ('shares/share', 'sambaPostexec', 'TextBox'),
            ('shares/share', 'sambaPreexec', 'TextBox'),
            ('shares/share', 'sambaWriteList', 'TextBox'),
            ('shares/share', 'sambaVFSObjects', 'TextBox'),
            ('shares/share', 'sambaMSDFSRoot', 'CheckBox'),
            ('shares/share', 'sambaInheritOwner', 'CheckBox'),
            ('shares/share', 'sambaInheritPermissions', 'CheckBox'),
            ('shares/share', 'sambaCustomSettings', 'MultiInput'),
            ('shares/share', 'nfsCustomSettings', 'TextBox'),
            ('shares/share', 'appendACL', 'TextBox'),
        ])
def test_widget_from_property_syntax(object, property, expected_widget, load_modules):
    m = modules.get(object)
    p = m.property_descriptions.get(property)
    widget = p.syntax.get_widget(p)
    assert widget == expected_widget


@pytest.mark.parametrize(
        'object, property, expected_widget_choices_options',
        [
            # users
            # users/user
            ('users/user', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            ('users/user', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('users/user', 'mailHomeServer', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'MailHomeServer'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('users/user', 'mailPrimaryAddress', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'primaryEmailAddressValidDomain'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('users/user', 'mailAlternativeAddress', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'emailAddressValidDomain'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            # computers
            # computers/ipmanagedclient
            ('computers/ipmanagedclient', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/ipmanagedclient', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/linux
            ('computers/linux', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/linux', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/linux', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/macos
            ('computers/macos', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/macos', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/macos', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/windows
            ('computers/windows', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/windows', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/windows', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/ubuntu
            ('computers/ubuntu', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/ubuntu', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/ubuntu', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/domaincontroller_master
            ('computers/domaincontroller_master', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/domaincontroller_master', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/domaincontroller_master', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/domaincontroller_slave
            ('computers/domaincontroller_slave', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/domaincontroller_slave', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/domaincontroller_slave', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/domaincontroller_backup
            ('computers/domaincontroller_backup', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/domaincontroller_backup', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/domaincontroller_backup', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/memberserver
            ('computers/memberserver', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/memberserver', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/memberserver', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # computers/windows_domaincontroller
            ('computers/windows_domaincontroller', 'network', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'network'}, 'dynamicValuesInfo': 'udm/syntax/choices/info', 'onChange': 'javascript:umc/modules/udm/callbacks:setNetwork'}),
            ('computers/windows_domaincontroller', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('computers/windows_domaincontroller', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # groups
            # groups/group
            ('groups/group', 'memberOf', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            ('groups/group', 'nestedGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            # settingd
            # settings/default
            ('settings/default', 'defaultGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('settings/default', 'defaultComputerGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('settings/default', 'defaultDomainControllerGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('settings/default', 'defaultDomainControllerMBGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('settings/default', 'defaultMemberServerGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            ('settings/default', 'defaultClientGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            # settings/portal_entry
            ('settings/portal_entry', 'allowedGroups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDNOrEmpty'}, 'objectType': 'groups/group'}),
            # settings/usertemplate
            ('settings/usertemplate', 'groups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
            ('settings/usertemplate', 'primaryGroup', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'dynamicValuesInfo': 'udm/syntax/choices/info'}),
            # shares/printer
            ('shares/printer', 'ACLGroups', {'dynamicValues': 'udm/syntax/choices', 'dynamicOptions': {'syntax': 'GroupDN'}, 'objectType': 'groups/group'}),
        ])
def test_widget_choices_options(object, property, expected_widget_choices_options, load_modules):
    m = modules.get(object)
    p = m.property_descriptions.get(property)
    widget_choices_options = p.syntax.get_widget_choices_options(p)
    print(widget_choices_options)
    assert widget_choices_options == expected_widget_choices_options
