#!/bin/sh
#
# Univention initrd
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 12.0.0-4; then
	# Bug #52993: recreate initramfs for all available kernels due to removed initramfs/init
	echo "recreate initramfs for all available kernels due to changes in univention-initrd..."
	update-initramfs -k all -c
	echo "done"
fi

exit 0
