#!/usr/bin/python3
#
# Univention Monitoring Plugin
#
# Copyright 2022 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

from univention.config_registry import ucr
from univention.monitoring import Alert


class NTP(Alert):

	def write_metrics(self):
		rc, output = self.exec_command(['/usr/lib/nagios/plugins/check_ntp_time', '-H', ucr['hostname']], env={'LANG': 'C'})
		try:
			ntp_offset = float(output.split('|', 1)[-1].split(';')[0].split('=')[-1].rstrip('s'))
		except ValueError:
			self.log.error('Checking NTP time failed: %s', output)
		else:
			self.write_metric('univention_ntp_offset_seconds', ntp_offset)
			self.log.debug(output)


if __name__ == '__main__':
	NTP.main()
