#!/usr/share/ucs-test/runner bash
## desc: |
##  Update localhost component from (un+)maintained
##  1. setup local repository for maintained and unmaintained component
##  2. check if all packages are installable
## roles-not: [basesystem]
## tags: [basic]
## packages:
##  - apache2 | apache2-mpm-prefork
## exposure: dangerous

RETVAL=110 # Test fehlgeschlagen
. pool.sh || exit 137

compname="test${RANDOM}"

setup_apache "${repoprefix}"

mkpdir "${_version_version}--component/${compname}" maintained "${ARCH}"
mkdeb "${pkgname}" 1 "${ARCH}" "${DIR}"
mkpkg "${DIR}"

mkpdir "${_version_version}--component/${compname}" unmaintained "${ARCH}"
mkdeb "${pkgname}" 2 "${ARCH}" "${DIR}"
mkpkg "${DIR}"

comp="repository/online/component/${compname}"
config_repo "${comp}=yes" "${comp}/parts=maintained"

(
	set -e
	checkapt "http://localhost\(:80\)\?/${repoprefix}/" "${DIRS[0]}"
	apt-get -qq update
	apt-get -qq install "${pkgname}"
	dpkg-query -W "${pkgname}" | grep -Fqx "${pkgname}	1"
	ucr set repository/online/component/"${compname}"/parts="maintained,unmaintained" # COMMA separated
	checkapt "http://localhost\(:80\)\?/${repoprefix}/" "${DIRS[@]}"
	apt-get -qq update
	apt-get -qq install "${pkgname}"
	dpkg-query -W "${pkgname}" | grep -Fqx "${pkgname}	2"
	checkdeb "${pkgname}" 1 2
)
[ $? -eq 0 ] && RETVAL=100 # Test bestanden (Keine Fehler)
dpkg -P --force-all "${pkgname}" >&3 2>&3

exit ${RETVAL}
# vim:set ft=sh:
