#!/usr/share/ucs-test/runner bash
## desc: |
##  Update localhost component with fixed version
##  1. setup local repository for maintained component with specific version
##  2. check if the package is installable
## roles-not: [basesystem]
## tags: [basic]
## packages:
##  - apache2 | apache2-mpm-prefork
## exposure: dangerous

RETVAL=110 # Test fehlgeschlagen
. pool.sh || exit 137

compname="test${RANDOM}"

setup_apache "${repoprefix}"

mkpdir "${major}.${minor}--component/${compname}" maintained "${ARCH}"
mkdeb "${pkgname}" 1 "${ARCH}" "${DIR}"
mkpkg "${DIR}"

minor+=1
mkpdir "${major}.${minor}--component/${compname}" maintained "${ARCH}"
mkdeb "${pkgname}" 2 "${ARCH}" "${DIR}"
mkpkg "${DIR}"

comp="repository/online/component/${compname}"
config_repo "${comp}=yes" "${comp}/parts=maintained" "${comp}/version=${major}.${minor}"

(
	set -e
	checkapt "http://localhost\(:80\)\?/${repoprefix}/" "${DIRS[1]}"
	apt-get -qq update
	apt-get -qq install "${pkgname}"
	dpkg-query -W "${pkgname}" | grep -Fqx "${pkgname}	2"
	checkdeb "${pkgname}" 2
)
[ $? -eq 0 ] && RETVAL=100 # Test bestanden (Keine Fehler)
dpkg -P --force-all "${pkgname}" >&3 2>&3

exit ${RETVAL}
# vim:set ft=sh:
