#!/usr/share/ucs-test/runner bash
## desc: Checking function of nscd listener module
## tags: [basic]
## roles-not: [basesystem]
## packages:
##  - univention-ldap-server
## exposure: dangerous

. "$TESTLIBPATH/base.sh" || exit 1
. "$TESTLIBPATH/user.sh" || exit 1
. "$TESTLIBPATH/group.sh" || exit 1

DOMAIN="$(ucr get domainname)"
LDAPBASE="$(ucr get ldap/base)"

cleanup_mail_domain () {

		if [[ "$setdomain" -ne 0 ]]; then
			if ! udm mail/domain remove --dn "cn=$DOMAIN,$LDAPBASE" ; then
				echo "Could not remove main/domain cn=$domainname,$ldap_base. Continue testing..."
			fi
		fi
 }

if ! [ -f /usr/lib/univention-directory-listener/system/nscd.py ]
then
    echo "nscd listener module not found"
	fail_test 1
	exit "$RETVAL"
else

	trap cleanup_mail_domain EXIT
        # create domain part in configured mail domains list
	setdomain=1
	if ! udm mail/domain create --set name=$DOMAIN ; then
		echo "Mail/domain object already exists or could not be created. Continue testing..."
		setdomain=0
	fi

	ERASENSCDCACHE=$(nscd --invalidate group)

	USERNAME=$(user_randomname)
	user_create "$USERNAME" || fail_test 1

	if [ "$USERNAME" == "Administrator" ]; then
		echo "Can not be an Administrator as user."
		fail_test 1
		exit "$RETVAL"
	fi

	GROUPNAME="$(group_randomnameme)"
	group_create "$GROUPNAME" || fail_test 1

	sleep 10

	group_adduser "$USERNAME" "$GROUPNAME" || fail_test 1
	ERASENSCDCACHE=$(nscd --invalidate group)

	sleep 30


	MEMBERTRUE=$(group_getent $GROUPNAME $USERNAME)
	if [ "$?" == "0" ]
	then
		echo "nscd listener module seems to work"
	else
		echo "nscd listener module doesn't seem to work"
		fail_test 1
	fi


	group_removeuser $USERNAME $GROUPNAME || fail_test 1
	ERASENSCDCACHE="$(nscd --invalidate group)"

	sleep 30


	MEMBERTRUE=$(group_getent $GROUPNAME $USERNAME)

	if [ "$?" == "1" ]
	then
		echo "nscd listener module seems to work"
	else
		echo "nscd listener module doesn't seem to work"
		fail_test 1
	fi

	user_remove $USERNAME || fail_test 1

	group_remove $GROUPNAME || fail_test 1

fi

exit "$RETVAL"