#!/usr/share/ucs-test/runner bash
## desc: Checking function of nscd listener module
## tags: [basic]
## roles-not: [basesystem]
## packages:
##  - univention-ldap-server
## exposure: dangerous

. "$TESTLIBPATH/base.sh" || exit 1
. "$TESTLIBPATH/user.sh" || exit 1
. "$TESTLIBPATH/group.sh" || exit 1
. "$TESTLIBPATH/maildomain.sh" || exit 1

DOMAIN="$(ucr get domainname)"
LDAPBASE="$(ucr get ldap/base)"
TIME_TO_WAIT=120 # time to wait for nscd listener

cleanup_mail_domain () {
    if [ "$rc" = "0" ]; then
        delete_mail_domain "$DOMAIN" || fail_test 1
    fi
}

if ! [ -f /usr/lib/univention-directory-listener/system/nscd.py ]
then
    echo "nscd listener module not found"
	fail_test 1
	exit "$RETVAL"
else

    # create domain part in configured mail domains list
	create_mail_domain "$DOMAIN"
	rc=$?

	trap cleanup_mail_domain EXIT

	ERASENSCDCACHE=$(nscd --invalidate group)

	USERNAME=$(user_randomname)
	user_create "$USERNAME" || fail_test 1

	if [ "$USERNAME" == "Administrator" ]; then
		echo "Can not be an Administrator as user."
		fail_test 1
		exit "$RETVAL"
	fi

	GROUPNAME="$(group_randomnameme)"
	group_create "$GROUPNAME" || fail_test 1

	sleep 10

	group_adduser "$USERNAME" "$GROUPNAME" || fail_test 1
	ERASENSCDCACHE=$(nscd --invalidate group)

	echo "Waiting for nscd listener module..."
	i=0
	while sleep 1s;
	do
		if [ $i -lt "$TIME_TO_WAIT" ]; then
			if getent group "$GROUPNAME" | grep -q "$USERNAME"; then
				echo "nscd listener module seems to work"
				break
			fi
		else
			echo "nscd listener module doesn't seem to work. Waited longer than $TIME_TO_WAIT seconds."
			fail_test 1
			break
		fi
		i=`expr $i + 1`
	done

	group_removeuser $USERNAME $GROUPNAME || fail_test 1
	ERASENSCDCACHE="$(nscd --invalidate group)"

	echo "Waiting for nscd listener module..."
	i=0
	while sleep 1s;
	do
		if [ $i -lt "$TIME_TO_WAIT" ]; then
			if ! getent group "$GROUPNAME" | grep -q "$USERNAME"; then
				echo "nscd listener module seems to work"
				break
			fi
		else
			echo "nscd listener module doesn't seem to work. Waited longer than $TIME_TO_WAIT seconds."
			fail_test 1
			break
		fi
		i=`expr $i + 1`
	done

	user_remove $USERNAME || fail_test 1

	group_remove $GROUPNAME || fail_test 1

fi

exit "$RETVAL"
