#!/usr/share/ucs-test/runner bash
# shellcheck shell=bash
## desc: memberOf is indexed after a fresh installation and absent after an upgrade of univention-ldap
## roles:
##  - domaincontroller_master
##  - domaincontroller_backup
## packages:
##  - univention-ldap-server
## exposure: safe

# shellcheck source=../../lib/base.sh
. "$TESTLIBPATH/base.sh" || exit 137

set -x

# TODO: Starting with UCS 5.2-7 and UCS 5.3, memberOf will always be indexed by default,
# also on upgrades from older versions. So, this test must be adjusted to assert that memberOf
# is always indexed from 5.2-7 / 5.3 onwards!

command -v mdb_stat >/dev/null || { echo "mdb_stat not available"; exit 77; }

# Output of "mdb_stat -a" has to contain "Status of memberOf" if memberOf is indexed.
mdb_stat -a /var/lib/univention-ldap/ldap 2>/dev/null | grep -qi '^Status of memberOf$' || fail_fast 1 "memberOf is not indexed after a fresh installation"

exit "$RETVAL"
