#! /bin/sh
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$1" in
configure)
	[ -x /etc/init.d/atftpd ] &&
		invoke-rc.d atftpd stop

	update-inetd --remove "tftp"
update-inetd --group BOOT --add "tftp               dgram   udp     wait \
        nobody /usr/sbin/tcpd /usr/sbin/in.tftpd --tftpd-timeout 300 --retry-timeout 5 --maxthread 100 --verbose=5  /var/lib/univention-client-boot/"

	deb-systemd-invoke try-reload-or-restart inetd.service

# configure firewall
ucr set security/packetfilter/package/univention-tftp/udp/69/all=ACCEPT \
		security/packetfilter/package/univention-tftp/udp/69/all/en="TFTP"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart
;;
esac

#DEBHELPER#

exit 0
