#ifndef GPLPV_VERSION_H
#define GPLPV_VERSION_H

#define EXPAND(x) STRINGIFY(x)
#define STRINGIFY(x) #x

#ifdef VERSION_MAJOR
  #ifdef BUILD_NUMBER
    #define VER_FILEVERSION             VERSION_MAJOR,VERSION_MINOR,REVISION,BUILD_NUMBER
    #define VER_FILEVERSION_STR         "GPLPV " EXPAND(VERSION_MAJOR) "." EXPAND(VERSION_MINOR) "." EXPAND(REVISION) "." EXPAND(BUILD_NUMBER)
  #else
    #define VER_FILEVERSION             VERSION_MAJOR,VERSION_MINOR,REVISION,0
    #define VER_FILEVERSION_STR         "GPLPV " EXPAND(VERSION_MAJOR) "." EXPAND(VERSION_MINOR) "." EXPAND(REVISION)
  #endif
#else
  #define VER_FILEVERSION             0,0,0,0
  #define VER_FILEVERSION_STR         "GPLPV Unversioned"
#endif

#endif
