#! /bin/sh
#
# Univention Maintenance
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$1" in
	configure)
		if [ -z "$2" ]; then
			#run script every 15 minutes
			univention-config-registry set \
								system/stats?yes \
								system/stats/cron?'0,30 * * * * '
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
