installer/modules/*.py lib/univention-installer/modules/
installer/*.py lib/univention-installer/
installer/*.sh lib/univention-installer/
installer/modules/kernel-2.4 lib/univention-installer/modules/
installer/modules/kernel-2.6 lib/univention-installer/modules/
installer/modules/filesystem lib/univention-installer/modules/
installer/modules/keymap lib/univention-installer/modules/
installer/modules/languages lib/univention-installer/modules/
installer/modules/timezone lib/univention-installer/modules/
installer/dhclient-script-wrapper lib/univention-installer/
installer/locale/de/LC_MESSAGES/installer.mo lib/univention-installer/locale/de/LC_MESSAGES/

