#!/usr/share/ucs-test/runner bash
## desc: "Display samba Groups as normal user"
## exposure: safe
## packages:
##  - univention-samba4
## roles-not: [basesystem]
## tags: [basic]

. "$TESTLIBPATH/user.sh" || exit 137

SAMBA="true"
MAIL="false"
KERBEROS="true"
PERSON="false"
POSIX="true"

username="$(user_randomname)"
password=univention

trap 'user_remove "$username"' INT TERM EXIT
user_create "$username" || fail_fast 1 "Could not create user $username."

#waiting for user replication
echo "waiting for user replication"
i=0
while ! ldbsearch -H "ldap://localhost" -U"$username%$password" "cn=$username" | grep -q '^dn:'
do
	let i=$i+1
	if [ "$i" = 10 ]; then
		fail_fast 1 "TIMEOUT: The user or share could not be found in samba ldb"
	fi
	sleep 3
done

echo "----print samba groups as a user"
samba-tool group list -U "$username%$password" | grep -q "Domain Users"
if [ $? != 0 ];then
	fail_test 1 "The test trying to display samba-Groups as a user failed"
fi

exit $RETVAL