#!/usr/share/ucs-test/runner bash
## desc: "Accessing sysvol with smbclient"
## exposure: safe
## packages:
##  - univention-samba4
## roles:
## - domaincontroller_master
## - domaincontroller_backup
## - domaincontroller_slave

. "$TESTLIBPATH/user.sh" || exit 137
. "$TESTLIBPATH/shares.sh" || exit 137
. "$TESTLIBPATH/random.sh" || exit 137

##create User
echo "----create User"
SAMBA="true"
MAIL="false"
KERBEROS="true"
PERSON="false"
POSIX="true"

username="$(user_randomname)"
password=univention

trap 'user_remove "$username"' INT TERM EXIT
if ! user_create "$username"; then
	fail_fast 1 "User could not be created"
fi


##waiting for user to be created
echo "Waiting for user to be created"
i=0
while true
do
	let i=$i+1
	sleep 3
	ldbsearch -H ldap://localhost -U"$username%$password" "cn=$username" | grep dn: && break
	if [ "$i" = 10 ]; then
		echo "TIMEOUT: The user or share could not be found in samba ldb"
		break
	fi
done

## in case password is not the default one
if [ $(univention-config-registry get server/role) = "domaincontroller_master" -a -e /root/root.secret ];then
	echo "Found /root/root.secret, using that secret for Administrator access"
	ADMINISTRATOR_PASSWORD="$(cat /root/root.secret)"
fi

##Put a file on sysvol as Administrator
echo "----Put a file on sysvol as Administrator"
output="$(smbclient //localhost/sysvol -U"$ADMINISTRATOR_USER%$ADMINISTRATOR_PASSWORD" -c "put /etc/hosts $domainname/t1" 2>&1)"
if [ $? != 0 ]; then
	echo "$output"
	fail_test 1 "Could not put file on sysvol as Administrator"
fi

##Access the folder Policies on sysvol as a user
echo "----Access the folder Policies on sysvol as a user"
output="$(smbclient //localhost/sysvol -U"$username%$password" -c "ls $domainname/Policies" 2>&1)"
if [ $? != 0 ]; then
	echo "$output"
	fail_test 1 "Could not access Policies on sysvol as a user"
fi

##Put a file in the folder Policies on sysvol as a user
echo "----Put a file in the folder Policies on sysvol as a user"
output="$(smbclient //localhost/sysvol -U"$username%$password" -c "put /etc/hosts $domainname/t1"  2>&1)"
if [ $? = 0 ]; then
	echo "$output"
	fail_test 1 "Successfully put a file on sysvol as a user"
fi

exit $RETVAL