#!/usr/share/ucs-test/runner bash
## desc: Test accessing sysvol with smbclient using machine.secret
## exposure: safe
## packages:
##  - univention-samba4
## bugs: [30818]
## roles:
## - domaincontroller_master
## - domaincontroller_backup
## - domaincontroller_slave

. "$TESTLIBPATH/shares.sh" || exit 137

password="$(cat /etc/machine.secret)"

target_host="$(univention-ldapsearch -xLLL "univentionService=S4 Connector" cn | sed -n 's/^cn: //p')"


info "----Accessing sysvol on $target_host.$domainname using smbclient and hostname/machine.secret credentials"

output="$(smbclient -U "$hostname\$%$password" "//$target_host.$domainname/sysvol" -c "ls $domainname/Policies" 2>&1)" &&
        exit $RETVAL

error "$output"
fail_test 1 "Could not access Policies on sysvol with machine.secret credentials"

exit $RETVAL
