#!/usr/share/ucs-test/runner bash
## desc: "Testing the sysvol replication"
## exposure: safe
## packages:
##  - univention-samba4
## roles:
## - domaincontroller_master
## - domaincontroller_backup
## - domaincontroller_slave
## tags:
##  - basic

. "$TESTLIBPATH/shares.sh" || exit 137
. "$TESTLIBPATH/random.sh" || exit 137

s4hosts=( $(univention-ldapsearch -xLLL "(univentionService=Samba 4)" cn | sed -ne 's/^cn: //p') )
for s4host_temp in "${s4hosts[@]}"
do
    ping -c 1 "$s4host_temp.$domainname" > /dev/null
    if [ "$?" = 0 -a "$s4host_temp" != "$hostname" ]; then
	s4host=$s4host_temp
	break	

    fi
done

echo "HOSTNAME:$s4host"
if [ -z "$s4host" ];then
    fail_fast 77 "Could not find another Samba4 Service in Domain"
fi


gponame="$(random_chars 8 "${_upperletters}${_lowerletters}${_ciphers}")"	## samba RC6 seems to dislike UTF-8 in GPO names
echo gponame "$gponame"

check_domainadmin_credentials || fail_fast 77 "UCR variables for admin credentials are not set"
ADMINISTRATOR_NAME="$(univention-ldapsearch -b "$tests_domainadmin_account" uid | grep uid | sed -ne 's/^uid: //p')"

## general sanity check: wait for the samba-share.py Listener to synchronize /etc/samba/shares.conf and /etc/samba/shares.conf.d (Bug #29399)
i=0
while ! samba-tool domain info 127.0.0.1 > /dev/null 2>&1
do
	let i="$i"+1
	if [ "$i" = 15 ]; then
		echo "samba-tool Failure (Bug #29399)" >&2
		break
	fi
	sleep 2
done

## create the GPO
echo "----create the GPO"
gpo_cn="$(samba-tool gpo create "$gponame" -U"$ADMINISTRATOR_NAME%$tests_domainadmin_pwd" | sed -n "s/GPO '$gponame' created as //p")"
if [ -n "$gpo_cn" ]; then
	trap 'samba-tool gpo del "$gpo_cn" -U"$ADMINISTRATOR_NAME%$tests_domainadmin_pwd"' INT TERM EXIT
else
	fail_fast 1 "WARNING: samba-tool gpo create did not return a GPO cn"
fi

## --local tests
i=0
echo "----search sam.ldb for GPO"
while true
do
	displayName="$(ldbsearch -H /var/lib/samba/private/sam.ldb "(&(objectClass=groupPolicyContainer)(cn=$gpo_cn))" displayName | sed -ne 's/^displayName: //p')"
	if [ -n "$displayName" ]; then
		break
	fi

	let i="$i"+1
	if [ "$i" = 20 ]; then
		fail_fast 1 "Could not find displayName of GPO in sam.ldb"
	fi
	sleep 1
done

echo "----check whether the directory for the GPO has been created"
i=0
while ! [ -d "/var/lib/samba/sysvol/$domainname/Policies/$gpo_cn" ]
do
	let i="$i"+1
	if [ "$i" = 20 ]; then
		fail_fast 1 "Directory for GPO has not been created"
	fi
	sleep 1
done

echo "----check whether the GPO is listed in samba-tool"
i=0
while ! ( output=$(samba-tool gpo show "$gpo_cn") && grep -Eq "^GPO\s+:\s$gpo_cn" <<<"$output" > /dev/null )
do
	let i="$i"+1
	if [ "$i" = 10 ]; then
		if [ -n "$output" ]; then
			echo "$output"
		fi
		fail_fast 1 "GPO is not listed in samba-tool"
	fi
	sleep 1
done

## Tests on remote DC
echo "----check whether the directory has been replicated to another s4host"
i=0
while ! echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname" test -d "/var/lib/samba/sysvol/$domainname/Policies/$gpo_cn" > /dev/null
do
	let i="$i"+1
	if [ "$i" =  600 ]; then
		fail_fast 1 "remote directory for GPO has not been created"
	fi
	sleep 3
done

##check whether samba-tool lists the GPO on another s4host
echo "----check whether samba-tool lists the GPO on another s4host."
i=0
while ! ( output="$(echo "$BINDPWD" | univention-ssh /dev/stdin root@"$s4host.$domainname" samba-tool gpo show "$gpo_cn")" && grep -Eq "^GPO\s+:\s$gpo_cn" <<<"$output" > /dev/null )
do
	let i="$i"+1
	if [ "$i" = 10 ]; then
		if [ -n "$output" ]; then
			echo "$output"
		fi
		fail_fast 1 "remote GPO is not listed in samba-tool"
	fi
	sleep 1
done


exit $RETVAL
