#!/bin/sh
#
# Univention Firewall
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# during installation set default policy to REJECT, during update to ACCEPT
if [ "$1" = "configure" ] && [ -n "$2" ] ; then
	ucr set security/packetfilter/defaultpolicy?ACCEPT
else
	ucr set security/packetfilter/defaultpolicy?REJECT
fi

exit 0
