#!/bin/bash
set -e -u
. ${0%/*}/common.sh

init

! univention-certificate new -name "$R64" -days 10
! univention-certificate renew -name "$R64" -days 10
! univention-certificate revoke -name "$R64"
! univention-certificate list
! univention-certificate check -name "$R64"
! univention-certificate list-all
! univention-certificate update-expired

printf '\nserver/role: domaincontroller_backup' >>"$UNIVENTION_BASECONF"
! univention-certificate new -name "$R64" -days 10
! univention-certificate renew -name "$R64" -days 10
! univention-certificate revoke -name "$R64"
! univention-certificate update-expired
univention-certificate list
univention-certificate list-all

printf '\nserver/role: domaincontroller_master' >>"$UNIVENTION_BASECONF"
univention-certificate new -name "$R64" -days 10
univention-certificate list
univention-certificate check -name "$R64"
univention-certificate renew -name "$R64" -days 10
univention-certificate revoke -name "$R64"
univention-certificate list-all
univention-certificate update-expired

:
