({
	'bold': '太字',
	'copy': 'コピー',
	'cut': '切り取り',
	'delete': '削除',
	'indent': 'インデント',
	'insertHorizontalRule': '水平罫線',
	'insertOrderedList': '番号付きリスト',
	'insertUnorderedList': '黒丸付きリスト',
	'italic': 'イタリック',
	'justifyCenter': '中央揃え',
	'justifyFull': '両端揃え',
	'justifyLeft': '左揃え',
	'justifyRight': '右揃え',
	'outdent': 'アウトデント',
	'paste': '貼り付け',
	'redo': 'やり直し',
	'removeFormat': '形式の除去',
	'selectAll': 'すべて選択',
	'strikethrough': '取り消し線',
	'subscript': '下付き文字',
	'superscript': '上付き文字',
	'underline': '下線',
	'undo': '元に戻す',
	'unlink': 'リンクの除去',
	'createLink': 'リンクの作成',
	'toggleDir': '方向の切り替え',
	'insertImage': 'イメージの挿入',
	'insertTable': 'テーブルの挿入/編集',
	'toggleTableBorder': 'テーブル・ボーダーの切り替え',
	'deleteTable': 'テーブルの削除',
	'tableProp': 'テーブル・プロパティー',
	'htmlToggle': 'HTML ソース',
	'foreColor': '前景色',
	'hiliteColor': '背景色',
	'plainFormatBlock': '段落スタイル',
	'formatBlock': '段落スタイル',
	'fontSize': 'フォント・サイズ',
	'fontName': 'フォント名',
	/* Error messages */
	'systemShortcutFF': '"${0}" アクションは、キーボード・ショートカットを使用して Mozilla Firefox でのみ使用できます。${1} を使用してください。'
})
