#!/bin/bash
#
# Univention RADIUS 802.1X
#  postrm script
#
# SPDX-FileCopyrightText: 2011-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
	remove|purge)
		univention-config-registry unset \
			security/packetfilter/package/univention-radius/udp/1812/all \
			security/packetfilter/package/univention-radius/udp/1812/all/en \
			security/packetfilter/package/univention-radius/udp/1813/all \
			security/packetfilter/package/univention-radius/udp/1813/all/en \
			security/packetfilter/package/univention-radius/udp/1814/all \
			security/packetfilter/package/univention-radius/udp/1814/all/en
		[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

		# shellcheck source=/dev/null
		. /usr/share/univention-lib/all.sh
		call_unjoinscript 20univention-radius.uinst
		;;
esac

fn="/etc/freeradius/3.0/sites-enabled/default"
if [ -L "$fn" ]; then
	if [ $(readlink "$fn") = /etc/freeradius/3.0/sites-available/default ]; then
		rm /etc/freeradius/3.0/sites-enabled/default
	fi
fi

exit 0
