#!/bin/bash
#
# Univention RADIUS 802.1X
#  preinst script
#
# SPDX-FileCopyrightText: 2011-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt-nl "7.0.7-3"; then
	default_enabled_site_link="/etc/freeradius/3.0/sites-enabled/default"
	package_default_enabled_site="../sites-available/default"
	backup_default_enabled_site_link="/etc/freeradius/3.0/sites-enabled/default.backup"

	default_enabled_site_target=$(readlink "$default_enabled_site_link")
	if [ "$default_enabled_site_target" != "$package_default_enabled_site" ]; then
		ln -s "$default_enabled_site_target" "$backup_default_enabled_site_link"
	fi
fi

exit 0
