include:
  - project: 'univention/documentation/sphinx-docker'
    file: 'pipeline/sphinx.yml'
    ref: "phahn/cc"

variables:
  ucs: 507
  DOC_TARGET_VERSION: "5.0"
  CHANGELOG_TARGET_VERSION: "5.0-7"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"

.sphinx-doc:
  image: $SPHINX_BASE
  stage: build
  interruptible: true
  variables:
    FORCE_COLOR: "TRUE"
    BUILDDIR: "_build/$language"
  artifacts:
    expire_in: 1 week
    paths:
      - $DOCS_DIR/_build
      - out
    when: always

.sphinx-html:
  extends:
    - .sphinx-doc
  script:
    - 'rm -rf "${DOCS_DIR}/${BUILDDIR}/linkcheck" "${DOCS_DIR}/${BUILDDIR}/spelling" "${DOCS_DIR}/${BUILDDIR}/build.err"'
    - 'make -C "$DOCS_DIR" -e SPHINXOPTS="-v -W --keep-going -w ${BUILDDIR}/build.err -D language=$language" -k linkcheck spelling html'
    - 'mkdir -p "out/$DOC_NAME/$DOC_TARGET_VERSION"'
    - 'mv "${DOCS_DIR}/${BUILDDIR}/html" "out/${DOC_NAME}/${DOC_TARGET_VERSION}/${language}"'
  after_script:
    - 'sphinx2gitlab-code-climate --prefix "$DOCS_DIR" -o gl-ccr-linkcheck.json linkcheck "${DOCS_DIR}/${BUILDDIR}/linkcheck/output.json"'
    - 'sphinx2gitlab-code-climate --prefix "$DOCS_DIR" -o gl-ccr-spelling.json spelling "${DOCS_DIR}/${BUILDDIR}/spelling/index.spelling"'
    - 'sphinx2gitlab-code-climate --prefix "$DOCS_DIR" -o gl-ccr-build.json build "${DOCS_DIR}/${BUILDDIR}/build.err"'
    - 'sphinx2gitlab-code-climate -o gl-code-quality-report.json merge gl-ccr-linkcheck.json gl-ccr-spelling.json gl-ccr-build.json'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "out/${DOC_NAME}/${DOC_TARGET_VERSION}/${language}/objects.inv" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${DOC_NAME}.${language}/${CI_COMMIT_REF_SLUG}/objects.inv" || :'
  artifacts:
    paths:
      - $DOCS_DIR/$BUILDDIR/html
      - $DOCS_DIR/$BUILDDIR/linkcheck
      - $DOCS_DIR/$BUILDDIR/spelling
      - out
    exclude:
      - out/**/*webpack-macros.html
      - out/**/.buildinfo
      - out/**/*.py
      - out/**/__pycache__/*
      - out/**/__pycache__
      - out/**/.doctrees
    reports:
      codequality: gl-code-quality-report.json

.sphinx-pdf:
  extends:
    - .sphinx-doc
  image: $SPHINX_FULL
  script:
    - 'make -C "$DOCS_DIR" -e SPHINXOPTS="-v -W --keep-going -D language=$language" latexpdf'
    - 'mkdir -p "out/$DOC_NAME/$DOC_TARGET_VERSION/$language"'
    - 'mv "$DOCS_DIR/_build/$language/latex/$DOC_NAME.pdf" "out/$DOC_NAME/$DOC_TARGET_VERSION/$language/"'
  artifacts:
    paths:
      - $DOCS_DIR/$BUILDDIR/latex
      - out

.publish:
  interruptible: false
  variables:
    GIT_STRATEGY: none

review:
  stage: merge
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  extends: .publish
  tags:
    - omar
  script:
    - 'rsync -av --delete out/ "/var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_COMMIT_REF_SLUG"'
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://apt.knut.univention.de/download/docs.$CI_COMMIT_REF_SLUG/
    on_stop: stop_review
    auto_stop_in: 1 week

stop_review:
  stage: merge
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
  needs:
    - review
  allow_failure: true
  extends: .publish
  tags:
    - omar
  script:
    - 'rm -rf "/var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_COMMIT_REF_SLUG"'
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

staging:
  stage: merge
  extends: .publish
  tags:
    - omar
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - 'rsync -av --delete out/ /var/univention/buildsystem2/test_mirror/ftp/download/docs'
  environment:
    name: staging
    url: http://apt.knut.univention.de/download/docs/
