#!/usr/share/ucs-test/runner python
## desc: Test the UMC service module autostart behaviour
## bugs: [34506]
## tags: [apptest]
## exposure: dangerous

import sys
sys.path.insert(0, '.')
from TestUMCSystemModule import TestUMCSystem

from univention.config_registry import ConfigRegistry
from univention.config_registry.frontend import ucr_update
import univention.testing.utils as utils


class TestUMCServiceAutostart(TestUMCSystem):

    def __init__(self):
        """Test Class constructor"""
        super(TestUMCServiceAutostart, self).__init__()
        self.initial_service_config = None

    def restore_initial_configuration(self, service_name):
        """
        Restores the autostart configuration as saved in the global var
        for provided 'service_name'
        """
        ucr_update(self.UCR,
                   {service_name + '/autostart': self.initial_service_config})

    def get_service_current_configuration(self, service_name_value):
        """
        Get the current UCR configuration for provided 'service_name_value' var
        Reloads the UCR before proceeding.
        """
        self.reload_ucr()
        ucr_value = None
        ucr_value = self.UCR.get(service_name_value)
        return ucr_value

    def set_service_configuration(self, service_names, setting):
        """Set the 'setting' for list of 'service_names' via UMC request"""
        try:
            request_result = self.Connection.request('services/' + setting,
                                                     service_names)
            if not request_result:
                utils.fail("Request 'services/%s' failed, no response "
                           "from hostname '%s'" % (setting, self.hostname))
            if not request_result['success']:
                utils.fail("Request 'services/%s' failed, no success in "
                           "response. Hostname '%s', response '%s'" %
                           (setting, self.hostname, request_result))
        except Exception as exc:
            utils.fail("Exception while making services/%s request: %s" %
                       (setting, exc))

    def check_service_autostart_possibilities(self, service_name):
        """
        Check all the possible variations of 'service_name' autostart settings
        """
        autostart_var = service_name + '/autostart'

        # saving initial service configuration
        self.initial_service_config = self.get_service_current_configuration(
                                          autostart_var)

        # make sure that 'service_name' autostart == 'yes' at first
        if self.get_service_current_configuration(autostart_var) != 'yes':
            self.set_service_configuration([service_name], 'start_auto')
            if self.get_service_current_configuration(autostart_var) != 'yes':
                utils.fail("Failed to set initial '%s' setting to "
                           "'yes'" % autostart_var)

        # case 1: autostart == 'yes', changing to 'no'
        if self.get_service_current_configuration(autostart_var) == 'yes':
            self.set_service_configuration([service_name], 'start_never')
            if self.get_service_current_configuration(autostart_var) != 'no':
                utils.fail("The '%s' was not changed from "
                           "'yes' to 'no' in UCR" % autostart_var)

        # case 2: autostart == 'no', changing to 'manually'
        if self.get_service_current_configuration(autostart_var) == 'no':
            self.set_service_configuration([service_name], 'start_manual')
            if self.get_service_current_configuration(autostart_var) != 'manually':
                utils.fail("The '%s' was not changed from "
                           "'no' to 'manually' in UCR" % autostart_var)

        # case 3: autostart == 'manually', changing to 'no'
        if self.get_service_current_configuration(autostart_var) == 'manually':
            self.set_service_configuration([service_name], 'start_never')
            if self.get_service_current_configuration(autostart_var) != 'no':
                utils.fail("The '%s' was not changed from "
                           "'manually' to 'no' in UCR" % autostart_var)

        # case 4: autostart == 'no', changing to 'yes'
        if self.get_service_current_configuration(autostart_var) == 'no':
            self.set_service_configuration([service_name], 'start_auto')
            if self.get_service_current_configuration(autostart_var) != 'yes':
                utils.fail("The '%s' was not changed from "
                           "'no' to 'yes' in UCR" % autostart_var)

        # case 5: autostart == 'yes', changing to 'manually'
        if self.get_service_current_configuration(autostart_var) == 'yes':
            self.set_service_configuration([service_name], 'start_manual')
            if self.get_service_current_configuration(autostart_var) != 'manually':
                utils.fail("The '%s' was not changed from "
                           "'yes' to 'manually' in UCR" % autostart_var)

        # case 6: autostart == 'manually', changing to 'yes'
        if self.get_service_current_configuration(autostart_var) == 'manually':
            self.set_service_configuration([service_name], 'start_auto')
            if self.get_service_current_configuration(autostart_var) != 'yes':
                utils.fail("The '%s' was not changed from "
                           "'manually' to 'yes' in UCR" % autostart_var)

    def main(self):
        """
        Method to test the UMC 'Name Service Caching Daemon' service
        autostart behaviour
        """
        self.get_ucr_credentials()
        self.create_connection_authenticate()

        service_name = 'nscd'
        self.check_service_presence(self.make_service_query_request(),
                                    service_name)
        try:
            self.check_service_autostart_possibilities(service_name)
        finally:
            self.restore_initial_configuration(service_name)


if __name__ == '__main__':
    TestUMC = TestUMCServiceAutostart()
    sys.exit(TestUMC.main())
