<?php
@%@UCRWARNING=# @%@

/**
 * SAML 2.0 remote SP metadata for simpleSAMLphp.
 *
 * See: http://simplesamlphp.org/docs/trunk/simplesamlphp-reference-sp-remote
*/


## Include all config files generated by UDM
require_once("/etc/simplesamlphp/metadata/metadata_include.php");

# important: no closing PHP tag here!
