<table style="width:100%;" cellspacing="0" cellpadding="0">
    <tr>
        <td style="width:150px">
           &nbsp;
        </td>
        <td>
            <table border="0" cellpadding="0" cellspacing="4">
            <tr>
                <td width="15" class="busy">&nbsp;</td>
                <td class="legend" style="padding-right:10px;"><?php echo _("Busy") ?></td>
                <td width="15" class="free">&nbsp;</td>
                <td class="legend" style="padding-right:10px;"><?php echo _("Possible Meeting Time") ?></td>
                <td width="15" class="unknown">&nbsp;</td>
                <td class="legend" style="padding-right:10px;"><?php echo _("No Information") ?></td>
            </tr>
            </table>
        </td>
    </tr>
</table>    


