<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">
<html>
<head> 
<title><?php echo $module ?>: System Capabilities Test</title>
<style type="text/css">
<!--    
body { font-family: Geneva,Arial,Helvetica,sans-serif; font-size: 10pt; }
td { font-family: Geneva,Arial,Helvetica,sans-serif; font-size: 10pt; }h1 { font-size: 12pt; color: black; font-family: Verdana,Geneva,Arial,Helvetica,
sans-serif; }
--> 
</style>      
</head> 

<body bgcolor="#ffffff" text="#000000">
    <table border="0" cellpadding="2" cellspacing="0" width="100%">
<tr><td>
