#!/usr/share/ucs-test/runner python
## desc: Tests the Univention Self Service
## tags: [apptest]
## roles: [domaincontroller_master]
## exposure: dangerous
## packages:
##   - univention-self-service
##   - univention-self-service-passwordreset-umc

import email
from urlparse import urlparse, parse_qs
import univention.testing.utils as utils
from univention.lib.umc import Client
from univention.config_registry import ConfigRegistry
from test_self_service import capture_mails
from univention.admin.uldap import getAdminConnection
from univention.admin.uexceptions import noObject


class EmailVerification(object):

	def __init__(self):
		self.ucr = ConfigRegistry()
		self.ucr.load()
		self.c = Client()
		self.user = {
			'lastname': 'foo1',
			'username': 'bar',
			'email': 'root@localhost',
			'password': 'univention',
		}
		self.dn = 'uid={},cn=users,{}'.format(self.user['username'], self.ucr.get('ldap/base'))

	def test_verification_email(self):
		timeout = 5
		with capture_mails(timeout=timeout) as mails:
			self.c.umc_command('passwordreset/create_account', self.user)
			utils.verify_ldap_object(self.dn, {'univentionPasswordRecoveryEmailVerified': ['FALSE']})

		mail = email.message_from_string(mails.data and mails.data[0]).get_payload(decode=True)
		print(mail)
		assert mail, 'No email has been received in %s seconds' % (timeout,)
		for line in mail.split():
			if line.startswith('https://'):
				verify_link = line
				break
		verify_fragment = urlparse(verify_link).fragment
		verify_params = parse_qs(verify_fragment)
		print(verify_params)
		self.c.umc_command('passwordreset/verify_contact', {
			'username': verify_params['username'][0],
			'token': verify_params['token'][0],
			'method': verify_params['method'][0],
		})
		print('checking account')
		utils.verify_ldap_object(self.dn, {'univentionPasswordRecoveryEmailVerified': ['TRUE']})


def main():
	ev = EmailVerification()
	try:
		ev.test_verification_email()
	finally:
		lo, po = getAdminConnection()
		try:
			lo.delete(ev.dn)
		except noObject:
			pass


if __name__ == '__main__':
	main()
