product: ucs
release: "4.4"
version: [9]
scope: ucs_4.4-0-errata4.4-9
src: libconfig-inifiles-perl
fix: 2.94-1+deb9u1
desc: |
 This update addresses the following issue:
 * CVE-2026-11527 (CVSS score 8.6 -
   CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H).
bug: [59765]
cve:
- CVE-2026-11527
