#!/usr/share/ucs-test/runner python
## desc: Create users/user with just the posix option unset
## tags: [udm]
## roles: [domaincontroller_master]
## bugs: [30932]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools
## versions:
##  3.1-1: skip

import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.ucr as ucr_test

if __name__ == '__main__':
	ucr = ucr_test.UCSTestConfigRegistry()
	ucr.load()

	with udm_test.UCSTestUDM() as udm:
		user = udm.create_user(primaryGroup='cn=Domain Admins,cn=groups,%s' % ucr['ldap/base'], options=['samba', 'person', 'mail', 'kerberos'])
		utils.verify_ldap_object(user)
