#!/usr/share/ucs-test/runner python
## desc: Mark the password of a kerberos user to be altered on next login
## tags: [udm]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools
## versions:
##  4.0-2: skip
##  4.3-0: fixed

import time
import univention.testing.udm as udm_test
import univention.testing.utils as utils


if __name__ == '__main__':
	date = time.gmtime(time.time())
	with udm_test.UCSTestUDM() as udm:
		user = udm.create_user()[0]
		udm.modify_object('users/user', dn=user, pwdChangeNextLogin='1')

		utils.verify_ldap_object(user, {'krb5PasswordEnd': [time.strftime('%Y%m%d', date) + '000000Z']})
