#!/usr/share/ucs-test/runner python
## desc: Try to use one username two times
## tags: [udm-users]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import sys
import univention.testing as test
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	if test.package_installed('univention-ox'):
		sys.exit(138)

	with udm_test.UCSTestUDM() as udm:
		name = udm.create_user()[1]
		try:
			udm.create_user(username = name)
		except udm_test.UCSTestUDM_CreateUDMObjectFailed:
			sys.exit(0)

	test.fail(' Successfully created an user with an username which is already in use, which should not be possible')
