#! /bin/sh
#
# Univention keycloak
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2024-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

eval "$(univention-config-registry shell ldap/base)"

if [ "$1" = "configure" ] && [ -n "$2" ]; then
	# update keycloak ldap federation config Bug 57100
	if dpkg --compare-versions "$2" lt-nl "1.0.10-6"; then
		if [ -e /var/univention-join/joined ] ; then
			if univention-app info | grep 'Installed:' | grep -q -w keycloak; then
				if [ -e "/etc/keycloak.secret" ]; then
					domain_admins="$(custom_groupname "Domain Admins")"
					# master realm
					# shellcheck disable=SC2154
					univention-keycloak \
						--realm master \
						ldap-federation \
						set \
						--name ldap-master-admin \
						--config \
						userObjectClasses="person" \
						customUserSearchFilter="(|(memberOf=cn=${domain_admins},cn=groups,${ldap_base})(memberOf=cn=DC Backup Hosts,cn=groups,${ldap_base}))" || true
					# ucs realm
					univention-keycloak ldap-federation set --config userObjectClasses="person" || true
				fi
			fi
		fi
	fi
	# update keycloak ldap federation config Bug 57205
	if dpkg --compare-versions "$2" lt-nl "1.0.11-2"; then
		if [ -e /var/univention-join/joined ] ; then
			if univention-app info | grep 'Installed:' | grep -q -w keycloak; then
				if [ -e "/etc/keycloak.secret" ]; then
					univention-keycloak ldap-federation set --config customUserSearchFilter="(uid=*)" || true
				fi
			fi
		fi
	fi
	# remove duplicate UID mappers Bug #57420
	if dpkg --compare-versions "$2" lt-nl "1.0.12-4"; then
		if [ -e /var/univention-join/joined ] ; then
			if univention-app info | grep 'Installed:' | grep -q -w keycloak; then
				if [ -e "/etc/keycloak.secret" ]; then
					/usr/share/univention-keycloak/fix-duplicate-uid-mappers || true
				fi
			fi
		fi
	fi
	# startTLS and connectionPooling are incompatible #58182
	if dpkg --compare-versions "$2" lt-nl "3.0.27-2"; then
		if [ -e /var/univention-join/joined ] ; then
			if univention-app info | grep 'Installed:' | grep -q -w keycloak; then
				if [ -e "/etc/keycloak.secret" ]; then
					config_realm_master=$(univention-keycloak --realm master ldap-federation get --name ldap-master-admin --json)
					start_tls_master=$(echo "$config_realm_master" | python3 -c "import sys, ast; print(ast.literal_eval(sys.stdin.read())['config']['startTls'][0])")
					if [ "$start_tls_master" = "true" ]; then
						echo "startTLS is enabled for realm 'master', disabling connectionPooling..."
						univention-keycloak --realm master ldap-federation set --name ldap-master-admin --config connectionPooling=false
					fi
					config_realm_ucs=$(univention-keycloak --realm ucs ldap-federation get --json)
					start_tls_ucs=$(echo "$config_realm_ucs" | python3 -c "import sys, ast; print(ast.literal_eval(sys.stdin.read())['config']['startTls'][0])")
					if [ "$start_tls_ucs" = "true" ]; then
						echo "startTLS is enabled for realm 'ucs', disabling connectionPooling..."
						univention-keycloak --realm ucs ldap-federation set --config connectionPooling=false
					fi
				fi
			fi
		fi
	fi
fi

exit 0
