# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

[build-system]
requires = [
    "setuptools >= 64",
    "pkgconfig",
    "python-debian",
]
build-backend = "setuptools.build_meta"

[project]
name = "univention-python-heimdal"
version = "0.0.0"
description = "Heimdal Kerberos Python bindings"
license = {text = "AGPL-3.0-only"}
requires-python = ">= 3.11"
dependencies = []
maintainers = [
    { name = "Univention GmbH", email = "packages@univention.de" },
]

[project.urls]
Homepage = "https://www.univention.de/"
