({
	'bold': 'Lihavointi',
	'copy': 'Kopioi',
	'cut': 'Leikkaa',
	'delete': 'Poista',
	'indent': 'Sisennä',
	'insertHorizontalRule': 'Vaakasuuntainen viiva',
	'insertOrderedList': 'Numeroitu luettelo',
	'insertUnorderedList': 'Numeroimaton luettelo',
	'italic': 'Kursivointi',
	'justifyCenter': 'Tasaus keskelle',
	'justifyFull': 'Tasaus',
	'justifyLeft': 'Tasaus vasemmalle',
	'justifyRight': 'Tasaus oikealle',
	'outdent': 'Ulonna',
	'paste': 'Liitä',
	'redo': 'Tee uudelleen',
	'removeFormat': 'Poista muotoilu',
	'selectAll': 'Valitse kaikki',
	'strikethrough': 'Yliviivaus',
	'subscript': 'Alaindeksi',
	'superscript': 'Yläindeksi',
	'underline': 'Alleviivaus',
	'undo': 'Kumoa',
	'unlink': 'Poista linkki',
	'createLink': 'Luo linkki',
	'toggleDir': 'Vaihda suuntaa',
	'insertImage': 'Lisää kuva',
	'insertTable': 'Lisää taulukko/muokkaa taulukkoa',
	'toggleTableBorder': 'Ota taulukon kehys käyttöön/poista kehys käytöstä',
	'deleteTable': 'Poista taulukko',
	'tableProp': 'Taulukon ominaisuudet',
	'htmlToggle': 'HTML-lähde',
	'foreColor': 'Edustaväri',
	'hiliteColor': 'Taustaväri',
	'plainFormatBlock': 'Kappaletyyli',
	'formatBlock': 'Kappaletyyli',
	'fontSize': 'Fontin koko',
	'fontName': 'Fontin nimi',
	/* Error messages */
	'systemShortcutFF': 'Toiminto "${0}" on käytettävissä vain Mozilla Firefox -ohjelmassa, kun käytetään pikanäppäimiä. Käytä kohdetta ${1}.'
})
