#! /bin/sh
#
# Univention Samba
#  postrm script
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 74univention-samba.uinst

	ucr unset security/packetfilter/package/univention-samba/tcp/137:139/all \
			security/packetfilter/package/univention-samba/tcp/137:139/all/en \
			security/packetfilter/package/univention-samba/udp/137:139/all \
			security/packetfilter/package/univention-samba/udp/137:139/all/en \
			security/packetfilter/package/univention-samba/udp/137/all \
			security/packetfilter/package/univention-samba/tcp/445/all \
			security/packetfilter/package/univention-samba/tcp/445/all/en \
			security/packetfilter/package/univention-samba/udp/445/all \
			security/packetfilter/package/univention-samba/udp/445/all/en
	[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

	ucr unset samba/share/home \
			samba/share/groups \
			samba/adminusers \
			samba/debug/level \
			samba/os/level \
			samba/profileserver \
			samba/profilepath \
			samba/homedirserver \
			samba/homedirpath \
			samba/homedirletter \
			samba/script/adduser \
			samba/script/deleteuser \
			samba/script/addgroup \
			samba/script/deletegroup \
			samba/script/addusertogroup \
			samba/script/deleteuserfromgroup \
			samba/script/addmachine \
			samba/script/setprimarygroup \
			samba/script/postusermodify \
			samba/winbind/nested/groups \
			samba/encrypt_passwords \
			samba/use_spnego \
			samba/client_use_spnego \
			samba/oplocks \
			samba/kernel_oplocks \
			samba/large_readwrite \
			samba/deadtime \
			samba/read_raw \
			samba/write_raw \
			samba/max_xmit \
			samba/max_open_files \
			samba/max/protocol \
			samba/min/protocol \
			samba/client/max/protocol \
			samba/client/min/protocol \
			samba/getwd_cache \
			samba/store_dos_attributes \
			samba/preserve_case \
			samba/short_preserve_case \
			samba/time_server \
			samba/guest_account \
			samba/map_to_guest \
			samba/netlogon/sync \
			samba/domain/logons \
			samba/password/checkscript \
			windows/wins-support \
			samba/role

	systemctl try-restart univention-directory-listener
fi

exit 0
