#!/usr/share/ucs-test/runner bash
## desc: "Join a domain without admin rights"
## exposure: safe
## packages:
##  - univention-samba
## roles: [memberserver]
## tags: [basic]
. "$TESTLIBPATH/base.sh" || exit 137
. "$TESTLIBPATH/user.sh" || exit 137

if ! current_ucs_version_greater_equal 2.3; then
	exit 131
fi

SAMBA="true"
MAIL="false"
KERBEROS="false"
PERSON="false"
POSIX="true"
username="$(user_randomname)"
trap 'user_remove "$username"' INT TERM EXIT
user_create "$username"

#wait for the user to be created
i=0
while true
do
    let i=$i+1
    sleep 1
    net rpc user -U"$username%$univention" | grep "$username" > /dev/null && break
    if [ $i == 20 ]; then
	echo "TIMEOUT: The User which has been created in UDM could not be found in samba."
	break
    fi
done


ADMINISTRATOR_DN="$(univention-directory-manager users/user list --filter uid="$ADMINISTRATOR_USER" | sed -ne 's/^DN: //p')"
USER_DN="$(univention-directory-manager users/user list --filter uid="$username" | sed -ne 's/^DN: //p')"

net rpc join -U "$username"%univention && \
	{ fail_fast 1 "Did a Domain join without the SeMachineAccountPrivilege"; }

univention-directory-manager users/user modify --binddn "$ADMINISTRATOR_DN" \
                                 	--bindpwd "$ADMINISTRATOR_PASSWORD" \
									--dn "$USER_DN" \
									--set "sambaPrivileges=SeMachineAccountPrivilege"

for i in {0..10}
do
	net rpc join -U "$username"%univention || \
	{ fail_fast 1 "Domain join failed"; }
done

exit 0
