#!/bin/sh
#
# Univention Directory Policy
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

univention-config-registry set ldap/policy/cron?"5 * * * *"

#DEBHELPER#

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl 14.0.2; then
	update-rc.d univention-directory-policy remove >/dev/null || true
fi

create_logfile /var/log/univention/ldap-policy.log "root:adm" 640

call_joinscript 20univention-directory-policy.inst

exit 0
