#!/bin/bash
#
# Univention App Center
#
# Copyright 2015 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.
#

PACKAGE=univention-appcenter
VERSION="$(dpkg-parsechangelog | sed -ne 's/^Version: //p')"

for loc in de; do
	echo "Compiling $loc.po!"
	if [ ! -f "python/$loc.po" ]; then
		cat > "python/$loc.po" <<- EOF
msgid ""
msgstr ""
"Project-Id-Version: $PACKAGE\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: $(date "+%Y-%m-%d")\n"
"PO-Revision-Date: $(date "+%Y-%m-%d %H:%M%z")\n"
"Last-Translator: $DEBFULLNAME <$DEBEMAIL>\n"
"Language-Team: \n"
"Language: German\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
		EOF
	fi
	xgettext --output="python/$loc.pot" --language=Python --no-location $(find python -name '*.py')
	msgmerge -N --update "python/$loc.po" "python/$loc.pot"
	rm "python/$loc.po~" "python/$loc.pot" || true
done
