#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Univention App Center
#  univention-rename-app
#
# Copyright 2014-2021 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.
#

import sys
from argparse import ArgumentParser

from univention.lib.package_manager import PackageManager
from univention.updater.tools import UniventionUpdater
from univention.config_registry import ConfigRegistry
from univention.management.console.modules.appcenter.util import ComponentManager, install_opener, rename_app

ucr = ConfigRegistry()
ucr.load()


def main():
	# type: () -> None
	description = '%prog changes the internal ID of an application. This means:' \
		'(1) unregister OLD_ID, remove from LDAP' \
		'(2) register NEW_ID, add to LDAP'
	parser = ArgumentParser(description=description)
	parser.add_argument("old_id")
	parser.add_argument("new_id")
	args = parser.parse_args()

	try:
		install_opener(ucr)
		uu = UniventionUpdater(False)
		component_manager = ComponentManager(ucr, uu)
		package_manager = PackageManager(lock=False)
		rename_app(args.old_id, args.new_id, component_manager, package_manager)
	except Exception:
		sys.stderr.write('ERROR: univention-rename-app "%s" "%s" did not succeed. Maybe a network error? In this case, just repeat the command.\n' % (args.old_id, args.new_id))
		sys.exit(1)
	else:
		sys.stdout.write('Rename done.\n')
		sys.exit(0)


if __name__ == '__main__':
	main()
