#!/bin/sh
#
# Univention NFS
#  postinst script for the debian package
#
# Copyright 2004-2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

if [ "$1" = configure -a -n "$2" ] && dpkg --compare-versions "$2" lt 0.8; then
	if [ -e /var/lib/univention-directory-listener/handlers/nfs-shares ]; then
		univention-directory-listener-ctrl resync nfs-shares
	fi
fi

univention-config-registry set nfs/ports?static

# configure firewall
ucr set security/packetfilter/package/univention-nfs/tcp/111/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/tcp/111/all/en="portmap" \
		security/packetfilter/package/univention-nfs/udp/111/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/udp/111/all/en="portmap" \
		security/packetfilter/package/univention-nfs/tcp/2049/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/tcp/2049/all/en="NFS" \
		security/packetfilter/package/univention-nfs/udp/2049/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/udp/2049/all/en="NFS" \
		security/packetfilter/package/univention-nfs/tcp/4660/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/tcp/4660/all/en="NFS" \
		security/packetfilter/package/univention-nfs/udp/4660/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/udp/4660/all/en="NFS" \
		security/packetfilter/package/univention-nfs/tcp/32765:32769/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/tcp/32765:32769/all/en="NFS related RPC daemons" \
		security/packetfilter/package/univention-nfs/udp/32765:32769/all="ACCEPT" \
		security/packetfilter/package/univention-nfs/udp/32765:32769/all/en="NFS related RPC daemons"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart


if [ "$1" = "configure" ]; then
	if test -f /etc/init.d/univention-directory-listener
		then
		/etc/init.d/univention-directory-listener crestart
	fi
fi

#DEBHELPER#

exit 0
