#!/bin/sh
#
# Univention NFS
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

case "$1" in
	configure)

		univention-config-registry set \
			nfs/ports?static \
			nfs/nfsd/nfs4?true \
			nfs/create/homesharepath?true \
			nfs/common/gssd?yes \
			nfs/common/idmapd?yes

		# configure firewall
		ucr set security/packetfilter/package/univention-nfs/tcp/111/all="ACCEPT" \
			security/packetfilter/package/univention-nfs/tcp/111/all/en="portmap" \
			security/packetfilter/package/univention-nfs/udp/111/all="ACCEPT" \
			security/packetfilter/package/univention-nfs/udp/111/all/en="portmap" \
			security/packetfilter/package/univention-nfs/tcp/2049/all="ACCEPT" \
			security/packetfilter/package/univention-nfs/tcp/2049/all/en="NFS" \
			security/packetfilter/package/univention-nfs/udp/2049/all="ACCEPT" \
			security/packetfilter/package/univention-nfs/udp/2049/all/en="NFS" \
			security/packetfilter/package/univention-nfs/tcp/32765:32769/all="ACCEPT" \
			security/packetfilter/package/univention-nfs/tcp/32765:32769/all/en="NFS related RPC daemons" \
			security/packetfilter/package/univention-nfs/udp/32765:32769/all="ACCEPT" \
			security/packetfilter/package/univention-nfs/udp/32765:32769/all/en="NFS related RPC daemons"
		[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

		# Bug #46587: Disable rpc-svcgssd.service for now on fresh installations only
		if [ -z "$2" ]
		then
			systemctl mask rpc-svcgssd.service
		fi

		systemctl try-restart univention-directory-listener

		call_joinscript 81univention-nfs-server.inst
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
