#!/usr/bin/python2.4
# -*- coding: utf-8 -*-
#
# Univention Package Database
#  python preporcessor
#
# Copyright 2004-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

import os, sys, py_compile

if len(sys.argv) == 2:
	input=sys.argv[1]
	output=input+'o'
elif len(sys.argv) == 3:
	input, output = sys.argv[1:]
else:
	sys.exit(1)

print 'byte-compiling: %s' % input

if os.path.exists(output):
	os.unlink(output)
e=py_compile.compile(input, output)
if not os.path.exists(output):
	sys.exit(1)
