#!/usr/bin/python3
#
# Univention Package Database
#  scans the installed packages
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

import univention.pkgdb


if __name__ == '__main__':
    univention.pkgdb.main()
