#!/usr/share/ucs-test/runner python
## desc: Basic email delivery
## tags: apptest
## exposure: dangerous
## packages: [univention-mail-server, univention-config, univention-directory-manager-tools]
## bugs: [23527, 35924]

#################
#  Information  #
#################
# This script tests the capability of the mail system to deliver mails to
# recpients with special mail addresses and to local users, thereby also
# testing the basic function of the mail system.
# For every mail address one user is created and deleted at the end of
# this script.
#################

from essential.mail import file_search_mail, send_mail
import time
import univention.testing.strings as uts
import univention.testing.ucr as ucr_test
import univention.testing.udm as udm_test
import univention.testing.utils as utils

def main():
	TIMEOUT = 120
	ucr = ucr_test.UCSTestConfigRegistry()
	ucr.load()
	with udm_test.UCSTestUDM() as udm:
		mailsToTest = []
		users = []
		domain = ucr.get('domainname')
		mails = [
			'BIG%ssmall@%s' % (uts.random_string(), domain),
			'%s.t.o.c@%s' % (uts.random_string(), domain),
			'un_sc%s@%s'  % (uts.random_string(), domain),
			'1fo%so2bar3@%s'  % (uts.random_string(), domain)
			]
		for mail in mails:
			userdn, username = udm.create_user(
					set={
						'mailHomeServer': '%s.%s' % (ucr.get('hostname'), domain),
						'mailPrimaryAddress': mail,
						}
					)
			users.append(username)
			mailsToTest.extend([mail, mail.upper(), mail.lower()])
		print mailsToTest

		test_cases1 = []
		for mail in mailsToTest:
			token = str(time.time())
			test_cases1.append([token, mail, False])
			print '\nTOKEN = %s\n' % token
			send_mail(recipients=mail, msg=token, idstring=token, subject='Test')

		test_cases2 = []
		for user in users:
			token = str(time.time())
			test_cases2.append([token, user, False])
			print '\nTOKEN = %s\n' % token
			send_mail(recipients=user, msg=token, subject='Test')

		test_cases3 = []
		for user in users:
			token = str(time.time())
			test_cases3.append([token, user, False])
			print '\nTOKEN = %s\n' % token
			# tls:
			send_mail(recipients=user, msg=token, subject='TestTLS', tls=True)

		print "\nWaiting up to %d seconds for delivering mails...\n" % (TIMEOUT, )

		for timeout in xrange(TIMEOUT, 0, -1):
			print 'Waiting up to %d seconds' % (timeout,)
			all_found = True
			for i, (token, mail, found)  in enumerate(test_cases1):
				if file_search_mail(tokenlist=[token], mail_address=mail):
					test_cases1[i][2] = True
				else:
					all_found = False
			for i, (token, user, found)  in enumerate(test_cases2):
				if file_search_mail(tokenlist=[token], user=user):
					test_cases2[i][2] = True
				else:
					all_found = False
			for i, (token, user, found)  in enumerate(test_cases3):
				if file_search_mail(tokenlist=[token], user=user):
					test_cases3[i][2] = True
				else:
					all_found = False
			if not all_found:
				time.sleep(1)

		for token, mail, found in test_cases1:
			if not found:
				utils.fail('Mail sent to %r with token %r was not delivered' % (mail, token))
		for token, user, found in test_cases2:
			if not found:
				utils.fail('Mail sent with token = %r, to %s was not delivered' % (token, user))
		for token, user, found in test_cases3:
			if not found:
				utils.fail('Mail sent with token = %r, to %s was not delivered (TLS used)' % (token, user))


if __name__ == '__main__':
	main()
