#!/usr/share/ucs-test/runner python
## desc: Cyrus authentication
## tags: [apptest]
## exposure: safe
## packages: [cyrus-common]
## bugs: [23527, 38321]

from subprocess import (Popen, PIPE)
import os
import univention.testing.utils as utils


def main():
	env = os.environ.copy()
	env.update({'COLUMNS':'80', 'LINES':'25', 'TERM':'xterm'})
	account = utils.UCSTestDomainAdminCredentials()
	cmd = [
		'/usr/bin/cyradm',
		'--server=localhost',
		'--password=%s' % (account.bindpw,),
		'--auth=login',
	]
	proc = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env)
	out, err = proc.communicate()
	if 'localhost>' not in out or err:
		utils.fail(err)

if __name__ == '__main__':
	main()
