#!/usr/share/ucs-test/runner python
## desc: IMAP mail login
## tags: [apptest]
## exposure: dangerous
## packages: [univention-mail-server]
## bugs: []

from essential.mailclient import MailClient_SSL
import univention.testing.strings as uts
import univention.testing.ucr as ucr_test
import univention.testing.udm as udm_test
import univention.testing.utils as utils

def main():
	with ucr_test.UCSTestConfigRegistry() as ucr:
		with udm_test.UCSTestUDM() as udm:
			username = uts.random_name()
			password = uts.random_string()
			mailAddress = '%s@%s' % (username, ucr.get('domainname'))
			userdn, username = udm.create_user(
					username=username,
					password=password,
					mailPrimaryAddress= mailAddress,
					option=['mail', 'person', 'posix', 'samba', 'pki']
					)


			print '* Test imap login with the correct password:'
			imap = MailClient_SSL('%s.%s' % (ucr.get('hostname'), ucr.get('domainname')))
			if imap.login_ok(mailAddress, password):
				utils.fail('IMAP login failed with the correct password')

			print '* Test imap login with the wrong password:'
			imap = MailClient_SSL('%s.%s' % (ucr.get('hostname'), ucr.get('domainname')))
			if imap.login_ok(mailAddress, uts.random_name(), expected_to_succeed=False):
				utils.fail('IMAP login succeeded with the wrong password')


if __name__ == '__main__':
	main()
