#!/usr/share/ucs-test/runner python
## desc: IMAP mail login
## tags: apptest
## exposure: dangerous
## packages: [univention-mail-server]
## bugs: []

from essential.mail import disable_mail_quota, enable_mail_quota, ImapMail
import univention.testing.strings as uts
import univention.testing.ucr as ucr_test
import univention.testing.udm as udm_test
import univention.testing.utils as utils

def main():
	with ucr_test.UCSTestConfigRegistry() as ucr:
		with udm_test.UCSTestUDM() as udm:
			username = uts.random_name()
			password = uts.random_string()
			mailAddress = '%s@%s' % (username, ucr.get('domainname'))
			userdn, username = udm.create_user(
					username=username,
					password=password,
					mailPrimaryAddress= mailAddress,
					option=['mail', 'person', 'posix', 'samba', 'pki']
					)

			imap = ImapMail()

			print '* Test imap login with the correct password:'
			if not imap.login_OK(mailAddress, password):
				utils.fail('IMAP login failed with the correct password')

			print '* Test imap login with the wrong password:'
			if imap.login_OK(mailAddress, uts.random_name()):
				utils.fail('IMAP login succeeded with the wrong password')


if __name__ == '__main__':
	main()
