#!/usr/share/ucs-test/runner python
## desc: Imap mail login
## tags: apptest
## exposure: dangerous
## packages: [univention-mail-server]
## bugs: []

from essential.mail import disable_mail_quota, enable_mail_quota, ImapMail
import univention.testing.strings as uts
import univention.testing.ucr as ucr_test
import univention.testing.udm as udm_test
import univention.testing.utils as utils
	
def main():
	with ucr_test.UCSTestConfigRegistry() as ucr:
		with udm_test.UCSTestUDM() as udm:
			username = uts.random_name()
			password = uts.random_string()
			userdn, username = udm.create_user(
					username=username,
					password=password,
					mailPrimaryAddress='%s@%s' % (username, ucr.get('mail/hosteddomains')),
					option=['mail', 'person', 'posix', 'samba', 'pki']
					)

			imap = ImapMail()

			disable_mail_quota()

			print '* Test imap login with the correct password:'
			if not imap.login_OK(username, password):
				utils.fail('imap login failed with the correct password')

			print '* Test imap login with the wrong password:'
			if imap.login_OK(username, '_'):
				utils.fail('imap login succeeded with the wrong password')

			enable_mail_quota()

			print '* Test imap login with the correct password:'
			if not imap.login_OK(username, password):
				utils.fail('imap login failed with the correct password')

			print '* Test imap login with the wrong password:'
			if imap.login_OK(username, '_'):
				utils.fail('imap login succeeded with the wrong password')


if __name__ == '__main__':
	main()
