#!/usr/share/ucs-test/runner python
## desc: Append nestedGroups during groups/group modification
## tags: [udm,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools

import univention.testing.utils as utils
import univention.testing.udm as udm_test

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		group = udm.create_group()[0]
		nested_groups = [udm.create_group()[0], udm.create_group()[0]]

		udm.modify_object('groups/group', dn=group, append={'nestedGroup': nested_groups})
		utils.verify_ldap_object(group, {'uniqueMember': nested_groups})
