#!/bin/sh
#
# Example Schema for Univention Directory Manager Example Module
#  postrm file for the example schema debian package for the directory manager example module
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
remove)
		test -e /etc/ldap/slapd.conf && /usr/sbin/univention-config-registry commit /etc/ldap/slapd.conf
		test -x /etc/init.d/slapd && invoke-rc.d slapd restart
	;;

purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
