#!/bin/sh
#
# Example Schema for Univention Directory Manager Example Module
#  postinst file for the example schema debian package for the directory manager example module
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
configure)
	test -x /etc/init.d/slapd && invoke-rc.d slapd restart
	;;

abort-upgrade|abort-remove|abort-deconfigure)
	;;

*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
