#!/bin/sh
#
# Univention Management Console Web Server
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/base.sh

# add apache modules for redirect to UMC web server
a2enmod wsgi
a2enmod proxy
a2enmod proxy_connect
a2enmod proxy_http
a2enmod headers
a2enmod lbmethod_bybusyness
a2enmod proxy_balancer
a2ensite univention.conf

if apache2ctl --configtest; then
	invoke-rc.d apache2 restart
fi

# update to UCS 5.0
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl 12.0.0-1; then
	# Delete old Python 2 cache which is incompatible with Python 3
	rm -f /var/cache/univention-management-console/saml-*.bdb
fi

# provide new settings
univention-config-registry set \
	umc/http/session/timeout?28800 \
	umc/http/response-timeout?310 \
	umc/http/autostart?yes \
	umc/http/port?8090 \
	umc/http/interface?127.0.0.1 \
	umc/server/upload/min_free_space?51200 \
	umc/http/content-security-policy/default-src?"'unsafe-eval'" \
	umc/http/content-security-policy/script-src?"'self' 'unsafe-inline' 'unsafe-eval' https://www.youtube.com/ https://s.ytimg.com/" \
	umc/http/content-security-policy/object-src?"'self'" \
	umc/http/content-security-policy/style-src?"'self' 'unsafe-inline'" \
	umc/http/content-security-policy/img-src?"*" \
	umc/http/content-security-policy/media-src?"*" \
	umc/http/content-security-policy/frame-src?"*" \
	umc/http/content-security-policy/font-src?"'self'" \
	umc/http/content-security-policy/connect-src?"'self'" \
	umc/http/content-security-policy/form-action?"'self'" \
	umc/http/content-security-policy/frame-ancestors?"'self'" \
	umc/login/content-security-policy/frame-ancestors?"'self'"

if [ "$1" = "configure" ]
then
	uinst=/usr/lib/univention-install/09univention-management-console-web-server.uinst
	[ -e "$uinst" ] && rm "$uinst"
fi

call_joinscript 92univention-management-console-web-server.inst

exit 0
