#!/bin/sh
#
# Univention Management Console Frontend
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# generate a new hash for the UMC frontend in order to avoid caching problems
# shellcheck source=/dev/null
. /usr/share/univention-lib/umc.sh
umc_frontend_new_hash

# provide new settings for localisation of umc frontend
univention-config-registry set "umc/web/feedback/mail?feedback@univention.de" \
	"umc/web/feedback/description?[UMC-Feedback] Traceback" \
	"umc/web/favorites/default?welcome,udm:users/user,udm:groups/group,udm:computers/computer,appcenter:appcenter,updater" \
	"umc/web/sso/enabled?true"

exit 0
