#!/bin/sh
#
# Univention Management Console Login
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# set default UCR settings
univention-config-registry set umc/login/links/how_do_i_login/enabled?true

if [ ! -e "/usr/share/univention-management-console-login/css/custom.css" ]; then
	cp /usr/share/univention-management-console-login/css/custom.css.example /usr/share/univention-management-console-login/css/custom.css
fi

exit 0
