usr/sbin/univention-management-console-acls
usr/sbin/univention-management-console-client
usr/sbin/univention-management-console-module
usr/sbin/univention-management-console-server
usr/share/locale/*
data/categories/icon/*.svg usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/scalable
umc-service-providers.py usr/lib/univention-directory-listener/system/
systemd/system/univention-management-console-server.service.d lib/systemd/system/
