data/categories/icon/*.svg	usr/share/univention-management-console-frontend/js/dijit/themes/umc/icons/scalable/
scripts/postrotate	usr/share/univention-management-console/
systemd/system/univention-management-console-server-multiprocessing.target lib/systemd/system/
systemd/system/univention-management-console-server.service.d	lib/systemd/system/
systemd/system/univention-management-console-server@.service	lib/systemd/system/
umc-service-providers.py	usr/lib/univention-directory-listener/system/
