#!/bin/sh
#
# Univention Management Console
#  prerm script for the debian package
#
# SPDX-FileCopyrightText: 2016-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]
then
	a2dissite univention.conf
	cp /usr/lib/univention-uninstall/09univention-management-console-web-server.uinst /usr/lib/univention-install/
	deb-systemd-invoke stop univention-management-console-server.service
fi

exit 0
