univention-management-console-web-server	usr/sbin/
92univention-management-console-web-server.inst usr/lib/univention-install/
09univention-management-console-web-server.uinst usr/lib/univention-uninstall/
usr/share/univention-management-console/
systemd/system/univention-management-console-web-server.service.d lib/systemd/system/
start_parallel_umc.py usr/sbin/
umc_parallel.service lib/systemd/system/
