univention-management-console-web-server	usr/sbin/
92univention-management-console-web-server.inst usr/lib/univention-install/
09univention-management-console-web-server.uinst usr/lib/univention-uninstall/
usr/share/univention-management-console/
systemd/system/univention-management-console-web-server.service.d lib/systemd/system/
umc_parallel.target lib/systemd/system/
univention-management-console-web-server-parallel-wrapper /usr/sbin/
univention-management-console-web-server@.service lib/systemd/system/
univention-management-console-server@.service lib/systemd/system/
