#!/bin/sh
# SPDX-FileCopyrightText: 2023-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Bug #55753: Fix UMC-web-server restart during upgrade from UCS 5.0-3+572..583
# Can/shall be removed with UCS 5.0-4
if [ "$1" = configure ] && [ -z "$2" ]
then
    sed -e '/^# Automatically added by dh_systemd_start\/12.1.1/,/^# End automatically added section/s#^\(if \[ -d /run/systemd/system \]\)\(; then\)$#\1 \&\& [ "\$1" = remove ]\2#' -i /var/lib/dpkg/info/univention-management-console-web-server.prerm /var/lib/dpkg/info/univention-management-console-server.prerm || :
fi

#DEBHELPER#

exit 0
