09univention-management-console-web-server.uinst	usr/lib/univention-uninstall/
92univention-management-console-web-server.inst	usr/lib/univention-install/
systemd/system/univention-management-console-web-server-multiprocessing.target	lib/systemd/system/
systemd/system/univention-management-console-web-server.service.d	lib/systemd/system/
systemd/system/univention-management-console-web-server@.service	lib/systemd/system/
univention-management-console-web-server	usr/sbin/
usr/share/univention-management-console/
