lib/*.sh	usr/share/univention-samba4/lib/
scripts/*	usr/share/univention-samba4/scripts/
*.inst	usr/lib/univention-install/
*.uinst	usr/lib/univention-uninstall/
univention-s4search	usr/sbin/
s4search-decode	usr/sbin/
samba-shares.py	usr/lib/univention-directory-listener/system/
samba4-idmap.py	usr/lib/univention-directory-listener/system/
lib/security
server_password_change.d/univention-samba4	usr/lib/univention-server/server_password_change.d/
sbin/*	usr/sbin/
