#!/bin/sh
#
# Univention Samba4 Sysvol Yync
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/base.sh

if [ "$1" = "configure" ]; then
	## create sysvol-sync logfile
	create_logfile /var/log/univention/sysvol-sync.log "root:adm" 640

	## activate sysvol replication
	univention-config-registry set samba4/sysvol/cleanup/cron?"4 4 * * *"

	## create the sysvol directory
	[ -d /var/lib/samba/sysvol ] ||
		install -m 755 -o root -g adm -d /var/lib/samba/sysvol

	## create a sysvol backup directory
	[ -d /var/lib/samba/sysvol_backup ] ||
		install -m 755 -o root -g adm -d /var/lib/samba/sysvol_backup
fi

# Fix permissions for the sysvol share
#  https://forge.univention.org/bugzilla/show_bug.cgi?id=27249
if [ "$1" = "configure" ] && [ -z "$2" ]
then
	SYSVOL_LOCKFILE="/var/lock/sysvol-sync-dir"
	touch "$SYSVOL_LOCKFILE" \
	&& chgrp "DC Slave Hosts" "$SYSVOL_LOCKFILE" \
	&& chmod g+w "$SYSVOL_LOCKFILE"

	ucr set sshd/config/ClientAliveInterval?60
	if [ -x /etc/init.d/ssh ]; then
		invoke-rc.d ssh reload
	fi
fi

exit 0
