#!/bin/sh
#
# Univention Samba4
#  prerm script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Test is_port_set ()
# is_port_set 389 389; echo $?
# is_port_set 7389,389 389; echo $?
# is_port_set 389,7389 389; echo $?
# is_port_set 389,7389,8389 389; echo $?
# is_port_set 7389,389,8389 389; echo $?
# is_port_set 7389,8389,389 389; echo $?
# is_port_set 7389,8389 389; echo $?

is_port_set ()
{
	echo "$1" | egrep "^${2},|,${2},|,${2}$|^${2}$" >/dev/null
}

eval "$(univention-config-registry shell)"

#DEBHELPER#

un_divert_univention_heimdal_service_cfg() {
	univention_heimdal_service_cfg='/etc/univention/service.info/services/univention-heimdal-kdc.cfg'
	dpkg-divert --local --rename \
		--divert "$univention_heimdal_service_cfg".disabled \
		--remove "$univention_heimdal_service_cfg" || true
}

if [ "$1" = "remove" ]; then

	eval "$(univention-config-registry shell)"

	if [ -x /etc/init.d/samba ]; then
		/etc/init.d/samba stop
	fi

	if [ -n "$slapd_port" ]; then
		is_port_set "$slapd_port" 389 || univention-config-registry set slapd/port="$slapd_port,389"
	fi
	if [ -n "$slapd_port_ldaps" ]; then
		is_port_set "$slapd_port_ldaps" 636 || univention-config-registry set slapd/port/ldaps="$slapd_port_ldaps,636"
	fi

	if [ -x /etc/init.d/slapd ]; then
		/etc/init.d/slapd crestart
	fi

	# Set DNS backend to ldap
	if [ "$dns_backend" = "samba4" ]; then
		ucr set dns/backend=ldap
		test -x /etc/init.d/named && invoke-rc.d named restart
	fi

	# Bug #43874: samba4 has that idea to divert the univention-service file to "not confuse the admin with a stopped heimdal-kdc", but now we're confusing systemd
	[ -d /run/systemd ] && systemctl unmask heimdal-kdc.service || :
	[ -d /run/systemd ] && systemctl enable heimdal-kdc.service || :
	ucr unset kerberos/autostart
	test -x /etc/init.d/heimdal-kdc && invoke-rc.d heimdal-kdc start

	un_divert_univention_heimdal_service_cfg

	cp /usr/lib/univention-uninstall/04univention-samba4.uinst /usr/lib/univention-install/
fi

exit 0

