#!/bin/sh
#
# Univention Samba4
#  postinst script
#
# Copyright 2004-2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/all.sh

if [ "$1" = "configure" ] && [ -z "$2" ]; then
	if [ -d '/var/lib/samba' ]; then
		mkdir -p /var/lib/samba3
		## backup existing samba3 lib dir
		cp -a /var/lib/samba/* /var/lib/samba3
	fi
fi

#DEBHELPER#

eval "$(univention-config-registry shell)"

dpkg-statoverride --update --add root root 0750 /var/log/samba || true


if [ -z "$2" ]; then
	mkdir -p /home/groups

	mkdir -p /etc/univention/skel/windows-profiles
	for dname in Win95 WinNT Win2k WinXP Win2K3 Vista Vista.V2 default default.V2; do
		mkdir -p /etc/univention/skel/windows-profiles/$dname
	done
fi

if [ "$1" = "configure" -a -n "$2" ] && dpkg --compare-versions "$2" lt 1.0.148-1 ; then
	mkdir -p /etc/univention/skel/windows-profiles/default
	mkdir -p /etc/univention/skel/windows-profiles/default.V2
fi


## samba3 defaults copied from univention-samba
univention-config-registry set \
	samba/share/home?yes \
	samba/share/groups?no \
	samba/adminusers?"administrator join-backup" \
	samba/encrypt_passwords?yes \
	samba/use_spnego?yes \
	samba/client_use_spnego?yes \
	samba/oplocks?yes \
	samba/kernel_oplocks?yes \
	samba/large_readwrite?yes \
	samba/deadtime?15 \
	samba/read_raw?yes \
	samba/write_raw?yes \
	samba/max_xmit?65535 \
	samba/getwd_cache?yes \
	samba/store_dos_attributes?yes \
	samba/preserve_case?yes \
	samba/short_preserve_case?yes \
	samba/guest_account?nobody \
	samba/map_to_guest?"Bad User"

## more samba3 defaults copied from univention-samba
if [ "$server_role" != "memberserver" ]
then
	if [ -n "$samba_netbios_name" ]
	then
		tmphostname=$samba_netbios_name
	else
		tmphostname="$hostname"
	fi
	univention-config-registry set samba/profileserver?$tmphostname \
								   samba/profilepath?'%U\windows-profiles\%a' \
								   samba/homedirserver?$tmphostname \
								   samba/homedirpath?%U \
								   samba/homedirletter?I
fi

univention-config-registry set \
	samba/debug/level?1 \
	samba4/sysvol/sync/jitter?60 \
	samba4/service/smb?'s3fs' \
	samba4/service/nmb?'nmbd' \
	samba4/ntacl/backend?'native'

# configure firewall
# http://technet.microsoft.com/en-us/library/dd772723%28WS.10%29.aspx
ucr set security/packetfilter/package/univention-samba4/tcp/389/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/389/all/en="LDAP" \
		security/packetfilter/package/univention-samba4/udp/389/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/389/all/en="LDAP" \
		security/packetfilter/package/univention-samba4/tcp/636/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/636/all/en="LDAPS" \
		security/packetfilter/package/univention-samba4/tcp/53/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/53/all/en="DNS" \
		security/packetfilter/package/univention-samba4/udp/53/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/53/all/en="DNS" \
		security/packetfilter/package/univention-samba4/udp/123/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/123/all/en="TIME" \
		security/packetfilter/package/univention-samba4/tcp/135/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/135/all/en="RPC (Samba)" \
		security/packetfilter/package/univention-samba4/tcp/137:139/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/137:139/all/en="netbios (Samba)" \
		security/packetfilter/package/univention-samba4/udp/137:139/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/137:139/all/en="netbios (Samba)" \
		security/packetfilter/package/univention-samba4/tcp/445/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/445/all/en="microsoft-ds (Samba)" \
		security/packetfilter/package/univention-samba4/udp/445/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/445/all/en="microsoft-ds (Samba)" \
		security/packetfilter/package/univention-samba4/tcp/1024/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/1024/all/en="KDM (Samba)" \
		security/packetfilter/package/univention-samba4/tcp/3268/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/3268/all/en="LDAP GC (Samba)" \
		security/packetfilter/package/univention-samba4/tcp/3269/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/3269/all/en="LDAP GC SSL (Samba)" \
		security/packetfilter/package/univention-samba4/tcp/88/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/88/all/en="Kerberos" \
		security/packetfilter/package/univention-samba4/udp/88/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/88/all/en="Kerberos" \
		security/packetfilter/package/univention-samba4/tcp/464/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/464/all/en="Kerberos change/set password" \
		security/packetfilter/package/univention-samba4/udp/464/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/udp/464/all/en="Kerberos change/set password" \
		security/packetfilter/package/univention-samba4/tcp/749/all="ACCEPT" \
		security/packetfilter/package/univention-samba4/tcp/749/all/en="Kerberos admin"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

if [ "$1" = "configure" ]; then


	if [ -z "$2" ]; then
    	univention-config-registry set samba4/autostart="no"                                                                                                                                            

		# only set this for new installations
		if [ "$server_role" = "domaincontroller_master" ]; then
			univention-config-registry set windows/wins-support=yes
		else
			univention-config-registry set windows/wins-support?no
			univention-config-registry set windows/wins-server?$ldap_master
		fi

		## New installation, remove leftover samba3.x rc?.d links 
		update-rc.d -f samba remove > /dev/null

	elif [ -n "$2" ]; then

		chgrp ntp /var/lib/samba/ntp_signd
		chmod g+x /var/lib/samba/ntp_signd

		if [ -x /etc/init.d/samba4 ]; then
			processes=$(pgrep -cfx '/usr/sbin/samba -D')
			if [ "$processes" = 0 ]; then
				/etc/init.d/samba4 start
			elif [ "$processes" = 1 ]; then
				pkill -9 -xf '/usr/sbin/samba -D'
				/etc/init.d/samba4 start
			else
				/etc/init.d/samba4 restart
			fi
		fi

		## Is the password in secrets.ldb the valid password? In some cases
		## the password from machine.secret is the correct password.
		##  https://forge.univention.org/bugzilla/show_bug.cgi?id=26641

		# get the secret from ldb
		secret="$(ldbsearch -H /var/lib/samba/private/secrets.ldb  flatname=$windows_domain secret | sed -ne 's|secret: ||p')"
		# get the host dn
		dn="$(ldbsearch -H /var/lib/samba/private/sam.ldb "(&(cn=$hostname)(objectClass=computer))" dn | ldapsearch-wrapper | sed -ne 's|^dn: ||p')"
		if [ -n "$dn" -a -n "$secret" ]; then
			machine_secret="$(cat /etc/machine.secret)"
			if [ "$secret" != "$machine_secret" ]; then
				# try to search with the machine secret in S4 LDAP
				s_res="$(univention-ldapsearch -s base -h $hostname.$domainname -p 389 -w "$machine_secret" -D "$dn" dn | sed -ne 's|^dn: ||p')"
				if [ -n "$s_res" ]; then
					# the password from machine.secret is the valid password, so change the secrets.ldb
					echo "Set secret for flatname=$windows_domain,cn=Primary Domains"
					ldbmodify -H //var/lib/samba/private/secrets.ldb <<-%EOF
dn: flatname=$windows_domain,cn=Primary Domains
changetype: modify
replace: secret
secret: $machine_secret
-
%EOF
					/etc/init.d/samba4 restart
				fi
			fi
		fi
		
		## The following block of code can be removed after ucs3.0-2
		if dpkg --compare-versions "$2" lt-nl "1.0.154-1"; then
			if [ "$samba_debug_level" = 2 ]; then
				#only set this when value does not differ from the previous default value and the package is upgraded from a version which did not include this paragraph
				univention-config-registry set samba/debug/level=1
			fi
			
			# Re-create /etc/krb5.keytab
			#  https://forge.univention.org/bugzilla/show_bug.cgi?id=27426
			/usr/share/univention-samba4/scripts/create-keytab.sh

			## remove samba(3) system startup links
			update-rc.d -f samba remove > /dev/null

			## create dns-$hostname account for bind9 SPN
			/usr/share/univention-samba4/scripts/create_dns-host_spn.py
		fi

		### The following block of code may be removed after ucs_3.1-0
		if dpkg --compare-versions "$2" lt-nl "2.0.1-1"; then

			## switch from franky style smbd config to s3fs forked smbd
			/etc/init.d/samba4 stop

			if [ "$samba4_service_smb" = 'smbd' ]; then
				## only set this when value does not differ from the previous default value
				univention-config-registry set samba4/service/smb='s3fs'

			fi

			## run dbcheck on update but backup first.
			if [ -d /var/lib/samba/private ]; then
				backup_id=$(date +%Y%m%d-%H%M%S)
				backup_dir="/var/backups/samba4.$backup_id"
				if [ -d "$backup_dir" ]; then
					rm -rf "$backup_dir"
				fi
				mkdir "$backup_dir" && \
				cp -a /var/lib/samba/private "$backup_dir" && \
				samba-tool dbcheck --cross-ncs --fix --yes
			fi

			## activate server password chages again
			univention-config-registry set server/password/change=yes

			/etc/init.d/samba4 start
		fi

	fi

	if test -f /etc/init.d/univention-directory-listener; then
		/etc/init.d/univention-directory-listener crestart
	fi
fi

call_joinscript 96univention-samba4.inst
## cannot call joinscript 98univention-samba4-dns.inst here, maybe the s4-connector did not run yet

##### Join-Script fragments that need to be executed automatically also on Master and Backup:
if [ "$server_role" = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]; then

	## The following block of code can be removed after ucs3.0-1
	if [ -n "$2" ] && dpkg --compare-versions "$2" lt-nl "1.0.126-3"; then
		## Set DNS records again in case Bug #26285 occured in UCS 3.0-0. 
		## Flow control copied from 96univention-samba4.inst

		if [ "$samba4_role" = 'DC' ]; then

			s4connectorservicedcs="$(ldapsearch -x -ZZ -LLL -D "$ldap_hostdn" -y /etc/machine.secret "(&(univentionService=S4 Connector)(objectClass=univentionDomainController))" cn | sed -n 's/^cn: \(.*\)/\1/p')"

			if [ "$s4connectorservicedcs" = "$hostname" ]; then

				/usr/share/univention-samba4/scripts/setup-dns-in-ucsldap.sh --dc --gc --pdc "$@"

			else

				/usr/share/univention-samba4/scripts/setup-dns-in-ucsldap.sh --dc "$@"

			fi

		elif [ "$samba4_role" = "RODC" ]; then

			/usr/share/univention-samba4/scripts/setup-dns-in-ucsldap.sh --rodc "$@"

		fi

	fi

fi

# Run a samba-tool ntacl sysvolreset, this is required for the rc6 upgrade
if [ "$1" = "configure" -a -n "$2" ] && dpkg --compare-versions "$2" lt-nl 2.0.28; then
	samba-tool ntacl sysvolreset 
fi

exit 0
