#! /bin/sh
#
# Univention Samba4
#  postrm script
#
# Copyright 2013-2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

#DEBHELPER#

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 04univention-samba4.uinst

	ucr unset windows/wins-support \
			samba/max_open_files \
			samba/quota/command \
			samba/max/protocol \
			samba/min/protocol \
			samba/client/min/protocol \
			samba/client/max/protocol \
			samba/share/netlogon

	ucr unset security/packetfilter/package/univention-samba4/tcp/389/all \
			security/packetfilter/package/univention-samba4/tcp/389/all/en \
			security/packetfilter/package/univention-samba4/udp/389/all \
			security/packetfilter/package/univention-samba4/udp/389/all/en \
			security/packetfilter/package/univention-samba4/tcp/636/all \
			security/packetfilter/package/univention-samba4/tcp/636/all/en \
			security/packetfilter/package/univention-samba4/tcp/53/all \
			security/packetfilter/package/univention-samba4/tcp/53/all/en \
			security/packetfilter/package/univention-samba4/udp/53/all \
			security/packetfilter/package/univention-samba4/udp/53/all/en \
			security/packetfilter/package/univention-samba4/udp/123/all \
			security/packetfilter/package/univention-samba4/udp/123/all/en \
			security/packetfilter/package/univention-samba4/tcp/135/all \
			security/packetfilter/package/univention-samba4/tcp/135/all/en \
			security/packetfilter/package/univention-samba4/tcp/137:139/all \
			security/packetfilter/package/univention-samba4/tcp/137:139/all/en \
			security/packetfilter/package/univention-samba4/udp/137:139/all \
			security/packetfilter/package/univention-samba4/udp/137:139/all/en \
			security/packetfilter/package/univention-samba4/tcp/445/all \
			security/packetfilter/package/univention-samba4/tcp/445/all/en \
			security/packetfilter/package/univention-samba4/udp/445/all \
			security/packetfilter/package/univention-samba4/udp/445/all/en \
			security/packetfilter/package/univention-samba4/tcp/1024/all \
			security/packetfilter/package/univention-samba4/tcp/1024/all/en \
			security/packetfilter/package/univention-samba4/tcp/3268/all \
			security/packetfilter/package/univention-samba4/tcp/3268/all/en \
			security/packetfilter/package/univention-samba4/tcp/3269/all \
			security/packetfilter/package/univention-samba4/tcp/3269/all/en \
			security/packetfilter/package/univention-samba4/tcp/88/all \
			security/packetfilter/package/univention-samba4/tcp/88/all/en \
			security/packetfilter/package/univention-samba4/udp/88/all \
			security/packetfilter/package/univention-samba4/udp/88/all/en \
			security/packetfilter/package/univention-samba4/tcp/464/all \
			security/packetfilter/package/univention-samba4/tcp/464/all/en \
			security/packetfilter/package/univention-samba4/udp/464/all \
			security/packetfilter/package/univention-samba4/udp/464/all/en \
			security/packetfilter/package/univention-samba4/tcp/749/all \
			security/packetfilter/package/univention-samba4/tcp/749/all/en
	[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

	test -x /etc/init.d/univention-directory-listener && invoke-rc.d univention-directory-listener crestart
fi

exit 0
