#! /bin/sh
#
# Univention Samba4
#  postrm script
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 04univention-samba4.uinst

	ucr unset windows/wins-support \
			samba/max_open_files \
			samba/quota/command \
			samba/max/protocol \
			samba/min/protocol \
			samba/client/min/protocol \
			samba/client/max/protocol \
			samba/share/netlogon

	ucr unset security/packetfilter/package/univention-samba4/tcp/389/all \
			security/packetfilter/package/univention-samba4/tcp/389/all/en \
			security/packetfilter/package/univention-samba4/udp/389/all \
			security/packetfilter/package/univention-samba4/udp/389/all/en \
			security/packetfilter/package/univention-samba4/tcp/636/all \
			security/packetfilter/package/univention-samba4/tcp/636/all/en \
			security/packetfilter/package/univention-samba4/tcp/53/all \
			security/packetfilter/package/univention-samba4/tcp/53/all/en \
			security/packetfilter/package/univention-samba4/udp/53/all \
			security/packetfilter/package/univention-samba4/udp/53/all/en \
			security/packetfilter/package/univention-samba4/udp/123/all \
			security/packetfilter/package/univention-samba4/udp/123/all/en \
			security/packetfilter/package/univention-samba4/tcp/135/all \
			security/packetfilter/package/univention-samba4/tcp/135/all/en \
			security/packetfilter/package/univention-samba4/tcp/137:139/all \
			security/packetfilter/package/univention-samba4/tcp/137:139/all/en \
			security/packetfilter/package/univention-samba4/udp/137:139/all \
			security/packetfilter/package/univention-samba4/udp/137:139/all/en \
			security/packetfilter/package/univention-samba4/tcp/445/all \
			security/packetfilter/package/univention-samba4/tcp/445/all/en \
			security/packetfilter/package/univention-samba4/udp/445/all \
			security/packetfilter/package/univention-samba4/udp/445/all/en \
			security/packetfilter/package/univention-samba4/tcp/1024/all \
			security/packetfilter/package/univention-samba4/tcp/1024/all/en \
			security/packetfilter/package/univention-samba4/tcp/3268/all \
			security/packetfilter/package/univention-samba4/tcp/3268/all/en \
			security/packetfilter/package/univention-samba4/tcp/3269/all \
			security/packetfilter/package/univention-samba4/tcp/3269/all/en \
			security/packetfilter/package/univention-samba4/tcp/88/all \
			security/packetfilter/package/univention-samba4/tcp/88/all/en \
			security/packetfilter/package/univention-samba4/udp/88/all \
			security/packetfilter/package/univention-samba4/udp/88/all/en \
			security/packetfilter/package/univention-samba4/tcp/464/all \
			security/packetfilter/package/univention-samba4/tcp/464/all/en \
			security/packetfilter/package/univention-samba4/udp/464/all \
			security/packetfilter/package/univention-samba4/udp/464/all/en \
			security/packetfilter/package/univention-samba4/tcp/749/all \
			security/packetfilter/package/univention-samba4/tcp/749/all/en
	[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

	systemctl try-restart univention-directory-listener
fi

exit 0
