@%@UCRWARNING=# @%@

@!@
# flake8: noqa
port = configRegistry.get("portal/port")
for path in configRegistry.get('portal/paths').split(','):
    print("""
Alias /%(path)sicons /usr/share/univention-portal/icons
ProxyPassMatch "^/%(path)sicons/.*" !
ProxyPassMatch /(%(path)s(portal|apps|navigation).json) http://127.0.0.1:%(port)s/$1 retry=0
ProxyPassMatch /(%(path)sapi/v1/.*) http://127.0.0.1:%(port)s/$1 retry=0
ProxyPassMatch /%(path)s(.*) http://127.0.0.1:8080/univention/portal/$1 retry=0
RedirectMatch permanent "^/%(bare)s$" "/%(path)s"
""" % {'path': path.strip().lstrip('/'), 'bare': path.strip().lstrip('/').rstrip('/'), 'port': port})  # noqa: E101
@!@
ProxyPassMatch /(univention/selfservice/api/v1/.*) http://127.0.0.1:8095/$1 retry=0
ProxyPassMatch /(univention/selfservice/.*) http://127.0.0.1:8080/$1 retry=0
RedirectMatch permanent "^/univention/selfservice$" "/univention/selfservice/"
