@%@UCRWARNING=# @%@

@!@
# flake8: noqa
port = configRegistry.get("portal/port")
for path in configRegistry.get('portal/paths').split(','):
    print("""
ProxyPassMatch /(%(path)s(portal|apps|navigation).json) http://127.0.0.1:%(port)s/$1 retry=0
ProxyPassMatch /%(path)s(.*) http://127.0.0.1:8080/$1 retry=0


#<Directory /var/www/%(path)s>
#	<FilesMatch "(portal|apps)\\.json|portal\\.css">
#		Header set Cache-Control "max-age=0, must-revalidate"
#	</FilesMatch>
#</Directory>
#<Directory /var/www/%(path)s>
#	Header set Cache-Control "max-age=0, must-revalidate"
#</Directory>
""" % {'path': path.strip().lstrip('/'), 'port': port})  # noqa: E101
@!@
ProxyPassMatch "^/univention/(portal|selfservice)/(api/v1/me)$" "http://localhost:8095"
ProxyPassMatch "^/univention/(portal|selfservice)/(portal\.json|navigation\.json)$" "http://localhost:8095"
ProxyPassMatch "^/univention/(portal|selfservice)/(sse-worker\.js)$" "http://localhost:8080/$2"
ProxyPassMatch "^/univention/portal/(icons/.*)$" "http://localhost:8080/$2"
ProxyPassMatch "^/univention/(portal|selfservice)/((css|fonts|i18n|media|js|oidc|custom)/.*)$" "http://localhost:8080/$2"
ProxyPassMatch "^/univention/(portal|selfservice)/(index\.html)$" "http://localhost:8080/$2"
ProxyPassMatch "^/univention/(portal|selfservice)/()$" "http://localhost:8080/$2"
ProxyPassMatch "^/univention/selfservice()$" "http://localhost:8080/$1"
ProxyPassMatch "^/univention/portal()$" "http://localhost:8080/$1"
