#!/bin/sh
#
# Univention Join preinst script
#
# Copyright 2009-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# This preinst has only transitional purposes and can be removed after UCS 2.3

# If /usr/lib/univention-install/.index.txt is a regular file and not a symbolic
# link we move the file around and point a symlink to /var/univention-join/.index.txt

if [ -e /usr/lib/univention-install/.index.txt ]; then
    if [ ! -L /usr/lib/univention-install/.index.txt ]; then
	if [ -e /var/univention-join/status ]; then
	    echo "Skipping transition, /var/univention-join/status already exists"
	else
	    mkdir -p /var/univention-join/
	    mv /usr/lib/univention-install/.index.txt /var/univention-join/status
	    ln -s /var/univention-join/status /usr/lib/univention-install/.index.txt
	fi
    fi
fi

if [ -e /usr/share/univention-join/.joined ]; then
    if [ ! -L /usr/share/univention-join/.joined ]; then
	mkdir -p /var/univention-join/
	touch /var/univention-join/joined
	rm /usr/share/univention-join/.joined
	ln -s /var/univention-join/joined /usr/share/univention-join/.joined
    fi
fi

if [ ! -d /var/univention-join ]; then
    mkdir -p /var/univention-join/
fi

exit 0
