#!/bin/sh
#
# Univention Join
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

#DEBHELPER#

create_logfile /var/log/univention/check_join_status.log "root:adm" 640
create_logfile /var/log/univention/join.log "root:adm" 640

call_joinscript 20univention-join.inst

exit 0
