#!/bin/sh
#
# Univention System Setup
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# create special user for univention-system-setup-boot
adduser --system --no-create-home --disabled-password --force-badname '__systemsetup__'

# set UMC ACLs for special user
/usr/sbin/univention-management-console-acls allow -u "__systemsetup__" -c "setup/*" -c "lib/server/*" -c "sysinfo/*" -H "*"

# For remote configuration give root the permission to see this module. Normally the
# ACL will be defined in the UMC package and can be removed here after UCS 3.0-2
/usr/sbin/univention-management-console-acls allow -u "root" -c "setup/*" -c "lib/server/*" -c "sysinfo/*" -H "*"

ucr set umc/web/appliance/fast_setup_mode?true

#DEBHELPER#

exit 0
