umc/python/setup/netconf	usr/share/pyshared/univention/management/console/modules/setup/
city-data/*json		usr/share/univention-system-setup
umc/js/setup/*png	usr/share/univention-management-console-frontend/js/umc/modules/setup
umc/js/setup/*svg	usr/share/univention-management-console-frontend/js/umc/modules/setup
umc/js/setup.css	usr/share/univention-management-console-frontend/js/umc/modules/
usr/share/univention-system-setup/dhclient-script-wrapper
usr/share/univention-system-setup/locale/languagelist
usr/share/univention-system-setup/locale/timezone
usr/share/univention-system-setup/locale/short-list/*.short
