#!/bin/sh
#
# Univention System Setup
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

check_returnvalue ()
{
	rval=$1
	errormessage=$2
	if [ "${rval}" != 0 ]; then
		echo "${errormessage}"
		exit "${rval}"
	fi
}


eval "$(univention-config-registry shell)"

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

create_logfile /var/log/univention/system-setup-boot.log "root:adm" 640

# prepare the server role selection
if [ "$1" = "configure" ]; then
	# set UCR variables for appliance mode
	/usr/sbin/univention-system-setup-boot start

	# make sure that the App Center cache is up-to-date
	[ -x /usr/bin/univention-app ] && univention-app update

	# setup local package repository
	if [ ! -s /var/cache/univention-system-setup/profile ] && [ ! -e /var/cache/univention-system-setup/packages/Packages ]; then
		/usr/share/univention-system-setup/download-packages -b
	fi
fi

#DEBHELPER#

if [ "$1" = "configure" ]; then
	# Show motd on unjoined systems (Bug #37129)
	univention-config-registry set 'system/setup/showloginmessage=true'
	pam-auth-update --package univention-system-setup-boot
	ucr commit /etc/pam.d/*
fi

exit 0
