#!/bin/sh
#
# Univention Setup
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh
create_logfile /var/log/univention/setup.log "root:adm" 640

chmod -R 700 /var/cache/univention-system-setup

# apt needs to access /var/cache/univention-system-setup/packages/ with user _apt
chmod a+x /var/cache/univention-system-setup

a2enconf univention-system-setup

exit 0
