#!/bin/sh
#
# Univention System Setup
#  postrm script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$1" in
remove|purge)
# remove init script univention-system-setup-boot-prepare manually from run-level
update-rc.d -f univention-system-setup-boot-prepare remove

pam-auth-update --force --package --remove univention-system-setup-boot
ucr commit /etc/pam.d/*
;;
esac

#DEBHELPER#

exit 0
