#!/bin/sh
#
# Univention Nagios Plugin
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2008-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell server/role)"

if [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
	# run join script
	/usr/lib/univention-install/35univention-nagios-opsi.inst
fi

exit 0
