#!/bin/sh
#
# Univention Directory Logger
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

registrySection='ldap/logging'
workdir='/var/lib/univention-directory-logger'
dellog="${workdir}/dellog"

if [ "$1" = "configure" ]; then
	install -m 0700 -o root -g adm -d "$workdir"
	install -m 0700 -o root -g adm -d "$dellog"

	eval "$(univention-config-registry shell ldap/base)"
	univention-config-registry set \
		"${registrySection}?yes" \
		"${registrySection}/dellogdir?${dellog}" \
		"${registrySection}/exclude1?cn=temporary,cn=univention,$ldap_base"

	if [ -z "$2" ]; then  # initial package installation
		univention-config-registry set \
			"${registrySection}/id-prefix?yes"
	fi

	univention-config-registry commit /etc/ldap/slapd.conf
	invoke-rc.d slapd crestart
	systemctl try-restart univention-directory-listener
fi

exit 0
