#!/bin/sh
#
# Univention Directory Logger
#  postrm script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

registrySection='ldap/logging'
workdir='/var/lib/univention-directory-logger'
dellog="${workdir}/dellog"

case "$1" in
	"remove")
		univention-config-registry unset \
			"${registrySection}/dellogdir" \
			"${registrySection}"
		systemctl try-restart univention-directory-listener
		univention-config-registry commit /etc/ldap/slapd.conf
		invoke-rc.d slapd crestart
		;;
	"upgrade")
		dpkg-statoverride --force --quiet --remove "${dellog}"
		;;
	"purge")
		rm -rf "${workdir}"
		rm /var/lib/univention-directory-listener/handlers/directory_logger
		;;
	*)
		;;
esac

exit 0
