#!/bin/sh
#
# Univention Directory Manager UMC module
#  postinst file
#
# SPDX-FileCopyrightText: 2011-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

univention-config-registry set directory/manager/web/modules/autosearch?1 \
	directory/manager/web/sizelimit?2000 \
	directory/reports/cleanup/cron?"0 0 * * *" \
	directory/reports/cleanup/age?43200 \
	directory/manager/web/modules/wizards/disabled?no \
	directory/manager/web/modules/search/advanced_on_open?false \
	directory/manager/web/modules/computers/computer/add/default?"computers/windows" \
	directory/manager/web/modules/groups/group/checks/circular_dependency?"yes" \
	umc/module/udm/users/self/disabled?true

# shellcheck disable=SC2154
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "10.0.1.24" && [ "$server_role" = "domaincontroller_master" ]; then
	umc_operation_create "udm-reports" "UDM - Reports" "" "udm/reports/query" "udm/reports/create" "udm/reports/get"
fi

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "10.0.9-2" && [ "$server_role" = "domaincontroller_master" ]; then
	if [ -e /var/univention-join/joined ] ; then
		# shellcheck source=/dev/null
		. /usr/share/univention-lib/umc.sh
		umc_operation_create "udm-blocklists" "UDM - Blocklists" "blocklists/all" "udm/*:objectType=blocklists/*" || true
	fi
fi



exit 0
