({
	'bold': 'Fetstil',
	'copy': 'Kopiera',
	'cut': 'Klipp ut',
	'delete': 'Ta bort',
	'indent': 'Indrag',
	'insertHorizontalRule': 'Horisontell linjal',
	'insertOrderedList': 'Numrerad lista',
	'insertUnorderedList': 'Punktlista',
	'italic': 'Kursiv',
	'justifyCenter': 'Centrera',
	'justifyFull': 'Marginaljustera',
	'justifyLeft': 'Vänsterjustera',
	'justifyRight': 'Högerjustera',
	'outdent': 'Utdrag',
	'paste': 'Klistra in',
	'redo': 'Gör om',
	'removeFormat': 'Ta bort format',
	'selectAll': 'Markera allt',
	'strikethrough': 'Genomstruken',
	'subscript': 'Nedsänkt',
	'superscript': 'Upphöjt',
	'underline': 'Understrykning',
	'undo': 'Ångra',
	'unlink': 'Ta bort länk',
	'createLink': 'Skapa länk',
	'toggleDir': 'Växla riktning',
	'insertImage': 'Infoga bild',
	'insertTable': 'Infoga/redigera tabell',
	'toggleTableBorder': 'Aktivera/avaktivera tabellram',
	'deleteTable': 'Ta bort tabell',
	'tableProp': 'Tabellegenskap',
	'htmlToggle': 'HTML-källkod',
	'foreColor': 'Förgrundsfärg',
	'hiliteColor': 'Bakgrundsfärg',
	'plainFormatBlock': 'Styckeformat',
	'formatBlock': 'Styckeformat',
	'fontSize': 'Teckenstorlek',
	'fontName': 'Teckensnittsnamn',
	/* Error messages */
	'systemShortcutFF': 'Åtgärden "${0}" är endast tillgänglig i Mozilla Firefox med hjälp av ett kortkommando. Använd ${1}.',
	'ctrlKey':'Ctrl+${0}'
})
