#!/bin/bash
@%@BCWARNING=#@%@

eval "$(univention-config-registry shell)"

if [ -n "$xorg_resolution_secondary" ]; then
	# try to set device names 
	xrandr_output=$(LC_ALL=C xrandr | sed -n 's| connected.*||p')
	prim_name="${xrandr_output%
*}"
	sec_name="${xrandr_output##*
}"
	if [ -n "$prim_name" -a -n "$sec_name" ]; then
		if [ "$xorg_autodetect" = "yes" ] || [ "$xorg_autodetect" = "true" ] || [ "$xorg_autodetect" = "on" ] || [ "$xorg_autodetect" = "1" ]; then
			autodetect=yes
		else
			autodetect=no
		fi
		if [ -z "$xorg_display_primary" -o -z "$xorg_display_secondary" -o "$autodetect" = "yes" ]; then
				
			if [ -z "$xorg_display_primary" -o -z "$xorg_display_secondary" ]; then
				export local_xorg_display_primary="$prim_name"
				export local_xorg_display_secondary="$sec_name"
			else
				export local_xorg_display_primary="$xorg_display_primary"
				export local_xorg_display_secondary="$xorg_display_secondary"
			fi

			if [ "$autodetect" = "yes" ]; then
				mode_primary="--auto"
				mode_secondary="--auto"
			else
				mode_primary="--mode $xorg_resolution"
				mode_secondary="--mode $xorg_resolution_secondary"
			fi

			if [ -n "$xorg_display_relative_position" ]; then
				if [ "$xorg_display_relative_position" = "right" ]; then
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --right-of $local_xorg_display_primary
				elif [ "$xorg_display_relative_position" = "below" ]; then
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --below $local_xorg_display_primary
				elif [ "$xorg_display_relative_position" = "above" ]; then
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --above $local_xorg_display_primary
				elif [ "$xorg_display_relative_position" = "left" ]; then
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --left-of $local_xorg_display_primary
				else
					logger "Dualhead setup: Unknown position setting xorg/display/relative-position: \"$xorg_display_relative_position\"."
				fi
			else
				xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary
			fi
		fi
	else
		logger "Dualhead setup: Did not found two xrandr output devices."
	fi
fi

exit 0
