#!/bin/bash
@%@BCWARNING=#@%@

# Copyright (C) 2004-2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of the software contained in this package
# as well as the source package itself are made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
# 
# Binary versions of this package provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
# 
# In the case you use the software under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

eval "$(univention-config-registry shell)"

if [ -n "$xorg_resolution_secondary" ]; then
	# try to set device names 
	xrandr_output=$(LC_ALL=C xrandr | sed -n 's| connected.*||p')
	prim_name="${xrandr_output%
*}"
	sec_name="${xrandr_output##*
}"
	if [ -n "$prim_name" -a -n "$sec_name" ]; then
		if [ "$xorg_autodetect" = "yes" ] || [ "$xorg_autodetect" = "true" ] || [ "$xorg_autodetect" = "on" ] || [ "$xorg_autodetect" = "1" ]; then
			autodetect=yes
		else
			autodetect=no
		fi
		if [ -z "$xorg_display_primary" -o -z "$xorg_display_secondary" -o "$autodetect" = "yes" ]; then
				
			if [ -z "$xorg_display_primary" -o -z "$xorg_display_secondary" ]; then
				export local_xorg_display_primary="$prim_name"
				export local_xorg_display_secondary="$sec_name"
			else
				export local_xorg_display_primary="$xorg_display_primary"
				export local_xorg_display_secondary="$xorg_display_secondary"
			fi

			if [ "$autodetect" = "yes" ]; then
				mode_primary="--auto"
				mode_secondary="--auto"
			else
				mode_primary="--mode $xorg_resolution"
				mode_secondary="--mode $xorg_resolution_secondary"
			fi

			if [ -n "$xorg_display_relative_position" ]; then
				if [ "$xorg_display_relative_position" = "right" ]; then
					xrandr --output $local_xorg_display_secondary --off
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --right-of $local_xorg_display_primary
				elif [ "$xorg_display_relative_position" = "below" ]; then
					xrandr --output $local_xorg_display_secondary --off
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --below $local_xorg_display_primary
				elif [ "$xorg_display_relative_position" = "above" ]; then
					xrandr --output $local_xorg_display_secondary --off
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --above $local_xorg_display_primary
				elif [ "$xorg_display_relative_position" = "left" ]; then
					xrandr --output $local_xorg_display_secondary --off
					xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary --left-of $local_xorg_display_primary
				else
					logger "Dualhead setup: Unknown position setting xorg/display/relative-position: \"$xorg_display_relative_position\"."
				fi
			else
				xrandr --output $local_xorg_display_secondary --off
				xrandr --output $local_xorg_display_primary $mode_primary --output $local_xorg_display_secondary $mode_secondary
			fi
		fi
	else
		logger "Dualhead setup: Did not found two xrandr output devices."
	fi
fi

exit 0
