#!/bin/sh
#
# postrm script for univention-mail-dovecot
#
# SPDX-FileCopyrightText: 2015-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/base.sh

#DEBHELPER#

case "$1" in
	remove)
		univention-config-registry unset \
			security/packetfilter/package/univention-mail-dovecot/tcp/110/all \
			security/packetfilter/package/univention-mail-dovecot/tcp/110/all/en \
			security/packetfilter/package/univention-mail-dovecot/tcp/143/all \
			security/packetfilter/package/univention-mail-dovecot/tcp/143/all/en \
			security/packetfilter/package/univention-mail-dovecot/tcp/993/all \
			security/packetfilter/package/univention-mail-dovecot/tcp/993/all/en \
			security/packetfilter/package/univention-mail-dovecot/tcp/995/all \
			security/packetfilter/package/univention-mail-dovecot/tcp/995/all/en \
			security/packetfilter/package/univention-mail-dovecot/tcp/4190/all \
			security/packetfilter/package/univention-mail-dovecot/tcp/4190/all/en
	;;
esac

systemctl try-reload-or-restart univention-directory-listener

case "$1" in
	purge)
		rm -f /etc/dovecot/master-users
	;;
esac

if [ -x "/etc/init.d/univention-firewall" ]; then
	deb-systemd-invoke restart univention-firewall
fi

if [ "$1" = "remove" ]
then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 18univention-mail-dovecot-uninstall.uinst
fi

exit 0
