#!/bin/sh
#
# prerm script for univention-mail-dovecot
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]
then
	cp /usr/lib/univention-uninstall/18univention-mail-dovecot-uninstall.uinst \
		/usr/lib/univention-install/

	QUOTASTATUSIP=$(ucr get mail/dovecot/quota-status/ip)
	if [ -z $QUOTASTATUSIP ]; then QUOTASTATUSIP="127.0.0.1"; fi
	QUOTASTATUSPORT=$(ucr get mail/dovecot/quota-status/port)
	if [ -z $QUOTASTATUSPORT ]; then QUOTASTATUSPORT="12340"; fi
	POLICY_SERVICE=$(ucr search --brief ^mail/postfix/smtpd/restrictions/recipient/ | egrep "mail/postfix/smtpd/restrictions/recipient/.*: check_policy_service inet:$QUOTASTATUSIP:$QUOTASTATUSPORT" | cut -d ':' -f 1)

	univention-config-registry unset \
		mail/postfix/dovecot_sasl \
		mail/postfix/virtual/transport \
		mail/dovecot \
		$POLICY_SERVICE

	deb-systemd-invoke restart postfix
fi

exit 0
