dovecot.py usr/lib/univention-directory-listener/system/
dovecot-shared-folder.py usr/lib/univention-directory-listener/system/
dovecot-postlogin.py usr/lib/dovecot
quota-warning.sh usr/lib/dovecot
modules/univention/mail/*.py usr/lib/python2.7/dist-packages/univention/mail
modules/univention/mail/*.py usr/lib/python3/dist-packages/univention/mail
usr/lib/univention-server/server_password_change.d/univention-mail-dovecot usr/lib/univention-server/server_password_change.d/
usr/share/univention-mail-dovecot/reapply_shared_folder_acls usr/share/univention-mail-dovecot/
