#! /bin/sh
#
# Univention Bind
#  postrm script for the univention-bind debian package
#
# SPDX-FileCopyrightText: 2017-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
remove|abort-install|disappear)
	dpkg-divert --quiet --rename \
		--package univention-bind \
		--divert /lib/systemd/system/bind9.service.debian \
		--remove /lib/systemd/system/bind9.service
	;;
esac

exit 0
