#!/bin/sh
#
# UCS@School
#  postinst script
#
# SPDX-FileCopyrightText: 2006-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

case "$1" in
	configure)
		if [ -z "$2" ]; then
			:
		else
			if test -x /etc/init.d/samba; then
				invoke-rc.d --query samba status
				rc=$?
				if [ "$rc" -eq 104 ] || [ "$rc" -eq 100 ]; then
					# systemctl restart samba # TODO <https://forge.univention.org/bugzilla/show_bug.cgi?id=44237>
					/etc/init.d/samba restart
				fi
			fi
		fi
		systemctl try-restart univention-directory-listener
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
