#!/bin/sh
#
# Univention Appliance Docker Container
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

. /usr/share/univention-lib/all.sh

# prepare the server role selection
if [ "$1" = "configure" ] && [ -z "$2" ] && [ ! -e /var/univention-join/joined ]; then
	# don't download packages during update of this metapackage

	# temporarily unset aptconf/dockerclean if it is set
	if is_ucr_true aptconf/dockerclean; then
		_set_aptconf_dockerclean() {
			ucr set aptconf/dockerclean="$aptconf_dockerclean"
		}
		trap _set_aptconf_dockerclean EXIT
		ucr set aptconf/dockerclean='false'
	fi
	if [ -d /var/cache/univention-system-setup/packages ]; then
		rm /var/cache/univention-system-setup/packages/*
		touch /var/cache/univention-system-setup/packages/Packages
	fi

	/usr/share/univention-docker-container-mode/download-packages \
		univention-container-role-server-common \
		univention-server-master
	/usr/share/univention-docker-container-mode/download-packages \
		univention-container-role-server-common \
		univention-server-backup
	/usr/share/univention-docker-container-mode/download-packages \
		univention-container-role-server-common \
		univention-server-slave
	/usr/share/univention-docker-container-mode/download-packages \
		univention-container-role-server-common \
		univention-server-member
	/usr/share/univention-docker-container-mode/download-packages \
		univention-basesystem
fi

exit 0
