#!/bin/sh
#
# postinst file for the debian package
#
# SPDX-FileCopyrightText: 2022-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(ucr shell server/role ldap/base)"

if [ "$server_role" = "domaincontroller_master" ] && dpkg --compare-versions "$2" lt-nl 1.0.0-4; then
	udm monitoring/alert modify --ignore_not_exists \
		--dn "cn=UNIVENTION_ADCONNECTOR_METRIC_MISSING,cn=monitoring,$ldap_base" \
		--set query="absent(univention_ad_connector_ad_reachable) == 1 or absent(univention_ad_connector_running) == 1 or absent(univention_ad_connector_rejects) == 1"
fi

exit 0
