ooo-wrapper usr/bin
oobase usr/bin
oocalc usr/bin
oodraw usr/bin
ooffice usr/bin
oofromtemplate usr/bin
ooimpress usr/bin
oomath usr/bin
ooweb usr/bin
oowriter usr/bin
files/usr/share/icons/locolor/32x32/apps/*.xpm usr/share/icons/locolor/32x32/apps
files/usr/share/icons/locolor/16x16/apps/*.xpm usr/share/icons/locolor/16x16/apps
files/usr/share/icons/locolor/22x22/apps/*.xpm usr/share/icons/locolor/22x22/apps
files/usr/share/icons/locolor/48x48/apps/*.xpm usr/share/icons/locolor/48x48/apps
files/usr/share/icons/hicolor/48x48/apps/*.xpm usr/share/icons/hicolor/48x48/apps
files/usr/share/icons/hicolor/16x16/apps/*.xpm usr/share/icons/hicolor/16x16/apps
files/usr/share/icons/hicolor/22x22/apps/*.xpm usr/share/icons/hicolor/22x22/apps
files/usr/share/icons/hicolor/32x32/apps/*.xpm usr/share/icons/hicolor/32x32/apps


