#!/bin/sh
# SPDX-FileCopyrightText: 2021-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

/usr/share/univention-group-membership-cache/univention-ldap-cache add-cache memberUids dn memberUid "(univentionObjectType=groups/group)"
/usr/share/univention-group-membership-cache/univention-ldap-cache add-cache uniqueMembers dn uniqueMember "(univentionObjectType=groups/group)"
/usr/share/univention-group-membership-cache/univention-ldap-cache create-listener-modules

exit 0
