#!/bin/bash
#
# Univention Appcenter
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

ucr set appcenter/docker?enabled
ucr set appcenter/docker/compose/network?172.16.1.1/16

#######
## This code can be used for further updates if
## scripts/docker-app-container-init-script will be changed
##
## if dpkg --compare-versions "$2" lt-nl 6.0.2-4; then
## 	for initscript in /etc/init.d/docker-app-*; do
## 		test -e "$initscript" || continue
## 		app_id="$(basename $initscript)"
## 		app_id=${app_id#docker-app-}
## 		cat /usr/share/docker-app-container-init-script | sed -e "s|@%@APPID@%@|$app_id|g" >"/etc/init.d/docker-app-$app_id"
## 	done
## fi


exit 0
