#!/bin/sh
#
# Univention Appcenter
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = configure ] && [ -z "$2" ]; then
	touch /var/log/univention/appcenter.log
	chown root:adm /var/log/univention/appcenter.log
	chmod 640 /var/log/univention/appcenter.log
fi

#DEBHELPER#

if [ -x /etc/init.d/slapd ] &&
	[ -x /usr/share/univention-ldap/ldap_setup_index ] &&
	[ -e /var/univention-join/joined ] &&
	[ "$1" = configure ] &&
	[ -z "$2" ] &&
	! ucr get ldap/index/eq | tr , '\n' | grep -Fxq univentionAppID &&
	univention-ldapsearch -LLL -o ldif-wrap=no -b cn=Subschema -s base attributeTypes | grep -Fq "NAME 'univentionAppID'"
then
	if pidof slapd >/dev/null 2>/dev/null
	then
		service slapd stop
		/usr/share/univention-ldap/ldap_setup_index --add-eq univentionAppID
		service slapd start
	else
		/usr/share/univention-ldap/ldap_setup_index --add-eq univentionAppID
	fi
fi

exit 0
