#!/bin/bash
#
# Univention Management Console Module Appcenter
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ -z "$2" ]; then
	# new installation. update local files once as there might be
	# meta files already in the cache that did not undergo
	# _update_local_files routine
	# See Bug#46813
	python3 -c "from univention.appcenter.actions import get_action; get_action('update')()._update_local_files()"
fi

univention-app umc-generate-app-cache

exit 0
