#!/bin/sh
#
# Univention Directory Replication
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
# Univention LDAP Listener replication module

. /usr/share/univention-lib/all.sh


create_logfile /var/log/univention/ldap-replication-resync.log "root:adm" 640

# make sure rootpw.conf is not readable
rootpw_filepath="/etc/ldap/rootpw.conf"
test -f "$rootpw_filepath" && chmod 600 "$rootpw_filepath" || true

univention-config-registry set	ldap/replication/filesystem/check?false \
						ldap/replication/filesystem/limit?10 \
						ldap/replication/filesystem/recipient?root

install -d -o listener -g root -m 0700 /var/lib/univention-directory-replication
chown -R listener:root /var/lib/univention-directory-replication
install -d -o listener -g root -m 0700 /var/univention-backup/replication

#DEBHELPER#

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 12.0.0-3 && [ -f "$rootpw_filepath" ]; then
	listenerpid=$(pgrep -f /usr/sbin/univention-directory-listener)
	if [ -n "$listenerpid" ]; then
		systemctl stop univention-directory-listener
	fi

	new_password="$(pwgen --numerals --capitalize --secure 64 1)"
	echo "rootpw \"$new_password\"" > "$rootpw_filepath"
	service slapd crestart

	if [ -n "$listenerpid" ]; then
		systemctl start univention-directory-listener
	fi
else
	systemctl try-restart univention-directory-listener
fi

exit 0
