etc/network/ucs-network-tools debian/univention-ifplugd/etc/network/
etc/network/if-up.d/[0-9]* debian/univention-ifplugd/etc/network/if-up.d/
etc/network/if-down.d/[0-9]* debian/univention-ifplugd/etc/network/if-down.d/
univention-ifplugd-enter-hook debian/univention-ifplugd/etc/dhcp3/dhclient-enter-hooks.d/
etc/NetworkManager/dhcp-hooks.d/[0-9]* debian/univention-ifplugd/etc/dhcp3/dhclient-enter-hooks.univention.d/
