[Unit]
OnFailure=slapd-failure.service
StartLimitIntervalSec=300
StartLimitBurst=20

[Service]
ExecCondition=/usr/lib/univention-ldap/slapd-condition
ExecStartPre=/usr/lib/univention-ldap/slapd-pre-start
ExecStartPost=/usr/lib/univention-ldap/slapd-post-start
Restart=on-failure
RestartSec=2
