[Unit]
OnFailure=slapd-failure.service

[Service]
ExecCondition=/usr/lib/univention-ldap/slapd-condition
ExecStartPre=/usr/lib/univention-ldap/slapd-pre-start
ExecStartPost=/usr/lib/univention-ldap/slapd-post-start
