#!/bin/sh
#
# Univention Admin
#  postinst file for the admin debian package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

univention-config-registry set 'nagios/client/checkraid?no' \
						  'nagios/client/autostart?yes'

#DEBHELPER#

eval "$(univention-config-registry shell)"

# create missing device file for dpt-i2o-raidutils
if [ ! -e /dev/dpti0 ] ; then
  mknod /dev/dpti0 c 151 0
fi

touch /var/lib/univention-nagios/check_univention_replication.cache
chmod 644 /var/lib/univention-nagios/check_univention_replication.cache
chown nagios:nagios /var/lib/univention-nagios/check_univention_replication.cache

if [ "$1" = "configure" ]; then
    cd /usr/share/nagios-plugins/templates-univention
    for f in *cfg; do
        ucf $f /etc/nagios-plugins/config/$f
    done
fi

# configure firewall
ucr set security/packetfilter/package/univention-nagios-client/tcp/5666/all="ACCEPT" \
		security/packetfilter/package/univention-nagios-client/tcp/5666/all/en="Nagios NRPE"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

if [ "$1" = "configure" ]; then
	systemctl try-restart univention-directory-listener
fi

/etc/init.d/nagios-nrpe-server restart

# shellcheck source=/dev/null
. /usr/share/univention-lib/base.sh
call_joinscript 30univention-nagios-client.inst

# rewrite broken configuration files
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl 13.0.2-6; then
	univention-directory-listener-ctrl resync nagios-client
fi

exit 0
