#!/bin/sh
#
# Univention Bootsplash
#  postinst script for the univention-bootsplash debian package
#
# Copyright (C) 2004, 2005, 2006 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA	 02110-1301	 USA

# console-screen must be removed completely as it does interrupt the bootsplash
update-rc.d -f console-screen.sh remove
dpkg-divert --rename --divert /etc/init.d/console-screen.sh.univention-bootsplash --add /etc/init.d/console-screen.sh

if [ "$1" = configure -a -z "$2" ]; then

    dpkg-divert --rename --divert /etc/init.d/rcS.ucs-bak  --add /etc/init.d/rcS
    dpkg-divert --rename --divert /etc/init.d/rc.ucs-bak  --add /etc/init.d/rc
	(
	 cd /etc/init.d
	 ln -sf rc.ucs rc
	 ln -sf rcS.ucs rcS
	)

fi

eval `univention-baseconfig shell`

if [ -n "$splash_theme" ]; then
	univention-baseconfig set bootsplash/theme?"$splash_theme"
	univention-baseconfig set bootsplash/size?all
	univention-baseconfig unset splash/theme
fi

if [ -z "`echo $grub_append | grep splash`" ] ; then
	univention-baseconfig set grub/append="splash=silent $grub_append"
fi

univention-baseconfig set grub/vga?791

univention-baseconfig set bootsplash/size?all


#DEBHELPER#

exit 0
