#!/bin/sh
#
# Univention Bootsplash
#  postinst script for the univention-bootsplash debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

eval "$(univention-config-registry shell)"

univention-config-registry set \
	bootsplash/theme?"ucs" \
	grub/bootsplash?splash

#DEBHELPER#

if [ -x /usr/sbin/update-initramfs ]; then
	update-initramfs -u
fi

if [ -x /usr/bin/update-grub ]; then
	update-grub
fi

exit 0
