#!/bin/sh
#
# Univention Print Server
#  postrm script for the debian package
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then

	handler_file=/var/lib/univention-directory-listener/handlers/cups-printers
	test -e "$handler_file" && rm -f "$handler_file"

	univention-config-registry unset cups/server \
		cups/admin \
		cups/systemgroup \
		cups/errorpolicy \
		cups/location/base \
		cups/location/admin \
		cups/filedevice \
		cups/autostart \
		cups/printserver \
		cups/debug/level \
		cups/server/alias

	ucr unset security/packetfilter/package/univention-printserver/tcp/631/all \
			security/packetfilter/package/univention-printserver/tcp/631/all/en \
			security/packetfilter/package/univention-printserver/udp/631/all \
			security/packetfilter/package/univention-printserver/udp/631/all/en
	[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

	systemctl try-restart univention-directory-listener
fi

exit 0

