#!/bin/sh
#
# Univention Print Server
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# shellcheck source=/dev/null

# cups backend
if dpkg-statoverride --list /usr/lib/cups/backend/cups-pdf >/dev/null
then
	dpkg-statoverride --remove --force /usr/lib/cups/backend/cups-pdf
fi
chmod 0700 /usr/lib/cups/backend/cups-pdf

# reload listener
if [ "$1" = "configure" ]; then
	systemctl try-restart univention-directory-listener
fi

#DEBHELPER#

exit 0
