#!/bin/sh
#
# Univention AD Connector
#  Start script for the AD Conenctor
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

umask 027
/usr/bin/python3 -W ignore -m univention.connector.ad.main "$@"
