#!/usr/bin/python3
#
# Univention Admingrp User Passwordreset
#  ldap-group-to-file-hooks.d script
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

import argparse
import grp
import subprocess

from univention.config_registry import handler_set, ucr


def _get_members_of(groupname: str) -> set[str]:
    try:
        grpstruct = grp.getgrnam(groupname)
        return set(grpstruct.gr_mem)
    except KeyError:
        return set()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-slapd-restart", action="store_true", help="do not restart the OpenLDAP server automatically")
    args = parser.parse_args()

    protected_groups = ucr.get('ldap/acl/user/passwordreset/protected/gid')
    if not protected_groups:
        return

    change = []
    for group in protected_groups.split(','):
        key = 'ldap/acl/user/passwordreset/internal/groupmemberlist/%s' % (group,)
        old_value = set(ucr.get(key, "").split(",")) - {""}
        new_value = _get_members_of(group)
        if old_value != new_value:
            change.append('%s=%s' % (key, ",".join(sorted(new_value))))

    if not change:
        return

    handler_set(change)
    subprocess.call(['ucr', 'commit', '/etc/ldap/slapd.conf'])

    if args.no_slapd_restart:
        return

    subprocess.call(['/etc/init.d/slapd', 'graceful-restart'])


if __name__ == '__main__':
    main()
