#!/usr/bin/python2.4
# -*- coding: utf-8 -*-
#
# Univention Directory Manager Modules
#  rename default container
#
# Copyright (C) 2004-2009 Univention GmbH
#
# http://www.univention.de/
# 
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


import ldap, string, sys

import univention.baseconfig

baseConfig=univention.baseconfig.baseConfig()
baseConfig.load()

baseDN=baseConfig['ldap/base']

lo=ldap.open('localhost', 389)
bindpw=open('/etc/ldap.secret').read()
if bindpw[-1] == '\n':
	bindpw=bindpw[0:-1]
lo.simple_bind_s("cn=admin,"+baseDN, bindpw)

count_changes = 0
warning = 0


print "\n  proof if cn=directory is renamed to cn=default containers\n"

res = lo.search_s(baseDN, ldap.SCOPE_SUBTREE, 'objectClass=univentionDirectory', ['cn'])


for i in range(0,len(res)):
	if res[i][1].has_key('cn') and res[i][0][:13] == "cn=directory,":
		print "  rename %s" % res[i][0]
		lo.rename_s(res[i][0], "cn=default containers", res[i][0][13:])
		print '  rename successfull, exit.\n'
		sys.exit(0)

	elif res[i][1].has_key('cn') and res[i][0][:22] == "cn=default containers,":
		print '  "cn=default containers" already exists, exit.\n'
		sys.exit(0)


print 'WARNING: object "cn=directory" (old) or "cn=default containers" (new) not found.'
print '         You need to create such an object with type "settings/directory" before'
print '         Updating to Version 1.3-1.\n'
