#!/usr/share/ucs-test/runner bash
## desc: "run samba selftest samba3.raw.composite"
## exposure: dangerous
## tags: [SKIP]
## bugs: [40558]

# Skip test, waiting for https://forge.univention.org/bugzilla/show_bug.cgi?id=49003

. "$TESTLIBPATH/base.sh" || exit 137

RETVAL=100

# setup
ucr set update/secure_apt='no' repository/online/sources='yes' repository/online/unmaintained='yes'
univention-install -y build-essential dpkg-dev
cd /opt
apt-get -y source samba
cd samba-*
apt-get -y build-dep samba
sed -i 's/$(conf_args)/$(conf_args) --enable-selftest/' debian/rules
for i in $IGNORE; do
    echo $i >> selftest/skip
done
debian/rules override_dh_auto_configure

TDB_NO_FSYNC=1 make -j test FAIL_IMMEDIATELY=1 SOCKET_WRAPPER_KEEP_PCAP=1 TESTS="samba3.raw.composite" || fail_fast 110


exit $RETVAL
