#!/bin/bash
#
# Univention Server
#  network script: modify resolv.conf
#
# Copyright 2009-2011 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /etc/network/ucs-network-tools
ucs_ignore_interface

eval "$(univention-config-registry shell nameserver/option/timeout nameserver1 nameserver2 nameserver3)"

if [ -n "$nameserver_option_timeout" ] && ! grep timeout /etc/resolv.conf &>/dev/null; then
	echo "options timeout:$nameserver_option_timeout" >> /etc/resolv.conf
fi

if ! grep nameserver /etc/resolv.conf &>/dev/null; then
	for i in $(seq 1 3); do
		dns="nameserver$i"
		if [ -n "${!dns}" ]; then
			echo "nameserver ${!dns}" >> /etc/resolv.conf
		fi
	done
fi

exit 0
