#!/bin/sh
#
# Univention System Setup
#  Univention System Setup script to alter the security profile of a system
#
# Copyright 2007-2011 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/lib/univention-system-setup/scripts/setup_utils.sh

is_variable_set "security_profile"

if [ $? = 0 ]; then
	exit 0
fi

eval "$(univention-config-registry shell)"

security_profile=`get_profile_var "security_profile"`


reset_services ()
{
  univention-config-registry unset \
    security/services/smtp \
    security/services/pop3 \
    security/services/krsh \
    security/services/nfs \
    security/services/x11 \
    security/services/nagios \
    security/services/dhcp \
    security/services/ftp \
    security/services/http \
    security/services/postgres \
    security/services/samba \
    security/services/tftp \
    security/services/ipp \
    security/services/pop3 \
    security/services/postgres \
    security/services/kerberos \
    security/services/imap \
    security/services/sieve \
    security/services/dns \
    security/services/ldap \
    security/services/telnet \
    security/services/ldap \
    security/services/time \
    security/services/umc \
    >> /var/log/univention/setup.log
}

if [ -z "$security_profile" ]; then
	exit 0
fi

echo `date` : "Configuring security profile : " $security_profile  >> /var/log/univention/setup.log

if [ -n "$security_profile" -a "$security_profile" = "strict" ]; then
  univention-config-registry set security/profile="strict" \
    security/packetfilter/disabled="false" \
    >> /var/log/univention/setup.log

  if [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
    univention-config-registry set \
      security/services/smtp="disabled" security/services/pop3="disabled" \
      security/services/kerberos="disabled" security/services/krsh="disabled" security/services/nfs="disabled" security/services/x11="disabled" \
      security/services/imap="disabled" security/services/sieve="disabled" security/services/nagios="disabled" security/services/dhcp="disabled" \
      security/services/dns="disabled" security/services/ftp="disabled" security/services/http="disabled" \
      security/services/postgres="disabled" security/services/time="disabled" security/services/samba="disabled" \
      security/services/telnet="disabled" security/services/tftp="disabled" security/services/ipp="disabled" security/services/umc="disabled" \
      >> /var/log/univention/setup.log
  fi


  # Right now the selection is identical to DC M/B, eventually merge later
  if [ "$server_role" = "fatclient" -o "$server_role" = "mobileclient" -o "$server_role" = "basesystem" ]; then
    univention-config-registry set \
      security/services/smtp="disabled" security/services/pop3="disabled" security/services/notifier="disabled" security/services/x11="disabled" \
      security/services/kerberos="disabled" security/services/krsh="disabled" security/services/nfs="disabled" \
      security/services/imap="disabled" security/services/sieve="disabled" security/services/nagios="disabled" security/services/dhcp="disabled" \
      security/services/dns="disabled" security/services/time="disabled" security/services/ftp="disabled" security/services/http="disabled" \
      security/services/postgres="disabled" security/services/samba="disabled" \
      security/services/telnet="disabled" security/services/tftp="disabled" security/services/ipp="disabled" security/services/umc="disabled" \
      >> /var/log/univention/setup.log
  fi

  if [ "$server_role" = "domaincontroller_slave" -o "$server_role" = "memberserver" ]; then
    univention-config-registry set \
      security/services/smtp="disabled" security/services/pop3="disabled" security/services/notifier="disabled" security/services/x11="disabled" \
      security/services/kerberos="disabled" security/services/krsh="disabled" security/services/nfs="disabled" \
      security/services/imap="disabled" security/services/sieve="disabled" security/services/time="disabled" security/services/nagios="disabled" security/services/dhcp="disabled" \
      security/services/dns="disabled" security/services/ftp="disabled" security/services/http="disabled" \
      security/services/postgres="disabled" security/services/samba="disabled" \
      security/services/telnet="disabled" security/services/tftp="disabled" security/services/ipp="disabled" security/services/umc="disabled" \
      >> /var/log/univention/setup.log
  fi

fi

if [ -n "$security_profile" -a "$security_profile" = "normal" ]; then
  reset_services
  univention-config-registry set \
    security/profile="normal" \
    security/packetfilter/disabled="false" \
    >> /var/log/univention/setup.log

  if [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
    univention-config-registry set security/services/telnet="disabled" security/services/ftp="disabled"  >> /var/log/univention/setup.log
  fi

  if [ "$server_role" = "domaincontroller_slave" -o "$server_role" = "memberserver" ]; then
    univention-config-registry set security/services/telnet="disabled" security/services/ftp="disabled"  >> /var/log/univention/setup.log
  fi

  if [ "$server_role" = "fatclient" -o "$server_role" = "mobileclient" -o "$server_role" = "basesystem" ]; then
    univention-config-registry set security/services/smtp="disabled" security/services/pop3="disabled" security/services/notifier="disabled" \
      security/services/kerberos="disabled" security/services/krsh="disabled" \
      security/services/imap="disabled" security/services/sieve="disabled" security/services/nagios="disabled" security/services/dhcp="disabled" \
      security/services/dns="disabled" security/services/ftp="disabled" \
      security/services/ldap="disabled" security/services/postgres="disabled" security/services/samba="disabled" \
      security/services/telnet="disabled" security/services/tftp="disabled" \
      >> /var/log/univention/setup.log
  fi
fi

if [ -n "$security_profile" -a "$security_profile" = "open" ]; then
  iptables -F
  reset_services
  univention-config-registry set security/profile="open" \
    security/packetfilter/disabled="true" \
    >> /var/log/univention/setup.log
fi

echo `date` : "Restarting univention-iptables "  >> /var/log/univention/setup.log

/etc/init.d/univention-iptables restart >> /var/log/univention/setup.log

exit 0
