.\"                                      Hey, EMACS: -*- nroff -*-
.TH UNIVENTION\-SET\-LOGFILE\-PERMISSIONS 8 2011-05-20
.SH NAME
univention\-set\-logfile\-permissions \- set restricted permissions on log files

.SH SYNOPSIS
.B univention\-set\-logfile\-permissions

.SH DESCRIPTION
This manual page documents briefly the
.B univention\-set\-logfile\-permissions
command.
It updates the file permissions on several log files located in
.I /var/log/
to be only writeable by user \fIroot\fP (resp. \fIwww-data\fP) and readable by group \fIadm\fP.

.SH FILES
.TP
.I /var/log/
Directory containing log files.
.TP
.I /var/log/univention/
Directory containing UCS specific log files.

.SH SEE ALSO
.BR syslogd (8),
.BR logroatet (8).

.SH AUTHOR
Copyright (c) 2001-2019 Univention GmbH, Germany
