#!/bin/sh
#
# Univention System Activation
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2015-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
	configure)
		chmod og+w /var/cache/univention-system-activation
		/etc/init.d/apache2 reload
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
