scripts/univention-system-activation	usr/sbin
scripts/notify_vendor.py	usr/share/univention-system-activation
src/*     usr/share/pyshared/univention/system_activation
www	usr/share/univention-system-activation
conffiles/etc/sudoers.d/univention-system-activation	etc/sudoers.d
conffiles/usr/lib/univention-system-setup/cleanup-post.d/96_enable_system_activation	usr/lib/univention-system-setup/cleanup-post.d
