#!/bin/sh
#
# Univention Licence Services
#  prerm script for the debian package
#
# Copyright 2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.

case "$1" in
    remove|deconfigure)
		a2dissite  'univention-system-activation'
		invoke-rc.d apache2 reload
		;;

	upgrade)
		;;

    failed-upgrade)
		;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

#DEBHELPER#

exit 0
