#!/bin/sh
#
# Univention System Activation
#  prerm script for the debian package
#
# SPDX-FileCopyrightText: 2015-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

eval "$(ucr shell)"

case "$1" in
    remove|deconfigure)
		# if package configuration is active, deactivate it
		if [ -e "/etc/apache2/sites-enabled/univention-system-activation.conf" ]; then
			/usr/sbin/univention-system-activation stop
		else
			/usr/sbin/univention-system-activation allow-root
		fi
		;;

	upgrade)
		;;

    failed-upgrade)
		;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

#DEBHELPER#

exit 0
