// DOCS FOR CUSTOM BUILDS AND LAYER FILES:
// http://dojotoolkit.org/book/dojo-book-0-9/part-4-meta-dojo/package-system-and-custom-builds (marked as outdated but still most usefull)
// http://trac.seagullproject.org/wiki/Integration/AJAX/dojo
dependencies = {
	layers: [
		{
			// name is the target directory for the release relative to the
			// 'dojo' directory
			name: "../unijit/unijit.js", // copyrightFile: "../unijit/Copyright",
			layerDependencies: [
			],
			dependencies: [
				// Terminology: From the documents above it seems there are two ways:
				// a) You may write a layer file unijit.js yourself with a bunch of dojo.require statements
				// b) OR you list the dojo.require'd widgets in this list
				// The build script is supposed to pull everything into the layer file in the release directory
				//
				// The list below includes all dojo.required widgets
				// from univention-webui/webui/include/*
				// it may be generated by calling ./extract_dojo.required_from_univention-webui.sh
				"dijit.form.CheckBox",
				"dijit.form.ComboBox",
				"dijit.form.FilteringSelect",
				"dijit.form.MultiSelect",
				"dijit.form.SimpleTextarea",
				"dijit.form.TextBox",
				"dijit.form.ValidationTextBox",
				"dijit.layout.ContentPane",
				"dijit.layout.StackContainer",
				"dojo.parser",
				// The list below includes all widgets declared or required by
				// unijit/form/DateTextBox.js
				"unijit.form.DateTextBox",
				"dijit.form.DateTextBox",
				"dijit._Calendar",
			]
		}
	],

	prefixes: [
		[ "dijit", "../dijit" ],
		[ "dojox", "../dojox" ],
		[ "unijit", "../../unijit" ]
	]
}
