#!/bin/sh
# SPDX-FileCopyrightText: 2020-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = upgrade ] && dpkg --compare-versions "${2:-}" lt-nl 14.0.4
then
	# cleanup runsv and switch to systemd unit
	sv -w 30 force-shutdown univention-directory-notifier || :
	rm -rf /etc/runit/univention/univention-directory-notifier
	rm -rf /etc/runit/univention-directory-notifier
	rm -rf /etc/univention/templates/files/etc/runit/univention-directory-notifier
fi

#DEBHELPER#

exit 0
