#!/bin/sh
#
# Univention Directory Notifier
#  postinst
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

univention-config-registry set notifier/autostart?yes

#DEBHELPER#

if [ ! -e /var/lib/univention-ldap/schema/id/id ]; then
	touch /var/lib/univention-ldap/schema/id/id
	chown listener /var/lib/univention-ldap/schema/id/id >/dev/null 2>&1
fi

if [ ! -e /var/lib/univention-ldap/schema/md5 ]; then
	touch /var/lib/univention-ldap/schema/md5
fi

i=notify/transaction
if [ ! -e "/var/lib/univention-ldap/$i" ]; then
	touch "/var/lib/univention-ldap/$i"
fi
if [ -e "/var/lib/univention-ldap/$i" ]; then
	chmod 640 "/var/lib/univention-ldap/$i"
	chgrp "DC Backup Hosts" "/var/lib/univention-ldap/$i"
fi
if [ ! -e "/var/lib/univention-ldap/$i.lock" ]; then
	touch "/var/lib/univention-ldap/$i.lock"
	chmod 600 "/var/lib/univention-ldap/$i.lock"
fi


univention-config-registry set notifier/debug/level?1

create_logfile /var/log/univention/notifier.log "root:adm" 640

# configure firewall
ucr set security/packetfilter/package/univention-directory-notifier/tcp/6669/all="ACCEPT" \
		security/packetfilter/package/univention-directory-notifier/tcp/6669/all/en="Univention Directory Notifier"
[ -x "/etc/init.d/univention-firewall" ] && service univention-firewall restart

call_joinscript 02univention-directory-notifier.inst

if [ "$1" = "configure" ]
then
	ucr set notifier/protocol/version?3
	systemctl restart univention-directory-notifier || :
fi

exit 0
