#!/usr/bin/python2.6
#
# Univention Installer
#
# Copyright 2004-2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

import os
import time

fh = open("/proc/cmdline", "r")
cmdline = fh.readlines()
fh.close
options = cmdline[0].strip().split(' ')
modules = []
load_defaultmodules = True

for option in options:
	if option.startswith("loadmodules") and option.find("=") != -1:
		opt, val = option.split('=', 1)
		val = val.strip('\'"')
		for m in val.split(','):
			modules.append(m)
	if option == "expert_partition":
		for m in ["raid1", "raid0", "raid5", "raid10"]:
			modules.append(m)
	if option == 'nodefaultmodules':
		load_defaultmodules = False

if load_defaultmodules:
	modules.extend( [ 'ide-generic', 'ide-disk', 'sd_mod', 'dm_mod', 'efivars' ] )

for m in modules:
	os.system('/sbin/modprobe %s >/dev/null 2>&1' % m)
	time.sleep(0.15)

os.system('udevadm settle')
