#!/bin/sh

#DEBHELPER#

/usr/sbin/update-grub 

# restart udev
if [ -x /etc/init.d/udev ]; then
	/etc/init.d/udev restart
fi

if [ -x "/etc/init.d/xend" ]; then
	update-rc.d xend defaults 20 21 >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d xend start || exit $?
	else
		/etc/init.d/xend start || exit $?
	fi
fi

if [ -x "/etc/init.d/xendomains" ]; then
	update-rc.d xendomains defaults 21 20 >/dev/null || exit $?
fi

exit 0
