#!/bin/sh
#
# Univention Serverview
#  init script
#
# Copyright 2008-2010 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.


START_SCRIPTS="eecd_mods_src eecd srvmagt srvmagt_scs"
STOP_SCRIPTS="srvmagt_scs srvmagt eecd eecd_mods_src"

case "$1" in 
start)
	for s in $START_SCRIPTS; do
		/etc/init.d/$s start
		ret=$?
		if [ "$ret" != 0 ]; then
			exit $ret
		fi
	done
	;;
stop)
	for s in $STOP_SCRIPTS; do
		/etc/init.d/$s stop
		ret=$?
		if [ "$ret" != 0 ]; then
			exit $ret
		fi
	done
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
	;;
esac

exit 0

