35univention-self-service-passwordreset-umc.inst usr/lib/univention-install/
65univention-self-service-passwordreset-umc.uinst usr/lib/univention-uninstall/
umc/python/passwordreset/sending/*.txt usr/share/univention-self-service/email_bodies
umc/python/passwordreset/email_change_notification_email_body.txt usr/share/univention-self-service/email_bodies
umc/python/passwordreset/deregistration_notification_email_body.txt usr/share/univention-self-service/email_bodies
self-service-passwordreset.schema usr/share/univention-self-service/
univention-self-service-request-count usr/lib/univention-self-service/
listener/selfservice.py usr/lib/univention-directory-listener/system/
