#!/bin/bash
#
# Univention Self Service
#  postinst file for the debian package
#
# Copyright 2015-2016 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

eval "$(univention-config-registry shell)"

if ! [ "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
	echo "ERROR: This package must be installed on a DC master or DC backup!"
	echo "ERROR: Please uninstall and install on a DC master or DC backup!"
fi

# web site logging
ACCESS_LOG=/var/log/univention/self-service-access.log
ERROR_LOG=/var/log/univention/self-service-error.log

if [ "$1" = "configure" -a -z "$2" ] ; then
	echo "Fresh installation..."
	adduser --system --no-create-home --group self-service
fi

touch $ACCESS_LOG $ERROR_LOG
chown self-service:adm $ACCESS_LOG $ERROR_LOG
chmod 640 $ACCESS_LOG $ERROR_LOG

/usr/lib/univention-server/server_password_change.d/univention-self-service postchange

univention-config-registry set \
	self-service/passwordreset/web/enabled?yes \
	"ucs/web/overview/entries/service/passwordreset/description=Reset your password or provide contact information" \
	"ucs/web/overview/entries/service/passwordreset/description/de=Setzen Sie Ihr Passwort zurück oder hinterlegen Sie Kontaktinformationen." \
	"ucs/web/overview/entries/service/passwordreset/label=Password Reset" \
	"ucs/web/overview/entries/service/passwordreset/label/de=Passwort zurücksetzen" \
	"ucs/web/overview/entries/service/passwordreset/link=/univention-self-service/?lang=en-US#passwordreset" \
	"ucs/web/overview/entries/service/passwordreset/link/de=/univention-self-service/?lang=de-DE#passwordreset" \
	"ucs/web/overview/entries/service/passwordreset/port_http=" \
	"ucs/web/overview/entries/service/passwordreset/port_https=443"

univention-config-registry set \
	self-service/passwordchange/web/enabled?yes \
	"ucs/web/overview/entries/service/passwordchange/description=Change your (expired) password." \
	"ucs/web/overview/entries/service/passwordchange/description/de=Ändern Sie Ihr (abgelaufenes) Passwort." \
	"ucs/web/overview/entries/service/passwordchange/label=Change Password" \
	"ucs/web/overview/entries/service/passwordchange/label/de=Passwort ändern" \
	"ucs/web/overview/entries/service/passwordchange/link=/univention-self-service/?lang=en-US#passwordchange" \
	"ucs/web/overview/entries/service/passwordchange/link/de=/univention-self-service/?lang=de-DE#passwordchange" \
	"ucs/web/overview/entries/service/passwordchange/port_http=" \
	"ucs/web/overview/entries/service/passwordchange/port_https=443"


if [ "$1" = "configure" ]; then
	uinst=/usr/lib/univention-install/65univention-self-service.uinst
	[ -e "$uinst" ] && rm "$uinst"
fi

. /usr/share/univention-lib/base.sh
call_joinscript 34univention-self-service.inst

exit 0
