listener/selfservice.py	usr/lib/univention-directory-listener/system/
self-service-passwordreset.schema	usr/share/univention-self-service/
umc/python/passwordreset/deregistration_notification_email_body.txt	usr/share/univention-self-service/email_bodies/
umc/python/passwordreset/email_change_notification_email_body.txt	usr/share/univention-self-service/email_bodies/
umc/python/passwordreset/sending/*.txt	usr/share/univention-self-service/email_bodies/
univention-self-service-request-count	usr/lib/univention-self-service/
