#!/bin/bash
#
# Univention Self Service
#  postrm file for the debian package
#
# Copyright 2015 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

case "$1" in
	purge)
		rm -f /etc/self-service-ldap.secret
	;;
esac

if [ "$1" = "remove" -o "$1" = "purge" ]; then
	univention-config-registry unset \
		ucs/web/overview/entries/service/passwordreset/description \
		ucs/web/overview/entries/service/passwordreset/description/de \
		ucs/web/overview/entries/service/passwordreset/icon \
		ucs/web/overview/entries/service/passwordreset/label \
		ucs/web/overview/entries/service/passwordreset/label/de \
		ucs/web/overview/entries/service/passwordreset/link \
		ucs/web/overview/entries/service/passwordreset/link/de \
		ucs/web/overview/entries/service/passwordreset/port_http \
		ucs/web/overview/entries/service/passwordreset/port_https

	univention-config-registry unset \
		ucs/web/overview/entries/service/passwordchange/description \
		ucs/web/overview/entries/service/passwordchange/description/de \
		ucs/web/overview/entries/service/passwordchange/icon \
		ucs/web/overview/entries/service/passwordchange/label \
		ucs/web/overview/entries/service/passwordchange/label/de \
		ucs/web/overview/entries/service/passwordchange/link \
		ucs/web/overview/entries/service/passwordchange/link/de \
		ucs/web/overview/entries/service/passwordchange/port_http \
		ucs/web/overview/entries/service/passwordchange/port_https

	# restart, so apache unloads WSGI and deactivats plugin in its config
	# retry if fail because of to quick successive restarts (from other frontend packages)
	invoke-rc.d apache2 restart
fi

if [ "$1" = "remove" ]
then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 66univention-self-service.uinst
fi

exit 0
