#!/bin/bash
#
# Univention Self Service
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

ucr set umc/self-service/invitation/enabled?true
mkdir -p /var/cache/univention-directory-listener/selfservice-invitation/
chown listener /var/cache/univention-directory-listener/selfservice-invitation/
systemctl try-restart univention-directory-listener

exit 0
