plymouth/*	usr/share/plymouth/themes
umc/js/appliance.css usr/share/univention-management-console-frontend/js/umc/modules
usr/share/univention-management-console-frontend/js/dijit/themes/umc/images/app-logo-umc-header.png	usr/share/univention-management-console-frontend/js/dijit/themes/umc/images
images/*	usr/share/univention-app-appliance-branding/images
tools/*	usr/share/univention-app-appliance-branding/
python/*	usr/share/pyshared/univention/app_appliance
