python/univention-upgrade usr/sbin/
python/univention-updater usr/share/univention-updater/
python/univention-actualise usr/share/univention-updater/
python/univention-repository-create usr/sbin/
python/univention-repository-update usr/sbin/

univention-directory-policy/univention-policy-set-repository-server usr/lib/univention-directory-policy/
univention-directory-policy/univention-policy-repository-sync usr/lib/univention-directory-policy/
univention-directory-policy/univention-policy-maintenance usr/lib/univention-directory-policy/

bash_completion.d/univention-updater etc/bash_completion.d/

script/univention-install usr/sbin/
script/univention-remove usr/sbin/
script/reboot.at var/lib/univention-updater/
script/univention-updater-check usr/share/univention-updater/
script/disable-apache2-umc usr/share/univention-updater/
script/enable-apache2-umc usr/share/univention-updater/
script/updater-statistics usr/share/univention-updater/
script/univention-updater-umc-dist-upgrade usr/share/univention-updater/
script/univention-updater-umc-univention-install usr/share/univention-updater/
script/univention-add-app usr/sbin/

license_uuid.py usr/lib/univention-directory-listener/system/

script/preup.sh usr/share/univention-updater/
script/postup.sh usr/share/univention-updater/

modules/univention/updater/*.py usr/lib/python2.7/dist-packages/univention/updater/

appliance-hooks.d/updater usr/lib/univention-system-setup/appliance-hooks.d/

apt.conf.d/*	etc/apt/apt.conf.d/
