#!/bin/sh
#
# Univention Updater
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

REPOSITORY="https://updates.software-univention.de/"

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

create_logfile /var/log/univention/repository.log "root:adm" 640
create_logfile /var/log/univention/security-updates.log "root:adm" 640
create_logfile /var/log/univention/errata-updates.log "root:adm" 640
create_logfile /var/log/univention/updater.log "root:adm" 640
create_logfile /var/log/univention/actualise.log "root:adm" 640

[ -d /etc/apt/sources.list.d ] || mkdir -p /etc/apt/sources.list.d

if [ "$1" = "configure" ]; then
	# update cronjob-entries
	if [ -x /usr/lib/univention-directory-policy/univention-policy-maintenance ]; then
		/usr/lib/univention-directory-policy/univention-policy-maintenance
	fi

	univention-config-registry set \
		repository/online/server?"${REPOSITORY}" \
		repository/credentials/'Univention Software Repository'/uris?'updates.software-univention.de updates-test.software-univention.de appcenter.software-univention.de appcenter-test.software-univention.de' \
		update/available?no \
		version/version?5.2 \
		version/patchlevel?6 \
		version/erratalevel?0
fi

#DEBHELPER#

# force the listener module license_uuid to be executed
if [ -x /usr/sbin/univention-directory-listener-ctrl ]; then
	/usr/sbin/univention-directory-listener-ctrl resync license_uuid || true
else
	systemctl try-restart univention-directory-listener
fi

exit 0
