#!/bin/sh
# Univention Spamassassin
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

eval "$(univention-config-registry shell)"

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

create_logfile_if_missing /var/log/univention/spamassassin-learn.log "root:adm" 640

adduser --quiet --system --home /var/lib/spamd --shell /bin/bash spamd

univention-config-registry set mail/antivir/spam?yes \
	mail/antispam/requiredhits?5.0 \
	mail/antispam/learndaily?yes \
	mail/antispam/rules/autoupdate?yes \
	mail/antispam/autostart?yes

#DEBHELPER#

if [ "$1" = "configure" ] && [ -z "$2" ]; then # installation
		if is_ucr_true mail/antispam/rules/autoupdate ; then
			# update spamassassin rules
			umask 022
			if [ -f /etc/cron.daily/spamassassin ] ; then
				echo "Updating spamassassin rules..."
				python3 -c 'import pty; pty.spawn(["/etc/cron.daily/spamassassin"])'
				echo "Updating spamassassin rules... done"
			else
				echo "ERROR: the update of the spamassassin rules failed. Please run 'sa-update' manually."
			fi
		else
			echo "WARNING: the automatic update of the spamassassin rules has been deactivated."
			echo "WARNING: for the correct function of spamassassin you may have to call sa-update manually."
		fi
fi

test -x /etc/init.d/amavis && invoke-rc.d amavis restart

exit 0
