#!/bin/sh
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
[ -n "$(debconf-get preseed/url)" ] || exit 0

port=$(debconf-get "univention-net-installer/feedback/port")
[ -z "$port" ] && port=49173

feedback () {
	[ -n "${1:-}" ] || return
	hostname | nc "$1" "$port"
	exit 0
}

# Profile
feedback "$(debconf-get "univention-net-installer/feedback/host")"
# IPAPEND|=1
[ -n "${ip:-}" ] &&
	feedback "$(echo "$ip" | cut -d: -f2)"
# DHCP
[ -s /var/lib/udhcp/udhcpc.leases ] &&
	feedback "$(sed -rne 's/^ *option dhcp-server-identifier ([0-9.]+);/\1/p' /var/lib/udhcp/udhcpc.leases)"
# repository=TFTP server?
feedback "$(env | sed -ne 's,^mirror/http/hostname=,,p')"
