#!/usr/share/ucs-test/runner python
## desc: Test creating minimal object for all computer roles
## tags: [udm-computers]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools



import univention.testing.udm as udm_test
import univention.testing.strings as uts
import univention.testing.utils as utils

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		for role in udm.COMPUTER_MODULES:
			computer = udm.create_object('computers/%s' % role, name = uts.random_string())
			if not utils.verify_ldap_object(computer):
				utils.fail('Could not find created %s "%s" in LDAP' % (role, computer))
			
