#!/bin/sh
#
# Univention KDE
#  postinst script for the debian package
#
# Copyright (C) 2004-2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of the software contained in this package
# as well as the source package itself are made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
# 
# Binary versions of this package provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
# 
# In the case you use the software under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

#DEBHELPER#

# default x cursor theme
if [ "$1" = "configure" ]; then
	xctheme="/etc/X11/cursors/oxy-steel.theme"
	update-alternatives --set x-cursor-theme $xctheme
fi

if [ "$1" = "configure"  ]; then
	update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/startkde 100 \
		--slave /usr/share/man/man1/x-session-manager.1.gz \
		x-session-manager.1.gz "/usr/share/man/man1/startkde.1.gz"
fi

rm -f /usr/share/apps/kdesktop/DesktopLinks/debian.desktop
rm -f /etc/kde3/debian/debian.desktop

eval "$(univention-config-registry shell server/role)"

if [ -n "$server_role" -a "$server_role" = "domaincontroller_master" -o "$server_role" = "domaincontroller_backup" ]; then
	/usr/lib/univention-install/78univention-kde.inst || true
fi

univention-config-registry set auth/kdeprofile?true

if [ "$1" = "configure" -a -z "$2" ]; then
	univention-config-registry set "hal/devices/group?root"
fi

# bug 17711
dpkg-statoverride --update --add root root 4755 /usr/lib/kde4/libexec/kcheckpass 

ldconfig

#cleaup old profiles
if [ ! -h /usr/share/univention-kde-profiles/ucs-3.0 -a -d /usr/share/univention-kde-profiles/ucs-3.0 ]; then
	mv /usr/share/univention-kde-profiles/ucs-3.0 /usr/share/univention-kde-profiles/ucs-3.0.old
	ln -sf /usr/share/univention-kde-profiles/ucs-4.0 /usr/share/univention-kde-profiles/ucs-3.0
fi
if [ ! -h /usr/share/univention-kde-profiles/ucs-23 -a -d /usr/share/univention-kde-profiles/ucs-23 ]; then
	mv /usr/share/univention-kde-profiles/ucs-23 /usr/share/univention-kde-profiles/ucs-23.old
	ln -sf /usr/share/univention-kde-profiles/kde4-ucs2.3 /usr/share/univention-kde-profiles/ucs-23
fi
if [ ! -h /usr/share/univention-kde-profiles/ucs-23-kde-menu -a -d /usr/share/univention-kde-profiles/ucs-23-kde-menu ]; then
	mv /usr/share/univention-kde-profiles/ucs-23-kde-menu /usr/share/univention-kde-profiles/ucs-23-kde-menu.old
	ln -sf /usr/share/univention-kde-profiles/kde4-menu /usr/share/univention-kde-profiles/ucs-23-kde-menu
fi

if [ ! -h /usr/share/univention-kde-profiles/ucs-green21 -a -d /usr/share/univention-kde-profiles/ucs-green21 ]; then
	mv /usr/share/univention-kde-profiles/ucs-green21 /usr/share/univention-kde-profiles/ucs-green21.old
	ln -sf /usr/share/univention-kde-profiles/kde4-ucs2.3 /usr/share/univention-kde-profiles/ucs-green21
fi
if [ ! -h /usr/share/univention-kde-profiles/ucs-kde-menu21 -a -d /usr/share/univention-kde-profiles/ucs-kde-menu21 ]; then
	mv /usr/share/univention-kde-profiles/ucs-kde-menu21 /usr/share/univention-kde-profiles/ucs-kde-menu21.old
	ln -sf /usr/share/univention-kde-profiles/kde4-menu /usr/share/univention-kde-profiles/ucs-kde-menu21
fi

exit 0
