#!/bin/sh

@%@BCWARNING=# @%@

@!@
if baseConfig.has_key('security/services/ftp') and baseConfig['security/services/ftp'] == 'disabled':
	print '/sbin/iptables -A INPUT  -p tcp --dport 21 -j REJECT'
@!@
