#!/bin/sh

@%@BCWARNING=# @%@

@!@
if baseConfig.has_key('security/services/krsh') and baseConfig['security/services/krsh'] == 'disabled':
	print '/sbin/iptables -A INPUT  -p tcp --dport 544 -j REJECT'
@!@
