product: ucs
release: "5.2"
version: [2, 3]
scope: ucs_5.2-0-errata5.2-3
src: cloud-init
fix: 22.4.2-1+deb12u3
desc: |
 This update addresses the following issues:
 * CVSS score 8.8 (CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H).
   (CVE-2024-6174)
 * CVSS score 5.9 (CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L).
   (CVE-2024-11584)
bug: [58611]
cve:
- CVE-2024-6174
- CVE-2024-11584
erratum: 186
announced: 2025-09-17
support: core
