#!/usr/share/ucs-test/runner bash
## desc: Change the server password
## roles-not: basesystem
## tags: basic
## exposure: dangerous

. "$TESTLIBPATH/base.sh" || exit 137

RETVAL=100

eval "$(ucr shell)"

old_interval=$server_password_interval

ucr set server/password/interval="$(date +%j | sed -e 's|^0*||')"

/usr/lib/univention-server/server_password_change || fail_test 110 "server_password_change failed"

ucr set server/password/interval="$old_interval"

wait_for_replication

/usr/share/univention-join/check_join_status || fail_test 110 "check_join_status failed"

exit $RETVAL

