#!/usr/share/ucs-test/runner python2.7
## desc: Try to install all default packages
## tags: [basic]
## packages: [univention-system-setup]
## exposure: safe
import sys
sys.path.append('/lib/univention-installer/')

import package_list
import subprocess
import univention.config_registry
import atexit

skipPackages = [
		'univention-scalix',
		'univention-scalix-amavis',
		'univention-ox',
		'univention-ox-directory-integration',
		'univention-oxae'
		]

rc = 100

ucr = univention.config_registry.ConfigRegistry()
ucr.load()

serverrole = ucr.get('server/role', 'basesystem')

if subprocess.Popen(['invoke-rc.d', 'cron', 'stop']).wait():
	print 'Failed to stop cron daemon'
	sys.exit(1)
atexit.register(subprocess.Popen, ['invoke-rc.d', 'cron', 'start'])

for packageList in package_list.PackageList:
	for packageEntry in packageList.get('Packages', []):
		name = packageEntry.get('Name', '')
		packages = packageEntry.get('Packages', '')
		role = packageEntry.get('Possible', ['all'])
		for package in packages:
			if package in skipPackages:
				continue

			if serverrole in role or 'all' in role:
				print 'test: %s' % package
				apt_get = subprocess.Popen(['apt-get', 'install', '-s', '--reinstall', package])
				if apt_get.wait() != 0:
					print 'Failed to install %s' % package
					rc = 110
				apt_get = subprocess.Popen(['apt-get', 'install', '-d', '--reinstall', '--yes', package])
				if apt_get.wait() != 0:
					print 'Failed to download %s' % package
					rc = 110

sys.exit(rc)

# vim: set ft=python :
