#!/usr/share/ucs-test/runner bash
## desc: Check univention-ssh echo -n
## bugs: [14212]
## tags: [univention]
## packages: [univention-ssh]
## exposure: safe

. "$TESTLIBPATH/base.sh" || exit 137

result="$(univention-ssh "$tests_domainadmin_pwdfile" "root@${hostname}.${domainname}" echo -n | wc -c ; echo "${PIPESTATUS[0]}")" || exit 110 # ERROR
if [ $'0\n0' = "$result" ]
then
	exit 100 # OK
else
	exit 110 # ERROR
fi
# vim:set ft=sh:
