nagios-server.py usr/lib/univention-directory-listener/system/
icon/nagios.png /var/www/icon/
icon/50x50/nagios.png /var/www/icon/50x50/
usr/share/univention-nagios-server/tools/univention-nagios-ldap-tool usr/share/univention-nagios-server/tools/
usr/share/univention-nagios-server/icons/*.gif usr/share/univention-nagios-server/icons/
usr/share/univention-nagios-server/icons/*.gd2 usr/share/univention-nagios-server/icons/
