#!/bin/sh

PREREQ="kernelextras"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

[ -x /sbin/usplash ] || exit 0

. /usr/share/initramfs-tools/hook-functions
THINCLIENT_CHROOT="/var/lib/univention-client-root"

mkdir -p ${DESTDIR}/usr/lib/usplash

copy_exec ${THINCLIENT_CHROOT}/lib/libusplash.so.0 /lib

copy_exec ${THINCLIENT_CHROOT}/sbin/usplash /sbin
copy_exec ${THINCLIENT_CHROOT}/sbin/usplash_write /sbin
if [ -f /etc/usplash.conf ]; then
	copy_exec /etc/usplash.conf /etc
fi

if [ -f ${THINCLIENT_CHROOT}/usr/lib/usplash/usplash-artwork.so ]; then
    copy_exec ${THINCLIENT_CHROOT}/usr/lib/usplash/usplash-artwork.so /usr/lib/usplash
fi
