</td></tr></table></td></tr></table>

<br />
<table border="0" align="center" width="100%" cellspacing="0" cellpadding="0"><tr><td nowrap="nowrap">
<input type="submit" class="button" value="<?php echo _("Save Options") ?>" />&nbsp;
<input type="reset" class="button" value="<?php echo _("Undo Changes") ?>" />&nbsp;
<input type="button" class="button" value="<?php echo _("Return to Options") ?>" onclick="document.prefs.actionID.value=0; document.prefs.group.value=''; document.prefs.submit();" />
</td></tr></table>
</form>
