#!/bin/sh
#
# Univention Dansguardian
#  postrm script for univention-dansguardian
#
# Copyright 2021-2022 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

#DEBHELPER#

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 21univention-dansguardian.uinst
fi

if [ "$1" = "purge" ]; then
	rm -f \
		/etc/dansguardian/dansguardian.conf \
		/etc/dansguardian/dansguardianfX.conf \
		/etc/dansguardian/dansguardianf[0-9]*.conf \
		/etc/dansguardian/lists/exceptionfileurllist \
		/etc/dansguardian/lists/bannedurllist \
		/etc/dansguardian/lists/exceptionmimetypelist \
		/etc/dansguardian/lists/exceptioniplist \
		/etc/dansguardian/lists/bannedregexpheaderlist \
		/etc/dansguardian/lists/exceptionphraselist \
		/etc/dansguardian/lists/authplugins/ipgroups \
		/etc/dansguardian/lists/logsitelist \
		/etc/dansguardian/lists/exceptionurllist \
		/etc/dansguardian/lists/headerregexplist \
		/etc/dansguardian/lists/weightedphraselist \
		/etc/dansguardian/lists/bannedmimetypelist \
		/etc/dansguardian/lists/exceptionregexpurllist \
		/etc/dansguardian/lists/bannedphraselist \
		/etc/dansguardian/lists/greysitelist \
		/etc/dansguardian/lists/contentregexplist \
		/etc/dansguardian/lists/bannedregexpurllist \
		/etc/dansguardian/lists/contentscanners/exceptionvirussitelist \
		/etc/dansguardian/lists/contentscanners/exceptionvirusurllist \
		/etc/dansguardian/lists/contentscanners/exceptionvirusextensionlist \
		/etc/dansguardian/lists/contentscanners/exceptionvirusmimetypelist \
		/etc/dansguardian/lists/bannedextensionlist \
		/etc/dansguardian/lists/logregexpurllist \
		/etc/dansguardian/lists/filtergroupslist \
		/etc/dansguardian/lists/logurllist \
		/etc/dansguardian/lists/exceptionsitelist \
		/etc/dansguardian/lists/urlregexplist \
		/etc/dansguardian/lists/greyurllist \
		/etc/dansguardian/lists/bannediplist \
		/etc/dansguardian/lists/exceptionfilesitelist \
		/etc/dansguardian/lists/exceptionextensionlist \
		/etc/dansguardian/lists/bannedsitelist
	find /etc/univention/templates/files/etc/dansguardian/lists/ -maxdepth 1 -type f -delete
fi

exit 0
