#!/bin/bash
#
# Univention Print Quota DB
#  postinst script for the debian package
#
# Copyright (C) 2004, 2005, 2006 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#DEBHELPER#

/etc/init.d/postgresql reload

eval `univention-baseconfig shell`

pykotadb=`su - postgres -c "psql --list"|awk '/ pykota /{print $1}'`
if [ ! "$pykotadb" ] ;then
	# only, if database does not exist
	su - postgres -c "PGOPTIONS='-c client_min_messages=ERROR ' psql -d template1 -f /usr/share/pykota/postgresql/pykota-postgresql.sql" > /dev/null
else
	# update to new database format
	if [ "$1" = "configure" -a -n "$" ] && dpkg --compare-versions "$2" lt 0.2; then
		if [ -f /usr/share/doc/pykota/initscripts/postgresql/upgrade-to-1.21.sql ]; then
			su - postgres -c "PGOPTIONS='-c client_min_messages=FATAL ' psql -f /usr/share/doc/pykota/initscripts/postgresql/upgrade-to-1.21.sql pykota"
		fi
	fi
fi

secret=`cat $cups_quota_secret`
su - postgres -c "echo \"ALTER USER pykotaadmin PASSWORD '$secret';\" |psql -d pykota"
su - postgres -c "echo \"ALTER USER pykotaadmin PASSWORD '';\" |psql -d pykota"

exit 0

