#!/bin/bash
#
# Univention Quota
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

#DEBHELPER#

eval "$(univention-config-registry shell)"

univention-config-registry set samba/quota/command?'/usr/sbin/univention-setquota'

if [ ! `echo $kernel_modules | grep quota_v2` ]; then
	univention-config-registry set kernel/modules="$kernel_modules;quota_v2"
fi

call_joinscript 71univention-quota.inst

systemctl restart univention-directory-listener

exit 0
