#!/bin/bash
#
# Univention system stats
#
# Copyright 2010-2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

date=$(date)
log="/var/log/univention/system-stats.log"

cmds[0]="$(which df) -lhT"
cmds[1]="$(which ps) auxf"
cmds[2]="$(which top) -b -n2"
cmds[3]="$(which free)"
cmds[4]="$(which uptime)"
cmds[5]="$(which sensors)"
cmds[6]="$(which smbstatus)"

# print usage
function usage () {
	echo usage: $(basename $0) [-h]
	echo "This script logs some systems stats (df, free, ...) in \"$log\"."

	exit 0
}

# get options
while getopts ':h:' OPTION ; do
	case $OPTION in
		h)   usage ;;
		*)   usage ;;
	esac
done

if [ ! -e "$log" ]; then
	: > "$log"
fi
chmod 640 $log
chgrp adm $log

# redirect output
exec 1>>"$log"
exec 2>/dev/null

echo "--- system stats for $date"
echo 

for cmd in "${cmds[@]}"; do
	tool=${cmd/ */}
	if [ -x "$tool" ]; then
		echo "-> $cmd"
		$cmd 
		echo 
	fi
done

echo "--- end system stats for $date"

exit 0
