#!/bin/sh
#
# Univention AntiVir Mail
#  rules file for the univention-antivir-mail debian package
#
# SPDX-FileCopyrightText: 2001-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only


univention-config-registry set mail/antivir/scanner?clamav \
			 			 mail/antivir?yes \
			 			 mail/antispam/requiredhits?5.0

# set correct permissions for clamav
adduser clamav amavis || true
chown clamav /var/run/clamav/ || true

univention-config-registry set clamav/archive/maxfiles?1000 \
						 clamav/archive/maxfilesize?10M \
						 clamav/archive/maxrecursion?5 \
						 clamav/database/mirror?"db.local.clamav.net database.clamav.net" \
						 clamav/checks?24

univention-config-registry set mail/antivir/banned/double_ext?"yes"	\
			  mail/antivir/banned/basic_ext?"yes"	\
			  mail/antivir/banned/long_ext?"no"	\
			  mail/antivir/banned/file_type?"no"	\
			  mail/antivir/banned/mime_type?"no"	\
			  mail/antivir/banned/rfc2046?"yes"

univention-config-registry set mail/antivir/amavis/autostart?"yes" \
								clamav/daemon/autostart?"yes" \
								clamav/freshclam/autostart?"yes" \
								'mail/antispam/bodysizelimit?300'

# new installations
if [ "$1" = "configure" ] && [ -z "$2" ]; then
	[ -e /var/lib/clamav/daily.cvd ] || install -o clamav -g clamav -m 0644 /usr/share/univention-antivir-mail/daily.cvd /var/lib/clamav/
	[ -e /var/lib/clamav/main.cvd ] || install -o clamav -g clamav -m 0644 /usr/share/univention-antivir-mail/main.cvd /var/lib/clamav/
fi

#DEBHELPER#

test -x /etc/init.d/clamav-daemon && /etc/init.d/clamav-daemon restart || true
test -x /etc/init.d/spamassassin && /etc/init.d/spamassassin restart || true


/etc/init.d/amavis restart
/etc/init.d/postfix reload

exit 0
