#!/bin/sh
#
# Remove univention-system-setup-boot package
#
# SPDX-FileCopyrightText: 2014-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

univention_app_cmd_exists() {
	[ -x /usr/bin/univention-app ]
	return $?
}

is_app_center_server_reachable() {
	SERVER="$(univention-config-registry get repository/app_center/server)"
	[ -z "$SERVER" ] && return 1
	ping -c 3 "$SERVER" > /dev/null 2>&1
	return $?
}

univention_app_cmd_exists && is_app_center_server_reachable && univention-app update

