#!/bin/sh
#
# UCS test
#  postinst script for the ucs-test-framework package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# Copyright 2013-2022 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

#DEBHELPER#

eval "$(ucr shell ldap/base)"

ucr set tests/domainadmin/account?"uid=Administrator,cn=users,$ldap_base" \
		tests/domainadmin/pwd?univention \
		tests/domainadmin/pwdfile?"/var/lib/ucs-test/pwdfile" \
		tests/root/pwdfile?"/var/lib/ucs-test/root-pwdfile" \
		tests/root/pwd?univention \

eval "$(ucr shell)"

if [ ! -f "$tests_domainadmin_pwdfile" ]
then
	mkdir -p "${tests_domainadmin_pwdfile%/*}"
	echo -n "$tests_domainadmin_pwd" > "$tests_domainadmin_pwdfile"
fi
chmod 600 "$tests_domainadmin_pwdfile"

if [ ! -f "$tests_root_pwdfile" ]
then
	mkdir -p "${tests_root_pwdfile%/*}"
	echo -n "$tests_root_pwd" > "$tests_root_pwdfile"
fi
chmod 600 "$tests_root_pwdfile"

exit 0
