@%@UCRWARNING=#@%@
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.
@!@
if configRegistry.get('interfaces/dhcp-client') != 'dhcpcd':
    print('# dhcpcd is disabled via UCR variable interfaces/dhcp-client')
    print('denyinterfaces *')
    print('nohook hostname')
    print('nohook resolv.conf')
@!@

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
@!@
zone = configRegistry.get('domainname', '')
hostname = configRegistry.get('hostname', '')
if configRegistry.is_true('dhcpcd/options/ddns', False):
    zone = configRegistry.get('dhcpcd/options/ddns/zone') or configRegistry.get('domainname', '')

if zone:
    print('hostname %s.%s' % (hostname, zone))
else:
    print('hostname %s' % hostname)

if configRegistry.is_true('dhcpcd/options/ddns/serverupdate', True):
    print('fqdn both')
else:
    print('fqdn none')
@!@

# Use the hardware address of the interface for the Client ID.
#clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
duid

# Persist interface configuration when dhcpcd exits.
persistent

# vendorclassid is set to blank to avoid sending the default of
# dhcpcd-<version>:<os>:<machine>:<platform>
vendorclassid

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search
option classless_static_routes
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

option subnet_mask, broadcast_address, routers
option dhcp6_name_servers, dhcp6_domain_search, dhcp6_fqdn, dhcp6_sntp_servers
option netbios_name_servers, netbios_scope

# Request a hostname from the network
option host_name

# Most distributions have NTP support.
option ntp_servers

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate SLAAC address using the Hardware Address of the interface
#slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID
slaac private

# disable writing of resolv.conf as it gets written by /etc/dhcpcd.exit-hook
nohook resolv.conf

# reboot + timeout should be below the 45 secs that NetworkManager waits before terminating dhclient, otherwise fallback script is not run
reboot 5

@!@
import os.path

print('timeout %s' % configRegistry.get('dhcpcd/options/timeout', '30'))
# TODO: retry
# dhcpcd keeps trying in the background unless started in oneshot mode.

LOCAL = '/etc/dhcpcd.conf.local'
if os.path.exists(LOCAL):
    print('# Local dhcpcd configuration from %s follows' % LOCAL)
    with open(LOCAL) as fd:
        print(fd.read())
@!@
