#!/usr/share/ucs-test/runner bash
#
# Univention System Activation
#  test script
#
# Copyright 2015-2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

. tools.inc.sh

timestamp_old=$(get_license_modify_timestamp)
license_file=$(mktemp)
cat /usr/share/univention-ldap/core-edition.ldif | univention-config-registry filter > $license_file
http --form "license=@${license_file}"
rm -f $license_file

if has_request_failed; then
	fail_fast 1 'Import request for uploaded license file failed'
fi

timestamp_new=$(get_license_modify_timestamp)
if [ "$timestamp_new" -le "$timestamp_old" ]; then
	fail_fast 1 'License has not been updated in the LDAP'
else
	echo "License data has been written to the LDAP."
fi
