#!/bin/bash
# vim: set ts=4 sw=4 et fileencoding=UTF-8:
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
set -e -u

TRANSLOG='/var/lib/univention-ldap/translog'

main () {
    local db action="${1?-Missing action}"
    shift

    db="$TRANSLOG/data.mdb"

    case "$action" in
    init)
        wrap setup_db ${1:+"$@"}
        ;;
    check)
        [ -f "$db" ]
        ;;
    db)
        echo "$db"
        ;;
    help|--help|-h)
        usage 0
        ;;
    *)
        usage 2 >&2
        ;;
    esac
}

die () {
    echo "${0##*/}: $*"
    exit 1
}

usage () {
    echo "Usage: ${0##*/} { init [--force] | check | db | help }"
    trap EXIT
    exit "${1:-0}"
}

setup_db () {
    while [ $# -ge 1 ]
    do
        case "$1" in
        --force)
            rm -rf "$TRANSLOG"
            ;;
        esac
        shift
    done
    [ -s "$db" ] &&
        [ -n "$(slapcat -f /etc/ldap/slapd.conf -b cn=translog -H 'ldap:///cn=translog??base')" ] &&
        return 0
    install -o openldap -g openldap -d "$TRANSLOG"
    slapadd -f /etc/ldap/slapd.conf -b cn=translog -l /usr/share/univention-ldap/translog.ldif
    chown -R -h openldap: "$TRANSLOG"
}

check_db () {
    [ -s "$db" ]
}

wrap () {
    tmp="$(mktemp)"
    trap cleanup EXIT
    echo "[$(date --rfc-3339=s)] $$ $0 $*" >"$tmp"
    "$@" >"$tmp" 2>&1
}

cleanup () {
    local rc=$?
    if [ "$rc" -ne 0 ]
    then
        set +e +u
        ps axf
        grep -i -n -e 'translog' -e '^[^#]' /etc/ldap/slapd.conf
        ls -l /var/lib/univention-ldap/translog/ /var/univention-join/
        cat /var/univention-join/status
    fi >>"$tmp"
    cat "$tmp" >>/var/log/univention/join.log
    [ -t 2 ] && cat "$tmp"
    rm -f "$tmp"
    return "$rc"
}

main ${1:+"$@"}
:

# Constraints
# * DB must be created before slapd can start
