libvirtd-acl.py usr/lib/univention-directory-listener/system/
univention-virtual-machine-manager-restore.py usr/sbin/univention-virtual-machine-manager-restore
43univention-virtual-machine-manager-node-common.inst usr/lib/univention-install/
57univention-virtual-machine-manager-node-common.uinst usr/lib/univention-uninstall/
conffiles/etc/runit/univention-libvirt/run etc/runit/univention-libvirt/
conffiles/etc/modprobe.d/loop.conf etc/modprobe.d/
libvirt-check.sh usr/lib/univention-virtual-machine-manager-node
