#!/bin/sh

# start univention-system-setup if in GTK mode
if [ -n "$DISPLAY" ]; then
	# Get DHCP IP address saved in UCR by /etc/network/if-up.d/12_ucr
	chroot /target sh -c 'mountpoint /proc || mount -t proc proc /proc'
	chroot /target ifup -a

	# Start services prevented by policy-rc.d until now
	chroot /target invoke-rc.d univention-runit start

	chroot /target /usr/share/univention-system-setup/startxwithfirefox --installer
fi

exit 0
