#!/usr/share/ucs-test/runner pytest-3
## desc: Test univentionObjectIdentifier
## tags: [udm,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools

import subprocess
import time
import uuid

import pytest

from univention.testing import utils
from univention.testing.ucr import UCSTestConfigRegistry


@pytest.fixture
def assert_autogenerated_univentionObjectIdentifier(lo):
    def _assert(dn: str):
        search_result = lo.search(base=dn)
        assert len(search_result) == 1
        properties = search_result[0][1]
        assert "univentionObjectIdentifier" in properties
        uuid.UUID(properties["univentionObjectIdentifier"][0].decode("utf-8"))
        # Check that creator ID is set
        assert "univentionObjectCreatorsID" in properties
        uuid.UUID(properties["univentionObjectCreatorsID"][0].decode("utf-8"))
    return _assert


class TestUniventionObjectIdentifier:
    @pytest.fixture(scope="class", autouse=True)
    def activate_univentionObjectIdentifier(self):
        with UCSTestConfigRegistry() as ucr:
            ucr.handler_set(['directory/manager/object-identifier/autogeneration=true'])
            subprocess.run(["systemctl", "restart", "univention-directory-manager-rest.service"], check=True)
            # Wait for the UDM REST API to be available
            time.sleep(2)
            yield

    def test_user_explicitly_set_univentionObjectIdentifier(self, udm):
        test_identifier = str(uuid.uuid4())
        user = udm.create_user(univentionObjectIdentifier=test_identifier)[0]
        utils.verify_ldap_object(user, {"univentionObjectIdentifier": [test_identifier.encode("UTF-8")]}, retry_count=0)

    def test_user_autogenerated_univentionObjectIdentifier(self, udm, assert_autogenerated_univentionObjectIdentifier):
        user = udm.create_user()[0]

        assert_autogenerated_univentionObjectIdentifier(user)

    def test_group_explicitly_set_univentionObjectIdentifier(self, udm):
        """Create groups/group"""
        test_identifier = str(uuid.uuid4())
        group = udm.create_group(univentionObjectIdentifier=test_identifier)[0]

        utils.verify_ldap_object(group, {"univentionObjectIdentifier": [test_identifier.encode("UTF-8")]}, retry_count=0)

    def test_group_autogenerated_univentionObjectIdentifier(self, udm, assert_autogenerated_univentionObjectIdentifier):
        group = udm.create_group()[0]

        assert_autogenerated_univentionObjectIdentifier(group)

    def test_user_modification_adds_modifiers_id(self, udm, lo):
        """Test that modifying a user sets the univentionObjectModifiersID"""
        user = udm.create_user()[0]

        # Verify initially only CreatorsID is set
        search_result = lo.search(base=user)
        assert len(search_result) == 1
        properties = search_result[0][1]
        assert "univentionObjectCreatorsID" in properties
        assert "univentionObjectModifiersID" not in properties

        # Modify the user
        udm.modify_object("users/user", dn=user, description="Modified description")

        # Verify ModifiersID is now set
        search_result = lo.search(base=user)
        assert len(search_result) == 1
        properties = search_result[0][1]
        assert "univentionObjectModifiersID" in properties
        uuid.UUID(properties["univentionObjectModifiersID"][0].decode("utf-8"))

    def test_group_modification_adds_modifiers_id(self, udm, lo):
        """Test that modifying a group sets the univentionObjectModifiersID"""
        group = udm.create_group()[0]

        # Verify initially only CreatorsID is set
        search_result = lo.search(base=group)
        assert len(search_result) == 1
        properties = search_result[0][1]
        assert "univentionObjectCreatorsID" in properties
        assert "univentionObjectModifiersID" not in properties

        # Modify the group
        udm.modify_object("groups/group", dn=group, description="Modified description")

        # Verify ModifiersID is now set
        search_result = lo.search(base=group)
        assert len(search_result) == 1
        properties = search_result[0][1]
        assert "univentionObjectModifiersID" in properties
        uuid.UUID(properties["univentionObjectModifiersID"][0].decode("utf-8"))
