#!/usr/bin/make -f
MAIN := installation-4.2 performance-guide-4.2 networks-4.2 printers-4.2
MAIN += domain-4.2 windows-4.2 windows-nt-4.2 uvmm-4.2
STYLESHEET := univention_extdocs
OPTIONS += --stringparam callout.graphics 0
OPTIONS += --stringparam callout.unicode 1

COMMON_DIR ?= ../doc-common
include $(COMMON_DIR)/Makefile
