#!/usr/bin/python2.4
# -*- coding: utf-8 -*-
#
# Univention Installer
#  definitions of package lists
#
# Copyright (C) 2004-2009 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from local import _

PackageList=[
{
	'Category': _('Services for Windows'),
	'CategoryShow': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
	'Description': _("Windows Components"),
	'Packages':
			[
				{
					'Name': _('Samba'),
					'Packages': ['univention-samba', 'samba'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'basesystem'],
					'Description': _("Samba Services"),
				},
				{
					'Name': _('Windows Installer'),
					'Packages': ['univention-windows-installer'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave' ],
					'Description': _("Automatic Installation for Windows Clients"),
				},
				{
					'Name': _('Samba PDC on Non-DC Master'),
					'Packages': ['univention-samba-slave-pdc'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Description': _("Samba PDC on Non-DC Master"),
				},
				{
					'Name': _('Winbind'),
					'Packages': ['winbind'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ 'memberserver' ],
					'Possible': ['all'],
					'Description': _("Winbind Service"),
				},
			],
},
{
	'Category': _('Mail/Groupware'),
	'CategoryShow': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave' ],
	'Description': _('Mail/Groupware Component'),
	'Packages':
			[
				{
					'Name': _('Scalix for UCS'),
					'Packages': ['univention-scalix', 'univention-scalix-amavis' ],
					'Edition': [ 'scalix' ],
					'Architecture': [ 'x86' ],
					'Active': ['domaincontroller_master' ],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'basesystem'],
					'Description': _('The Scalix Groupware'),
				},
				{
					'Name': _('Kolab 2 for UCS'),
					'Packages': ['univention-kolab2', 'univention-kolab2-framework', 'univention-mail-postfix-kolab2', 'univention-mail-cyrus-kolab2'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Edition': [ 'ugs' ],
					'Active': ['domaincontroller_master' ],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave'],
					'Description': _('Groupware based on Kolab 2'),
				},
				{
					'Name': _('Kolab 2 web client'),
					'Packages': ['univention-kolab2-webclient'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Edition': [ 'ugs' ],
					'Active': ['domaincontroller_master' ],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave'],
					'Description': _('Horde Webclient for Kolab 2 for UCS'),
				},
				{
					'Name': _('Standard mail services'),
					'Packages': ['univention-mail-postfix', 'univention-mail-cyrus'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [''], 
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'Basis'],
					'Description': _('Standard mail services with postfix and cyrus (SMTP/POP/IMAP)'),
				},
			],
},
{
	'Category': _('IP management'),
	'CategoryShow': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
	'Description': _("Several IP Components"),
	'Packages':
			[
				{
					'Name': _('DNS'),
					'Packages': ['univention-bind', 'univention-bind-proxy', 'bind9'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave'],
					'Description': _("DNS Server and Proxy"),
				},
				{
					'Name': _('DHCP'),
					'Packages': ['univention-dhcp', 'dhcp3-server'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Description': _("DHCP Server"),
				},

			],
},
{
	'Category': _('System services'),
	'CategoryShow': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
	'Description': _("Additional Services"),
	'Packages':
			[
				{
					'Name': _('Bacula (Backup)'),
					'Packages': ['bacula'],
					'Edition': [ 'oxae' ],
					'Architecture': [ 'x86' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Network based Backup Software'),
				},
				{
					'Name': _('Open-Xchange'),
					'Packages': ['univention-ox', 'univention-ox-directory-integration', 'univention-oxae'],
					'Edition': [ 'oxae' ],
					'Architecture': [ 'x86' ],
					'Active': ['domaincontroller_master'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'Basis'],
					'Description': _('Open-Xchange Groupware Server'),
				},
				{
					'Name': _('Samba'),
					'Packages': ['univention-samba', 'samba', 'cupsys', 'cupsys-bsd', 'cupsys-client', 'cupsys-driver-gimpprint', 'foomatic-db-gimp-print', 'foomatic-db-hpijs', 'foomatic-filters-ppds'],
					'Edition': [ 'oxae' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'basesystem'],
					'Description': _("Samba Services"),
				},
				{
					'Name': _('Terminal server'),
					'Packages': ['univention-application-server'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Description': _('X-Window-System Client for Terminal Services'),
				},
				{
					'Name': _('Thin client environment'),
					'Packages': ['univention-thin-client'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Description': _('Thinclient Infrastructure'),
				},
				{
					'Name': _('Print server'),
					'Packages': ['univention-printserver', 'cupsys'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Possible': ['all'],
					'Description': _('Print server based on cups'),
				},
				{
					'Name': _('Print quota'),
					'Packages': ['univention-printquota', 'pykota', 'univention-printquotadb'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Print quota support based on pykota'),
				},
				{
					'Name': _('Nagios server'),
					'Packages': ['univention-nagios-server'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ 'domaincontroller_master' ],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Description': _('Host, service and network monitoring program '),
				},
				{
					'Name': _('Nagios client'),
					'Packages': ['univention-nagios-client'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ 'domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver' ],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver' ],
					'Description': _('Host, service and network monitoring program '),
				},
				{
					'Name': _('Univention AD Connector'),
					'Packages': ['univention-ad-connector'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ ],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup'],
					'Description': _('Sync users and groups with Active Directory'),
				},
				{
					'Name': _('Fax server'),
					'Packages': ['univention-fax-server'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ ],
					'Possible': ['all'],
					'Description': _('Fax server based on hylafax'),
				},
				{
					'Name': _('Squid proxy server'),
					'Packages': ['univention-squid', 'squid'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ ],
					'Possible': ['all'],
					'Description': _('Web Proxy Services'),
				},
				{
					'Name': _('OpenSSH server'),
					'Packages': ['openssh-server'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ 'all' ],
					'Possible': [ 'all' ],
					'Description': _("Secure shell server, an rshd replacement"),
				},
				{
					'Name': _('FreeNX server'),
					'Packages': ['freenx'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ ],
					'Possible': ['all'],
					'Description': _('FreeNX server'),
				},
				{
					'Name': _('VNC server'),
					'Packages': ['tightvncserver', 'univention-fonts'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [  ],
					'Possible': [ 'all' ],
					'Description': _("Server for remote desktop access"),
				},
				{
					'Name': _('Xen hypervisor'),
					'Packages': ['univention-xen'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86' ],
					'Active': [ ],
					'Possible': ['all'],
					'Description': _('Xen hypervisor environment to run virtualised hosts.'),
				},
				{
					'Name': _('Xen kernel images'),
					'Packages': ['univention-kernel-image-2.6.18-xen'],
					'Architecture': [ 'x86' ],
					'Active': [ ],
					'Possible': ['all'],
					'Description': _('Xen kernel images to Xen guests.'),
				},
				{
					'Name': _('UCS Net Installer'),
					'Packages': ['univention-net-installer'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup'],
					'Possible': ['all'],
					'Description': _('Install UCS over the network'),
				},
			],
},
{
	'Category': _('Administrative tools'),
	'CategoryShow': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
	'Description': _('Administrative tools'),
	'Packages':
			[
				{
					'Name': _('Univention Directory Manager'),
					'Packages': ['univention-directory-manager', 'python-univention-license'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup'],
					'Possible': ['domaincontroller_master', 'domaincontroller_backup'],
					'Description': _('Univention Director Manager Web Frontend'),
				},
				{
					'Name': _('Univention Management Console'),
					'Packages': ['univention-management-console'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Configuration Frontend for Servers and Clients'),
				},
				{
					'Name': _('Univention Software Monitor'),
					'Packages': ['univention-pkgdb'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master'],
					'Possible': ['all'],
					'Description': _('Univention packagestatus database'),
				},
			],
},
{
	'Category': _('Backup'),
	'CategoryShow': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
	'Description': _('Backup Tools'),
	'Packages':
			[
				{
					'Name': _('Bacula (Backup)'),
					'Packages': ['bacula'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Network based Backup Software'),
				},
				{
					'Name': _('Unidump'),
					'Packages': ['unidump'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Tape Backup Software'),
				},
				{
					'Name': _('Remote backup'),
					'Packages': ['univention-remote-backup'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Backup Software based on rsync'),
				},
			],
},
{
	'Category': _('Desktop Environment'),
	'CategoryShow': ['all'],
	'Description': _('Desktop Environment packages'),
	'Packages':
			[
				{
					'Name': _('Graphical user interface'),
					'Packages': ['univention-x-core', 'univention-gdm', 'univention-gdm-sessions'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'EditionDisable': [ 'oxae' ],
					'Possible': ['all'],
					'Description': _('Core Packages for a Graphical Desktop Environment'),
				},
				{
					'Name': _('KDE desktop'),
					'Packages': ['univention-kde', 'ispell', 'ingerman'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'EditionDisable': [ 'oxae' ],
					'Possible': ['all'],
					'Description': _('KDE - K Desktop Environment'),
				},
				{
					'Name': _('OpenOffice.org'),
					'Packages': ['univention-ooffice2', 'myspell-de-de'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('OpenOffice.org is a full-featured office productivity suite.'),
				},
				{
					'Name': _('Mozilla Firefox'),
					'Packages': ['univention-mozilla-firefox'],
					'Architecture': [ 'x86' ],
					'EditionDisable': [ 'oxae' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Firefox Webbrowser'),
				},
				{
					'Name': "  %s" % _('Java plugin/runtime'),
					'Packages': ['univention-java'],
					'Architecture': [ 'x86' ],
					'EditionDisable': [ 'oxae' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Java Virtual Machine'),
				},
				{
					'Name': "  %s" %_('Flash plugin'),
					'Packages': ['univention-flashplugin'],
					'Architecture': [ 'x86' ],
					'EditionDisable': [ 'oxae' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Flashplugin for webbrowsers'),
				},
				{
					'Name': "  %s" %_('Mplayer plugin'),
					'Packages': ['mozilla-mplayer'],
					'Edition': [ 'scalix', 'ugs' ],
					'EditionDisable': [ 'oxae' ],
					'Architecture': [ 'x86' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Mplayer for webbrowsers'),
				},
				{
					'Name': _('Gimp'),
					'Packages': ['gimp'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('The GNU Image Manipulation Program'),
				},
				{
					'Name': _('Acrobat Reader'),
					'Packages': ['acroread-de'],
					'Architecture': [ 'x86' ],
					'EditionDisable': [ 'oxae' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('PDF Viewer'),
				},
				{
					'Name': _('Additional KDE applications'),
					'Packages': ['k3b', 'k3b-i18n', 'cdrdao', 'kdeartwork-misc', 'kdeartwork-emoticons', 'kdeartwork-style', 'kdeartwork-theme-icon', 'kscreensaver', 'kdewallpapers', 'kdeartwork-theme-window', 'kamera', 'kfax', 'kpdf', 'kview', 'kuickshow', 'ksnapshot', 'ark', 'kcalc', 'kgpg', 'klaptopdaemon', 'kwalletmanager', 'kdepim', 'kompose' ],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('More KDE applications, like k3b, kdegraphics, kdeadmin, kdeartwork, kdetoys or kdeutils'),
				},
				{
					'Name': _('Desktop search (kerry/beagle)'),
					'Packages': ['kerry' ],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Desktop search with kerry and beagle'),
				},
				{
					'Name': _('Multimedia applications'),
					'Packages': ['amarok', 'kaffeine', 'kmplayer', 'kdemultimedia', 'mplayer'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Multimedia applications, like amarok, kmplayer or mplayer'),
				},
				{
					'Name': _('Fax client'),
					'Packages': ['univention-fax-client'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Fax client'),
				},
				{
					'Name': _('Evolution'),
					'Packages': ['evolution'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [''],
					'Possible': ['all'],
					'Description': _('The GNOME Mailer'),
				},
				{
					'Name': _('VNC viewer'),
					'Packages': ['xtightvncviewer'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ ],
					'Possible': [ 'all' ],
					'Description': _("Client for remote desktop Access"),
				},
				{
					'Name': _('Microsoft fonts'),
					'Packages': ['msttcorefonts'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ ],
					'Possible': [ 'all' ],
					'Description': _("Microsoft fonts"),
				},
			],
},
{
	'Category': _('Tools'),
	'CategoryShow': ['all'],
	'Description': _("Extra Tools"),
	'Packages':
			[
				{
					'Name': _('OpenSSH client'),
					'Packages': ['openssh-client'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ 'all' ],
					'Possible': [ 'all' ],
					'Description': _("Secure shell client, an rlogin/rsh/rcp replacement"),
				},
				{
					'Name': _('DHCP client'),
					'Packages': ['dhcp-client'],
					'Edition': [ 'scalix', 'ugs' ],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['mobile_client', 'managed_client'],
					'Possible': [ 'all' ],
					'Description': _("Dynamic IP configuration"),
				},
				{
					'Name': _('vim'),
					'Packages': ['vim'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ 'all' ],
					'Possible': [ 'all' ],
					'Description': _("Vim is an advanced text editor."),
				},
				{
					'Name': _('emacs'),
					'Packages': ['emacs21'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [ '' ],
					'Possible': [ 'all' ],
					'Description': _("GNU Emacs is an advanced text editor."),
				},
				{
					'Name': _('less'),
					'Packages': ['less'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['all'],
					'Possible': ['all'],
					'Description': _('Pager program similar to more'),
				},
				{
					'Name': _('elinks'),
					'Packages': ['elinks'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': [],
					'Possible': ['all'],
					'Description': _('Advanced text-mode WWW browser'),
				},
				{
					'Name': _('wget'),
					'Packages': ['wget'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['all'],
					'Possible': ['all'],
					'Description': _('Retrieves files from the web'),
				},
				{
					'Name': _('nmap'),
					'Packages': ['nmap'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver'],
					'Possible': ['all'],
					'Description': _('The Network Mapper'),
				},
				{
					'Name': _('zip/unzip'),
					'Packages': ['zip', 'unzip'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['all'],
					'Possible': ['all'],
					'Description': _('Archiver/De-Archiver for .zip files'),
				},
				{
					'Name': _('eject'),
					'Packages': ['eject'],
					'Architecture': [ 'x86', 'powerpc' ],
					'Active': ['all'],
					'Possible': ['all'],
					'Description': _('Ejects CDs and operates CD-Changers under Linux'),
				},
				{
					'Name': _('Java'),
					'Packages': ['univention-java'],
					'Architecture': [ 'x86' ],
					'Active': ['domaincontroller_master', 'domaincontroller_backup', 'domaincontroller_slave', 'memberserver', 'mobile_client', 'managed_client'],
					'Possible': ['all'],
					'Description': _('Java Virtual Machine'),
				},
			]

},
]
