#!/bin/sh
#
# Univention Package Template
#  postinst script
#
# SPDX-FileCopyrightText: 2010-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

case "$1" in
	configure)

		# call the join script
		call_joinscript 76univention-package-template.inst

		# if [ -z "$2" ]; then  # fresh installation
		# fi
		# if dpkg --compare-versions "$2" lt-nl 8.0.1-1; then # upgrade
		# fi

		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
