#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Univention Updater
#  read the repository settings
#
# Copyright 2004-2020 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.
import os
import subprocess

from univention.config_registry import ConfigRegistry

# Name of the cron.d file
CRON_D = '/etc/cron.d/univention-repository-sync'


configRegistry = ConfigRegistry()
configRegistry.load()

if os.path.exists(CRON_D):
    os.unlink(CRON_D)

ldap_hostdn = configRegistry.get('ldap/hostdn')
if ldap_hostdn:
    cmd = (
        'univention_policy_result',
        '-D', ldap_hostdn,
        '-y', '/etc/machine.secret',
        '-s',
        ldap_hostdn,
    )
    p1 = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    assert p1.stdout

    cron = ''

    for line in p1.stdout:
        key, value = line.decode('utf-8').split('=', 1)
        value = value.strip('"')
        if key == 'univentionRepositoryCron':
            cron = value

    if p1.wait():
        raise SystemExit('failed to execute univention_policy_result')

    if cron:
        with open(CRON_D, 'w') as cron_file:
            cron_file.write('# cron job for syncing repository\n')
            if cron != '* * * * * ':
                cron_file.write('%s root /usr/sbin/univention-repository-update net\n' % cron)
