#!/bin/sh
#
# Univention Admingrp User Passwordreset
#  UCR script
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

/var/lib/ldap-group-to-file-hooks.d/admingrp-user-passwordreset --no-slapd-restart
test -x /etc/init.d/slapd && /etc/init.d/slapd graceful-restart

exit 0
