({
	'bold': 'מודגש',
	'copy': 'העתקה',
	'cut': 'גזירה',
	'delete': 'מחיקה',
	'indent': 'הגדלת כניסה',
	'insertHorizontalRule': 'קו אופקי',
	'insertOrderedList': 'רשימה ממוספרת',
	'insertUnorderedList': 'רשימה עם תבליטים',
	'italic': 'נטוי',
	'justifyCenter': 'יישור למרכז',
	'justifyFull': 'יישור דו-צדדי',
	'justifyLeft': 'יישור לשמאל',
	'justifyRight': 'יישור לימין',
	'outdent': 'הקטנת כניסה',
	'paste': 'הדבקה',
	'redo': 'שחזור פעולה',
	'removeFormat': 'סילוק עיצוב',
	'selectAll': 'בחירת הכל',
	'strikethrough': 'קו חוצה',
	'subscript': 'כתב תחתי',
	'superscript': 'כתב עילי',
	'underline': 'קו תחתי',
	'undo': 'ביטול פעולה',
	'unlink': 'סילוק הקישור',
	'createLink': 'יצירת קישור',
	'toggleDir': 'מיתוג כיוון  ',
	'insertImage': 'הוספת תמונה',
	'insertTable': 'הוספת/עריכת טבלה',
	'toggleTableBorder': 'מיתוג גבול טבלה',
	'deleteTable': 'מחיקת טבלה',
	'tableProp': 'תכונת טבלה',
	'htmlToggle': 'מקור HTML',
	'foreColor': 'צבע חזית ',
	'hiliteColor': 'צבע רקע',
	'plainFormatBlock': 'סגנון פיסקה',
	'formatBlock': 'סגנון פיסקה',
	'fontSize': 'גופן יחסי',
	'fontName': 'שם גופן',
	/* Error messages */
	'systemShortcutFF': 'הפעולה "${0}" זמינה בדפדפן Mozilla Firefox רק באמצעות קיצור דרך במקלדת. נא להשתמש ב-${1}.'
})
