#!/usr/share/ucs-test/runner bash
## desc: Test Apache2 SSL ciphers
## bugs: [38632]
## packages:
##  - openssl
## exposure: safe
set -e -u

. "$TESTLIBPATH/base.sh" || exit 137

OPENSSL="$(dpkg-query -W -f '${Version}' openssl)"
if dpkg --compare-versions "$OPENSSL" lt 1.0.1e-2.107.201603011735; then
	cipher_families=(LOW EXPORT aNULL MD5 RC4)
else
	cipher_families=(aNULL MD5 RC4)
fi

for cipher in "${cipher_families[@]}"
do
	info "$cipher"
	ciphers="$(openssl ciphers "$cipher")"
	openssl s_client \
		-CAfile /etc/univention/ssl/ucsCA/CAcert.pem \
		-connect localhost:443 \
		-cipher "$ciphers" \
		-quiet -no_ign_eof </dev/null 2>&1 |
	grep -q -F 'handshake failure' ||
		fail_test 1 "$cipher"
done

exit ${RETVAL:-0}
# vim: set ft=sh :
