#!/bin/sh
#
# Univention Package Database
#  postrm script for the Debian package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

set -e

if [ "$1" = "purge" ]
then
	if [ -e /etc/postgresql/pkgdb.secret ]; then
		rm /etc/postgresql/pkgdb.secret
	fi
	su - postgres -c 'psql -v ON_ERROR_STOP= -q' <<EOF
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET client_min_messages = warning;
DROP DATABASE IF EXISTS pkgdb;
DROP ROLE IF EXISTS pkgdbu;
DROP ROLE IF EXISTS pkgdbg;
EOF
fi

#DEBHELPER#

if [ "$1" = "remove" ]
then
	# shellcheck source=/dev/null
	. /usr/share/univention-lib/all.sh
	# always call 65 after 50 (to remove service)
	# packages are always removed in unison because of cross-dependencies
	call_unjoinscript 65univention-management-console-module-pkgdb.uinst || :
fi

exit 0
