#!/bin/sh
#
# Univention Management Console Module pkgdb (Software Monitor)
#  postrm script for the debian package
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = "remove" ]
then
	# shellcheck source=/dev/null
	. /usr/share/univention-lib/all.sh
	# always call 65 after 50 (to remove service)
	# packages are always removed in unison because of cross-dependencies
	call_unjoinscript 50univention-pkgdb.uinst || :
fi

#DEBHELPER#

exit 0
