#!/usr/share/ucs-test/runner bash
# shellcheck shell=bash
## desc: test join hooks
## bugs: [47940]
## packages:
##  - univention-join
## roles:
##  - domaincontroller_master
##  - domaincontroller_backup
##  - domaincontroller_slave
##  - memberserver
## exposure: careful

eval "$(ucr shell)"

# shellcheck source=../../lib/base.sh
. "$TESTLIBPATH/base.sh" || exit 137
# shellcheck source=../../lib/undo.sh
. "$TESTLIBPATH/undo.sh" || exit 137
# shellcheck source=../../lib/random.sh
. "$TESTLIBPATH/random.sh" || exit 137

tmp="$(mktemp -d)"
undo rm -rf "$tmp"
rnd="$(random_chars)"

udm-test settings/data create --set name="$rnd.prejoin" --set data_type=join/pre-join \
	--set data="$(printf '#!/bin/sh\ntouch %q/prejoin' "$tmp" | bzip2 | base64 -w 0)"
undo udm-test settings/data remove --dn "cn=$rnd.prejoin,${ldap_base:?}"
udm-test settings/data create --set name="$rnd.prejoinscripts" --set data_type=join/pre-joinscripts \
	--set data="$(printf '#!/bin/sh\ntouch %q/prejoinscripts' "$tmp" | bzip2 | base64 -w 0)"
undo udm-test settings/data remove --dn "cn=$rnd.prejoinscripts,$ldap_base"
udm-test settings/data create --set name="$rnd.postjoinscripts" --set data_type=join/post-joinscripts \
	--set data="$(printf '#!/bin/sh\ntouch %q/postjoinscripts' "$tmp" | bzip2 | base64 -w 0)"
undo udm-test settings/data remove --dn "cn=$rnd.postjoinscripts,$ldap_base"

# indirect pre-join test
/usr/share/univention-join/univention-join-hooks \
	--server-role "${server_role:?}" \
	--hooktype join/pre-join \
	--master "${ldap_master:?}" \
	--binddn "${tests_domainadmin_account:?}" \
	--bindpwdfile "${tests_domainadmin_pwdfile:?}"
[ -e "$tmp/prejoin" ] || fail_test 110

uid="${tests_domainadmin_account%%,*}"
univention-run-join-scripts -dcaccount "${uid#uid=}" -dcpwd "$tests_domainadmin_pwdfile"
[ -e "$tmp/prejoinscripts" ] || fail_test 110
[ -e "$tmp/postjoinscripts" ] || fail_test 110

exit "${RETVAL:-0}"
