#!/usr/bin/env python

import argparse
import gettext

from univention.config_registry import ConfigRegistry

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument('language_code',
						type=str,
						help="two char language code, e.g. 'fr'")
	args = parser.parse_args()
	gettext.translation('ucr-l10n', languages=[args.language_code]).install()
	ucr = ConfigRegistry()
	ucr.load()
	overview_ucrvs = {k: v for k, v in ucr.items() if 'ucs/web/overview/entries' in k}
	ucrvs_translated = {}
	for ucrv, value in overview_ucrvs.items():
		translation = _(value)
		if not translation == value:
			ucrvs_translated['{}/{}'.format(ucrv, args.language_code)] = translation
	ucr.update(ucrvs_translated)
	ucr.save()
