#!/usr/share/ucs-test/runner bash
# shellcheck shell=bash
## desc: Check join status
## roles-not: [basesystem]
## tags:
##  - basic
##  - apptest
## exposure: safe

# shellcheck source=../../lib/base.sh
. "$TESTLIBPATH/base.sh" || exit 137

/usr/share/univention-join/check_join_status ||
	fail_fast 110 "check_join_status failed"
