#!/usr/share/ucs-test/runner bash
## desc: Check Secure APT is enabled
## tags:
##  - basic
##  - apptest
## exposure: safe
. /usr/share/univention-lib/ucr.sh || exit 137
is_ucr_true update/secure_apt
