#!/usr/share/ucs-test/runner bash
## desc: Check if ldbsearch is possible
## exposure: safe
## tags:
##  - basic
##  - apptest
## bugs: [40434]
## packages:
## - univention-samba4

. "$TESTLIBPATH/base.sh" || exit 137

ldbsearch -H "ldaps://$(hostname -f)" \
	-U"$(hostname)$%$(cat /etc/machine.secret)" \
	-s base ||
	fail_fast 1 "Failed to run ldbsearch with the host account"
