#!/bin/sh
#
# Univention Client Login
#  test script: shell server
#
# Copyright (C) 2001, 2002, 2003, 2004, 2005, 2006 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

i=0;

while :; do

while read -t 2 INLINE; do
	i=$[i+1];
	echo $i "$INLINE" | logger
	set $INLINE;

	case $1 in

	# keep-alive
	"1" )
	echo "2";
	echo "4 xterm";
	;;

	# ok
	"2" )
	echo "got ok from client" | logger;
	echo "8";
	;;

	# setenv
	"3" )
	shift;
	export "$1"="$2";
	echo "2";
	;;

	#run
	"4" )
	shift;
	prog="$1";
	shift;
	"$prog" $@
	echo "2";
	;;

	#start
	"5" )
	shift;
	prog="$1";
	shift;
	"$prog" $@ &
	echo "2";
	;;

	#exit
	"6" )
	echo "2";
	exit 1;
	;;

	#error
	"7" )
	echo "2";
	exit 1;
	;;

	* )
	echo "unknown command: $1" | logger
	echo "8";
	exit 1;
 	;;

    esac;

done;

echo "timeout" | logger

done;
