#!/bin/sh

eval $(univention-baseconfig shell)

/etc/init.d/drbd stop


if [ ! -e /etc/univention/installation_profile ]; then
	echo "Profile not found: /etc/univention/installation_profile"
	exit 1
fi

# primary or secondary?
drbdPrimary=`ldapsearch -x -b "$ldap_hostdn" univentionDrbdPrimary=1 -LLL univentionDrbdPrimary | grep ^univentionDrbdPrimary`

if [ -n "$drbdPrimary" ]; then
	# primary
	drbdPrimaryName="$hostname"
	drbdPrimaryIP=`ldapsearch -x -b "$ldap_hostdn" univentionDrbdIp | grep ^univentionDrbdIp: | sed -e 's|univentionDrbdIp: ||'`
	if [ -z "$drbdPrimaryIP" ]; then
		drbdPrimaryIP=`univention-baseconfig get interfaces/eth0/address`
	fi
	drbdSecondaryName=`ldapsearch -x -b "$ldap_hostdn" -LLL univentionDrbdSecondaryAddress | grep ^univentionDrbdSecondaryAddress: | sed -e 's|univentionDrbdSecondaryAddress: ||'`
	if [ -z "$drbdSecondaryName" ]; then
		echo "ERROR: The drbd secondary host entry for this drbd primary was not found."
		exit 1
	fi
	drbdSecondaryIP=`ldapsearch -x "(&(|(objectClass=univentionDomainController)(objectClass=univentionMemberserver))(cn=$drbdSecondaryName))" univentionDrbdIp | grep ^univentionDrbdIp: | sed -e 's|univentionDrbdIp: ||'`
	if [ -z "$drbdSecondaryIP" ]; then
		drbdSecondaryIP=`ldapsearch -x "(&(|(objectClass=univentionDomainController)(objectClass=univentionMemberserver))(cn=$drbdSecondaryName))" aRecord | grep ^aRecord: | sed -e 's|aRecord: ||'`
	fi

	if [ -z "$drbdSecondaryIP" ]; then
		echo "ERROR: No vaid ip address of the drbd secondary host found."
		exit 1
	fi

else
	# secondary
	drbdSecondaryName="$hostname"
	drbdSecondaryIP=`ldapsearch -x -b "$ldap_hostdn" univentionDrbdIp | grep ^univentionDrbdIp: | sed -e 's|univentionDrbdIp: ||'`
	if [ -z "$drbdSecondaryIP" ]; then
		drbdSecondaryIP=`univention-baseconfig get interfaces/eth0/address`
	fi

	#search my master
	drbdPrimaryName=`ldapsearch -x "(&(|(objectClass=univentionDomainController)(objectClass=univentionMemberserver))(univentionDrbdSecondaryAddress=$hostname)(!(cn=$hostname)))" | grep ^cn: | sed -e 's|cn: ||'`
	if [ -z "$drbdPrimaryName" ]; then
		echo "ERROR: The drbd secondary host entry was not found in the ldap directory. ldap search filter: \"univentionDrbdSecondaryAddress=$hostname\""
		exit 1
	fi

	drbdPrimaryIP=`ldapsearch -x "(&(|(objectClass=univentionDomainController)(objectClass=univentionMemberserver))(cn=$drbdPrimaryName))" univentionDrbdIp | grep ^univentionDrbdIp: | sed -e 's|univentionDrbdIp: ||'`
	if [ -z "$drbdPrimaryIP" ]; then
		drbdPrimaryIP=`ldapsearch -x "(&(|(objectClass=univentionDomainController)(objectClass=univentionMemberserver))(cn=$drbdPrimaryName))" aRecord | grep ^aRecord: | sed -e 's|aRecord: ||'`
	fi

	if [ -z "$drbdPrimaryIP" ]; then
		echo "ERROR: IP of the secondary drbd host was not found"
		exit 1
	fi
fi

## installation profile example:
# drbd=yes
# drbd_protocol="C"
# drbd_resource="foo"
# drbd_device="/dev/drbd0"
# drbd_disk="/dev/vg_ucs/vol2"
# drbd_port="7788"

# drbd_meta_disk="internal"
# drbd_startup_wfc_timeout="0"
# drbd_startup_degr_wfc_timeout="120"
# drbd_disk_on_io_error=detach


# clear settings
univention-baseconfig search drbd/ | while read line; do
	var=$(echo $line | sed -e 's|: .*||')
	univention-baseconfig unset $var
done

modprobe drbd >/dev/null 2>&1
if [ $? != 0 ]; then
	apt-get update >/dev/null ; apt-get install drbd8-modules-$(uname -r) >/dev/null
	modprobe drbd
	if [ $? != 0 ]; then
		echo "ERROR: failed to load the drbd kernel module"
		exit 1
	fi
fi

. /etc/univention/installation_profile

if [ "$drbd" = "yes" -o "$drbd" = "true" ]; then
	if [ -z "$drbd_resource" ]; then
		echo "ERROR: drbd_resource is not set in /etc/univention/installation_profile"
		exit 1
	fi
	if [ -z "$drbd_port" ]; then
		drbd_port=7788
	fi
	if [ -z "$drbd_device" ]; then
		drbd_device="/dev/drbd0"
	fi
	if [ -z "$drbd_protocol" ]; then
		drbd_protocol="C"
	fi

	univention-baseconfig set drbd/resource/$drbd_resource/protocol="$drbd_protocol"

	univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdPrimaryName/address="$drbdPrimaryIP:$drbd_port"
	univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdPrimaryName/device="$drbd_device"
	univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdSecondaryName/address="$drbdSecondaryIP:$drbd_port"
	univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdSecondaryName/device="$drbd_device"

	if [ -n "$drbdPrimary" ]; then
		self=$drbdPrimaryName
	else
		self=$drbdSecondaryName
	fi

	if [ -n "$drbd_disk" ]; then
		univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdPrimaryName/disk="$drbd_disk"
		univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdSecondaryName/disk="$drbd_disk"
	fi


	if [ -n "$drbd_meta_disk" ]; then
		univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdPrimaryName/meta-disk="$drbd_meta_disk"
		univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdSecondaryName/meta-disk="$drbd_meta_disk"
	elif [ -n "$drbd_flexible_meta_disk" ]; then
		univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdPrimaryName/flexible-meta-disk="$drbd_flexible_meta_disk"
		univention-baseconfig set drbd/resource/$drbd_resource/on/$drbdSecondaryName/flexible-meta-disk="$drbd_flexible_meta_disk"
	fi

	if [ -n "$drbd_disk_on_io_error" ]; then
		univention-baseconfig set drbd/resource/$drbd_resource/disk/on-io-error="$drbd_disk_on_io_error"
	fi

	if [ -n "$drbd_startup_wfc_timeout" ]; then
		univention-baseconfig set drbd/resource/$drbd_resource/startup/wfc-timeout="$drbd_startup_wfc_timeout"
	fi

	if [ -n "$drbd_startup_degr_wfc_timeout" ]; then
		univention-baseconfig set drbd/resource/$drbd_resource/startup/degr-wfc-timeout="$drbd_startup_degr_wfc_timeout"
	fi
else
	echo "ERROR: drbd=yes is not set in /etc/univention/installation_profile"
	exit 1
fi

umount $drbd_disk

if [ -n "$drbdPrimary" ]; then
	sed -i "s|^$drbd_disk |$drbd_device |" /etc/fstab
else
	sed -i "s|^$drbd_disk |#$drbd_device |" /etc/fstab
fi

yes yes | INIT_VERSION=fake drbdadm create-md  $drbd_resource

INIT_VERSION=fake drbdadm up $drbd_resource

if [ -n "$drbdPrimary" ]; then
	drbdsetup $drbd_device primary -o
	sleep 3
	mount $drbd_device
fi


exit 0
