#!/bin/sh
#
# Restart the Directory Notifier after an interface was stopped.
#  See https://forge.univention.org/bugzilla/show_bug.cgi?id=30408
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

have () {
	command -v "$1" >/dev/null 2>&1
}
have univention-directory-notifier || exit 0

. /etc/network/ucs-network-tools
ucs_ignore_interface

systemctl try-restart univention-directory-notifier

exit 0
