#!/bin/bash
echo 'eth0 already part of bridge br1'
set -e -u

tmp=$(mktemp -d)
trap "rm -rf '$tmp'" EXIT

export UNIVENTION_BASECONF="$tmp/base.conf"
cat <<'__UCR__' >"$UNIVENTION_BASECONF"
# univention_ base.conf

interfaces/eth0/type: dynamic
interfaces/br1/type: dynamic
__UCR__

mkdir -p "$tmp/eth0/brport"
mkdir -p "$tmp/br1"
"$(dirname "$0")/../ucs-kvm-setup-bridge" --dry-run --sys-root "$tmp" >"$tmp/out" && exit 1

diff -u "$tmp/out" - <<'__OUT__'
__OUT__
