version: '3.1'

services:
  portal-server:
    container_name: univention-portal-server
    # TODO: Merge Florian's MR: univention/dev/ucs!263
    image: gitregistry.knut.univention.de/univention/dev/projects/portal/portal-server:0.86.1-pre-fbest-fix-assets-root-path
    # command: /usr/bin/python3 /usr/sbin/univention-portal-server
    # entrypoint: /bin/bash -c sleep infinity
    security_opt:
      - seccomp:/etc/docker/seccomp-systemd.json
    restart: unless-stopped  # on-failure
    env_file: /etc/univention-portal/server.env
    volumes:
      # TODO: Make this file configurable to use ObjectStorageCache or FileCache
      - /usr/share/univention-portal/portals.json:/usr/share/univention-portal/portals.json
      # TODO: There is a listener module in UCS, we just need to mount the files
      - /var/cache/univention-portal:/var/cache/univention-portal
      - /etc/univention/ssl/ucsCA/CAcert.pem:/etc/univention/ssl/ucsCA/CAcert.pem:ro
      - /etc/machine.secret:/etc/machine.secret:ro
    ports:
      - "8095:80"
  portal-frontend:
    container_name: univention-portal-frontend
    image: gitregistry.knut.univention.de/univention/dev/projects/portal/portal-frontend:latest
    # command: yarn serve --port 80 mode production
    security_opt:
      - seccomp:/etc/docker/seccomp-systemd.json
    restart: unless-stopped  # on-failure
    env_file: /etc/univention-portal/server.env
    volumes:
      - /etc/univention/ssl/ucsCA/CAcert.pem:/etc/univention/ssl/ucsCA/CAcert.pem:ro
    ports:
      - "8080:80"
