#!/bin/sh
#
# Univention Configuration Registry
#  postinst file
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

rm -f "/etc/univention/templates/cache"

univention-config-registry set ldap/base?dc=univention,dc=unconfigured \
	ldap/server/name?ds1 \
	ldap/server/ip?127.0.0.1 \
	ldap/client/retry/count?10 \
	logrotate/rotate?weekly \
	logrotate/rotate/count?12 \
	logrotate/compress?yes \
	logrotate/missingok?yes \
	logrotate/create?"640 root adm" \
	logrotate/notifempty?yes \
	nameserver/option/timeout?2 \
	update/secure_apt?yes \
	ucr/backup/enabled?yes \
	ucr/replog/enabled?yes \
	ntp/signed?yes \
	ntp/tinker/panic?0 \
	kernel/fs/inotify/max_queued_events?16384 \
	kernel/fs/inotify/max_user_instances?512 \
	kernel/fs/inotify/max_user_watches?32768

eval "$(univention-config-registry shell logrotate/rotate/count)"
univention-config-registry set \
	"logrotate/syslog/rotate/count?$((${logrotate_rotate_count:-1} * 7))" \
	'logrotate/syslog/rotate?daily'

# services
univention-config-registry set cron/autostart?yes \
	inetd/autostart?yes \
	nscd/autostart?yes \
	ntp/autostart?yes \
	sshd/autostart?yes \
	rpcbind/autostart?yes \

# syslog
	univention-config-registry set syslog/mail/mirrorto/syslog?no \
		'systemd/journald/Storage?persistent' \
		'systemd/journald/SystemMaxFileSize?100M' \
		'systemd/journald/MaxFileSec?1 day' \
		'systemd/journald/MaxRetentionSec?12 week' \
		'ntp/noquery?true'

getent passwd tss >/dev/null || useradd --system tss
getent group scanner >/dev/null || addgroup --system scanner
getent group nvram >/dev/null || addgroup --system nvram
getent group rdma >/dev/null || addgroup --system rdma
getent group fuse >/dev/null || addgroup --system fuse
getent group kvm >/dev/null || addgroup --system kvm

#DEBHELPER#

# to use pam_faillock (account locking) via ssh the passwordauthentication
# must be disabled otherwise the pam stack won't use for authentication
#  https://forge.univention.org/bugzilla/show_bug.cgi?id=18750
univention-config-registry set sshd/port?22 \
	sshd/permitroot?yes \
	sshd/xforwarding?no \
	sshd/challengeresponse?yes \
	sshd/passwordauthentication?no

if [ -n "${locale:-}" ]; then
	locale-gen || true
fi

# configure firewall
univention-config-registry set \
	security/packetfilter/package/univention-base-files/tcp/22/all=ACCEPT \
	security/packetfilter/package/univention-base-files/tcp/22/all/en="SSH" \
	security/packetfilter/package/univention-base-files/udp/123/all=ACCEPT \
	security/packetfilter/package/univention-base-files/udp/123/all/en="ntp"

[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

# The nouveau driver from Linux 3.10 is incompatible with the UCS xorg userland (Bug #31701)
univention-config-registry set kernel/blacklist?"nouveau"

# protect these logfiles against arbitrary access
dpkg-statoverride --update --add root root 0640 /var/log/dpkg.log || true
dpkg-statoverride --update --add root root 0640 /var/log/bootstrap.log || true
dpkg-statoverride --update --add root root 0640 /var/log/faillog || true

if test -x /etc/init.d/ssh; then
	invoke-rc.d ssh reload
fi

if [ "$1" = configure ] && dpkg --compare-versions "${2:-}" lt-nl 11.0.7; then
    if [ "$(sysctl --values net.ipv4.neigh.default.gc_thresh1)" -ne 128 ] || [ "$(sysctl --values net.ipv4.neigh.default.gc_thresh2)" -ne  512 ] || [ "$(sysctl --values net.ipv4.neigh.default.gc_thresh3)" -ne 1024 ]; then
        univention-config-registry set kernel/net/ipv4/neigh/default/gc_thresh1?"$(sysctl --values net.ipv4.neigh.default.gc_thresh1)"
        univention-config-registry set kernel/net/ipv4/neigh/default/gc_thresh2?"$(sysctl --values net.ipv4.neigh.default.gc_thresh2)"
        univention-config-registry set kernel/net/ipv4/neigh/default/gc_thresh3?"$(sysctl --values net.ipv4.neigh.default.gc_thresh3)"
    fi
    systemctl try-restart systemd-sysctl.service || true
fi

exit 0
