#!/bin/sh
#
# Univention Configuration Registry
#  preinst file
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# https://forge.univention.org/bugzilla/show_bug.cgi?id=666
dpkg-divert --rename --quiet --divert /etc/motd.debian --package univention-base-files --add /etc/motd

# https://forge.univention.org/bugzilla/show_bug.cgi?id=27759
dpkg-divert --rename --quiet --divert /etc/motd.tail.debian --package univention-base-files --add /etc/motd.tail

rm -f /etc/univention/templates/modules/keymap.pyc

#DEBHELPER#

exit 0
