#!/bin/sh
#
# Univention Web
#  prerm file for the univention-web-js debian package
#
# SPDX-FileCopyrightText: 2017-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$1" in
    remove|deconfigure)
		# unregister JavaScript hook
		a2disconf univention-web.conf || true
		univention-config-registry unset "umc/web/hooks/univention-web-js"
		;;

	upgrade)
		;;

    failed-upgrade)
		;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
		;;
esac

#DEBHELPER#

exit 0
