#!/bin/sh
# SPDX-FileCopyrightText: 2020-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = upgrade ] && dpkg --compare-versions "${2:-}" lt-nl 14.0.1-1
then
	sv -w 30 force-shutdown univention-directory-listener || true
	rm -rf /etc/runit/univention/univention-directory-listener
	rm -rf /etc/runit/univention-directory-listener
	rm -rf /etc/univention/templates/files/etc/runit/univention-directory-listener
fi

#DEBHELPER#

exit 0
