src/listener usr/sbin/univention-directory-listener
src/dump usr/sbin/univention-directory-listener-dump
src/verify usr/sbin/univention-directory-listener-verify
src/listener-ctrl usr/sbin/univention-directory-listener-ctrl
python/get_notifier_id.py usr/share/univention-directory-listener/
python/ldap_server.py usr/lib/univention-directory-listener/system
python/listener.py usr/lib/python2.4/site-packages
03univention-directory-listener.inst usr/lib/univention-install/
