#!/bin/sh
# SPDX-FileCopyrightText: 2015-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

TARGET='/target'
PROFILE="${TARGET}/var/cache/univention-system-setup/profile"

mkdir -p "${PROFILE%/*}"
debconf-dumpdb -p '^uss/' configdb |
	sed -rne '/ \(null\)$/d;s,^uss/(\S+) \S+ (.+),\1="\2",p' >>"$PROFILE"
for var in hostname domainname windows/domain ldap/base locale/default
do
	grep -F -q "$var=" "$PROFILE" ||
		echo "$var=\"$(chroot /target ucr get $var)\"" >>"$PROFILE"
done

CMD="/tmp/run-setup"
cat >"${TARGET}/${CMD}" <<__SH__
#!/bin/sh
exec >>"/var/log/univention/setup-join.log" 2>&1

mv -f /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.UCS
if [ -f /sbin/start-stop-daemon.REAL ]
then
	mv -f /sbin/start-stop-daemon /sbin/start-stop-daemon.UCS
	dpkg-divert --quiet --remove --rename /sbin/start-stop-daemon
fi

/usr/lib/univention-system-setup/scripts/setup-join.sh

if [ -f /sbin/start-stop-daemon.UCS ]
then
	dpkg-divert --quiet --add --divert "/sbin/start-stop-daemon.REAL" --rename "/sbin/start-stop-daemon"
	mv -f /sbin/start-stop-daemon.UCS /sbin/start-stop-daemon
fi
mv -f /usr/sbin/policy-rc.d.UCS /usr/sbin/policy-rc.d
:
__SH__
chmod 755 "${TARGET}/${CMD}"
in-target "$CMD" && :
ret=$?
rm -f "${TARGET}/${CMD}"

exit $ret
