#!/bin/sh
#
# Univention Net Installer Daemon
#  postinst script
#
# SPDX-FileCopyrightText: 2013-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

case "$1" in
	configure)
		# configure firewall
		univention-config-registry set \
			security/packetfilter/package/univention-net-installer-daemon/tcp/49173/all="ACCEPT" \
			security/packetfilter/package/univention-net-installer-daemon/tcp/49173/all/en="univention-net-installer-daemon"
		[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
