#!/bin/bash
#
# Univention Reports
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2007-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

#DEBHELPER#

create_logfile /var/log/univention/directory-reports.log "root:adm" 640

eval "$(univention-config-registry shell)"

univention-config-registry set directory/reports/logo?/usr/share/univention-directory-reports/univention_logo.png \
	directory/reports/templates/pdf/user1?'users/user "PDF Document" /etc/univention/directory/reports/default users.rml' \
	directory/reports/templates/pdf/group1?'groups/group "PDF Document" /etc/univention/directory/reports/default groups.rml' \
	directory/reports/templates/pdf/computer1?'computers/computer "PDF Document" /etc/univention/directory/reports/default computers.rml' \
	directory/reports/templates/csv/user1?'users/user "CSV Report" /etc/univention/directory/reports/default users.csv' \
	directory/reports/templates/csv/group1?'groups/group "CSV Report" /etc/univention/directory/reports/default groups.csv' \
	directory/reports/templates/csv/computer1?'computers/computer "CSV Report" /etc/univention/directory/reports/default computers.csv'

exit 0
