#!/bin/bash
#
# Univention Reports LaTex
#  postinst file for the debian package
#
# SPDX-FileCopyrightText: 2017-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

#DEBHELPER#

eval "$(univention-config-registry shell)"

univention-config-registry set \
	directory/reports/templates/pdf/user2?'users/user "PDF Latex Document" /etc/univention/directory/reports/default users.tex' \
	directory/reports/templates/pdf/group2?'groups/group "PDF Latex Document" /etc/univention/directory/reports/default groups.tex' \
	directory/reports/templates/pdf/computer2?'computers/computer "PDF Latex Document" /etc/univention/directory/reports/default computers.tex' \

exit 0
