#!/bin/bash
#
# Univention Reports
#  postinst file for the debian package
#
# Copyright 2007-2014 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/all.sh

#DEBHELPER#

create_logfile /var/log/univention/directory-reports.log "root:adm" 640

eval "$(univention-config-registry shell)"

# remove old variables
if [ -n "$directory_reports_templates_default1" ]; then
	univention-config-registry unset directory/reports/templates/default1
fi
if [ -n "$directory_reports_templates_default2" ]; then
	univention-config-registry unset directory/reports/templates/default2
fi

# migration from older package version
if dpkg --compare-versions "$2" lt-nl 3.0.1-1; then
	# unset old UCR variables if they have not been changed in the meanwhile
	echo 'directory/reports/templates/csv/computer1 computers/computer "Standard CSV Report" /etc/univention/directory/reports/default/computers.csv
	directory/reports/templates/csv/group1 groups/group "Standard CSV Report" /etc/univention/directory/reports/default/groups.csv
	directory/reports/templates/csv/user1 users/user "Standard CSV Report" /etc/univention/directory/reports/default/users.csv
	directory/reports/templates/pdf/computer1 computers/computer "Standard Report" /etc/univention/directory/reports/default/computers.tex
	directory/reports/templates/pdf/group1 groups/group "Standard Report" /etc/univention/directory/reports/default/groups.tex
	directory/reports/templates/pdf/user1 users/user "Standard Report" /etc/univention/directory/reports/default/users.tex' \
	| (
		keyList=()
		while read key val; do
			[ "$(univention-config-registry get "$key")" = "$val" ] && keyList+=("$key")
		done

		# unset all keys at once
		[ "${#keyList[@]}" -gt 0 ] && univention-config-registry unset "${keyList[@]}"
	)

	# for compatibility reasons, try to set a link to the header.tex and footer.tex 
	# files, so that old reports do not break .. only do this in case the original 
	# template has not been modified
	tmpPath=/etc/univention/directory/reports
	for ifile in header.tex footer.tex; do
		if [ ! -e /etc/univention/templates/files/$tmpPath/$ifile ]; then
			rm -f $tmpPath/$ifile 
			ln -s $tmpPath/default/de_DE/$ifile $tmpPath/$ifile
		fi
	done
fi

# set default values for UCR variables
univention-config-registry set directory/reports/logo?/usr/share/univention-directory-reports/univention_logo.png \
	directory/reports/templates/pdf/user1?'users/user "Standard Report" /etc/univention/directory/reports/default users.tex' \
	directory/reports/templates/pdf/group1?'groups/group "Standard Report" /etc/univention/directory/reports/default groups.tex' \
	directory/reports/templates/pdf/computer1?'computers/computer "Standard Report" /etc/univention/directory/reports/default computers.tex' \
	directory/reports/templates/csv/user1?'users/user "Standard CSV Report" /etc/univention/directory/reports/default users.csv' \
	directory/reports/templates/csv/group1?'groups/group "Standard CSV Report" /etc/univention/directory/reports/default groups.csv' \
	directory/reports/templates/csv/computer1?'computers/computer "Standard CSV Report" /etc/univention/directory/reports/default computers.csv'

exit 0
