# SPDX-FileCopyrightText: 2025-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

version: "3"
services:
  updater:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/work/src
    networks:
      - frontend
    stdin_open: true
    tty: true

networks:
  frontend:
    driver: bridge
