#!/bin/bash
## desc: Rename binary named object
main () {
	$BUG34749 && exit 0
	new_name='RFC4514_ "#+,;<=>\'
	cn_escaped="$(python -c 'import sys,re,ldap.dn;print re.sub(r"\\(.)", lambda m: r"\%02X"%(ord(m.group(1)),), ldap.dn.dn2str(((("cn", sys.argv[1], 1),),)))' "$new_name")"
	udm settings/packages create --position "cn=visible,$BASE" --set name=test
	wait_listener

	udm settings/packages modify --dn "cn=test,cn=visible,$BASE" --set name="$new_name"
	check "cn=test,cn=visible" "" - r
	check "$cn_escaped,cn=visible" - "" a

	udm settings/packages remove --dn "$cn_escaped,cn=visible,$BASE"
}
. "${0%/*}/common.sh"
