#!/bin/bash
## desc: Create, modify, move twice unfiltered objects
## bugs: [34355]
main () {
	udm settings/packages create --position "cn=visible,$BASE" --set name=test1
	a="$(uuid "cn=test1,cn=visible,$BASE")"
	udm settings/packages create --position "cn=visible,$BASE" --set name=test2
	b="$(uuid "cn=test2,cn=visible,$BASE")"

	listener stop
	udm settings/packages modify --dn "cn=test1,cn=visible,$BASE" --append packageList="test$RANDOM"
	udm settings/packages modify --dn "cn=test2,cn=visible,$BASE" --set name=test3
	[ "$b" = "$(uuid "cn=test3,cn=visible,$BASE")" ]
	udm settings/packages modify --dn "cn=test1,cn=visible,$BASE" --set name=test2
	[ "$a" = "$(uuid "cn=test2,cn=visible,$BASE")" ]
	listener start
	if $BUG34355
	then
		check "cn=test1,cn=visible" "$a" - m
		check "cn=test2,cn=visible" "$b" - r
		check "cn=test3,cn=visible" - "$b" a
		# check "cn=test1,cn=visible" "$a" - r # was deleted by 'm'
		check "cn=test2,cn=visible" - "$a" a
	else
		check "cn=test2,cn=visible" "$b" - r
		check "cn=test3,cn=visible" - "$b" a
		check "cn=test1,cn=visible" "$a" - r
		check "cn=test2,cn=visible" - "$a" a
		check "cn=test2,cn=visible" "$a" "$a" m
	fi

	udm settings/packages remove --dn "cn=test2,cn=visible,$BASE"
	udm settings/packages remove --dn "cn=test3,cn=visible,$BASE"
}
. "${0%/*}/common.sh"
