#!/bin/bash
## desc: Create filtered object and move to unfiltered (and delete)
main () {
	udm settings/packages create --position "cn=restricted,$BASE" --set name=test
	wait_listener

	udm settings/packages move --dn "cn=test,cn=restricted,$BASE" --position "cn=visible,$BASE"
	neg check "cn=test,cn=restricted" "" - r
	check "cn=test,cn=visible" - "" a

	udm settings/packages remove --dn "cn=test,cn=visible,$BASE"
}
. "${0%/*}/common.sh"
