#!/bin/sh
#
# Univention AD Connector
#  postinst script of the exchange extension
#
# SPDX-FileCopyrightText: 2004-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

univention-config-registry set	connector/ad/mapping/user/primarymail?true \
				connector/ad/mapping/group/primarymail?true \
				connector/ad/mapping/user/alternativemail?true \
				connector/ad/mapping/group/alternativemail?true \
				connector/ad/mapping/user/exchange?true \
				connector/ad/mapping/group/exchange?true

if [ -x /etc/init.d/univention-ad-connector ]; then
    /etc/init.d/univention-ad-connector crestart || true
fi

if [ -x /etc/init.d/slapd ]; then
    /etc/init.d/slapd restart || true
fi

#DEBHELPER#

exit 0
