univention-ad-connector usr/sbin/
univention-adsearch usr/sbin/
univention-ad-member usr/share/univention-ad-connector/scripts
univention-connector-list-rejected usr/sbin/
scripts/prepare-new-instance usr/share/univention-ad-connector/scripts

conffiles/etc/univention/connector/ad/mapping etc/univention/connector/ad/
files/var/www/univention-ad-connector/.htaccess var/www/univention-ad-connector/

# apache config
apache2.conf etc/apache2/conf.d/univention-ad-connector

19univention-ad-connector.uinst usr/lib/univention-uninstall/
81univention-ad-connector.inst usr/lib/univention-install/

windows/ucs-ad-connector/msi-package/vcredist_x86.exe usr/share/univention-ad-connector/

# AD Connector Listener Module
ad-connector.py usr/lib/univention-directory-listener/system
