univention-ad-connector usr/sbin/
univention-adsearch usr/sbin/
univention-connector-list-rejected usr/sbin/
scripts/prepare-new-instance usr/share/univention-ad-connector/scripts

conffiles/etc/univention/connector/ad/mapping etc/univention/connector/ad/
files/var/www/univention-ad-connector/index.html var/www/univention-ad-connector/

# apache config
apache2.conf etc/apache2/conf.d/univention-ad-connector

windows/ucs-ad-connector/msi-package/vcredist_x86.exe usr/share/univention-ad-connector/

# AD Connector Listener Module
ad-connector.py usr/lib/univention-directory-listener/system
