#AD Connector Listener Module
ad-connector.py	usr/lib/univention-directory-listener/system/
scripts/make-deleted-objects-readable-for-this-machine	usr/share/univention-ad-connector/scripts/
scripts/prepare-new-instance	usr/share/univention-ad-connector/scripts/
scripts/remove_ad_rejected.py	usr/share/univention-ad-connector/
scripts/remove_ucs_rejected.py	usr/share/univention-ad-connector/
scripts/resync_object_from_ad.py	usr/share/univention-ad-connector/
scripts/resync_object_from_ucs.py	usr/share/univention-ad-connector/
scripts/well-known-sid-object-rename	usr/share/univention-ad-connector/scripts/
univention-ad-connector	usr/sbin/
univention-adconnector-list-rejected	usr/sbin/
univention-adsearch	usr/sbin/
