#!/bin/sh
#
# Univention AD Connector
#  postrm script of the ad connector package
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then
	systemctl try-restart univention-directory-listener

	handler_file=/var/lib/univention-directory-listener/handlers/ad-connector
	test -e "$handler_file" && rm -f "$handler_file"

	db=/etc/univention/connector/internal.sqlite
	test -e "$db" && mv "$db" "${db}_backup_$(date +%Y%m%d%H%M%S)"
fi

exit 0
