#!/bin/sh
### BEGIN INIT INFO
# Provides:          univention-ad-connector
# Required-Start:    $network $remote_fs slapd
# Required-Stop:     $network $remote_fs slapd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Univention AD Connector
### END INIT INFO
# pidfile: /var/run/univention-ad-connector
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

ADCONNECTORPID=/var/run/univention-ad-connector
DAEMON="/usr/sbin/univention-ad-connector"

test -x "$DAEMON" || exit 0

. /lib/lsb/init-functions
DESC=$(get_lsb_header_val "$0" Short-Description)

case "$1" in
	start)
		# check ucr autostart setting
		if [ -f "/usr/share/univention-config-registry/init-autostart.lib" ]; then
			. "/usr/share/univention-config-registry/init-autostart.lib"
			check_autostart ad-connector connector/ad/autostart
		fi
		log_daemon_msg "Starting $DESC" "$NAME"
		start-stop-daemon --start --oknodo --quiet --pidfile "$ADCONNECTORPID" --startas "$DAEMON"
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		start-stop-daemon --stop --oknodo --retry TERM/300/KILL/5 --quiet --pidfile "$ADCONNECTORPID"
		log_end_msg $?
		;;
	restart|force-reload)
		"$0" stop
		sleep 2 # give it some time to die
		"$0" start
		;;
	status)
		status_of_proc -p "$ADCONNECTORPID" "$DAEMON" "$DESC"
		;;
	crestart)
		pidofproc -p "$ADCONNECTORPID" "$DAEMON" && "$0" restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart|crestart|force-reload|status}"
		exit 1
		;;
esac
