Document: univention-identity-provider
Title: Debian univention-identity-provider Manual
Author: <insert document author here>
Abstract: This manual describes what univention-identity-provider is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/univention-identity-provider/univention-identity-provider.sgml.gz

Format: postscript
Files: /usr/share/doc/univention-identity-provider/univention-identity-provider.ps.gz

Format: text
Files: /usr/share/doc/univention-identity-provider/univention-identity-provider.text.gz

Format: HTML
Index: /usr/share/doc/univention-identity-provider/html/index.html
Files: /usr/share/doc/univention-identity-provider/html/*.html
