#!/bin/sh

set -e

if [ install = "$1" -o upgrade = "$1" ]; then 
	echo "PRE-INST"
	dpkg-divert --package univention-identity-provider --add --rename --divert /etc/simplesamlphp/config.php.debian-orginal /etc/simplesamlphp/config.php
	dpkg-divert --package univention-identity-provider --add --rename --divert /etc/simplesamlphp/authsources.php.debian-orginal /etc/simplesamlphp/authsources.php
fi  

#DEBHELPER#

exit 0



