#!/bin/sh
#
# Univention LDAP Configuration
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2001-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# UCS 4.2-1-errata: add univentionUDMPropertyCopyable to index. Is part of joinscript and can be removed somewhen.
if [ -x /usr/share/univention-ldap/ldap_setup_index ] &&
	[ -e /var/univention-join/joined ] &&
	[ "$1" = configure ] &&
	[ -z "$2" ] &&
	! ucr get ldap/index/eq | tr , '\n' | grep -Fxq univentionUDMPropertyCopyable &&
	univention-ldapsearch -LLL -o ldif-wrap=no -b cn=Subschema -s base attributeTypes | grep -Fq "NAME 'univentionUDMPropertyCopyable'"
then
	if pidof slapd >/dev/null 2>/dev/null
	then
		deb-systemd-invoke stop slapd.service
		/usr/share/univention-ldap/ldap_setup_index --add-eq univentionUDMPropertyCopyable
		deb-systemd-invoke start slapd.service
	else
		/usr/share/univention-ldap/ldap_setup_index --add-eq univentionUDMPropertyCopyable
	fi
fi

if [ "$1" = "configure" ] && [ -z "$2" ]; then
		# start on Primary, slapd may be down by schema-conflicts which are cleared by a new slapd.conf-template
		server_role=$(ucr get server/role)
		if [ "$server_role" = "domaincontroller_master" ]
		then
			deb-systemd-invoke restart slapd
		else
			deb-systemd-invoke try-restart slapd
		fi
fi

exit 0
