#!/bin/bash
#
# Univention LDAP Server
#  postinst script for the debian package
#
# SPDX-FileCopyrightText: 2017-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(univention-config-registry shell)"

restart_slapd ()
{
	deb-systemd-invoke stop slapd.service
	sleep 1
	if [ -n "$(pidof slapd)" ]; then
		killall slapd
		sleep 1
		if [ -n "$(pidof slapd)" ]; then
			killall -9 slapd
			sleep 1
		fi
	fi
	deb-systemd-invoke start slapd.service
}

if [ "$1" = "configure" ]; then
	if [ "$server_role" = "domaincontroller_master" ]; then
		if dpkg --compare-versions "$2" lt-nl 18.2.3; then
			restart_slapd
		fi
	fi
fi

exit 0
