univention-backup2master usr/lib/univention-ldap/
univention-ldap-backup usr/sbin/
01univention-ldap-server-init.inst usr/lib/univention-install/
10univention-ldap-server.inst usr/lib/univention-install/
scripts/convert_shadowMax.py usr/share/univention-ldap/
scripts/convert_univentionMailSharedFolderDeliveryAddress.py usr/share/univention-ldap/
python/settings_ldapschema.py usr/lib/univention-directory-listener/system/
python/settings_ldapacl.py usr/lib/univention-directory-listener/system/
