#!/bin/bash
#
# Univention Debmirror
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

. /usr/share/univention-lib/all.sh

eval "$(univention-config-registry shell)"

#DEBHELPER#

# activate local repository on installation only
if [ "$1" = "configure" ] && [ -z "$2" ]; then
	univention-config-registry set local/repository?yes
fi

call_joinscript 77univention-debmirror.inst

a2ensite univention-repository
/etc/init.d/apache2 reload || true

exit 0
