# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

[build-system]
requires = ["setuptools >= 64", "python-debian"]
build-backend = "setuptools.build_meta"

[project]
name = "univention-management-console"
version = "0.0.0"
description = "Univention Management Console"
license = "AGPL-3.0-only"
requires-python = ">= 3.11"
dependencies = [
    "python-ldap",
    "tornado",
    "univention-config-registry",
    "univention-debug-python",
    "univention-directory-manager-modules",
    "univention-lib",
    "univention-python",
]
