#!/bin/bash
#
# postinst script
#
# SPDX-FileCopyrightText: 2019-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

eval "$(ucr shell admin/diary/db.*)"
if [ -z "$admin_diary_dbhost" ] \
	|| [ "$admin_diary_dbhost" = "localhost" ]; then

	SECRET_FILE="/etc/admin-diary.secret"
	if [ ! -e "$SECRET_FILE" ]; then
		touch "$SECRET_FILE"
		chmod 0700 "$SECRET_FILE"
		PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c20)"
		echo -n "$PASSWORD" > "$SECRET_FILE"
	fi

	if [ -x /etc/init.d/mysql ]; then
		ucr set admin/diary/dbms?mysql
	elif [ -x /etc/init.d/postgresql ]; then
		ucr set admin/diary/dbms?postgresql
	else
		echo "ERROR: Cannot determine local database type" 2>&1
	fi
elif [ -z "$admin_diary_dbms" ]; then
	echo "ERROR: admin/diary/dbhost is set in UCR but admin/diary/dbms is not" 2>&1
fi

exit 0
