#!/bin/bash
#
# postinst script
#
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

ucr set admin/diary/backend/port?10514
ucr set admin/diary/query/limit?1000

eval "$(ucr shell admin/diary/backend/port)"

case "$1" in
	configure)
		if [ -z "$2" ]; then  # Installation
			univention-config-registry set \
				security/packetfilter/package/univention-admin-diary/tcp/"$admin_diary_backend_port"/all="ACCEPT" \
				security/packetfilter/package/univention-admin-diary/tcp/"$admin_diary_backend_port"/all/en="rsyslog relp+TLS"
			invoke-rc.d univention-firewall restart

		fi
		invoke-rc.d rsyslog try-restart
		;;
esac

exit 0
