#! /bin/sh
#
# Univention Squid
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

# the proxy user needs to be in the group winbindd_priv to be able to access winbind
adduser proxy winbindd_priv

LOCALINCLUDE=/etc/squid/local.conf
if [ ! -e "$LOCALINCLUDE" ]; then
	echo "# add local config here" >> "$LOCALINCLUDE"
fi

ucr set squid/transparentproxy?false \
	squid/cache?yes \
	squid/debug/level?ALL,1 \
	squid/forwardedfor?off \
	squid/cache/format?ufs \
	squid/cache/directory?/var/spool/squid \
	squid/cache/size?512 \
	squid/cache/l1_size?16 \
	squid/cache/l2_size?256 \
	squid/basicauth/encoding_wrapper?true

invoke-rc.d squid restart

# configure firewall
ucr set security/packetfilter/package/univention-squid/tcp/3128/all="ACCEPT" \
		security/packetfilter/package/univention-squid/tcp/3128/all/en="HTTP proxy"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

if [ "$1" = "configure" ]; then
	uinst=/usr/lib/univention-install/60univention-squid.uinst
	[ -e "$uinst" ] && rm "$uinst"
fi

call_joinscript 79univention-squid.inst

exit 0
