#! /bin/sh
#
# Univention Samba
#  postrm script
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 60univention-squid.uinst

	ucr unset \
		squid/transparentproxy \
		squid/cache \
		squid/debug/level \
		security/packetfilter/package/univention-squid/tcp/3128/all/en \
		security/packetfilter/package/univention-squid/tcp/3128/all

	[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

	[ -e "/etc/squid.secret" ] && rm -f /etc/squid.secret

fi

exit 0
