({
	'bold': 'Negrito',
	'copy': 'Copiar',
	'cut': 'Recortar',
	'delete': 'Excluir ',
	'indent': 'Recuar',
	'insertHorizontalRule': 'Régua Horizontal',
	'insertOrderedList': 'Lista Numerada',
	'insertUnorderedList': 'Lista com Marcadores',
	'italic': 'Itálico',
	'justifyCenter': 'Alinhar pelo Centro',
	'justifyFull': 'Justificar',
	'justifyLeft': 'Alinhar pela Esquerda',
	'justifyRight': 'Alinhar pela Direita',
	'outdent': 'Não-chanfrado',
	'paste': 'Colar',
	'redo': 'Refazer',
	'removeFormat': 'Remover Formato',
	'selectAll': 'Selecionar Todos',
	'strikethrough': 'Tachado',
	'subscript': 'Subscrito',
	'superscript': 'Sobrescrito',
	'underline': 'Sublinhado',
	'undo': 'Desfazer',
	'unlink': 'Remover Link',
	'createLink': 'Criar Link',
	'toggleDir': 'Alternar Direção',
	'insertImage': 'Inserir Imagem',
	'insertTable': 'Inserir/Editar Tabela',
	'toggleTableBorder': 'Alternar Moldura da Tabela',
	'deleteTable': 'Excluir Tabela',
	'tableProp': 'Propriedade da Tabela',
	'htmlToggle': 'Origem HTML',
	'foreColor': 'Cor do Primeiro Plano',
	'hiliteColor': 'Cor de segundo plano',
	'plainFormatBlock': 'Estilo de Parágrafo',
	'formatBlock': 'Estilo de Parágrafo',
	'fontSize': 'Tamanho da Fonte',
	'fontName': 'Nome da Fonte',
	/* Error messages */
	'systemShortcutFF': 'A ação "${0}" está disponível apenas no Mozilla Firefox utilizando um atalho do teclado. Utilize ${1}.'
})
