({
	'bold': 'Grassetto',
	'copy': 'Copia',
	'cut': 'Taglia',
	'delete': 'Elimina',
	'indent': 'Rientra',
	'insertHorizontalRule': 'Righello orizzontale',
	'insertOrderedList': 'Elenco numerato',
	'insertUnorderedList': 'Elenco puntato',
	'italic': 'Corsivo',
	'justifyCenter': 'Allinea al centro',
	'justifyFull': 'Giustifica',
	'justifyLeft': 'Allinea a sinistra',
	'justifyRight': 'Allinea a destra',
	'outdent': 'Rimuovi rientro',
	'paste': 'Incolla',
	'redo': 'Ripristina',
	'removeFormat': 'Rimuovi formato',
	'selectAll': 'Seleziona tutto',
	'strikethrough': 'Barrato',
	'subscript': 'Pedice',
	'superscript': 'Apice',
	'underline': 'Sottolineato',
	'undo': 'Annulla',
	'unlink': 'Rimuovi collegamento',
	'createLink': 'Crea collegamento',
	'toggleDir': 'Inverti direzione',
	'insertImage': 'Inserisci immagine',
	'insertTable': 'Inserisci/Modifica tabella',
	'toggleTableBorder': 'Mostra/Nascondi margine tabella',
	'deleteTable': 'Elimina tabella',
	'tableProp': 'Proprietà tabella',
	'htmlToggle': 'Origine HTML',
	'foreColor': 'Colore primo piano',
	'hiliteColor': 'Colore sfondo',
	'plainFormatBlock': 'Stile paragrafo',
	'formatBlock': 'Stile paragrafo',
	'fontSize': 'Dimensione carattere',
	'fontName': 'Nome carattere',
	/* Error messages */
	'systemShortcutFF': 'L\'azione "${0}" è disponibile solo in Mozilla Firefox tramite tasti di scelta rapida. Utilizzare ${1}.'
})
