#!/usr/share/ucs-test/runner python
## desc: Testing the base functionality to move an OU
## tags: [udm-containers,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		ouName = uts.random_name()
		ou = udm.create_object('container/ou', name = ouName)
		ou2 = udm.create_object('container/ou', name = uts.random_name())
		
		udm.move_object('container/ou', dn = ou, position = ou2)
		
		expectedDN = 'ou=%s,%s' % (ouName, ou2)

		if not utils.verify_ldap_object(expectedDN):
			utils.fail('Expected created OU to be at "%s" after moving, but could not find it there' % expectedDN)


