#!/usr/share/ucs-test/runner python
## desc: Test the base functionality to move an OU recursively
## tags: [udm-containers]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import sys
import univention.uldap as uldap
import univention.testing.udm as udm_test
import univention.testing.strings as uts


if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		ouName = uts.random_string()
		ou2Name = uts.random_string()
		ou = udm.create_object('container/ou', name = ouName)
		ou2 = udm.create_object('container/ou', name = ou2Name)
		ou3 = udm.create_object('container/ou', name = uts.random_name())

		udm.move_object('container/ou', dn = ou, position = ou2)
		udm.move_object('container/ou', dn = ou2, position = ou3)

		expectedDN = 'ou=%s,ou=%s,%s' % (ouName, ou2Name, ou3)
		ldap = uldap.getAdminConnection()
		result = ldap.searchDn(base = ','.join(expectedDN.split(',')[1:]), filter = '(&(ou=%s)(objectClass=organizationalUnit))' % ouName)
		for dn in result:
			if dn == expectedDN:
				break
		else:
			print 'Test FAILED. Expected created OU to be at "%s" after moving, but could not be found there.' % expectedDN
			sys.exit(1)
