#!/usr/share/ucs-test/runner python
## desc: Testing the base functionality to move an CN
## tags: [udm-containers,apptest]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		cnName = uts.random_name()
		cn = udm.create_object('container/cn', name = cnName)
		cn2 = udm.create_object('container/cn', name = uts.random_name())

		udm.move_object('container/cn', dn = cn, position = cn2)
		expectedDN = 'cn=%s,%s' % (cnName, cn2)

		if not utils.verify_ldap_object(expectedDN):	
			utils.fail('Expected created CN to be at "%s" after moving, but could find it there' % expectedDN)


