#!/bin/sh
# postinst script for python-univention-lib
#
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

univention-config-registry set \
	'listener/shares/whitelist/defaults?/home/*:/opt/*:/run/*:/media/*:/mnt/*:/srv/*' \
	'listener/shares/whitelist/opsi4ucs?/var/lib/opsi/*' \
	'listener/shares/whitelist/univention-printserver-pdf?/var/spool/cups-pdf/*' \
	'listener/shares/whitelist/ucs-school-import?/home/*' \
	'listener/shares/whitelist/italc-windows?/usr/share/italc-windows/*'
exit 0
