#!/usr/share/ucs-test/runner bash
# shellcheck shell=bash
## desc: Check univention-scp und univention-ssh-rsync
## tags: [univention]
## packages: [univention-ssh]
## exposure: safe

# shellcheck source=../../lib/base.sh
. "${TESTLIBPATH}/base.sh" || exit 137

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

if \
	univention-ssh-rsync "${tests_root_pwdfile:?}" /etc/hostname "root@${hostname:?}.${domainname:?}:$tmp/ping" &&
	cmp /etc/hostname "$tmp/ping" &&
	univention-scp "$tests_root_pwdfile" "root@${hostname}.${domainname}:$tmp/ping" "$tmp/pong" &&
	cmp /etc/hostname "$tmp/pong"
then
	exit 100 # OK
else
	exit 110 # ERROR
fi
# vim:set ft=sh:
