#!/usr/share/ucs-test/runner bash
## desc: Check univention-ssh echo yes/no
## bugs: [14212]
## tags: [univention]
## packages: [univention-ssh]
## exposure: safe

. "$TESTLIBPATH/base.sh" || exit 137

if [ yes/no = "$(univention-ssh "$tests_domainadmin_pwdfile" "root@${hostname}.${domainname}" echo -n yes/no)" ]
then
	exit 100 # OK
else
	exit 110 # ERROR
fi
# vim:set ft=sh:
