#!/usr/bin/python
# vim: set fileencoding=utf-8 :
# pylint: disable=R0903,R0201

import argparse
import libvirt

parser = argparse.ArgumentParser(description='Destroy and erase a virtual machine from a KVM server.')
parser.add_argument('--name', dest='vm_name', required=True, help='The name of the virtual machine.')
parser.add_argument('--server', dest='kvm_server', required=True, help='The fqdn of the kvm server.')
args = parser.parse_args()

VM_NAME = args.vm_name
HOST = 'qemu+ssh://build@' + args.kvm_server + '/system'

conn = libvirt.open(HOST)
dom = conn.lookupByName(VM_NAME)
dom.destroy()
dom.undefine()
