#!/bin/bash

while(true); do

	eval "$(ucr shell)"
	[ -z ${ucs_server_sso_fqdn} ] || ucs_server_sso_fqdn="ucs-sso.${domainname}"
	[ -z ${ucs_server_sso_cert} ] && ucs_server_sso_cert="/etc/univention/ssl/${ucs_server_sso_fqdn}/cert.pem"
	[ -z ${ucs_server_sso_key} ] && ucs_server_sso_key="/etc/univention/ssl/${ucs_server_sso_fqdn}/secret.key"


	timeout 5 bash -c "while read -r fn; do echo "$fn" >/dev/null 2>&1;done <    <(echo "stats" | openssl s_client -connect "${ucs_server_sso_fqdn}:11212" -cert "$cert_path" -key "$key_path" >/dev/null 2>&1)"

	ret="$?"
	# command ran into timeout
	if [ $ret == 124 ]; then
		systemctl is-active --quiet "stunnel4.service"
		if [ "$?" == 0 ]; then
			# stunnel4 is running but doesn't answer. Kill and restart
			echo "Killing stunnel4 to restart, it seems to be hanging. See https://forge.univention.org/bugzilla/show_bug.cgi?id=52196"
			kill -9 "$(pidof -x stunnel4)"
		fi
	fi
	sleep 30
done
