#!/bin/bash
# -*- coding: utf-8 -*-
#
# Univention SAML
# service to monitor stunnel4
#
# Copyright 2013-2021 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.


while true; do

	eval "$(ucr shell)"
	[ -z ${ucs_server_sso_fqdn} ] || ucs_server_sso_fqdn="ucs-sso.${domainname}"
	[ -z ${ucs_server_sso_cert} ] && ucs_server_sso_cert="/etc/univention/ssl/${ucs_server_sso_fqdn}/cert.pem"
	[ -z ${ucs_server_sso_key} ] && ucs_server_sso_key="/etc/univention/ssl/${ucs_server_sso_fqdn}/secret.key"


	timeout 5 bash -c "while read -r fn; do echo "$fn" >/dev/null 2>&1;done <    <(echo "stats" | openssl s_client -connect "${ucs_server_sso_fqdn}:11212" -cert "$cert_path" -key "$key_path" >/dev/null 2>&1)"

	ret="$?"
	# command ran into timeout
	if [ $ret == 124 ]; then
		systemctl is-active --quiet "stunnel4.service"
		if [ "$?" == 0 ]; then
			# stunnel4 is running but doesn't answer. Kill and restart
			echo "Killing stunnel4 to restart, it seems to be hanging. See https://forge.univention.org/bugzilla/show_bug.cgi?id=52196"
			kill -9 "$(pidof -x stunnel4)"
		fi
	fi
	sleep 30
done
