#!/bin/sh
#
# Univention Nagios Plugin
#  rules file for the debian package
#
# SPDX-FileCopyrightText: 2011-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "configure" ]; then
	uinst=/usr/lib/univention-install/69univention-nagios-s4-connector.uinst
	[ -e "$uinst" ] && rm "$uinst"
fi

. /usr/share/univention-lib/base.sh
call_joinscript 31univention-nagios-s4-connector.inst

exit 0
