#!/bin/sh
#
# Univention System Setup
# restart UMC server components
#
# SPDX-FileCopyrightText: 2014-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# unset ssl certificate variables,
# from now on use the new certificate
ucr unset \
	apache2/ssl/certificate \
	apache2/ssl/key \
	apache2/ssl/ca

/usr/share/univention-updater/disable-apache2-umc
/usr/share/univention-updater/enable-apache2-umc

exit 0
