[package]
name = "univention-radius"
version = "10.0.1"
edition = "2021"

[[bin]]
name = "univention-radius-ntlm-auth"
path = "src/main.rs"

[[bin]]
name = "univention-radius-check-access"
path = "src/check_access.rs"

[dependencies]
univentionpolicy = "14"
univentionconfig = "18"
hex = "0.4"
des = "0.8"
md4 = "0.10"
digest = "0.10"
cipher = "0.4"
libc = "0.2"
log = "0.4"
once_cell = "1.20"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
subtle = "2"
