#!/bin/sh
#
# Univention Directory Manager
#  postinst file for the directory manager debian package
#
# Copyright (C) 2004, 2005, 2006, 2007 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#DEBHELPER#

eval `univention-baseconfig shell`

createLogfile () {
	if [ ! -e $1 ] ; then
		touch $1
		chown $2 $1
		chmod $3 $1
	fi
}

createLogfile /var/log/univention/directory-reports-cleanup.log "root:adm" 640

if [ "$server_role"  = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]; then
	/usr/lib/univention-install/25univention-directory-manager.inst || true
fi

# rename baseconfig variables
function bc_rename() {
	old=$1
	new=$2
	predefined=$3
	if [ -n "$old" ]; then
		univention-config-registry set "${new}?${old}"
	else
		univention-config-registry set "${new}?${predefined}"
	fi
}

if [ "$1" = configure ]; then
	bc_rename "$admin_web_debug_level" "directory/manager/web/debug/level" "0"
	if [ "$admin_web_language" = "de" ]; then
		admin_web_language="de_DE.utf8"
	elif [ "$admin_web_language" = "en" ]; then
		admin_web_language="en_US.utf8"
	fi
	if [ -n "$locale_default" ]; then
		univention-baseconfig set directory/manager/web/language="$(echo $locale_default | sed -e 's|:.*||')"
	else
		bc_rename "$admin_web_language" "directory/manager/web/language" "de_DE.utf8"
	fi

	bc_rename "$admin_timeout" "directory/manager/timeout" "300"

	if [ -n "$admin_timeout" ]; then
		univention-baseconfig unset admin/timeout
	fi
	if [ -n "$admin_web_language" ]; then
		univention-baseconfig unset admin/web/language
	fi
	if [ -n "$admin_web_debug_level" ]; then
		univention-baseconfig unset admin/web/debug/level
	fi
fi

univention-config-registry set ssl/validity/check?yes
univention-config-registry set directory/reports/cleanup/cron?"0 0 * * *"
univention-config-registry set directory/reports/cleanup/age?43200

for path in /usr/share/univention-directory-manager/www/icon /usr/share/univention-directory-manager/www/style /usr/share/univention-directory-manager/www/includes; do
	if [ -d $path -a ! -h $path ]; then
		rm -r $path
	fi
done

test -h /usr/share/univention-directory-manager/www/index.php || ln -s /usr/share/univention-webui/www/index.php /usr/share/univention-directory-manager/www
test -h /usr/share/univention-directory-manager/www/file.php || ln -s /usr/share/univention-webui/www/file.php /usr/share/univention-directory-manager/www

test -h /var/www/univention-directory-manager || ln -s /usr/share/univention-directory-manager/www /var/www/univention-directory-manager


chown www-data:www-data /usr/share/univention-directory-manager/www/directory-reports
chmod 700 /usr/share/univention-directory-manager/www/directory-reports

if [ "$1" = configure -a -n "$2" ] && dpkg --compare-versions "$2" lt 3.1.4-1; then
	ln -sf /usr/share/univention-webui-style/icon /usr/share/univention-directory-manager/www/icon
	a2ensite univention-directory-manager
elif [ "$1" = configure -a -z "$2" ]; then
	ln -sf /usr/share/univention-webui-style/icon /usr/share/univention-directory-manager/www/icon
	a2ensite univention-directory-manager
fi

if [ "$1" = "configure" -a -n "$2" ]; then

	for i in `ps -ef | egrep "/usr/bin/python2.4.*/usr/share/univention-admin/uniconf/univention-admin.py" | awk '{print $2}'`; do
		kill $i >/dev/null 2>&1
	done
	a2dissite univention-admin

	sleep 1

	/etc/init.d/apache2 reload || true
else
	/etc/init.d/apache2 reload || true
fi
