#!/bin/sh
#
#DEBHELPER#

set -e

ldapsearch -x -b dc=univention,dc=qa
ldapsearch -x -b dc=univention,dc=test
ldapsearch -x -b dc=univention,dc=local
echo "univention.qa"
echo "univention.test"
echo "univention.local"

/usr/lib/univention-install/34univention-management-console-server.inst || true
