.\"                                      Hey, EMACS: -*- nroff -*-
.TH UNIVENTION-DIRECTORY-LISTENER-VERIFY 8 2012-03-16 UCS
.SH NAME
univention\-directory\-listener\-verify \- verify UCS listener cache
.SH SYNOPSIS
.B univention\-directory\-listener\-verify
.RI [ options ]
.BI \-b\  base-dn
.BI \-D\  bind-dn
.BI \-w\  password
.SH DESCRIPTION
This manual page documents briefly the
.B univention\-directory\-listener\-verify
command, which compares the data from LDAP with the data in the listener cache.
.SH OPTIONS
A summary of options is included below.
.TP
.BI \-d\  level
Set debugging \fIlevel\fP.
.TP
.BI \-c\  directory
Use the \fIcache.db\fP from given \fIdirectory\fP instead of from \fI/var/lib/univention\-directory\-listener\fP.
.TP
.BI \-D\  bind-dn
LDAP bind dn.
.TP
.BI \-w\  password
LDAP bind password.
.TP
.BI \-b\  base-dn
LDAP base dn.
.SH FILES
.TP
.I /var/lib/univention\-directory\-listener/
Default directory used by the
.BR univention\-directory\-listener (8).
.SH SEE ALSO
.BR univention\-directory\-listener (8),
.BR univention\-directory\-listener\-dump (8).
.br
This program is documented fully in the
.IR "Univention Corporate Server Manual" .
.SH AUTHOR
Copyright (c) 2001-2019 Univention GmbH, Germany
