#!/bin/sh
#
# Univention DHCP
#  postinst script
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

set -e

# If for some reason we lost the original init script, try to recover it BEFORE undoing the UCR template divert
undo_divert () {
	local init='/etc/init.d/isc-dhcp-server' fallback
	[ "$1" = configure ] || return 0
	dpkg --compare-versions "${2:-}" lt-nl 14.0.2-1 || return 0
	[ "$(dpkg-divert --truename "$init")" = "$init.debian" ] || return 0
	[ -f "$init.debian" ] && return 0
	for fallback in "$init.dpkg-remove" "$init.dpkg-backup" "$init.dpkg-bak" "$init"*
	do
		[ -f "$fallback" ] || continue
		cp "$fallback" "$init.debian" && return 0
	done
	echo "ABORT: The init script will be gone" >&2
	ls -gGd "$init"* >&2
	exit 1
}
undo_divert "$@"

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/base.sh
create_logfile_if_missing /var/log/univention/dhcp.log root:adm 640

if [ "$1" = configure ]
then
	eval "$(univention-config-registry shell)"

	case "${dhcpd_enable:-}" in
	'')
		univention-config-registry set dhcpd/autostart?"yes"
		;;
	yes|true|1)
		univention-config-registry set dhcpd/autostart?"yes"
		ucr unset dhcpd/enable
		;;
	*)
		univention-config-registry set dhcpd/autostart?"no"
		ucr unset dhcpd/enable
		;;
	esac

	univention-config-registry set \
		security/packetfilter/package/univention-dhcp/udp/67/all=ACCEPT \
		security/packetfilter/package/univention-dhcp/udp/67/all/en="DHCP" \
		security/packetfilter/package/univention-dhcp/udp/68/all=ACCEPT \
		security/packetfilter/package/univention-dhcp/udp/68/all/en="DHCP" \
		dhcpd/restart/listener?yes

	case "${server_role:-}" in
	domaincontroller_master|domaincontroller_backup)
		/usr/lib/univention-install/25univention-dhcp.inst || true
		;;
	esac

	# shellcheck disable=SC2015
	dpkg --compare-versions "${2:-}" lt-nl 14.0.4 &&
		[ -f /var/univention-join/joined ] &&
		touch /var/univention-join/dhcp-server

	if [ -d /run/systemd/system ]
	then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke restart isc-dhcp-server.service univention-directory-listener.service univention-firewall.service
	fi

	# shellcheck disable=SC2015
	dpkg --compare-versions "${2:-}" lt-nl 14.0.3 &&
		update-rc.d -f univention-dhcp remove ||
		:
fi

exit 0
