#!/bin/sh
# SPDX-FileCopyrightText: 2020-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

if [ "$1" = upgrade ] && dpkg --compare-versions "${2:-}" lt-nl 14.0.2-3
then
	sv -w 30 force-shutdown univention-dhcp || true
	rm -rf /etc/runit/univention-dhcp
	rm -rf /etc/runit/univention/univention-dhcp
	rm -rf /etc/univention/templates/files/etc/runit/univention-dhcp
	univention-config-registry update
fi

#DEBHELPER#

exit 0
