#!/bin/sh
#
# SPDX-FileCopyrightText: 2021-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

case "$1" in
purge)
	ucr --keys-only search --brief --non-empty ^dhcpd/ |
		xargs ucr unset \
		security/packetfilter/package/univention-dhcp/udp/67/all \
		security/packetfilter/package/univention-dhcp/udp/67/all/en \
		security/packetfilter/package/univention-dhcp/udp/68/all \
		security/packetfilter/package/univention-dhcp/udp/68/all/en \

	rm -f /var/log/univention/dhcp.log
	rm -f /var/univention-join/dhcp-server
	;;
esac

#DEBHELPER#

exit 0
