#!/bin/sh
#
# Univention S4 Connector
#  postrm script of the samba4 connector package
#
# SPDX-FileCopyrightText: 2013-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

if [ "$1" = "remove" ]; then
	. /usr/share/univention-lib/all.sh
	call_unjoinscript 03univention-s4-connector.uinst

	systemctl try-restart univention-directory-listener

	handler_file=/var/lib/univention-directory-listener/handlers/s4-connector
	test -e "$handler_file" && rm -f "$handler_file"

	db=/etc/univention/connector/s4internal.sqlite
	test -e "$db" && mv "$db" "${db}_backup_$(date +%Y%m%d%H%M%S)"

fi

exit 0
