#!/bin/bash

source "$TESTLIBPATH/base.lib"
source "$TESTLIBPATH/udm.lib"
source "$TESTLIBPATH/s4connector.lib"

if [ -z "$connector_s4_ldap_host" ]; then
	warning "connector/s4/ldap/host is empty."
	warning "Assuming that the Ad-Connector isn't configured."
	warning "Skipping test."
	exit 137
fi

TEST_BASIC=false
INFO_LINE="Create and modify AD-Group with umlauts in read-mode"
TEST_SERVER_ROLE="domaincontroller_master domaincontroller_backup"
TEST_PACKAGES="univention-config univention-s4-connector"

UDM_groups_group_name="ä$(randomchars)ö"
AD_GROUP_DN="CN=$UDM_groups_group_name,CN=Groups,$(ad_get_base)"

SYNCMODE="$(ad_get_sync_mode)"

ad_set_sync_mode "read"

ad_creategroup "$UDM_groups_group_name" || fail_test 110
ad_wait_for_synchronization; check_bool 0 110

ad_exists "$AD_GROUP_DN"; check_bool 0 110
udm_exists "groups/group"; check_bool 0 110

ad_verify_attribute	"$AD_GROUP_DN" "sAMAccountName" "$UDM_groups_group_name"; check_bool 0 110
ad_verify_attribute	"$AD_GROUP_DN" "cn" "$UDM_groups_group_name"; check_bool 0 110
ad_verify_attribute	"$AD_GROUP_DN" "name" "$UDM_groups_group_name"; check_bool 0 110

udm_verify_udm_attribute "name" "$UDM_groups_group_name" "groups/group"; check_bool 0 110

ad_delete "$AD_GROUP_DN" || fail_test 110
ad_wait_for_synchronization; check_bool 0 110

udm_exists "groups/group"; check_bool 1 110
ad_exists "$AD_GROUP_DN"; check_bool 1 110

ad_set_sync_mode "$SYNCMODE"

exit "$RETVAL"
