#!/bin/bash

source "$TESTLIBPATH/base.lib"
source "$TESTLIBPATH/udm.lib"
source "$TESTLIBPATH/s4connector.lib"

if [ -z "$connector_s4_ldap_host" ]; then
	warning "connector/s4/ldap/host is empty."
	warning "Assuming that the Ad-Connector isn't configured."
	warning "Skipping test."
	exit 137
fi

TEST_BASIC=false
INFO_LINE="Check whether container can be recursively removed on ucs-side in write-mode"
TEST_SERVER_ROLE="domaincontroller_master domaincontroller_backup"
TEST_PACKAGES="univention-config univention-s4-connector"

#                 Container3
#                /
#      Container1--User
#     /
# Base

# shall become

# Base

CONTAINER1="$(randomchars)1"
AD_CONTAINER1_DN="CN=$CONTAINER1,$(ad_get_base)"
CONTAINER3="$(randomchars)3"
AD_CONTAINER3_DN="CN=$CONTAINER3,CN=$CONTAINER1,$(ad_get_base)"
USER="$(randomchars)"
AD_USER_DN="CN=$USER,CN=$CONTAINER1,$(ad_get_base)"
UDM_users_user_username="$USER"
UDM_users_user_lastname="$(randomchars)"
# If the password doesn't adhere the configured Windows-Password-Guidelines
# weird things might happen when the user is synced to AD.
UDM_users_user_password="U$(randomchars)123"

SYNCMODE="$(ad_get_sync_mode)"
ad_set_sync_mode "write"

section "Create initial Tree structure"

UDM_container_cn_name="$CONTAINER1"
udm_create "container/cn" || fail_test 110
UDM_container_cn_name="$CONTAINER3"
udm_create "container/cn" "" "" "cn=$CONTAINER1,$ldap_base" || fail_test 110
UDM_users_user_username="$USER"
udm_create "users/user" "" "" "cn=$CONTAINER1,$ldap_base" || fail_test 110

ad_wait_for_synchronization; check_bool 0 110

UDM_container_cn_name="$CONTAINER1"
udm_exists "container/cn"; check_bool 0 110
ad_exists "$AD_CONTAINER1_DN"; check_bool 0 110
UDM_container_cn_name="$CONTAINER3"
udm_exists "container/cn" "" "" "cn=$CONTAINER1,$ldap_base"; check_bool 0 110
ad_exists "$AD_CONTAINER3_DN"; check_bool 0 110
udm_exists "users/user" "" "" "cn=$CONTAINER1,$ldap_base"; check_bool 0 110

section "Recursively remove $CONTAINER1"

UDM_container_cn_name="$CONTAINER1"
udm_remove "container/cn" || fail_test 110

ad_wait_for_synchronization; check_bool 0 110

UDM_container_cn_name="$CONTAINER1"
udm_exists "container/cn"; check_bool 1 110
ad_exists "$AD_CONTAINER1_DN"; check_bool 1 110
UDM_container_cn_name="$CONTAINER3"
udm_exists "container/cn" "" "" "cn=$CONTAINER1,$ldap_base"; check_bool 1 110
ad_exists "$AD_CONTAINER3_DN"; check_bool 1 110
udm_exists "users/user" "" "" "cn=$CONTAINER1,$ldap_base"; check_bool 1 110

ad_set_sync_mode "$SYNCMODE"

exit "$RETVAL"
