#!/bin/bash

source "$TESTLIBPATH/base.lib"
source "$TESTLIBPATH/udm.lib"
source "$TESTLIBPATH/s4connector.lib"

if [ -z "$connector_s4_ldap_host" ]; then
	warning "connector/s4/ldap/host is empty."
	warning "Assuming that the Ad-Connector isn't configured."
	warning "Skipping test."
	exit 137
fi

TEST_BASIC=false
INFO_LINE="Create and remove an AD-Ou in read mode"
TEST_SERVER_ROLE="domaincontroller_master domaincontroller_backup"
TEST_PACKAGES="univention-config univention-s4-connector"

UDM_container_ou_name="$(randomchars)"
UDM_container_ou_description="$(randomchars)"
AD_OU_DN="OU=$UDM_container_ou_name,$(ad_get_base)"

SYNCMODE="$(ad_get_sync_mode)"

ad_set_sync_mode "read"

ad_createou "$UDM_container_ou_name" "$UDM_container_ou_description" || fail_test 110
ad_wait_for_synchronization; check_bool 0 110

ad_exists "$AD_OU_DN"; check_bool 0 110
udm_exists "container/ou"; check_bool 0 110

ad_delete "$AD_OU_DN" || fail_test 110
ad_wait_for_synchronization; check_bool 0 110

ad_exists "$AD_OU_DN"; check_bool 1 110
udm_exists "container/ou"; check_bool 1 110

ad_set_sync_mode "$SYNCMODE"

exit "$RETVAL"
