#!/bin/sh
#
# Univention Kolab2 Webclient
#  postinst script
#
# Copyright (C) 2004, 2005, 2006, 2007 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

a2enmod php5

# create database, user and tables
share=/usr/share/univention-kolab2-webclient/
su - postgres -c "psql -d template1 -f $share/create.pgsql.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/horde_datatree.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/horde_prefs.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/horde_syncml.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/horde_histories.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/kronolith.pgsql.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/turba_objects.pgsql.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/nag.pgsql.sql &> /dev/null"
su - postgres -c "psql -d horde -f $share/mnemo.pgsql.sql &> /dev/null"


eval `univention-baseconfig --shell dump`

# create horde user
if [ ! -e /etc/horde.secret ]; then
	tmp=$(mktemp)
	makepasswd --nocrypt > $tmp
	passwd=$(cat $tmp)
	hash=$(mkpasswd --hash=md5 -s < $tmp)
	touch /etc/horde.secret
	chmod 600 /etc/horde.secret
	echo $passwd > /etc/horde.secret
	chown www-data /etc/horde.secret
	rm -f $tmp
	# set passwd for database user horde
	su - postgres -c "echo \"ALTER USER horde WITH PASSWORD '$passwd'\" | psql -d template1 -f -"
fi

if [ "$1" = configure -a -n "$2" ] && dpkg --compare-versions "$2" lt 0.2.0-47; then
	univention-baseconfig set horde/application/gollem?false
fi

univention-baseconfig set	horde/application/turba?true \
							horde/application/kronolith?true \
							horde/application/mnemo?true \
							horde/application/nag?true \
							horde/application/gollem?true \
							horde/application/ingo?true \
							horde/application/passwd?true \
							horde/calendar/day/inline_time?false \
							horde/calendar/week/inline_time?false \
							horde/calendar/workweek/display?true \
							horde/calendar/edit/save_as_new?true \
							horde/calendar/invitation/send?true \
							horde/menu/options?true \
							horde/menu/hide_groupware?false \
							horde/menu/width?250 \
							horde/menu/save_state?true \
							horde/mailer/type?smtp

univention-baseconfig set php/memory/limit?64

dpkg-statoverride --force --update --add www-data adm 755 /var/log/horde

#DEBHELPER#

# restart services
if [ -x /etc/init.d/postgresql ]; then
	/etc/init.d/postgresql restart
fi

if [ -x /etc/init.d/postgresql-7.4 ]; then
	/etc/init.d/postgresql-7.4 restart
fi

if [ -x /etc/init.d/cyrus22 ]; then
	/etc/init.d/cyrus22 restart
fi

/etc/init.d/apache2 reload


if [ "$1" = configure -a -z "$2" ]; then
	/usr/share/univention-kolab2-webclient/turba-permissions.py
fi

if [ -x /etc/init.d/univention-directory-listener ]; then
	/etc/init.d/univention-directory-listener crestart
fi

exit 0

