#!/bin/sh
#
# Univention Postgresql
#  postinst
#
# SPDX-FileCopyrightText: 2004-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh

case "$1" in
	configure)
		if [ -z "$2" ] # installation
		then
			# configure firewall
			ucr set security/packetfilter/package/univention-postgresql-15/tcp/5432/all="ACCEPT" \
				security/packetfilter/package/univention-postgresql-15/tcp/5432/all/en="postgresql"
			if [ -x "/etc/init.d/univention-firewall" ]
			then
				invoke-rc.d univention-firewall restart
			fi
		fi

		# restart postgresql to load correct configfiles (Bug #27786)
		service postgresql restart
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
