#!/bin/sh
#
# Univention Postgresql
#
# SPDX-FileCopyrightText: 2023-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only


if [ "$1" = "configure" ] && [ -n "$2" ]
then
	if [ "$(ucr get postgres15/password-encryption)" = "md5" ]
	then
		ucr set postgres17/password-encryption?md5
	fi
	if [ "$(ucr get postgres15/pg_hba/password-encryption)" = "md5" ]
	then
		ucr set postgres17/pg_hba/password-encryption?md5
	fi
fi

#DEBHELPER#

exit 0
