#! /bin/bash
#
# Univention Apache
#  postinst file for the univention-apache debian package
#
# SPDX-FileCopyrightText: 2001-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

a2enmod authnz_pam || true
a2enmod unique_id || true
a2enmod rewrite || true
a2enmod headers || true
a2enmod proxy || true

# disable event before activating prefork
a2dismod mpm_event || true
a2enmod mpm_prefork || true

a2enconf ucs.conf || true

if [ "$1" = configure ] && [ -z "$2" ]; then
	a2dismod ssl || true
	a2enmod ssl || true
	a2dissite default-ssl.conf || true
	a2ensite default-ssl.conf || true
	a2dissite include-vhosts.conf || true
	a2ensite include-vhosts.conf || true
fi

univention-config-registry set apache2/autostart?"yes"
univention-config-registry set apache2/loglevel?"warn"
univention-config-registry set apache2/documentroot?"/var/www/"
univention-config-registry set apache2/maxclients?150
univention-config-registry set mail/alias/webmaster?root
univention-config-registry set apache2/startsite?"univention/"
univention-config-registry set ucs/server/robots/disallow?"/"
univention-config-registry set apache2/force_https/exclude/request_uri/mod-status?/server-status
univention-config-registry set apache2/force_https/exclude/http_host/localhost?localhost

# configure firewall
ucr set security/packetfilter/package/univention-apache/tcp/80/all=ACCEPT \
        security/packetfilter/package/univention-apache/tcp/80/all/en="HTTP" \
        security/packetfilter/package/univention-apache/tcp/443/all=ACCEPT \
		security/packetfilter/package/univention-apache/tcp/443/all/en="HTTPS"
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart

eval "$(univention-config-registry shell)"

if [ "$server_role"  = "domaincontroller_master" ] || [ "$server_role" = "domaincontroller_backup" ]; then
	/usr/lib/univention-install/08univention-apache.inst || true
fi

#remove old ucr variables
keys=$(ucr --keys-only search --key 'ucs/web/overview/entries/admin/(invalid-certificate|invalid-certificate-list|root-certificate|ldap-master)/.*')
if [ -n "$keys" ]; then
	ucr unset $keys
fi

#Check, whether we can safely enable ssl
#The private key could also be included inside the certificate file, so we don't require it here
ENABLE_SSL=yes
CERT_PATH="/etc/univention/ssl/$hostname.$domainname/cert.pem"

if [ ! -z "$apache2_ssl_certificate" ]; then
	CERT_PATH="$apache2_ssl_certificate"
fi

if [ ! -f "$CERT_PATH" ]; then
	ENABLE_SSL=no
fi

if [ $ENABLE_SSL = yes ]; then
	a2enmod ssl
	a2ensite default-ssl.conf || true
else
	a2dismod ssl
	a2dissite default-ssl.conf|| true
fi

if [ -x /etc/init.d/apache2 ] && apache2ctl --configtest; then
	# better stop&start, as this behaves differently to restart
	invoke-rc.d apache2 stop
	sleep 3
	invoke-rc.d apache2 start
fi

exit 0
