data	usr/share/univention-demo-configuration/
portal/*.css	usr/share/univention-demo-configuration/portal/
portal/*.html	var/www/apps/
portal/*.jpg.b64	usr/share/univention-demo-configuration/portal/
portal/*.json	usr/lib/univention-portal/config/
portal/*.ldif	usr/share/univention-demo-configuration/portal/
portal/*.py	usr/lib/python3/dist-packages/univention/portal/extensions/
portal/*.sh	usr/share/univention-demo-configuration/portal/
portal/*.svg	usr/share/univention-demo-configuration/portal/
usr
