#!/bin/sh
#
# restricted configuration for demo.univention.de
#  preinst script
#
# Copyright 2012-2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

case "$1" in
	install)
		for module in join packages quota reboot services setup sysinfo top ucr updater appcenter
		do
			dpkg-divert --package univention-demo-configuration --add --rename --divert \
				/usr/share/univention-management-console/modules/"$module".xml.real \
				/usr/share/univention-management-console/modules/"$module".xml
		done
		for file in \
			/usr/share/univention-management-console-frontend/js/umc/app/login.html \
			/etc/univention/templates/files/etc/nagios3/apache2.conf
		do
			dpkg-divert --package univention-demo-configuration --add --rename --divert "$file.real" "$file"
			# copy diverted files such that conf files are not recognized as having been changed
			[ ! -e "$file" ] && cp "$file.real" "$file"
		done
		;;
	upgrade|abort-upgrade)
		# new diverts (Bug #29595), can be removed after the release of UCS 3.1
		for module in appcenter
		do
			dpkg-divert --package univention-demo-configuration --add --rename --divert \
				/usr/share/univention-management-console/modules/"$module".xml.real \
				/usr/share/univention-management-console/modules/"$module".xml
		done

		# login.html changed its location (Bug #33083), for update to UCS 3.2
		for file in \
			/usr/share/univention-management-console-frontend/js/umc/app/login.html
		do
			dpkg-divert --package univention-demo-configuration --add --rename --divert "$file.real" "$file"
		done

		for file in \
			/etc/univention/templates/files/etc/nagios3/apache2.conf
		do
			dpkg-divert --package univention-demo-configuration --add --rename --divert "$file.real" "$file"
			# copy diverted files such that conf files are not recognized as having been changed
			[ ! -e "$file" ] && cp "$file.real" "$file"
		done
		;;
	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
