#!/bin/sh
#
# restricted configuration for demo.univention.de
#  postinst script
#
# Copyright 2012-2014 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

. /usr/share/univention-lib/all.sh
. /usr/share/univention-lib/umc.sh

eval "$(ucr shell)"

_undivert() {
	[ -e "$1" -a -e "$1.real" ] && rm -f "$1"  # make sure that also config files are removed
	dpkg-divert --package univention-demo-configuration --remove --rename "$1"
}

case "$1" in
	configure)
		# umc overview
		univention-config-registry set \
			ucs/web/overview/entries/admin/demo-configuration/description/de?'Die Univention-Support-Datenbank' \
			ucs/web/overview/entries/admin/demo-configuration/description?'The Univention support database' \
			ucs/web/overview/entries/admin/demo-configuration/label?'Univention SDB' \
			ucs/web/overview/entries/admin/demo-configuration/label/de?'Univention SDB' \
			ucs/web/overview/entries/admin/demo-configuration/link?'http://sdb.univention.de' \
			ucs/web/overview/entries/admin/demo-configuration/priority?'80'

		univention-config-registry unset \
			ucs/web/overview/entries/admin/demo-configuration/icon

		# disable update checks and hints for available updates
		ucr set update/check/cron/enabled=no
		ucr set --force \
			update/reboot/required=false \
			update/available=false

		# hide Administrator + machine account by default
		udm "users/user" modify --dn "uid=Administrator,cn=users,$ldap_base" --set objectFlag=hidden
		udm "computers/$server_role" modify --dn "$ldap_hostdn" --set objectFlag=hidden

		# remove obsolete nagios template and allow anonymous access
		_undivert /etc/univention/templates/files/etc/nagios3/apache2.conf
		ucr set nagios/server/authenticate=no

		# in UCS 3.x login.html was diverted, not anymore in UCS 4.0
		_undivert /usr/share/univention-management-console-frontend/js/umc/app/login.html

		# reload services
		umc_frontend_new_hash
		invoke-rc.d apache2 reload
		invoke-rc.d slapd restart
		invoke-rc.d univention-management-console-server reload

		# add test data only upon initial installation
		if [ -z "$2" ]; then
			/usr/share/univention-demo-configuration/data/create_import_commands.py | bash
		fi
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
