#!/bin/sh
#
# restricted configuration for demo.univention.de
#  preinst script
#
# Copyright 2012-2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

#DEBHELPER#

_divert() {
	dpkg-divert --package univention-demo-configuration --add --rename --divert "$1.real" "$1"
}

case "$1" in
	install|upgrade)
		# create necessary diversions
		for file in /usr/share/univention-web/js/umc/i18n/de/branding.json /usr/share/univention-web/js/umc/i18n/en/branding.json; do
			_divert "$file"
		done

		for module in appcenter diagnostic ipchange join lib passwordchange quota reboot services setup sysinfo top ucr updater printers saml-serviceprovider serveroverview udm; do
			_divert /usr/share/univention-management-console/modules/"$module".xml
		done
		;;
	abort-upgrade)
		;;
	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
