#!/bin/sh
#
# restricted configuration for demo.univention.de
#  postrm script
#
# Copyright 2012-2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

#DEBHELPER#

. /usr/share/univention-lib/umc.sh

eval "$(ucr shell)"

_undivert() {
	[ -e "$1" -a -e "$1" ] && rm -f "$1"  # make sure that also config files are removed
	dpkg-divert --package univention-demo-configuration --remove --rename "$1"
}

_list_diverted_files() {
	LC_ALL=C dpkg-divert --list univention-demo-configuration | sed 's/diversion of \(.*\) to .*/\1/'
}

case "$1" in
	remove|disappear|failed-upgrade|abort-install)
		# umc overview
		univention-config-registry unset \
			ucs/web/overview/entries/admin/demo-configuration/description/de \
			ucs/web/overview/entries/admin/demo-configuration/description \
			ucs/web/overview/entries/admin/demo-configuration/icon \
			ucs/web/overview/entries/admin/demo-configuration/label \
			ucs/web/overview/entries/admin/demo-configuration/label/de \
			ucs/web/overview/entries/admin/demo-configuration/link \
			ucs/web/overview/entries/admin/demo-configuration/priority

		# remove all diversions associated with this package
		_list_diverted_files | while read file
		do
			_undivert "$file"
		done

		# show the Administrator account by default
		udm users/user modify --dn "uid=Administrator,cn=users,$ldap_base" --set objectFlag=""

		# disallow anonymous access to nagios
		ucr set nagios/server/authenticate=yes

		# reload services
		umc_frontend_new_hash
		invoke-rc.d apache2 reload
		invoke-rc.d slapd restart
		invoke-rc.d univention-management-console-server reload
		;;
	purge)
		;;
	upgrade)
		;;
	abort-upgrade)
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
