#!/bin/sh
# SPDX-FileCopyrightText: 2012-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/umc.sh

eval "$(ucr shell)"
: "${ldap_base:?missing}" "${server_role:?missing}" "${ldap_hostdn:?missing}"

_undivert() {
	[ -e "$1" ] && [ -e "$1" ] && rm -f "$1"  # make sure that also config files are removed
	dpkg-divert --package univention-demo-configuration --remove --rename "$1"
}

_list_diverted_files() {
	LC_ALL=C dpkg-divert --list univention-demo-configuration | sed 's/diversion of \(.*\) to .*/\1/'
}

case "$1" in
	remove|disappear|failed-upgrade|abort-install)
		# umc overview
		ucr --keys-only search --key 'ucs/web/overview/entries/service/(demo-configuration|demo-configuration-forum)/.*' |
			xargs ucr unset umc/web/hooks/univention-demo-configuration

		# enable update checks again
		ucr set update/check/cron/enabled=yes
		ucr unset --force \
			update/reboot/required \
			update/available

		# remove all diversions associated with this package
		_list_diverted_files | while read -r file
		do
			_undivert "$file"
		done

		# show the Administrator account by default
		udm users/user modify --dn "uid=Administrator,cn=users,$ldap_base" --remove objectFlag="hidden"
		udm "computers/$server_role" modify --dn "$ldap_hostdn" --remove objectFlag="hidden"

		# reload services
		deb-systemd-invoke reload apache2.service
		deb-systemd-invoke restart slapd.service
		deb-systemd-invoke reload univention-management-console-server.service
		;;
	purge)
		;;
	upgrade)
		;;
	abort-upgrade)
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
