#!/bin/sh
# SPDX-FileCopyrightText: 2012-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

# shellcheck source=/dev/null
. /usr/share/univention-lib/all.sh
# shellcheck source=/dev/null
. /usr/share/univention-lib/umc.sh

eval "$(ucr shell)"
: "${ldap_base:?missing}" "${server_role:?missing}" "${ldap_hostdn:?missing}"

_undivert() {
	[ -e "$1" ] && [ -e "$1.real" ] && rm -f "$1"  # make sure that also config files are removed
	dpkg-divert --package univention-demo-configuration --remove --rename "$1"
}

case "$1" in
	configure)
		# register JavaScript hook
		univention-config-registry set umc/web/hooks/univention-demo-configuration=univention_demo directory/manager/rest/html-view-enabled=true

		# disable update checks and hints for available updates
		ucr set update/check/cron/enabled=no
		ucr set --force \
			update/reboot/required=false \
			update/available=false

		# hide Administrator + machine account by default
		udm "users/user" modify --dn "uid=Administrator,cn=users,$ldap_base" --set objectFlag=hidden
		udm "computers/$server_role" modify --dn "$ldap_hostdn" --set objectFlag=hidden

		# upgrade to 4.2 - remove obsolete diversion
		_undivert /usr/share/univention-management-console-frontend/js/umc/hook.js

		# reload services
		deb-systemd-invoke reload apache2.service
		deb-systemd-invoke restart slapd.service
		deb-systemd-invoke reload univention-management-console-server.service univention-directory-manager-rest.service

		# add test data only upon initial installation
		if [ -z "$2" ]; then
			/usr/share/univention-demo-configuration/data/create_import_commands.py | bash
			/usr/share/univention-demo-configuration/portal/register_portal_entries.sh
		fi

		# Online Demo UMC has a unique piwik tracking id
		sed -i 's|Piwik.getTracker("https://www.piwik.univention.de/piwik.php",14)|Piwik.getTracker("https://www.piwik.univention.de/piwik.php",37)|' /usr/share/univention-web/js/dojo/dojo.js
		sed -i 's|PortalReloaderUDM|DemoPortalReloader|' /usr/share/univention-portal/portals.json
		univention-portal update --reason demo
		service univention-portal-server restart

		ucr set umc/cookie-banner/show=true \
			umc/cookie-banner/text/de='Wir verwenden auf dieser Webseite Cookies und andere Technologien, um sicherzustellen, dass die Seite zuverlässig, sicher und für Besucher optimal läuft. Damit das funktioniert, messen wir, wie häufig unsere Seite besucht und wie sie genutzt wird. Mit dem Button "Akzeptieren" stimmen Sie der Verwendung zu. Weitere Informationen erhalten Sie in unserer <a href="https://www.univention.de/datenschutzerklaerung/" target="_blank">Datenschutzerklärung</a>.' \
			umc/cookie-banner/text/en='We use cookies and other technologies on this website to ensure that the site works reliably, securely, and optimally for visitors. For this to work, we measure how often our website is visited and how it is used. By clicking the "Accept" button, you consent to their use. Further information can be found in our <a href="https://www.univention.com/privacy-statement/" target="_blank">Data Privacy Policy</a>.'
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
