#!/bin/sh
#
# restricted configuration for demo.univention.de
#  preinst script
#
# SPDX-FileCopyrightText: 2012-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

_divert() {
	dpkg-divert --package univention-demo-configuration --add --rename --divert "$1.real" "$1"
}

case "$1" in
	install|upgrade)
		# create necessary diversions
		for file in /usr/share/univention-web/js/umc/i18n/de/branding.json /usr/share/univention-web/js/umc/i18n/en/branding.json; do
			_divert "$file"
		done

		for module in appcenter diagnostic ipchange join lib passwordchange quota reboot services setup sysinfo top ucr updater printers saml-serviceprovider udm-portals-portal serveroverview udm; do
			_divert /usr/share/univention-management-console/modules/"$module".xml
		done
		;;
	abort-upgrade)
		;;
	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
