#!/bin/sh
### BEGIN INIT INFO
# Provides:          univention-demo-configuration
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Should-Start:      bind9
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: restricted configuration for demo.univention.de
### END INIT INFO
#
# Copyright 2012-2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.
PATH=/usr/sbin:/usr/bin:/sbin:/bin

case "$1" in
	start|restart|force-reload)
		# make sure listener is running before updating as some join scripts
		# will depend on the listener running ... shut down UMC server during the update
		/etc/init.d/univention-management-console-server stop
		ucr set --force \
			listener/autostart=yes \
			umc/server/autostart=no
		/etc/init.d/univention-directory-listener restart

		# update system to latest package status
		ucr commit /etc/apt/sources.list.d/*
		while [ -e /var/lock/univention-updater ]
		do
			# make sure that there is no other updater process running (Bug #45070)
			sleep 1
		done
		univention-upgrade --noninteractive
		univention-config-registry set update/reboot/required=false

		# disable the listener after an update to make sure that LDAP changes
		# do not affect the actual system ... re-enable the UMC server
		/etc/init.d/univention-directory-listener stop
		ucr set --force listener/autostart=no
		ucr unset --force umc/server/autostart
		/etc/init.d/univention-management-console-server start

		# update list of apps
		univention-app update
		;;
	stop|status)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
